### ISSUE TITLE
Input/Output module ...

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1]
HDF5 is part of the core of the data policy at ESRF. The natural binding for hdf5 is h5py.
The idea is to provide an API similar to h5py in silx when addressing images and specfiles.

Today: there is 1 binding for SpecFile and 2 for images: EdfImage and fabio.
H5py offers a Dataset class with _attrs_ which matches pretty well with the data/header dichotomy in image formats. Re-implementing the behavior (or subclassing?) Dataset solves most of the discussion about the API. The second advantage is about the formation to silx as trainee have to learn only one API.
# Difference between HDF5/other format

The main difference between HDF5 and  other is the hierarchical structure which is exposed as a Python dictionary where most of the other formats are using a linear structure.  The natural design would then be to use (/expose?)  a Python list as container to Dataset instances in a File object.  
# About file/file-series

The h5py File module provides a "driver" option to select the way data are saved. Moreover, file series would be represented as "prefix_%04d.img" to create a unified view, like what is done in h5py.
# Work to be performed:
- Implement Dataset, Attribute, and File
- Provide drivers for the various file formats (re-using the code existing in the pre-existing libraries)
# Advantages:

The transition to HDF5 over the period 2010-2015 has been very slow, most scientists being:
- reluctant to change something which already works
- don't want to learn yet another API
  If one wants actually to promote HDF5, offering the same API between HDF5/legacy would allow to bridge the gap.

**Comment by vasole** [comment]
- I like the idea of having the API used for the most complete file format applicable to the other simpler format.

- I would leave the file-series for later discussion. HDF5 (not h5py) does that not to select a series of files but to split a single file. The concept of a stack of files falls on a different use case. You can have stacks of files using the family driver for instance.

- I do not see the need to implement Dataset, Attribute and File. When converting from specfile or EDF to HDF5 one does not need Attributes for instance, but one certainly needs Groups. If you mean not to raise an exception when trying to access the attributes instead of returning the same thing h5py returns when there are no attributes then I agree.

**Comment by vasole** [comment]
Slides of presentation: [silx-io.pdf](https://github.com/silx-kit/silx/files/107826/silx-io.pdf)

**Comment by vasole** [comment]
Summary
=======

- The proposal to access SPEC files in the same way as HDF5 files was well received

- The most repeated word from the meeting participants was "official":

    - Official SPEC to NeXus converter
    - Official layout of ESRF NeXus files

**Comment by vasole** [comment]
The HDF5 and SPEC file unification seems to have happened and the HDF5 widget is taking care of it.

That widget should also be able to achieve the same with 2D images via FabIO. Should we close this issue (eventually replacing it by a more dedicated one to images)?

**Comment by kif** [comment]
On Tue, 20 Sep 2016 07:51:56 -0700
V. Armando Solé <notifications@github.com> wrote:

> The HDF5 and SPEC file unification seems to have happened and the HDF5 widget is taking care of it.
> 
> That widget should also be able to achieve the same with 2D images via FabIO. Should we close this issue (eventually replacing it by a more dedicated one to images)?
> 

Makes sense to me.
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
Few comments:
- Our binding only concern input
- Maybe we have to discuss about the `fabio->h5` binding
- I created a method `load_file_as_h5py(filename)`. It would be nice to expose it in the `io` module

What i have about that is quite stable now.
Then I can create a PR containing that. It will make the merge of the hdf5widget PR easier.

**Comment by vasole** [comment]
Yes and no. We also contemplate the possibility to export dictionaries in other formats with HDF5 among them but I get your point and yes, we have to clarify output. Concerning writing of HDF5 files we are currently relying on h5py and writing of SPEC files is something I am not sure we want to support (to be discussed). I suppose that for image formats other than TIFF or EDF out best approach would be to use FabIO and, if FabIO is present, then to use FabIO for those too. My personal taste is to export in few but widespread formats (HDF5, TIFF and CSV) leaving more specialized formats to dedicated packages (FabIO, SOLEIL's converters, ...)
