### ISSUE TITLE
silx utils function

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1001]
@pierrepaleo developed some functions that are actually on the gui interface for freeart.
It is actually being modified in order to deal with silx fbp.
On this code there is some function to compute the center of rotation of a sinogram, rescale intensity and enhance_contrast. 
Do we want some (all ? ) of them to be moved to silx. It will probably interest some users.

**Comment by t20100** [comment]
+1

**Comment by payno** [comment]
removed due to duplication with #1026
