### ISSUE TITLE
[doc] conf.py should not modify the PYTHONPATH

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1010]
Hello, same probleme reported for pyFAI issue 646

    diff --git a/doc/source/conf.py b/doc/source/conf.py
    index 30abf54..44f0a3e 100644
    --- a/doc/source/conf.py
    +++ b/doc/source/conf.py
    @@ -15,16 +15,12 @@ import sys
     import os
     import glob
     import subprocess
    +import silx
 
     # If extensions (or modules to document with autodoc) are in another directory,
     # add these directories to sys.path here. If the directory is relative to the
     # documentation root, use os.path.abspath to make it absolute, like shown here.
     # sys.path.insert(0, os.path.abspath('.'))
    -dirname = os.path.dirname
    -root_dir = dirname(dirname(dirname(os.path.abspath(__file__))))
    -import silx
    -source_dir = dirname(dirname(silx.__file__))
    -os.environ["PYTHONPATH"] = source_dir + os.pathsep + os.environ.get("PYTHONPATH", "")
 
     # -- General configuration -----------------------------------------------------

**Comment by vallsv** [comment]
I will fix that. It is effectivly not needed will we only use `python setup.py build_doc`.

**Comment by picca** [comment]
please keep the build_doc and build_man targets separate.
It is important for the Debian packaging.
