### ISSUE TITLE
[build] Cython files are not located at the fully qualified name location

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1015]
@picca have this logs will compiling the debian package (relative to https://github.com/silx-kit/silx/issues/1012).

```
Warning: Extension name 'silx.io.specfile' does not match fully qualified name 'specfile' of 'silx/io/specfile/specfile.pyx'
Warning: Extension name 'silx.math.fit.functions' does not match fully qualified name 'functions' of 'silx/math/fit/functions/functions.pyx'
Warning: Extension name 'silx.math.fit.filters' does not match fully qualified name 'filters' of 'silx/math/fit/filters/filters.pyx'
Warning: Extension name 'silx.math.fit.peaks' does not match fully qualified name 'peaks' of 'silx/math/fit/peaks/peaks.pyx'
Warning: Extension name 'silx.math.chistogramnd' does not match fully qualified name 'chistogramnd' of 'silx/math/histogramnd/chistogramnd.pyx'
Warning: Extension name 'silx.math.chistogramnd_lut' does not match fully qualified name 'chistogramnd_lut' of 'silx/math/histogramnd/chistogramnd_lut.pyx'
Warning: Extension name 'silx.math.marchingcubes' does not match fully qualified name 'marchingcubes' of 'silx/math/marchingcubes/marchingcubes.pyx'
Warning: Extension name 'silx.math.combo' does not match fully qualified name 'combo' of 'silx/math/combo/combo.pyx'
```

It is maybe a warning from a special Cython version. @PiRK try to reprocude it without success.

It looks like we do not locate always Cython file at the final module location.

For example we expecte to have an ext module `silx.io.specfile` but the Cython file is located at `silx/io/specfile/specfile.pyx`. It would make sens to have a `silx/io/specfile.pyx` file.

**Comment by picca** [comment]
Yes sire,

I have cython     | 0.25.2-1

**Comment by PiRK** [comment]
Cython 0.21.1 on my machine.

We have a consistency issue anyway, because some of our pyx files are at the location of their fully qualified name (`silx.image.bilinear` ...) while some other are in a subfolder together with a C-library that they are wrapping (all the ones that show warnings on your machine).

I will try to fix this.
