### ISSUE TITLE
[ExternalResources] It raises a SkipTest

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1020]
While this function is not part of test library, it is not a good idea to raise an exception from unittest module.

Plus if resources are not available, it is maybe not a good idea to skip tests as a default behaviour.

**Comment by picca** [comment]
Hello, same problem than with pyFAI, during the Debian build there is no network available.

So it fails with this error message

```
======================================================================
FAIL: test_dowload_all (silx.test.test_resources.TestExternalResources)
test the download of all files from silx.org
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/silx/test/test_resources.py", line 83, in test_dowload_all
    self.assertGreater(len(l), 1, "At least 2 items were downloaded")
AssertionError: At least 2 items were downloaded

----------------------------------------------------------------------
Ran 762 tests in 94.848s

FAILED (failures=1, skipped=38)
```

**Comment by vallsv** [comment]
Did you use the last master?

**Comment by picca** [comment]
Not at all, I am preparing a debian package from the latest pip available release 0.5.0

**Comment by vallsv** [comment]
Then i don't know how we can work. If you want to cherry-pick things, you can try https://github.com/silx-kit/silx/pull/1018, which should fix the problem. Or is it better to patch a the branch 0.5?

**Comment by vallsv** [comment]
BTW you should reopen https://github.com/silx-kit/silx/issues/1009, cause this issue is not relative to the same thing.

**Comment by picca** [comment]
No problem valentin,

I just unactivated the test now in order to progress from my side during the build process.
I want to discover a maximum of problem now in order to have something working out of the box with a minimum of debian patch for the next release.
I am working now on the qt test during the build :)

**Comment by t20100** [comment]
closing as should be fixed now
