### ISSUE TITLE
Could you provide a .desktop file for the silx application

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1038]
It would be nice to have a silx-view.desktop file in order to access the viewer from the menues.

A nice icon should be great also ;)

**Comment by vallsv** [comment]
Sounds interesting. Here is some entries https://stackoverflow.com/questions/25284879/install-desktop-file-with-setup-py

**Comment by t20100** [comment]
I created a .desktop file + 48x48 icon in PR #1086 
@picca is that enough for you? Do you know projects that integrate the copy of those files to their setup.py?

Not sure how to have python installing it at the right place (handling --user and virtualenv).
Packages to check: https://github.com/welshjf/install_freedesktop, https://launchpad.net/python-distutils-extra (there's a Debian package).

**Comment by t20100** [comment]
Closed by #1086
