### ISSUE TITLE
Problem with GUI test on appveyor and travis

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1039]
I guess system pops can explain things...

![appveyor - ci 4](https://user-images.githubusercontent.com/7579321/29354793-d9e95792-826e-11e7-8899-3d896159dce8.png)
![appveyor - ci 3](https://user-images.githubusercontent.com/7579321/29354797-de009318-826e-11e7-8b43-ec6ecb90f033.png)

**Comment by vallsv** [comment]
Well, it looks to be not the case on appveyor: 
![appveyor - ci 5](https://user-images.githubusercontent.com/7579321/29356797-b6861b76-8275-11e7-911a-836beac0a1d1.png)

**Comment by t20100** [comment]
Did you tried the registry patch proposed in: https://github.com/appveyor/ci/issues/1715?

**Comment by vallsv** [comment]
Yes, but it have to be applied before our scripts have hands on it, else it have no effects.

**Comment by vallsv** [comment]
- I create a branch to play around that https://github.com/silx-kit/silx/pull/1024 (it should fix problems a have with the mouse, but not this one, it also introduce few other things we can cherry pick one of this days)
- And GUI tests was disabled by https://github.com/silx-kit/silx/pull/1050 while it is not fixed

**Comment by vallsv** [comment]
And i have no feed back from Travis

**Comment by vallsv** [comment]
Travis answer that they will check it is possible to disable the popup. But ask us if we can close it by our-self. I think it is not so easy while we never know when and when the dialog pop.
