### ISSUE TITLE
MCA data dtype

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1052]
When I tried to convert a SPEC file with mostly MCA data, I found that the resulting HDF5 file is 3 times larger than the original SPEC file.

The problem is that I read the MCA data into an array of `dtype=numpy.double`, when the data is integers (mostly zeroes and ones).

The original C function `SfGetMca` already stores the data into an array of `double**`. Why is that? Can MCA data be anything else than integers?

**Comment by PiRK** [comment]
OK. Then I will close the issue.

**Comment by PiRK** [comment]
With shuffle and GZIP compression the resulting HDF5 is smaller by a factor of 4.8 than the SPEC file, FYI.

**Comment by vasole** [comment]
Any performance improvement when using it with silx view when comparing the compressed and the uncompressed?

**Comment by PiRK** [comment]
Compressed file created with: `python bootstrap.py silx convert ../../data/mesh_and_mca.dat -o test.h5 --mode w --shuffle --compression gzip`
Uncompressed file created with: `python bootstrap.py silx convert ../../data/mesh_and_mca.dat -o test.h5 -m w`

Compressed size: 41M
Uncompressed size: 613M

Access time less than a second for both HDF5 files when viewing it with `python bootstrap.py silx view test.h5` (access to the dataset /1.1/instrument/mca_0/data to view the first spectrum as a curve).
