### ISSUE TITLE
[silx view] About box should display availability of some common HDF5 filters

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1064]
@kif talked about that in https://github.com/silx-kit/silx/issues/860

The better way to move away `hdf5plugins` from the about box is IMO to display if some expected filters are available.

Unfortunately, as i remember, `h5py` (or the C library) do not allow yet to check if a filter is available while the filter was not already used to decode a dataset. We can improve this issue when this feature is available.

**Comment by vasole** [comment]
I reported it in https://github.com/h5py/h5py/issues/843

It looks like the problem is at the HDF5 level.

**Comment by vasole** [comment]
One (ugly?) way to overcome the limitation would be to ship with silx a small HDF5 file containing an example dataset of each of the plugins we want to test. I would not do it. A proper message informing about the missing plugin and the eventual solution when trying to access the dataset should be enough.

**Comment by vallsv** [comment]
We can use ```H5Zfilter_avail``` to check and display availability of most important filters in the about box.

Or displaying availability of filters per dataset can be enough.
