### ISSUE TITLE
[Plot1D] enhancement proposal: axes selection, support numpy 2D array with field names

### ISSUE THREAD

**Issue by mguijarr** [silx-kit/silx#1069]
It would be wonderful if `Plot1D` could support setting data as a numpy 2D array like this for example:

```
array([(1504107740.466219, 495.3961129884609),
       (1504107740.567702, 498.6558010547177),
       (1504107740.668392, 498.9141729466354),
       (1504107740.769094, 500.62077018706),
       (1504107740.869791, 496.8179944409576),
       (1504107740.970479, 502.3195427689161),
       (1504107741.071163, 500.7967042862891),
       (1504107741.171848, 504.38705410105825),
       (1504107741.272545, 499.8094277045018),
       (1504107741.373239, 493.4727782167612)],
      dtype=[('timestamp', '<f8'), ('diode', '<f8')])
```

`Plot1D` could display timestamp on X and diode values on Y with the names of the axes already set to `timestamp` and `diode` (fields data from numpy array dtype). User should be able to select what to plot (which column is source for X data, Y data) and eventually multiple curves could be displayed if several Y data sources are selected.

A bit like what is already in PyMca, in fact.

**Comment by vasole** [comment]
For maximum compatibility with existing software (for instance HDF5View, NeXPy), we recommend not to mix different items. In your case, if the source is an HDF5, one would expect a timestamp dataset and a diode dataset. 

By other hand we do support NXdata groups describing a plot with labels, error bars, ...

@PiRK How generic is the NXdata interpretation? Perhaps what the poster is requiring can be achieved going through the NXdata interpreter.

**Comment by mguijarr** [comment]
In fact data is coming live from the network during acquisition in the case I describe in this issue. It is not related to HDF5 at all.

A generic "tree of data" implementation can be useful to represent data, but still we want to be able to plot it and select axes to display. To my knowledge, this is missing still in Plot1D.

**Comment by vasole** [comment]
On 30.08.2017 21:43, Matias Guijarro wrote:
> In fact data is coming live from the network during acquisition in the
> case I describe in this issue. It is not related to HDF5 at all.
> 

I was imaging it. Therefore my question about how generic was the NXdata 
interpreter because that representation is very complete. It supports 
more than just 1d plots: 1d, 2d, 3d, axes, labels, uncertainties, ...

**Comment by t20100** [comment]
For a bunch of 1D data with names (e.g., a 2D numpy array with named rows), we can have a rather generic widget inheriting from `Plot1D` with an extra widget to choose a dataset for the X axis and multiple dataset for the Y axis, @mguijarr already did something like that.

For more structured data, it should be possible to implement an h5py-like API as was done over spec and fabio... and then reuse the hdf5 tree and the viewer.

**Comment by vallsv** [comment]
> For more structured data, it should be possible to implement an h5py-like API as was done over spec and fabio... and then reuse the hdf5 tree and the viewer.

We create `silx.io.commonh5` (used by `spech5` and `fabioh5`). With that, you can create h5py tree in memory. That can be used for this kind of usecase.

**Comment by PiRK** [comment]
The NXdata viewer supports multiple curves with a common single x axis dataset. But if I remember correctly, all  the y data must be in a single dataset, and share the same name/label & unit.

A specialized widget with an `addCurves` method accepting a structured numpy array would be the simplest solution. I'm not sure if using structured arrays for this situation is very common or good practice, though. I've never used structured arrays in practice.

**Comment by vasole** [comment]
I think a dedicated widget would be unavoidable because the open posters wants to be able to choose the x axis as well.

I am reluctant to propose a solution "a la PyMca" because a solution following the NXdata approach would allow more things (uncertainties, labels, ...).

As usual I guess we'll end up having the two things ... 

@t20100 

BTW now that we support NXdata, I think we should consider the possibility to export plots in that format if HDF5 is available..

**Comment by t20100** [comment]
Related expectation from the code camp: In the curve view of the six viewer to be able to choose one column for the X and another(s) for the Y

**Comment by vasole** [comment]
@mguijarr 

Is this of actuality?

**Comment by mguijarr** [comment]
We worked around this issue.
