### ISSUE TITLE
what about a silx.distutils module

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1076]
Hello you are using a bunch of identical Buildxxx in your setup.py.
What about putting this into a distutils module whcih could be use in all other modules, pyFAI, pymca, fisx etc..

The first comming to my mind is the BuildMan target.

Cheers

**Comment by vallsv** [comment]
Thanks to ask. I proposed it few days ago.
I think it would be painless to manage something like that.
We can move mostly everything from our setup.py, run_tests.py, plus tools used in CI.

**Comment by vallsv** [comment]
Oups bad button

**Comment by vallsv** [comment]
Well, in fact i am not for a module, but for another project:
- Easy to package -> No binary code -> A single python package
- Fast to release -> outside of silx -> released everytime it is needed
- Dependency on build only

**Comment by picca** [comment]
In fact if there is one more package this is more work for the packaging...

**Comment by vallsv** [comment]
Anyway it is only used to build resulting package?

**Comment by picca** [comment]
Since you need everything inorder to build your package. It means one more package :)

**Comment by vallsv** [comment]
On our last silx meeting we talk a little about that. Using a specific project + a `git subtree` per projects can do the trick. A prototype can be easily done, but the task is not assigned.

**Comment by vasole** [comment]
Decide to take no action.
