### ISSUE TITLE
[build] debugging the build_man is hard.

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1089]
Hello, while pacakging I faced a problem with the build_man target.
The only out put if help2man could not generate the doc is
Can not build the man pages.

It would be nice if insteead of raison the exception, the script could be executed with --help and --version (both)

This way the build log should contain the real problem during the build.
Usually a missing build dependency.

It is also important to change the directory before executing the script since there is a protection against execution of the build_man from the source directory.

Cheers

**Comment by vallsv** [comment]
> It would be nice if insteead of raison the exception, the script could be executed with --help and --version (both)

I faced the same problem. The solution you propose is a good idea.
If you know another better tool than help2man, where we can provide our own application output it can also be very nice.

**Comment by picca** [comment]
Maybe we need to wait for this

https://bugs.python.org/issue14102

**Comment by vallsv** [comment]
It should be fixed now, as if there is a problem we reexecute the script without help2man to see the problem.
