### ISSUE TITLE
[silx convert] Add silx version information in output hdf5 file

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1105]
From discussion in PR #1053:

> It would be good to write somewhere that the file was generated by silx-convert with the "silx version". This kind of information can be very useful at one point. Maybe Nexus files have a specific field for that?

**Comment by PiRK** [comment]
Should we use a proper NXprocess group for this? http://download.nexusformat.org/sphinx/classes/base_classes/NXprocess.html?highlight=program

In PR #1148 I just create a dataset named *silx_versions* and a dataset named *convert_commands* (plural because an output HDF5 file can be appended).

**Comment by vasole** [comment]
@PiRK:  No. That information is to be written as attribute of the root level.

http://download.nexusformat.org/doc/html/classes/base_classes/NXroot.html?highlight=nxroot

**Comment by PiRK** [comment]
Done.
