### ISSUE TITLE
[io] Explain the h5py-like API

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1124]
The documentation of various methods and classes mentions our _h5py-like API_, but no documentation nor link is provided. We just assume that users know the API or can easily figure it out.

At the very least, we should provide a link to the h5py documentation in `silx.io`. We could maybe provide a tutorial (_Getting started with silx.io_ ?).

Documentation topics : groups mimicking nested dictionaries (`.keys(), .items()` ...), datasets mimicking numpy arrays (`.shape, .ndims, .size, .dtype`)

**Comment by t20100** [comment]
+1
