### ISSUE TITLE
[plot3d] Silx 3D viewer continuous rotation

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#1125]
It would be nice to have a button to activate the live rotation of the 3D view (along one chosen axis ? Or just the vertical one).

Would be useful, with the possibility of changing the iso surface value / cut plane location.

**Comment by t20100** [comment]
To me it sounds simpler for the user to rotate around to vertical axis, so it's a single click operation.

The user can align the volume axis he would like to rotate around with the vertical (either manual or using the tool button providing pre-defined viewpoint), and s.he should even be able to do so while the volume is rotating.

**Comment by vincefn** [comment]
Sounds good to me, rotation around just the vertical axis is totally sufficient.
