### ISSUE TITLE
Provide h5py windows wheel supporting Eiger data

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#113]
This needs to containing the HDF5 library plus the LZ4 plugin ...
@picca Do you have such a beast at Soleil ?

**Comment by picca** [comment]
Yes we have an Eiger at SOLEIL. And in the neer futur it will be on the SIXS beameline.
surface diffraction.

Cheers

**Comment by kif** [comment]
On Fri, 24 Jun 2016 08:13:31 -0700
picca <notifications@github.com> wrote:

> Yes we have an Eiger at SOLEIL. And in the neer futur it will be on the SIXS beameline.
> surface diffraction.

My question was rather if you had the LZ4 plugins compiled for
windows... Eugen made the stuff so simple for debian that we forgot
about windows.

**Comment by picca** [comment]
> My question was rather if you had the LZ4 plugins compiled for
> windows...

I do not know about this

> Eugen made the stuff so simple for debian that we forgot
> about windows.

Can we integrate his work into the official Debian in order to make it available for the univers :) ?

**Comment by kif** [comment]
On Sat, 25 Jun 2016 01:15:47 -0700
picca <notifications@github.com> wrote:

> > My question was rather if you had the LZ4 plugins compiled for
> > windows...
> 
> I do not know about this

so we will have to do it :(
 
> > Eugen made the stuff so simple for debian that we forgot
> > about windows.
> 
> Can we integrate his work into the official Debian in order to make it available for the univers :) ?

Not clean enough: there is one package which defines an environment
variable telling HDF5 where to look for its plugins. 
The second package actually contains the plugin. 

Debian would expect the first package to be integrated as a patch, redefining the plugin directory, in
the HDF5 package.
This needs to change the C-file directly.

Cheers,

**Comment by picca** [comment]
> so we will have to do it :(

This plugin system will be a big fail for hdf5.

now we will have unreadable files... with open source solutions.
this is a door open for DRM.

> Not clean enough: there is one package which defines an environment
> variable telling HDF5 where to look for its plugins.
> The second package actually contains the plugin.

> Debian would expect the first package to be integrated as a patch, redefining the plugin directory, in
> the HDF5 package.
> This needs to change the C-file directly.


do you know if this will be officially integrate into hdf5 ?

Cheers,

**Comment by kif** [comment]
On Sun, 26 Jun 2016 11:55:29 -0700
picca <notifications@github.com> wrote:

> do you know if this will be officially integrate into hdf5 ?

From a debian perspective, the minimum is to replace
"/usr/local/hdf5/lib/plugin"[1] with "/usr/share/hdf5/plugin" plus a
bunch of symbolic links, one per plugin.
This should be accepted by the debian maintainers of the HDF5 package.

**Comment by vasole** [comment]
Good news. I have managed to get the LZ4 plugin working for windows x64  and python 3.5.
Still to test on more data and to try to build for python 2.7.

**Comment by andygotz** [comment]
Great! Do we have the plugins installed and working on the rnice cluster?

Andy

**Comment by kif** [comment]
On Thu, 30 Jun 2016 12:53:37 -0700
Andy Gotz <notifications@github.com> wrote:

> Great! Do we have the plugins installed and working on the rnice cluster?

Those plugins are available on the rnice since Jan 23  2015 ... i.e a couple of days after the first Eiger was put in "production".
The issue is windows

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vasole** [comment]
hdf5plugin project created under the silx-kit umbrella.

The LZ4 shared libraries for Python 2.7 and Python 3.5 provided.

**Comment by vasole** [comment]
Done. If it does not work, please open issues at the silx-kit/hdf5plugin repository.
