### ISSUE TITLE
Create a provisional landing page

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#114]
Currently www.silx.org goes to wiki.edna-site.org. Until we have a proper landing page, it would be convenient to redirect it to the github project page.

**Comment by kif** [comment]
On Fri, 24 Jun 2016 08:21:32 -0700
V. Armando Solé <notifications@github.com> wrote:

> Currently www.silx.org goes to wiki.edna-site.org. Until we have a proper landing page, it would be convenient to redirect it to the github project page.

done

**Comment by kif** [comment]
close #114
