### ISSUE TITLE
[Dependency] numpy minimal version.

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1144]
It would be good to add the minimal version of numpy supported.
This mean get the minimal target between debian 7 (1.6) and debian 8 (1.8).
This mean knowing if we should drop debian7 or not.

For now I add the more constraining one for us (1.6).

**Comment by vasole** [comment]
The minimal versions warranted to work with silx are those shipped with Debian 8. Anything else is on best effort base.

**Comment by t20100** [comment]
Sounds reasonable.
But then, this means we stop providing Debian 7 packages... as those packages will surely breaks (if not already) as we develop on Debian 8 or more recent environments.

**Comment by t20100** [comment]
closes by #1145
