### ISSUE TITLE
[plot] BaseMaskToolsWidget - plot default

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1150]
signature is :  MaskToolsWidget(self, parent=None, plot=None)
but when passing plot to None:

    self.plot.sigInteractiveModeChanged.connect(
AttributeError: 'NoneType' object has no attribute 'sigInteractiveModeChanged'

From my understanding of the code : plot can't be None in BaseMaskToolsWidget, it should not have default parameter. Creating a new Plot has no sense.

**Comment by t20100** [comment]
Yes `plot` argument cannot be None which is default.
The thing is we want to have parent as the first argument of QWidgets and optional, so we need to provide a default value to all other arguments even if they are required.

Two options:
- Live with it, eventually adding an `assert plot is not None`.
- Allowing `plot` argument to be None or even removing it and adding `get/setPlot` methods and make sure the wiring of signals is done right.

To me this is not in the public API so it does not matter much.
