### ISSUE TITLE
[plot] reset for the plotWidget

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#1153]
Is there a way to resets the plotWidget to the default values? plotWidget.clear() works fine, but I want something that also acts on the axes and title.

**Comment by t20100** [comment]
At the moment, there's no such `factoryReset` method.

**Comment by mretegan** [comment]
Since I already subclass PlotWidget, I can write a small method to do what I want.

**Comment by t20100** [comment]
Or make a PR for it ;)

**Comment by t20100** [comment]
@mretegan will handle it on his side, so unless there is other demand for it, I propose to close this issue.

**Comment by mretegan** [comment]
Fine by me.
