### ISSUE TITLE
[silx view] directly open data from hdf5 path from the command line

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#1157]
It would be very practical if it was possible to supply an hdf5 path to directly display a given data array.

For example:
`silx view data.h5:/entry_1/instrument_1/detector_1/data`
or:
`silx view data.h5 --h5path=/entry_1/instrument_1/detector_1/data`

Often searching for the correct hdf5 path can be long, and it will only get worse once files are nexusified...

Maybe also add `--viewer=Cube` to choose the view ? 8-)

**Comment by vasole** [comment]
It should be already there...

In principle we should support URIs and silx convert is already taken care of them.

The syntax is:

filename::/path/to/dataset

and I guess silx view should also support

filename::/path/to/NXdataGroup

**Comment by t20100** [comment]
It's not supported in `silx view`

**Comment by vallsv** [comment]
It is not supported, but there is no problem to support it.

The GUI already support to display a subnode, then we only have to parsed it in `silx.io.open`.

There is maybe an issue with our `commonh5` memory management (if we want to try `filename.edf::/scan_0`), but we should not have problem with HDF5 files.
