### ISSUE TITLE
[debian] buildd failed in unstable with python3.6 during the run_tests

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1172]
Hello, it seems that there is a problem during the unit test with python 3.6.
I do not understand why it works with python 3.5 and not with python 3.6...

```
See 'prog help <command>' to read about a specific subcommand
I: pybuild base:184: env PYTHONPATH=/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build GPU=False SILX_OPENCL=False SILX_TEST_LAW_MEM=True xvfb-run -a --server-args="-screen 0 1024x768x24" python3.6-dbg run_tests.py -v
INFO:root:Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.5.0 from /<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build/silx
Traceback (most recent call last):
  File "run_tests.py", line 369, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
  File "/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build/silx/test/__init__.py", line 49, in suite
    from . import test_sx
  File "/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build/silx/test/test_sx.py", line 73, in <module>
    from silx.gui import qt
  File "/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build/silx/gui/qt/__init__.py", line 54, in <module>
    from ._qt import *  # noqa
  File "/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build/silx/gui/qt/_qt.py", line 110, in <module>
    from PyQt4.QtCore import *  # noqa
ModuleNotFoundError: No module named 'PyQt4.QtCore'
E: pybuild pybuild:283: test: plugin custom failed with: exit code=1: env PYTHONPATH=/<<BUILDDIR>>/silx-0.5.0+dfsg/.pybuild/pythonX.Y-dbg_3.6/build GPU=False SILX_OPENCL=False SILX_TEST_LAW_MEM=True xvfb-run -a --server-args="-screen 0 1024x768x24" python3.6-dbg run_tests.py -v
dh_auto_test: pybuild --test -i python{version}-dbg -p "3.6 3.5" -s custom "--test-args=env PYTHONPATH={build_dir} GPU=False SILX_OPENCL=False SILX_TEST_LAW_MEM=True xvfb-run -a --server-args=\"-screen 0 1024x768x24\" {interpreter} run_tests.py -v" returned exit code 13
debian/rules:64: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 25
make[1]: Leaving directory '/<<BUILDDIR>>/silx-0.5.0+dfsg'
debian/rules:27: recipe for target 'build-arch' failed
make: *** [build-arch] Error 2
```

**Comment by kif** [comment]
On Wed, 20 Sep 2017 08:31:57 +0000 (UTC)
picca <notifications@github.com> wrote:

> Hello, it seems that there is a problem during the unit test with python 3.6.
> I do not understand why it works with python 3.5 and not with python 3.6...
]
> ModuleNotFoundError: No module named 'PyQt4.QtCore'


I guess we are doing a try/except on "ImportError", not ModuleNotFoundError ...
This is surprising as we test on python3.6 in travis ... we have to investigate

**Comment by t20100** [comment]
@picca, from a look at the code, your situation should be that `import PyQt4` works (and selected the binding) but `from PyQt4.QtCore` fails... What is installed on the system where it's failing?

On our side we can probe the Qt binding by importing `Py????.QtCore` rather that `Py????`, but this situation looks weird.

**Comment by t20100** [comment]
... but that would be more complicated code to deal with `sip.setsipapi`

**Comment by vallsv** [comment]
`Qt4` is not anymore abailable right? Maybe the package `PyQt4` is still available for Python 3.6?

**Comment by picca** [comment]
On the buildd system, the packages installed are only the Build-Depends of the package so only PyQt5.
For me the problem is the ImportError vs ModuleNotFoundError.

**Comment by picca** [comment]
looking at here,  https://docs.python.org/dev/library/exceptions.html#exception-hierarchy it seems that catching via ImportError should work.

**Comment by picca** [comment]
AFter looking at the build log, it seems that python-qt4, and python3-pyqt4 are also installed.
So maybe there is an issue with the python3-qt4 module for python3.6

**Comment by picca** [comment]
ok the problem is in fabio, I forgot to add python3-pyqt4-dbg to python3-fabio-dbg.

I take care of this tomorrow

**Comment by t20100** [comment]
OK, that explains the fact that `PyQt4` is there but `PyQt4.QtCore` is not.

**Comment by t20100** [comment]
closing as it seems to be fixed, reopen if not
