### ISSUE TITLE
[silx view] Cannot view a 2D array of boolean as an image

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1177]
First reported in PR #1174

**Comment by vincefn** [comment]
It may be needed to convert the data to (u)int8 as matplotlib does not always display nicely bool values IIRC (values not shown when hovering pointer?)

**Comment by t20100** [comment]
From a quick look at it:
- matplotlib seems OK (at least on debian 8)
- the data viewer is not handling boolean dataset
- `min_max` function does not support it either (called when computing data range for the colormap).
- Probably other tools (profile, histogram, save?...) does not support boolean type (at least they have never been tested with booleans).
So simplest/safest would indeed be to convert to (u)int8.
