### ISSUE TITLE
Add a module to ease usage from console

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#118]
Proposal: Provide a module meant to be used from the console which detects python, ipython or jupyter and provides a 'flattened namespace' of the project + start QApplication and set Qt API version if necessary + run %pylab.

Usage: `from silx.pylab import *`... or any better name?

**Comment by vasole** [comment]
I think there are two different points there.

- The flattened module itself.
- The use of widgets from the console.

Both problems are solved in PyMca by providing just the flattened module (easy).

**Comment by vasole** [comment]
I guess this closed by #120. Further actions (use of widgets from the console) would need a separate issue.
