### ISSUE TITLE
Initial aspect ratio and colormaps for ImageView?

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#1185]
Hi,

Maybe this is documented but I can't find an answer.

I have a class inherited from `ImageView`. I'd like to keep the data aspect ratio and have a logarithmic color map from start, without having to click the buttons every time. How do I do this?

Here's the code,
https://github.com/alexbjorling/nanomax-analysis-utils/blob/master/apps/limaLiveViewer.py

**Comment by t20100** [comment]
Hi,

You can set data aspect ratio with: `self.setKeepDataAspectRatio(True)` (http://www.silx.org/doc/silx/0.5.0/modules/gui/plot/plot.html#silx.gui.plot.Plot.Plot.setKeepDataAspectRatio).

And you can set the default colormap to log scale with: `self.setColormap(normalization='log')` (http://www.silx.org/doc/silx/0.5.0/modules/gui/plot/imageview.html#silx.gui.plot.ImageView.ImageView.setColormap)

It not clear enough from the doc that `ImageView` also provides all functions from the `PlotWidget`.
`self.setColormap(normalization='log')` is working in last release (0.5.0) but it is borken in current github version, I'm fixing it now.

**Comment by alexbjorling** [comment]
Ah, I was only looking one level up in the inheritance tree, at `PlotWindow`.

And thanks for the fix.

**Comment by t20100** [comment]
Most of the plotting API is defined in silx.gui.plot.Plot in 0.5.0.
It will be defined in silx.gui.plot.PlotWidget in 0.6.0 as we merge those 2 classes (this should be transparent for the user).

**Comment by vasole** [comment]
BTW #639 should be closed with all those features, shouldn't it?
