### ISSUE TITLE
ImageView.setImage resets zoom with reset=False

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#1187]
Hi,

I am updating a live `ImageView` regularly, and the zoom is reset every time even if I specify `reset=False`. The line profile ROIs are not reset.

```python
self.setImage(image, copy=False, reset=False)
```

I'm on the 0.5.0 release.

**Comment by alexbjorling** [comment]
The actual code is here
https://github.com/alexbjorling/nanomax-analysis-utils/blob/master/apps/limaLiveViewer.py

**Comment by t20100** [comment]
My bad...
I've made a fix for it (it is part of Pull Request #1186: commit https://github.com/silx-kit/silx/pull/1186/commits/f2ba1aef4325ca3587a43bb3e4459f3328d0086b).
It will be available shortly in github and in 0.6.0 release (i.e., early October).

**Comment by alexbjorling** [comment]
Super, thanks for the quick response!

**Comment by t20100** [comment]
Better to fix it before the release!

**Comment by t20100** [comment]
Closed by  #1186
