### ISSUE TITLE
[OpenCL] interpolation & decimation

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1199]
Provide interpolation (nearest/bilinear) and decimation (Lanczos2/3) functions and a couple of kernel using them.

**Comment by vasole** [comment]
Besides sending a data buffer, will it be possible to have as input already existing OpenGL textures too? That would be great.

**Comment by kif** [comment]
On Fri, 06 Oct 2017 05:34:22 +0000 (UTC)
V. Armando Solé <notifications@github.com> wrote:

> Besides sending a data buffer, will it be possible to have as input already existing OpenGL textures too? That would be great.

I don't know if one can copy a texture to a buffer (beside copying pixel by pixel). I need to investigate.

**Comment by t20100** [comment]
I don't think you can do a conversion between texture and buffer without a copy, but the copy can be done on the device (with cl_khr_gl_sharing extension).
