### ISSUE TITLE
Localized numeric values are not correctly interpreted

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#1200]
I've found an issue (latest master) when using the silx viewer, on a French-localized computer (mac):

- open a stack of images from the silx viewer
- open the colormap dialog. The min/max values are printed with a dot as separator ('5.2')
- it is not possible to enter a new value with a  dot separator ('4.7') because (I assume) a localised float-format validation is enforced in the entry box (I guess Qt auto-recognised the locale)
- if I enter a comma-separated value ('4,7'), I get a popup widget with a 'ValueError', could not convert string to float, because silx expects the C locale
- the colormap dialog cannot be opened any more because it continues to remember the comma-separated value entered, which triggers an immediate ValueError which can't be corrected.

**Comment by vasole** [comment]
What happens is one starts the viewer as LC_ALL=C silx view ...?

**Comment by vincefn** [comment]
No difference, I also tried exporting in the console:
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

Even with all the console LC* variables to en values, it still does not work. 

Looks like Qt gets the localisation parameters directly from the OS GUI/environment. Can you call setLocale globally for the whole Qt application or specifically for Validators ?

**Comment by vasole** [comment]
@vallsv 

Well, for the case of silx view, I would say it should force the locale. We are not at the library level and therefore an application should be allowed to do so.

**Comment by vincefn** [comment]
Still in the silx viewer, the input field for the iso surface level in the **3D** view correctly accepts localised input values (2,1).
@t20100 you know why is that input correctly handling the locale ?

This being said, forcing the C locale for the silx viewer should be fine for anyone, if it can be done with Qt. (I had a similar issue with wx and Fox a few years ago, and it turned out the only way I could use validators for fields was to use the OS locale - I did not manage to change it globally for the app, there were cases this did not work)

**Comment by vasole** [comment]
I guess the code below should do the job:

```
from silx.gui import qt
qt.QLocale.setDefault(qt.QLocale.c())
```

**Comment by vincefn** [comment]
Seems to do the trick if added right after (in silx/app/view.py, Viewer.__init__): `qt.QMainWindow.__init__(self)`

**Comment by t20100** [comment]
@vincefn, for the isolevel in the parameter tree in the 3D view, the editor/display widgets are managed by `QStyledItemDelegate` while in the colormap dialog the conversion text from/to float is done with Python.

**Comment by vallsv** [comment]
First exception
```
ERROR:silx.gui.qt._qt:<type 'exceptions.ValueError'> invalid literal for float(): 0,000352461   File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/ColormapDialog.py", line 485, in _minEditingFinished
    if self._minValue.value() > self._maxValue.value():
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/ColormapDialog.py", line 94, in value
    return float(self.text())
```

Second blocking exception
```
ERROR:silx.gui.qt._qt:<type 'exceptions.ValueError'> invalid literal for float(): 0,000352461   File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/actions/control.py", line 363, in _actionTriggered
    self._dialog.setDataRange(dataMin, dataMax)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/ColormapDialog.py", line 396, in setDataRange
    self._plotUpdate()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/ColormapDialog.py", line 253, in _plotUpdate
    start, end = self._minValue.value(), self._maxValue.value()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/ColormapDialog.py", line 94, in value
    return float(self.text())
```

**Comment by vallsv** [comment]
Setting C local is not enough. A comma is a valid separator for thousand then the exception can still occur.

**Comment by vasole** [comment]
It is a valid separator for thousand that is unsupported by python itself regardless the locale used.

**Comment by vasole** [comment]
Are we aiming at things like this?

```
def myFloat(x):
    try:
        return float(x)
    except ValueError:
        if ',' in x:
            try:
                if '.' in x:
                    return float(x.replace(',','""))
                else:
                    return float(x.replace(',','.'))
            except:
                return float(x)
        elif '.' in x:
            try:
                return float(x.replace('.',','))
            except:
                return float(x)
        else:
            raise
```

**Comment by vincefn** [comment]
I think the correct way to convert would be to use locale.atof(), if pyqt does not provide a higher method to get data from a numeric field, and if it's not possible to set the locale globally.

**Comment by vasole** [comment]
It is possible to set the locale globally.

What I find not correct is to set the locale at a widget level. An application might want to keep using the user locale.

To use locale.atof() is not thread safe.
