### ISSUE TITLE
[NXdataViewer] Toggle points/line/line-points action does not work

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1207]
Nothing happens when clicking on the icon.

**Comment by t20100** [comment]
For me, this is working for curves but not for scatter plots (i.e., when you give a value to each (x, y) point).

BTW, there is an issue when calling `ArrayCurvePlot.setCurveData` without 'ylabel' argument.

**Comment by PiRK** [comment]
The reason why a scatter is displayed is that the `mr` dataset is not monotonically increasing. In fact, it is monotonically decreasing. Should we interpret a monotonically decreasing axis as a curve too?.

**Comment by vasole** [comment]
Yes. Always decreasing or always increasing can be nicely represented by a line :-)

**Comment by t20100** [comment]
Sounds right.
Nexus does not provide a description of whether it is a curve or a scatter plot?

**Comment by vasole** [comment]
Not as far as I know. I always allow the user to show the lines. If that makes sense or not is not my problem then :-)
