### ISSUE TITLE
[Tomo] FBP test fails under windows

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1237]
investigation under way

**Comment by kif** [comment]
the computer has 3 drivers: intel, amd and nvidia. 
the one selected for running the tests is:
'GeForce GT 640' on 'NVIDIA CUDA'

I will test all 3 devices and check if any of them works

**Comment by kif** [comment]
It works when using Intel and AMD CPU driver.

**Comment by kif** [comment]
using the CPU code on the GPU does not help,
nor using volatile shared arrays.

**Comment by kif** [comment]
@pierrepaleo  do you have an idea ?

**Comment by kif** [comment]
Compiles neither on MacOS

**Comment by vasole** [comment]
I confirm it runs smoothly on CPU under windows.
On GPU, the example does not generate a good sinogram.

**Comment by vasole** [comment]
Closed by #1247
