### ISSUE TITLE
Sphinx version

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#125]
After merging PR #123, sphinx (1.2.3) gave me an error when building the doc:
`sphinx.errors.ThemeError: no theme named 'classic' found (missing theme.conf?)`

I fixed it by upgrading my sphinx to 1.4.4. 

I can see the same problem on the nightly build log. Maybe a sphinx upgrade is necessary on the server.

**Comment by kif** [comment]
Actually, it is event a FBFS on debian 8
 
sphinx.errors.ThemeError: no theme named 'classic' found (missing theme.conf?)
debian/rules:25: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/kieffer/workspace/silx/package/silx-0.2.0a0'
debian/rules:13: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Build failed, please investigate ...
