### ISSUE TITLE
[profile] won't show the profile window

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1256]
Under windows PC.
When I launch the silx view and display some dataset using the `Image` and `Image stack` views :
- if I am on full screen mode the profile window won't appear (and won't be launched, I can't see them)
But if I am not on the full screen mode then It work ??? !!!
- if not on full screen mode work perfectly.

Don't know where the issue is (profile window, viewer or somewhere in the middle).

**Comment by PiRK** [comment]
`silx.gui.plot.Profile.ProfileToolBar._showProfileMainWindow` is the obvious suspect.
