### ISSUE TITLE
Avoiding C dependency to numpy from cython?

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1263]
Following #1261, how important is it to avoid depending on numpy as C level?

If we want to keep doing so, it would be good to have some unified definition of sized types.

**Comment by vasole** [comment]
The relevance is if one considers the code is usable as C code (outside of Python). If the code will never be used outside Python, that it is not a big deal.

In principle one solves those problems using the C99 header stdint.h and dealing with the VS2008 case separately. For instance, what I had to put to get bitshuffle compatible with VS2008:

```
#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)   /* C99 */
# include <stdint.h>
#else
typedef unsigned char       uint8_t;
typedef unsigned short      uint16_t;
typedef unsigned int        uint32_t;
typedef signed int        int32_t;
typedef unsigned long long  uint64_t;
typedef long long           int64_t;
#endif
```

**Comment by vasole** [comment]
I had missed the point "from cython". If it is at cython level, I would not expect major issues from the numpy dependency.

**Comment by vallsv** [comment]
FYI, here is the numpy file defining all thous types https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_common.h

**Comment by vasole** [comment]
No problem to use numpy types.
