### ISSUE TITLE
[plot] Saving a 2D plot as an image

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#1266]
I get the following error:

```
Traceback (most recent call last):
  File "/home/retegan/.local/lib/python3.5/site-packages/silx/gui/plot/actions/io.py", line 394, in _actionTriggered
    return self._saveImage(filename, nameFilter)
  File "/home/retegan/.local/lib/python3.5/site-packages/silx/gui/plot/actions/io.py", line 326, in _saveImage
    rgbaImage = image.getRgbaImageData(copy=False)
  File "/home/retegan/.local/lib/python3.5/site-packages/silx/gui/plot/items/image.py", line 306, in getRgbaImageData
    **colormap)
TypeError: applyColormapToData() argument after ** must be a mapping, not Colormap
```

**Comment by t20100** [comment]
This was fixed in https://github.com/silx-kit/silx/commit/85868bcad28fd83ee87bdbb96009cb7991aa1110#diff-7540662c18f8403026a60e0f604dbb56 which is included in v0.6.0.

Which version are you running? and how did you installed if?

**Comment by mretegan** [comment]
I was on a three week-old version of silx; updating to the current fixed the issue. Sorry about that. 

Regarding the feature however, saving a 2D plot as an "Image as PNG" results in a different image than what is shown on screen, regardless of how I set the aspect ratio of the plot. If I save it as a "Plot Snapshot as PNG" the aspect ratio is kept. Is this done on purpose?

**Comment by t20100** [comment]
Saving "Image as PNG" convert the data to RGBA and saves it as an image with the same shape as the original data regardless of aspect ratio and image scale.

Saving "Plot Snapshot as PNG" takes a snapshot of the widget and so keeps aspect ratio, image scale and the size of the snapshot is that of the widget.

I don't know how we could explain it better in the GUI.

**Comment by vasole** [comment]
No clear solution. I think I was using "Image as PNG" and "Widget as PNG"

**Comment by vasole** [comment]
Can this be closed?
