### ISSUE TITLE
[plot] Mask: Use different color for the current selection and the mask

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1270]
As it is, when drawing an opaque mask, it is not possible to see the currently drawn polygon (and in particular the starting point) as the same color is used to display both the mask and the drawn polygon.

**Comment by vallsv** [comment]
I try 2 different ways
- Adding a black border
- Dotted lines using 2 colors: black+maskcolor

![screenshot from 2018-01-29 11 33 22](https://user-images.githubusercontent.com/7579321/35506634-d8f5762c-04e1-11e8-9c5a-103aa57557b2.png)

Anyway both request some refactoring plus some changes on the MPL and OpenGL backend, then i think it will not be for the Silx release 0.7.

**Comment by vallsv** [comment]
My ugly test, in case https://github.com/vallsv/silx/commit/088a140d245c0d92d2c5a80371277ae2eb5b5408
