### ISSUE TITLE
[v0.6] Wheel for macOS

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1271]
Seems that silx dependencies (h5py...) are not taking into account when installing the wheel under macOS.

**Comment by kif** [comment]
On Sun, 08 Oct 2017 12:04:41 +0000 (UTC)
payno <notifications@github.com> wrote:

> Seems that silx dependencies (h5py...) are not taking into account when installing the wheel under macOS.

Hi Henri,

I hope you enjoy Barcelona.

The only "strict" dependency are numpy and setuptools ... silx can be installed without h5py, PyQt or pyopencl.

Do you believe this is a bug ?

Cheers,

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vasole** [comment]
It is certainly not a bug because it is our choice.

If I remember well, for a "complete" or "almost complete"installation one has to use the requirements file:

https://github.com/silx-kit/silx/blob/master/requirements.txt

**Comment by payno** [comment]
ok my bad.
yes using the requirements work.
I haven't see the installation. Someone came to me after the talk saying 'dependencies' where not installed. But I fought h5py was on it.
