### ISSUE TITLE
[debian8 package] app issue ?

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1272]
Someone at icalepcs try to install silx from the debian8 package with root rights and he the executable (silx view, six convert...) where not correctly installed.

I made the installation using a clone of project.
Didn't had enough time to confirm the issue but a check on the installation of the executable would be nice to be sure.

**Comment by kif** [comment]
On Sun, 08 Oct 2017 13:33:20 +0000 (UTC)
payno <notifications@github.com> wrote:

> Someone at icalepcs try to install silx from the debian8 package with root rights and he the executable (silx view, six convert...) where not correctly installed.
> 
> I made the installation using a clone of project.
> Didn't had enough time to confirm the issue but a check on the installation of the executable would be nice to be sure.

I just checked the packages and the look OK.
Did you install silx or python3-silx ? 
The former contains the scripts for installation which are used by the
later. python2-silx is not used by silx executable.

Cheers,
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vasole** [comment]
Remember we can start the program without the scripts. From the code camp slides:

![image](https://user-images.githubusercontent.com/5636251/31327560-647829c0-acd0-11e7-865d-4561f2eb9e1a.png)

**Comment by t20100** [comment]
I just installed silx (not only python*-silx) on my debian 8 machine and it works fine.

**Comment by vasole** [comment]
As far as I have understood, the script is tied to a particular version of the silx python library.

If one installs the library and not the script, one has to use the python(3) -m silx approach.

**Comment by t20100** [comment]
The scripts are in a `silx` package which uses `python3-silx`.
If only `python*-silx` is installed, yes, the corresponding `python* -m silx` should be used.

**Comment by payno** [comment]
Ok that it.
He followed the instructions from the documentation,
which goes for 
```
sudo apt-get install python-silx python3-silx
```
Maybe since we have executable a warning/note should be added ?

**Comment by vasole** [comment]
Why? If one installs silx as apt-get install silx the dependencies should be there.

**Comment by vasole** [comment]
I think if the guy followed the documentation, then the documentation should follow the silx pacakge and the ways to start the application written above.
