### ISSUE TITLE
[gui] silx tests do not pass with matplotlib 2.1.0 (at least under windows)

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1273]
To reproduce just install latest matplotlib and silx and run silx test.

It gets a recursive QWidget:::repaint: Recursive repaint detected.

My system:

python 3.6.2
silx 0.6.0
matplotlib 2.1.0
PyQt5 5.8
Qt 5.8.0

**Comment by t20100** [comment]
This comes from a change of behavior in matplotlib and the fact that we override the `draw` method in the backend to use matplotlib blitting feature to redraw faster when not change is made.
I have to check if the fix is as simple as renaming our `draw` method (not sure)...
