### ISSUE TITLE
Projection from silx.opencl.projection has AttributeError

### ISSUE THREAD

**Issue by jcesardasilva** [silx-kit/silx#1279]
Hi, 
I am using Silx in Ubuntu 16 and with python 2.7.12 and, when I try to using the module Projection from silx.opencl.projection, I get and AttributeError. Please, see below what I am trying to do. It was just for testing. 
 
```
In [1]: from silx.opencl.projection import Projection
In [2]: my_slice=np.arange(2048*2048).reshape((2048,2048))
In [3]: n_angles = 320
In [4]: my_axis_pos = (my_slice.shape[1]-1)/2.0
In [5]: P = Projection(my_slice.shape, angles=np.linspace(0, np.pi, n_angles, Fa
   ...: lse), axis_position=my_axis_pos)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-2f64ea5b43c8> in <module>()
----> 1 P = Projection(my_slice.shape, angles=np.linspace(0, np.pi, n_angles, False), axis_position=my_axis_pos)

/usr/local/lib/python2.7/dist-packages/silx/opencl/projection.pyc in __init__(self, slice_shape, angles, axis_position, detector_width, normalize, ctx, devicetype, platformid, deviceid, profile)
     89         OpenclProcessing.__init__(self, ctx=ctx, devicetype=devicetype,
     90                                   platformid=platformid, deviceid=deviceid,
---> 91                                   profile=profile)
     92         self.shape = slice_shape
     93         self.axis_pos = axis_position

/usr/local/lib/python2.7/dist-packages/silx/opencl/processing.pyc in __init__(self, ctx, devicetype, platformid, deviceid, block_size, profile)
    120             self.ctx = ctx
    121         else:
--> 122             self.ctx = ocl.create_context(devicetype=devicetype, platformid=platformid, deviceid=deviceid)
    123         device_name = self.ctx.devices[0].name.strip()
    124         platform_name = self.ctx.devices[0].platform.name.strip()

AttributeError: 'NoneType' object has no attribute 'create_context'
```

**Comment by t20100** [comment]
Hi,

It looks like pyopencl is not installed. For OpenCL processing, you also need to install Mako.

If you want to install all silx dependencies with `pip`, you can download this requirements file: https://github.com/silx-kit/silx/blob/master/requirements.txt and run `pip install -r requirements.txt`

**Comment by jcesardasilva** [comment]
Well, Mako is installed in my computer and I am not using any virtual environment. See below.
```
pip install mako
Requirement already satisfied: mako in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from mako)
```
All the requirements for Silx are already satisfied. I did the install via pip and via cloning of github, but neither of them fixes this issues.

**Comment by t20100** [comment]
Ok, then if `pyopencl` is installed, the other possibility for `ocl` to be `None` is that there is no opencl device available (i.e., drivers are not installed).

You can check which platforms and devices are available either with the `clinfo` tool or with:
```
import pyopencl
for platform in pyopencl.get_platforms():
    print(platform, platform.get_devices())
```

**Comment by jcesardasilva** [comment]
Ah, this can be. It seems this computer does not have a device in the platform. So, this means I cannot run this module in such a computer, right?
```
~$ clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.0.7
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Clover
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.

```

**Comment by t20100** [comment]
It means you have to install the drivers: *-opencl-icd package corresponding to your hardware (e.g., Intel GPU or Nvidia GPU with proprietary drivers?).
OpenCL can run on both CPU and GPU but it needs the appropriate driver.

**Comment by jcesardasilva** [comment]
Thank you very much. This improved, but now I got another error related to CFFI. I tried with python3 too and the same error appears. It is a runtimeerror now claiming image format not supported, but I am not passing any image yet, only creating the propagator. See below:
```
P = Projection(my_slice.shape, angles=np.linspace(0, np.pi, n_angles, Fa
   ...: lse), axis_position=my_axis_pos)
   ...: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-f4225df5939e> in <module>()
      3 n_angles = 320
      4 my_axis_pos = (my_slice.shape[1]-1)/2.0
----> 5 P = Projection(my_slice.shape, angles=np.linspace(0, np.pi, n_angles, False), axis_position=my_axis_pos)

/usr/local/lib/python3.5/dist-packages/silx/opencl/projection.py in __init__(self, slice_shape, angles, axis_position, detector_width, normalize, ctx, devicetype, platformid, deviceid, profile)
    152             self.allocate_slice()
    153         else:
--> 154             self.allocate_textures()
    155         self.allocate_buffers()
    156         self._ex_sino = np.zeros((self._dimrecy, self._dimrecx),

/usr/local/lib/python3.5/dist-packages/silx/opencl/projection.py in allocate_textures(self)
    202                     pyopencl.channel_order.INTENSITY,
    203                     pyopencl.channel_type.FLOAT
--> 204                 ), hostbuf=np.ascontiguousarray(self._tmp_extended_img.T),
    205             )
    206 

/usr/local/lib/python3.5/dist-packages/pyopencl/cffi_cl.py in __init__(self, context, flags, format, shape, pitches, hostbuf, is_array, buffer)
   2732             desc.buffer = buffer
   2733 
-> 2734             self.__init_dispatch(context, flags, format, desc, hostbuf)
   2735         else:
   2736             # legacy init for CL 1.1 and older

/usr/local/lib/python3.5/dist-packages/pyopencl/cffi_cl.py in __init_dispatch(self, *args)
   2597         if len(args) == 5:
   2598             # >= 1.2
-> 2599             self.__init_1_2(*args)
   2600         elif len(args) == 6:
   2601             # <= 1.1

/usr/local/lib/python3.5/dist-packages/pyopencl/cffi_cl.py in __init_1_2(self, context, flags, fmt, desc, hostbuf)
   2610         ptr = _ffi.new('clobj_t*')
   2611         _handle_error(_lib.create_image_from_desc(ptr, context.ptr, flags,
-> 2612                                                   fmt.ptr, desc.ptr, c_buf))
   2613         self.ptr = ptr[0]
   2614 

/usr/local/lib/python3.5/dist-packages/pyopencl/cffi_cl.py in _handle_error(error)
    643     _lib.free_pointer(error.msg)
    644     _lib.free_pointer(error)
--> 645     raise e
    646 
    647 # }}}

RuntimeError: clCreateImage failed: IMAGE_FORMAT_NOT_SUPPORTED

```

**Comment by kif** [comment]
On Tue, 10 Oct 2017 05:54:27 -0700
Julio Cesar da Silva <notifications@github.com> wrote:

> Hi, 
> I am using Silx in Ubuntu 16 and with python 2.7.12 and, when I try to using the module Projection from silx.opencl.projection, I get and AttributeError. Please, see below what I am trying to do. It was just for testing. 

Hi Julio,

We know the forward projector is not (yet) properly working. 
Only the backprojection is working for now (with filtering on CPU) 
We left the code but is untested and undocumented.

You issue highlights the importance of the tomography tools. 
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
On Tue, 10 Oct 2017 13:59:49 +0000 (UTC)
Julio Cesar da Silva <notifications@github.com> wrote:

> Ah, this can be. It seems this computer does not have a device in the platform. So, this means I cannot run this module in such a computer, right?
> ```
> ~$ clinfo
> Number of platforms                               1
>   Platform Name                                   Clover

Clover is often an issue ... 
do you have a nvidia card with nouveau or an AMD one ?

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by jcesardasilva** [comment]
Thank you Jerome, Thank you Thomas. In fact, for my work here, a fast projector is much more important than the backprojector. I wrote an iterative projection alignment which does the projection (using the projector) about 30 times for a nice convergency. Today it is very slow and I thought of using Silx projector which is supposed to be faster than mine. 
Anyhow, I will be interested in learning when the Silx Projector is more robust. For the moment, I am considering to use another computer for this, like the ones in OAR if it works.

**Comment by jcesardasilva** [comment]
I ran the Silx Projector in another computer and everything work smoothly and nicely. Once had to install pyopencl (pip install pyopencl) in my virtual env. The projector took about 2 seconds for an array of 2048 x 2048, while my previous projector took about 50 seconds. So, I am adopting the Silx projector and I am going to close the issue.

**Comment by kif** [comment]
On Tue, 10 Oct 2017 16:07:43 +0000 (UTC)
Julio Cesar da Silva <notifications@github.com> wrote:

> I ran the Silx Projector in another computer and everything work smoothly and nicely. Once had to install pyopencl (pip install pyopencl) in my virtual env. The projector took about 2 seconds for an array of 2048 x 2048, while my previous projector took about 50 seconds. So, I am adopting the Silx projector and I am going to close the issue. 

Thanks for the feed-back. 
It is very important for us to know where it works (and where it does
not) as the code (kernels) chosen may vary. Can you validate the
results are correct as well ? Since Pierre left, we are missing a
specialist who is able to validate the code.

Tomography is a unknown territory for us.

Cheers,

Jerome
