### ISSUE TITLE
[project] Banches names

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1284]
The last version of silx uses the name
- `v0.6`
While others uses the name
- `0.5.0`
- `0.4.0`

It looks like all this names are faulty.
The branch name should not contains the `v` (reserved for tag versions) prefix, and should not contains the third digit (which is also reserved for the tag version).

Than i would rename all this branches, as it is done in PyFAI: `0.6`, `0.5`, `0.4`, `0.3`

**Comment by vasole** [comment]
There should be a branch per minor release number and a tag for each release. Example: a branch 0.6 with the tags v0.6.0, v0.6.1, ...

**Comment by vallsv** [comment]
Done
