### ISSUE TITLE
[PyPI] Provide link to silx home page in package metadata.

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1292]
Home page should point to www.silx.org and bug tracker to the issues in GitHub.

**Comment by t20100** [comment]
I couldn't find how to set the bug tracker URL from setup.py.

**Comment by PiRK** [comment]
It seems this is another feature that has been removed from the PyPi web interface. I could not find anything either.

Can we remove the 0.6.1 milestone?

**Comment by vasole** [comment]
What it cannot be found is the bug tracker. The home page (www.silx.org) should be there.

**Comment by PiRK** [comment]
This part of the issue can be closed (#1319).

**Comment by t20100** [comment]
Closed by #1319
