### ISSUE TITLE
PlotWidget test failing with matplotlib 1.5.0 -- 2.0.2

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1330]
```
python run_tests.py --installed silx.gui.plot.test.testPlotWidget.TestPlotWidget.testResizeWidget
INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.6.1 from /users/knobel/.local/lib/python2.7/site-packages/silx
F
Stderr:
ERROR:silx.gui.plot.test.utils:Plot is still alive

======================================================================
FAIL: testResizeWidget (silx.gui.plot.test.testPlotWidget.TestPlotWidget)
Test resizing the widget and receiving limitsChanged events
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/plot/test/testPlotWidget.py", line 142, in testResizeWidget
    self.assertNotEqual(listener.callCount(), 0)
AssertionError: 0 == 0

----------------------------------------------------------------------
Ran 1 test in 1.548s

FAILED (failures=1)
```
Spotted on Debian9.
Installing matplotlib 2.1.0 fixes the issue.

**Comment by PiRK** [comment]
Issue confirmed also on Windows, with matplotlib==2.0.0, 2.0.1, 2.0.2. Fixed with 2.1.0rc1 and later.

**Comment by PiRK** [comment]
Actually, the problem starts to appear with matplotlib 1.5.0. Version 1.4.3 was working..

**Comment by vasole** [comment]
Strange. I have been using those versions of matplotlib and running the tests (for instance in July when matplotlib 2.1.0rc was not out yet)

**Comment by PiRK** [comment]
I see that it is a fairly recent test (https://github.com/silx-kit/silx/commit/e6cdb232241d2f6b45d8c24a3429fb93fd099da4#diff-7656a5e1909820d7f7b07d8bdb3e2788). 

Additional info: the `Axis.sigLimitsChanged` is correctly emitted as expected when zooming in with the mouse, when resetting the zoom with the toolbar action, and when activating/deactivating the keep aspect ratio action.  
It is not emitted when resizing the window with the mouse nor when calling `Axis.setLimits`.
