### ISSUE TITLE
Zenodo did not automatically create a DOI for v0.6.1

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1367]
Should we try deleting the release&tag on github and restarting the tagging process from scratch ?

**Comment by vallsv** [comment]
Asking them by mail should be enough no?

**Comment by PiRK** [comment]
I contacted Zenodo via their support web page.

**Comment by PiRK** [comment]
That was swiftly fixed by Zenodo's support: 
> From a brief investigation, we found that during the release process, there was probably an issue either on our network or storage stack, which interrupted the transfer of the release zipball from GitHub. I restarted the process and the release seems to be published now at "https://zenodo.org/record/1115640" under the DOI "10.5281/zenodo.1115640".
