### ISSUE TITLE
[CI] Test environment for python2 on OSX is broken on Travis

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1373]
```
$ python -m pip install --upgrade pip
/usr/bin/python: No module named pip
```

**Comment by vallsv** [comment]
It was working yesterday. Then maybe a transitional problem.

**Comment by t20100** [comment]
This should be the reason: https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

**Comment by t20100** [comment]
Answer from Travis: #8835

**Comment by t20100** [comment]
In the meantime, #1372 will do the job

**Comment by t20100** [comment]
we do no more test python2 on macOS
