### ISSUE TITLE
[View] NxData not recognized

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1407]
Data produced by pyFAI-difmap not recognized/interpreted by "silx view"

**Comment by vallsv** [comment]
Checked with @PiRK.

The NXdata from Soleil will be difficult to support. We don't really understand what they wanted to plot. They provide:
- data: a list of spectrum per motor position (requested as spectrum interpretation).
- 4 axes for the motor axes (the one which is slided, as result not displayed on the plot)

There is no problem to support the NXdata from diff_map. It will be supported by PR #1409
- `axes` from `q` is not needed
- it can be reworked using attribute on the NXdata group, and removing everything else:
```
interpretation="spectrum"
signal="data"
axes="q"
```
