### ISSUE TITLE
How to access Spec shared memory?

### ISSUE THREAD

**Issue by maurov** [silx-kit/silx#1415]
Hello,

I would like using Silx instead of Oxidis/Pymca for showing live data on the beamline at the ESRF. For this I need to access the shared memory of Spec (image_data, SCAN_D, etc,)  Do you have an example showing how this could be performed?

Thanks,
Mauro

PS: I apologize if this is not the right place to ask this question.

**Comment by vasole** [comment]
PyMca is currently the only distribution channel of the module.

If what you want is to avoid importing it from PyMca I think you will have to copy the module from the PyMca sources and add it to your own project.

**Comment by maurov** [comment]
@vasole OK, I can import the `spswrap` module from PyMca, no problem with that.

I would like to have an example how to run a Plot1D/Plot2D widget in an application continuously showing the SCAN_D/image_data from a Spec session when the memory is updated. What would be the best way to do this?

**Comment by vallsv** [comment]
That's an interesting question. It sounds good to move it somewhere outside PyMCA if possible.

**Comment by vasole** [comment]
@maurov 

The question belongs then to a PyMca and not to silx

@vallsv 

- sps does not comply with "windows, linux, Mac" if not it would be already in silx
- Probably something based on SpecClient would be more appropriate
- it only makes sense to use sps on machines where SPEC is installed therefore PyMca is not a "heavy" dependency in that case as PyMca is usually installed on those machines
- I do not intend to maintain multiple sps distribution channels

**Comment by vasole** [comment]
@maurov 

In the examples directory of silx, you have a module to update a plot from a thread:

https://github.com/silx-kit/silx/blob/master/examples/plotUpdateFromThread.py

I guess it is that what you need.

**Comment by maurov** [comment]
@vasole

Yes, that's exactly the example I was looking for! OK, I have to admit that my initial question was not correctly stated, sorry for that.

Just for documentation, I have obtained what wanted by:

1) `from PyMca5.PyMcaIO import spswrap`
2) redefine the `run` method in `UpdateThread`

Thanks for the help!
