### ISSUE TITLE
[silx view] We can display many time the same colormap dialog

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1429]
For example if we open it from different `DataView`s (2d and stack).
Then it is not really the same dialog.
It is normal, it is not a big problem, it is difficult to fix, but it is here.

**Comment by t20100** [comment]
For the `DataView`s we could use a checkable colormap action that show/hides the `ColormapDialog`.

For this we need a new colormap action and that `DataView`s use `PlotWidget` and adds the toolbars to it (to use the new colormap action)...

**Comment by vallsv** [comment]
Sounds good then i make a try. But it looks difficult. The relation between colormap action and plot is one-to-one (the relation between QAction and QToolbar is also one-to-one). it will require a lot of code, and a non generic one (dependency with the plot API).

**Comment by t20100** [comment]
A way to do it is to make a colormap action that takes a `Colormap` object as parameter rather than getting it from the plot. It is then the application (here the `DataView`) that does the synchronization.
Maybe worth discussing it.

**Comment by vallsv** [comment]
Iv got a working concept by injecting a unique ColorDialog into each ColormapAction.

Ill do a try as you said. Forcing a specific colormap sounds good.

**Comment by vallsv** [comment]
By using a single colormap action we lose the concept of plot, and then we can't update the dialog using the plot. It looks to be more and more a hack -_-.

**Comment by t20100** [comment]
Yes it only works if you always use the same colormap object over all the plots, otherwise it fails.
Maybe we can discuss that.

**Comment by vallsv** [comment]
Closed via #1428.
