### ISSUE TITLE
[specfile] add backward compatibility layer with previous specfile

### ISSUE THREAD

**Issue by maurov** [silx-kit/silx#143]
Hello,

It would be nice to have a compatibility layer between specfile in SILX and specfile in PyMca. This would permit to upgrade all scripts reading SPEC files via the PyMca API replacing a single line:

 `from PyMca5.PyMcaIO import specfilewrapper as specfile`

with

`from silx.io.specfile import SpecFile as specfile`

Thanks,
Mauro

**Comment by vasole** [comment]
Closed by #163
