### ISSUE TITLE
[silx view] Complex view colormaps

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1448]
With the last integration of `silx view` and improvement of the `colormap dialog` It is possible to improve colormap management in the complex viewer, by sharing colormaps with same "physical data":
- a single one for the amplitudes info (r, i, |x|)
- a single one for the phases (or a little more)

That's just an idea, and the usability have to be tested. What do you think about @t20100?

**Comment by t20100** [comment]
Maybe it is enough indeed.

@vincefn, do you think it would be better this way?

**Comment by vincefn** [comment]
I'm not sure what is the proposed change. If it is just using the same colormap for all real-valued data (r, i, |x|)), then sure it is a good idea.

**Comment by t20100** [comment]
Yes this is it, thanks.
