### ISSUE TITLE
[fabioh5] Use more convenient type for counters and positioners

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1450]
The convertion of EDF headers use the smallest binary type available to code a string header, in order to have an accurate value with the smallest memory usage.

```
foo: 0
foo2: 1.1
foo3: bar
```
In this case `foo` will be a `uint8`, `foo2` an `float16` or `float32`, `foo3` a string.

Feedback from @vasole, it would be better to use less types for counters and positioners cause it is not very convenient to work with, and it can introduce calculation problems.

Then
- It would be good to only use 2 types for numbers: `float32` and `int32`, else the counter/positioner expect a bigger precision. As result avoid `unisigned int`, avoid type smaller than 32 bits.
- It would be even better to use only 2 types for the whole counter/positioner: one for integers, one for floats. Then if one of the counter/positioner request a 64 bits floating point precision, all counters/positioners requesting floating point will use 64 bits precision.

**Comment by vallsv** [comment]
Let me know it the issue is well described.

**Comment by vasole** [comment]
Yes, it is properly described. Implementing the first of the two points it is already enough to me.

The second one is aesthetically desirable but it might be counter productive (one could use a counter to normalize a stack of float32 data and then generate a stack of float64 data if care is not taken).
