### ISSUE TITLE
[Plot] Add colormap object

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#146]
We could create a colormap object:
- It could still be accessed as a dictionary 
- It would be simpler to define colormaps
- Easy to manipulate

**Comment by vallsv** [comment]
After a talk with Thomas, and following the refactoring he did on plot items, it would be nice to:
- Refactoring the plot3d colormap as a non mutable plot object (should be easy)
- Then
    - provide setters and events
    - connecting it to the item objects
    - updating the GUI manipulating colormap

**Comment by payno** [comment]
After a discussion with @t20100 and @vallsv, the Colormap object should be included in the silx.gui.plot and used by plot and plot3d modules. It should also :

- not contained the 'autoscale' variable should be replaced by None values for vmin and vmax.
- None is a valid value for vmin and vmax
- Colormap object should have a changed signal
- Should have a copy function
- should have a __getitem__ function
- should have a fromDict and getDict function
- should have a getColorMapRange function (returning the vmin, vmax tuple )
- should have a getColorMapLut fonction returning the list of colors for this colormap
- should have an applyColormap(data, vmin, vmax) function
- should have a copy function

**Comment by t20100** [comment]
Closed by #898
