### ISSUE TITLE
[plot] format definition for saving a plot as HDF5

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1462]
I see the need for saving plots as NXdata, for users to export displays into other applications. But while I was working on #1442 , I noticed several NXdata limitations that make it difficult to save a complex plot. For instance, it seems difficult to stretch the NXdata specifications to save multiples curves with different number of samples, or to save a mix of curves, images... 

A complete format would, however, be very useful for us to save plot "sessions" for silx applications.

i'm wondering if it would make sense for us to define our own format, ignoring NXdata completely, or if we should use NXdata for individual plot items (curves, images...) and regroup them inside a plot group with additional metadata.

The solution based on NXdata could look like:

```
plotName
    @class = "silx_plot"
    @title = "Plot title"
    @xaxis_scale = "linear"
    @yaxis_scale = "logarithmic"
    @xlabel = "channels"
    @ylabel = "count"
    curve1_name: 
        @NXclass = "NXdata"
        @legend = "my first spectrum"
        @signal = "y"
        @axes = "x",
        y = float32(1024)
            @long_name = "curve y label (possibly different from plot y label)"
        x = int32(1024)
            @long_name = "curve x label"
    image1_name:
        @NXclass = "NXdata"
        @legend = "pretty background image"
        @signal = "image"
        @axes = ".",  "x"
        image = float32(100, 1024)
        x = int32(1024)
            @long_name = "image x label"
...
```

A solution without NXdata could look like
```
plot
    @class = "silx_plot"
    @title = "Plot title"
    @xaxis_scale = "linear"
    @yaxis_scale = "logarithmic"
    @xlabel = "channels"
    @ylabel = "count"
    curves
        curve1_legend
            y = float32(100, 1024)
                @label = "curve y label"
            x = float32(100, 1024)
                @label = "curve x label"
         curve2_legend
            ...
    images
      image1_legend
          image = float32(100, 1024)
          origin
          scale
    histograms
       ...
    scatters
        ....
    markers
        ...
```

**Comment by vasole** [comment]
A complete plot I see it difficult. To mix curves, images and scatter combining auxiliary_signals and auxiliary_axes I see it quite feasible but not if the complete description with colormaps, colors... is to be stored.
