### ISSUE TITLE
Grid Image view. Desirable feature in silx?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1473]
Several beamlines (particularly ID13 but also ID21) have inquired about the possibility to display multiple images side by side.

The first question is of course is if we want that in silx or it is responsibility of the applications to achieve that as most applications take the easy solution of browsing a stack.

The point is that I was wondering if with the shared axes feature of silx it would be simple enough to get a table or a grid containing widgets to have simultaneous visualization of several images in such a way that when one zooms in one image the zoom is applied to all of them, the colormap could be changed to all of them, ...

**Comment by t20100** [comment]
There is already a demo for axes synchronization: `examples/syncaxis.py`.
At first, we can add one that is closer to a real use case.

**Comment by vallsv** [comment]
In case, that's something we could provide on `silx view` by selecting many datasets, for only some special cases like curves or images. But it really depend on there use case. If it match something really generic or not.

**Comment by vasole** [comment]
The use case is an NXdata containing several images. For instance to visualize the different elemental maps (Fe, Co, Ni, ...) associated to a fluorescence map.

**Comment by vasole** [comment]
Just to make it clear, to be able to toggle from the usual stack view of images to a grid of images.
It could be even implemented as an action with a pull down menu specifying the desired layout ( (2, 1), (2, 2), ...)

**Comment by vasole** [comment]
There are two needs:

- Gallery of thumbnails 
- Side by side image comparison

**Comment by vasole** [comment]
Question replaced by #2243
