### ISSUE TITLE
[silx convert] Unnecessary group at top level created converting SPEC file

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1498]
Using the command ``silx convert align.spec -o align.h5`` or ``silx convert align.spec`` the generated HDF5 file contains a top level directory named align.spec that should not be there.

**Comment by PiRK** [comment]
We currently provide the option ` --no-root-group` for this.

Do we still want to generate this extra group level when multiple files are converted at once and `--no-root-group` option is not specified?

I can imagine a use case for which adding an extra top level directory is useful even when converting a single file: when files are appended to an existing output HDF5 file. If the scan number is always different, no extra group level is required, but if some scan number are identical in two input files, there will be conflicts.

One solution would be to do the exact opposite of what we are doing now: don't create an extra group by default, allow to create one with an option `--root-group`.  This would require the user to be aware of risks of overwriting data in the default case.

In any case, I think the behavior should remain consistent, no matter if the user runs  `silx convert align.spec` or `silx convert *.spec`.
