### ISSUE TITLE
[silx view] visualization images of complex numbers

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#1503]
The new control for displaying amplitude, phase, etc. of an image of complex number is very good!

I would like to ask you to add a new entry "square amplitude"  |A|**2 This represents intensity when the complex number is an amplitude (wave, electric field, etc).

Thanks,
 
Manuel

**Comment by t20100** [comment]
Hi @srio,
I added a "square amplitude" mode to the complex viewer in PR #1509.

Best
