### ISSUE TITLE
[Plot] Plot2D should diplay intensity along with X and Y in the bottom toolbar.  

### ISSUE THREAD

**Issue by WatierYves** [silx-kit/silx#151]
As in ImageView, in my humble opinion, the Plot2D  should display pixel intensity (value) when fly over with mouse.

**Comment by kif** [comment]
On Mon, 04 Jul 2016 07:01:43 -0700
WatierYves <notifications@github.com> wrote:

> As in ImageView, in my humble opinion, the Plot2D  should display pixel intensity (value) when fly over with mouse. 
+1
