### ISSUE TITLE
[Plot] Plot2D with multiple image files - Should have by default a way to pass from one image to the next. 

### ISSUE THREAD

**Issue by WatierYves** [silx-kit/silx#152]
After adding multiple images in Plot2D, expected behavior is to have a possibility to move from one to another.  Slider or [<] [>] buttons would be sufficient and not take too much place. A way to have displayed the legend parameter of each image should be there too (to know which image is on the screen ).

**Comment by vasole** [comment]
I see some solutions:

- Support Image Stacks with a dedicated widget
- Generalize the legend widget in order to apply it not only to curves.

**Comment by t20100** [comment]
+1 for a dedicated Image stack widget to display images one by one.
We probably get problems if we mix browsing a stack of images and images where origin and scale can be set for each image as in PlotWindow.

By the way, the stack widget can be named Plot2D and replace the current one... or not.

**Comment by vasole** [comment]
Just as comment. In PyMca I have dedicated stack image browsers with added functionalities (sliders, range for summing, median filter,...) in a fairly compact interface.

**Comment by t20100** [comment]
There is now a dedicated StackView widget for image stack:
http://www.silx.org/doc/silx/dev/modules/gui/plot/stackview.html#module-silx.gui.plot.StackView
So I'm closing this issue.
