### ISSUE TITLE
[convert] file series fail because of None in attrs

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1537]
When merging a file series with *silx convert*, the process now fails because the "file" attribute *@filename* is *None*. 
This causes the following error:
`TypeError: Object dtype dtype('O') has no native HDF5 equivalent`

I think that previously it didn't crash because the was a coercion of all attributes to a dtype *numpy.string_*, so we ended up with a *@filename=b"None"*. 

I'm not sure if this is a `fabioh5` bug or a `silx.io.convert` bug.

In `silx.io.convert`, this patch fixes the issue:

```
diff --git a/silx/io/convert.py b/silx/io/convert.py
index 3af2c44..a2839fd 100644
--- a/silx/io/convert.py
+++ b/silx/io/convert.py
@@ -165,8 +165,9 @@ class Hdf5Writer(object):
         root_grp = h5f[self.h5path]
         for key in infile.attrs:
             if self.overwrite_data or key not in root_grp.attrs:
-                root_grp.attrs.create(key,
-                                      infile.attrs[key])
+                if infile.attrs[key] is not None:
+                    root_grp.attrs.create(key,
+                                          infile.attrs[key])
```
 
If we want to fix this In `fabioh5`, we could set the `@filename` attribute to "", or "None", or drop it altogether.

**Comment by vasole** [comment]
It is a very bad idea to have that attribute at root level. The only place where that attribute (not existing under NeXus) will not conflict with anything is inside the group created for destination under instrument.

**Comment by vasole** [comment]
My bad. The attribute indeed exists under NeXus. The simplest is then to use as @file_name the file name of the first file used in the conversion process. Since the @file_name attribute is optional, it it is None, it should be simply not written.
