### ISSUE TITLE
[ci] We do not provide pyopencl 2015.1 for Python 3.6

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1546]
Travis Python 3.6 spend time to recompile it. https://travis-ci.org/silx-kit/silx/jobs/336118872

- Should we build it?
- Should we use an up-to-date version of pyopencl (2015 sounds old)

**Comment by t20100** [comment]
It added a wheel of pyopencl v2018.1 for python 3.6 to our wheelhouse.
Tests are OK, see PR #1550
