### ISSUE TITLE
[plot] save spec file with more decimal digits

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#1547]
Saving a plot as SpecFile, the precision is quite poor, e.g., 

#N 2
#L  Energy [eV]  Number of Rays weighted by $\Vert\mathbf{E_{\sigma}}+\mathbf{E_{\pi}}\Vert^2$
9137.63  25.07346
9137.63  25.07346
9137.63  26.49942
9137.63  26.49942
...

If saved as txt, it is OK: 
9.137629999999999200e+03 2.507346120464817929e+01
9.137630199004974202e+03 2.507346120464817929e+01
9.137630199004974202e+03 2.649942103435959595e+01
9.137630398009949204e+03 2.649942103435959595e+01

Could be saved as Spec with same format/precision? 

Thanks

**Comment by vasole** [comment]
Most of the times we are using float32 data in the plots and basically you are missing one digit. Currently specfile is saved as %.7g while original specfile format usually uses %.4f or %.5f I think the best solution not to have loses is to save in binary format (for instance HDF5) but if the data are float32 to have 8 or more digits should be enough.
