### ISSUE TITLE
Please add mime type to silx view

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1549]
It would be great if we could double click on a supported file and open it directly from the nautilus etc...

Can you add .desktop files for silx view and set the right mime-type

https://developer.gnome.org/integration-guide/stable/mime.html.en

It would be great also add edf as an image type :)

Cheers

Frederic

Ps: Same of other esrf tools  ;)

**Comment by vallsv** [comment]
Sure, i would be good, but for a new minmetype like EDF files, it have to be registered somewhere no?

**Comment by vallsv** [comment]
Sorry, everything is explained, we can use custom formats. But it could be better to register this format is a wider score.

We already have the desktop file, then it looks to be quite easy.
