### ISSUE TITLE
[Gui] Rework qt.py

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#155]
- Add import uic?
- Doc: Explain what this module imports + links to PyQt* PySide documentation + an example to illustrate the fact that this is a flat namespace, e.g., widget = qt.QWidget() ...
- Add qt.QtBinding which is the Qt binding module used, so one can do from qt.QtBinding import [...]
  instead of using the string qt.BINDING to know which binding is used and have if/else construct to do extra imports.

**Comment by t20100** [comment]
- No uic module in PySide
- Mistake: No way to do from qt.QtBinding import [...]

**Comment by vasole** [comment]
Lines 32 and 34 should say Qt binding and not Qt bindings. The rest is Ok.
