### ISSUE TITLE
[fabio] Fabio is not up-to-date on edna-site

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1552]
silx fail on nightly build cause fabio is not up-to-date.

The constraint `fabio >= 0.6` is on the `requirement.txt`. And i don't check the way it is build on edna-site.

Then

- Should we update manually fabio on edna-site? It will work until a new constraint.
- Should we execute the manifest? create a virtualenv and so on?

**Comment by t20100** [comment]
I've update fabio on edna-site, it looks to work.
