### ISSUE TITLE
[plot] addImage replace=True default argument is missleading

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1555]
I keep forgetting about the `replace=True` in `PlotWidget.addImage` and get missleaded when displaying more than one image in the plot.

Now that there is the plot object oriented API and a `setData` on the image object, can't we drop the `replace=True` argument ?

**Comment by vallsv** [comment]
+1

**Comment by vasole** [comment]
I would not drop it because it is more common to display just one image than several. At most I would just change the default behavior.

**Comment by vasole** [comment]
Please do not forget that the functional API is going to be used from the command line (ipython, BLISS, ...)

**Comment by t20100** [comment]
Then, are we OK to have `replace=False` as default for `addImage` (as for other `add*` method) ?
For displaying a single image, the image is already replaced when calling `addImage` with the same legend.

**Comment by t20100** [comment]
Agreed to do it.
This should have a limited impact as the default legend is not iterating, so calling twice `addImage` will update the image.
