### ISSUE TITLE
Move ColormapDialog inside silx.gui.dialog

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1557]

**Comment by t20100** [comment]
The only constraint I see is about inter package (circular) dependencies as`ColormapDialog` depends on `silx.gui.plot` for `Colormap` and `PlotWidget` and the plot relies on the ColormapDialog...

**Comment by vallsv** [comment]
From meeting comments.

If we move ColormapDialog we also should
- Move Colormap (maybe inside `silx.gui.utils`)
- Reduce the use of matplotlib from Colormap
- Also move the ColorBar widget (maybe inside `silx.gui.widgets`)
