### ISSUE TITLE
[plot] Curves on right axis are display behind left axis content

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1573]
This occurs with matplotlib backend.
It is a problem when one wants to overlay a curve on the right axis over an image on the left axis

To reproduce:
```
from silx import sx
w = sx.imshow(((0, 1), (2, 3)))
w.addCurve((0, 3), (0, 2), yaxis='right')
```

Is it OK to put right axis content over left axis?

**Comment by vasole** [comment]
That is "normal". The right axis has a lower z order than the left axis in order to be able to catch the events of the left axis. As far as I know, only the axis that is "on top" catches the events.

**Comment by t20100** [comment]
This is fixed with current master (order of matplotlib axes has been changed).
