### ISSUE TITLE
[plot] Plot2D widget's ColorBar disappear

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1592]
To reproduce:
```
from silx import sx
w = sx.imshow()
w.hide()
w.show()
```
and the colorbar is not visible.

**Comment by payno** [comment]
It's look like on this case that the showEvent is not call the second time.
But don't know why.
This is not inheritance issue even if missing on the showEvent() and hideEvent() from the ColormapDialog.

**Comment by payno** [comment]
looks like there is strange connection between colormapAction

`        
if checked is True:
            self._dialog.show()
            self._updateColormap()
        else:
            self._dialog.hide()
`

and the Colorbar

`
def showEvent(self, event):
        print('in show event')
        self._connectPlot()
        if self._viewAction is not None and not self._viewAction.isChecked():
            return
            self._viewAction.setChecked(True)
        qt.QWidget.showEvent(self, event)

    def hideEvent(self, event):
        print('in hide event')
        self._disconnectPlot()
        if self._viewAction is not None and self._viewAction.isChecked():
            self._viewAction.setChecked(False)
        qt.QWidget.hideEvent(self, event)
`

**Comment by vallsv** [comment]
It looks like the problem come from the fact the widget also provide at the same time the plot action.

As the ColorBar could be an independant object, i will first create a `ColorBarAction` to manage the tools.
