### ISSUE TITLE
Issue save as Nx data

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1595]
/36145412-33315426-10a9-11e8-92f2-45215dd1dc74.png)
When opening this sino.edf (seems to not be limited to this file) file and saving it with 'image as NX data' it save it.

But when opening the generated file it give me the message 'NXroot group provides...malformed' at the root level as show in the image.

![screenshot - 02132018 - 11 32 01 am](https://user-images.githubusercontent.com/12907796/36145441-4b4944b0-10a9-11e8-917a-1dd83bd93d4d.png)

**Comment by PiRK** [comment]
Probably due to missing `@NX_class = 'NXentry'` when writing the output file. 

I need to also double-check if this message is always displayed when a default entry is specified at the root but not NXdata is specified at entry.
