### ISSUE TITLE
[datafiledialog] It would be nice to allow to select an NXentry

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1599]
Request from Manolo

**Comment by PiRK** [comment]
If we want to start allowing specific filters, I think we should make it generic to be able to specify any `key/value` attribute pairs. Or even just provide a way to give a filter callback function, that analyzes the item and returns True or False.

**Comment by vasole** [comment]
Concerning the request, is it not equivalent to just selecting a group or what he wants is to prevent digging into the NXentry groups? For that particular case selecting a group instead of a dataset should be enough.

**Comment by PiRK** [comment]
My understanding is that we want to be able to limit the kind of group/dataset that the user can select with the dialog, by adding additional constraints on the attributes, or possibly even constraints on the content of the group/dataset.

**Comment by PiRK** [comment]
Something like:            
```
            nxdataDialog = DataFileDialog(self)
            nxdataDialog.setFilterMode(DataFileDialog.FilterMode.ExistingGroup)
            nxdataDialog.setAdditionalFilterCallback(silx.io.nxdata.is_valid NXdata)
```

**Comment by vallsv** [comment]
That's already possible with a very simple inheritance. I mean it is very easy to do anyway. A callback is not very Qt friendly, but could be very useful.

But if you want it for this release let me know.

Anyway, i am not sure it is a good idea to use `is_valid_NXdata` while it imply a "validity" which is not trivial, and nothing will be explained to the user on the dialog. A simple test on `NX_class` should be enough. Up to the dev which using the dialog to take care of the validity of the data.

**Comment by PiRK** [comment]
OK, if it is easy to do with a simple inheritance, I don't necessarily need it to be part of silx. And I don't need it for this release.
