### ISSUE TITLE
[plot] Snapping to point

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#1611]
Would it be possible for this to be available without the need of having the curve enabled?

**Comment by t20100** [comment]
Do mean enable snapping for all curves?

I think it would also be the opportunity to simplify how to enable/disable it.
As it is now, you need to enable it in the PositionInfo AND to have the crosshair.

**Comment by vasole** [comment]
I would discourage to enable it for all curves instead of having it for the active curve. It may become impossible to recover the point coordinates of a curve when there are several around. First one selects the curve then one select the point.

**Comment by mretegan** [comment]
I think that when one wants to get the precise position of a point, will first zoom to the region of canvas where the point is. This way the snapping should be easier to make.

Maybe there are use cases where activating the curve is really required to limit the snapping, but maybe this can implemented in a way that snapping to all curves is also possible.

**Comment by vasole** [comment]
You usually work with two curves :) while there are people around using thousands of them (so many that one cannot even zoom if there is no wheel mouse).

**Comment by t20100** [comment]
To me it is reasonable to provide different snapping modes that one can select, or at least helpers or sample code on how to do this.
In case of snapping mode, the default one should be be consistent with the current one and conservative if there is many curves.

As for plotting thousands of curves, it would be better to think of a dedicated widget that displays a sort of density map of curves and allows to display a subset of them.
I made a very quick prototype: https://github.com/t20100/sandbox/blob/master/curves/CurvesView.py
