### ISSUE TITLE
[sample code] animatedicons.py not working if mng is not supported

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1623]

**Comment by vallsv** [comment]
I will take a look at it tomorrow. On Qt5 we already only use PNG files for animations.

**Comment by t20100** [comment]
Should we remove the animated icon from movie? (at least from the example)

**Comment by vallsv** [comment]
I think so. I also would prefer to list everything as it is done on the icon example. And maybe merge both, we don't need 2 examples. It should only be used as resource explorer IMO.

**Comment by t20100** [comment]
+1
