### ISSUE TITLE
[plot] Docked widgets always shown at bottom when instanstiated

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1629]
We seem to have lost the functionality of showing docked widgets to the right of the plot when the plot was much wider than tall.

**Comment by t20100** [comment]
Now it seems to always show on the right side and never on the bottom...

**Comment by vasole** [comment]
No, now it should check the size of the parent.

**Comment by t20100** [comment]
It "should"... but it doesn't seems to change anything.
