### ISSUE TITLE
[NXdataView] No warning if old specification is met

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1636]
I got the following report:

``
I confirm that with Silx version  0.7.0-dev0 the plot loads automatically when clicking the "plot_1" NXdata node.
Nevertheless, the console output shows 66 times the same warning:
WARNING:silx.io.nxdata:NXdata warning: NXdata group does not define a signal attr. Testing legacy specification.
``

Indeed, that WARNING should be an INFO and the complain should arrive if none of the NXdata specifications are met.

**Comment by PiRK** [comment]
I'm a bit worried by the "66 times". I imagine that we can parse the data a few times before we display it in the DataViewer.  But 66 times is a lot. I'm hoping there are multiple groups causing the same warning, in this instance. To be sure, I added the name of the faulty group in the warning message.

**Comment by vasole** [comment]
@PiRK There was only one group.
