### ISSUE TITLE
[plot] Profile should use coordinates not just indices

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1642]
- When extracting a horizontal or vertical profile the x axis should correspond to the original coordinates
- When extracting a line profile one has two possibilities a) to use as x axis the coordinates corresponding to longest projection or b) to use the distance between the points.

**Comment by mretegan** [comment]
Yeah, that would be useful.

**Comment by t20100** [comment]
For v0.8, do it for horizontal and vertical profile at least

**Comment by t20100** [comment]
Move to v0.9 as PR #1959 implements it for horizontal and vertical profile.

Free line profile still needs to be addressed.
