### ISSUE TITLE
[plot] Speed up colormap calculation

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1648]
The display of dynamic scatter plots is very slow even using the OpenGL backend.

- It should be fixed at the very least for that backend.
- Since we can send the colormaps in most cases, it would be convenient to calculate ourselves the colormap instead of relying on matplotlib.

**Comment by t20100** [comment]
When using the OpenGL backend, colormap is slow for scatter plots because it is not done on the GPU

**Comment by t20100** [comment]
I opened issue #1663 for OpenGL scatter plot colormap computation.
Let's keep this issue for CPU computation of colormaps.
