### ISSUE TITLE
Installing using pip

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#165]
I get the following error when I try to install on a Windows 10 machine with Python 3.5:

```
C:\Users\Marius Retegan>pip install silx
Collecting silx
  Using cached silx-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MARIUS~1\AppData\Local\Temp\pip-build-da97tpoi\silx\setup.py", line 41, in <module>
        from numpy.distutils.misc_util import Configuration
    ImportError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MARIUS~1\AppData\Local\Temp\pip-build-da97tpoi\silx\

C:\Users\Marius Retegan>pip list
pip (8.1.2)
setuptools (20.10.1)
```

**Comment by kif** [comment]
On Wed, 06 Jul 2016 00:48:47 -0700
Marius Retegan <notifications@github.com> wrote:

> I get the following error when I try to install on a Windows 10 machine with Python 3.5:
> 

Indeed there is a bug on version 0.1.
Now we are preparing a release 0.2 (within a week) 

For now I would suggest to download the requirement.txt from the master:

pip install -r requirement.txt #-> install everything needed, including numpy

and retrieve the binary from appveyor:
https://ci.appveyor.com/project/ESRF/silx/build/job/vf97n9x05hmauusu/artifacts

and install it.

Cheers, J.

**Comment by vasole** [comment]
Probably you have installed Python 3.5 32-bit instead of 64-bit.

**Comment by vasole** [comment]
It was the usual 32-bit installation problem.
