### ISSUE TITLE
[datafiledialog] QFileDialog shortcuts looks to be working on Linux PyQt5.10.1 now

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1688]
It's the new PyQt5 version, then better to not merge it on the 0.7 release.

See https://github.com/vallsv/silx/commit/13b678897674af52f60c113859143206facc29a6

**Comment by vallsv** [comment]
It looks to work on PyQt 5.10.1, let's way for the next release.
```
from PyQt5 import Qt
app = Qt.QApplication([])
def printSidebarUrls():
    d = Qt.QFileDialog()
    d.setOption(Qt.QFileDialog.DontUseNativeDialog, True)
    print(d.sidebarUrls())
    d.deleteLater()
    d = None

Qt.QTimer.singleShot(500, printSidebarUrls)
app.exec_()
```

**Comment by vasole** [comment]
Can this be closed?

**Comment by vallsv** [comment]
No, cause I would like to be sure the next PyQt will support it as it was creating a segfault. Unfortunately the last PyQt wheel is not working on my computer (Python3.5)
