### ISSUE TITLE
[build] Disabling OpenMP by default

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1698]
It would be safer and simpler to disable OpenMP by default in setup.py, and enable it when needed (i.e., in debian packages or when building from source)

**Comment by vasole** [comment]
OK with me. That makes sure we do not make mistakes. :+1:

**Comment by kif** [comment]
On Thu, 01 Mar 2018 02:45:22 -0800
Thomas VINCENT <notifications@github.com> wrote:

> It would be safer and simpler to disable OpenMP by default in setup.py, and enable it when needed (i.e., in debian packages or when building from source)

I am not that enthusiatic ...
@picca, what do you think about this:

We disable OpenMP in all wheels (windows, Mac and manylinux) but not in other types of build (debian packages).

What about RPM and ARCH packages ?

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
I think we conclude last time that it was not a good idea to disable it by default, cause it will never be tested. But i am not sure cause i don't find in in the silx minutes.

**Comment by t20100** [comment]
We said we would keep it enabled by default and disable it only when building the wheels, so I'm closing it.
