### ISSUE TITLE
[plot] Add a PlotScatter widget to the widget zoo

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1706]
We provide `Plot1D` for curves, `Plot2D` for images but there is no plot widget providing the tools for scatter plots like getting data value (see #1705), a scatter plot profile (see #1613) and the already available scatter mask.

**Comment by vasole** [comment]
:+1:

**Comment by vallsv** [comment]
Why can't it be part of Plot2D? Is there need of specific tools? Which make sens in case of the complex widget cause there is a dedicated tool (while this tool could also be set visible in case of active complex item).

Else i am afraid it will became a nightmare.

**Comment by t20100** [comment]
Why do you think it would be a nightmare?

The machinery to deal with scatter plot for mask, profile and displaying data value is different than that of images. It might be possible to combine them, but that would need quite some refactoring.
Even if we do so, I still think it is worth to have a dedicated widget as a few extra small tools can be needed: toggle log scale axes, marker size and shape.
