### ISSUE TITLE
wheels does not claim the minimal version of numpy required

### ISSUE THREAD

**Issue by jonwright** [silx-kit/silx#1740]
In [3]: silx.io.specfile.SpecFile("31oct98.dat")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-8e08275efa8d> in <module>()
----> 1 silx.io.specfile.SpecFile("31oct98.dat")

/home/jon/Downloads/silx-training/silx/io/specfile.pyx in silx.io.specfile.SpecFile.__cinit__()

NameError: name 'SF_ERR_NO_ERRORS' is not defined

(xenial)jon@localhost:~/Downloads/silx-training$ python    
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import silx
>>> silx.version
'0.7.0'

**Comment by jonwright** [comment]
Seems to be a problem of the pypi wheel not matching the xenial system numpy. Fixed by recompiling silx.

**Comment by kif** [comment]
On Tue, 20 Mar 2018 04:09:53 -0700
Jon Wright <notifications@github.com> wrote:

> Seems to be a problem of the pypi wheel not matching the xenial system numpy. Fixed by recompiling silx.

Wheels are built to be installed on "up-to-date" systems (typically
virtual-envs where you can make a "pip install --upgrade").

Cheers,

-- 
Jérôme Kieffer

**Comment by jonwright** [comment]
In which case there is a bug in the documentation: 
http://www.silx.org/doc/silx/latest/install.html
"Linux
If NumPy is not installed on your system, you need to install it first, preferably with the package manager of your system"

**Comment by t20100** [comment]
As the wheels impose a specific version of `numpy`, they should claim it in the `install_requires`.

**Comment by vasole** [comment]
Why do they impose a particular version of numpy?

**Comment by vasole** [comment]
Besides that, it seems we have an error on the handling of an error....

**Comment by PiRK** [comment]
> Besides that, it seems we have an error on the handling of an error....

I had a quick look, and I don't see any obvious problem. `SF_ERR_NO_ERRORS` is defined as a module attribute, so unless there is a subtlety I don't understand for *cdef* classes,  *SF_ERR_NO_ERRORS* should be available in `__cinit__`.

**Comment by t20100** [comment]
A few tests:
- If we compile silx with numpy 1.8 (minimum version in `requirements.txt`, lower than Debian 8 (1.8.2) but available as wheels) it seems to work with latest version.
- If we compile it with latest numpy (1.14.2), it does not work with previous minor version (1.13.3) with errors like:
`RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb`

**Comment by t20100** [comment]
Actually due to `h5py` probably compiling wheels with latest `numpy` as well...

And PR #1745 improved the situation.

**Comment by t20100** [comment]
PR #1745 and PR #1749 improves the situation (by restricting the usage of numpy C API) up to the point that `silx` built with numpy 1.14.2 works with numpy 1.9... but not 1.8.

Anyhow, numpy claims this is NOT supported.
The only way to make clean wheels is to build them with the version of numpy that is advertised as minimal supported version in `install_requires`.

**Comment by t20100** [comment]
closing as PR #1745 and #1749 minimize C level dependency on numpy and PR #1756 makes sure the wheel advertises the version of numpy it was built with.
PR #1745 also includes a patch to improve initial reported issue.
