### ISSUE TITLE
Ready .vol files

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1741]
PyHST is generating .vol files. Those are binary files which have to be associated with a .vol.info and/or a .vol.xml files to get the contain shape.

Those files seems to be used a lot and it would be interesting to have silx or fabio reading them.
But the problem from my point of view is the file association that has to be made to read them correctly.

Here is an example of a file set:

D2_H2_T2_h_multipag_1079.vol   -> contains binary data
D2_H2_T2_h_multipag_1079.vol.info -> contains information to read the data 
D2_H2_T2_h_multipag_1079.vol.xml -> contains the same information as the .info (at least on this case)

**Comment by vasole** [comment]
The elegant solution for that is to create an HDF5 file with external storage when trying to read a .vol file.

We might need to contribute to h5py to get that:

https://github.com/h5py/h5py/issues/945

**Comment by payno** [comment]
It seems there is already a pull request implementing the desired functionality:

https://github.com/h5py/h5py/pull/1000

**Comment by t20100** [comment]
Why not using `.npy`? It is composed of a small header with the shape and data type and the raw data...
https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html

**Comment by vasole** [comment]
The memory mapped file approach:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html

**Comment by jcesardasilva** [comment]
Concerning the code by @payno above, one can easily write a wrapper to read the shape such as: 
```
# Usually, the file .vol.info contains de size of the volume
linesff = []
infofilename = vol_file+'.info'
with open(infofilename,'r') as ff:
    for lines in ff:
        linesff.append(lines.strip('\n'))
x_size = int(linesff[1].split('=')[1])
y_size = int(linesff[2].split('=')[1])
z_size = int(linesff[3].split('=')[1])
shape = (x_size,y_size,z_size)
```
Or any other less verbose version of it. Maybe even as a nested function and we can simply use a decorator into function convertVolToH5.
