### ISSUE TITLE
[plot] Change Y axis orientation default for image widgets

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1744]
During the last training it was suggested to display by default images with Y axis going downward.

We can do this at different level: `sx.imshow` or for each image plot widget: `Plot2D`, `ImageView`, `ComplexImageView`, `StackView`.
Doing it at the widget level would break current behavior (and no deprecation warning is possible)...

**Comment by t20100** [comment]
To me, the question here was more: did we choose the default Y axis orientation for images because it's the same as for curves or because it covers enough cases. BTW, matplotlib `imshow` looks to have Y axis downward by default.

Now that there is a silx application we can consider have settings.
But I would use it for the application and eventually for `sx` module but not for widgets where each application should decide.

**Comment by vasole** [comment]
I guess we chose it as default for Plot because it covers all cases.

For imshow by sure we can take matplotlib's default.

For ScatterView by sure it is like Plot and that makes me doubt about applying the imshow behavior to Plot2D.

**Comment by vallsv** [comment]
Settings for `silx view` looks to be a good idea.

**Comment by t20100** [comment]
I created issue #1746 for discussing `silx view` settings.

**Comment by vasole** [comment]
I would just make imshow compatible with matplotlib setting but I did not take into account that the matplotlib defaults can be different too (use of rcparams).
