### ISSUE TITLE
Add load/save settings for silx view

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1746]
Discussion started in #1744

**Comment by vasole** [comment]
Needed:

- Defaults for silx view (including geometry of the application itself) automatically saved
- A way for silx view to bypass the saved settings
- A way to provide defaults for silx:
    - Default colormap (linear, log, viridis, grey, temperature, ...)
    - Default image origin (up, down)
    - Default fit functions and fit configurations
    - Default binding (matplotlib or OpenGL)
    - ...

- A way for applications to set the silx defaults with the possibility to ask silx widgets to use the defaults saved as silx settings or using the defaults imposed by the application.

**Comment by vallsv** [comment]
All the features are not there, like fitting or the bypass, but it could be already enough for the 0.8 milestones?

**Comment by vasole** [comment]
Is it too difficult to just add the bypass (--fresh or -f in analogy with SPEC and PyMca flags)? I had to add it in PyMca because of people saving the settings in one terminal and then using the program from a different one therefore leading to huge inconveniences (for instance when switching from dual screen to single screen).

The fit it can wait.

**Comment by vallsv** [comment]
- No it is not difficult to add a `--fresh` and it is much safer.
- It is also easy to store ini file always (i check the Qt API, Qt take care of the path).

**Comment by vallsv** [comment]
Hmmm, well, a bypass and a fresh is not the same usage...
- `fresh` will open the file, clear it, and save it at the end (in case something is buggy, it can help)
- `bypass` will not use user preference at all

Are we talking about 2 features?

**Comment by t20100** [comment]
Wouldn't `fresh` be enough?

**Comment by vallsv** [comment]
Well, i will do it at least.

**Comment by vallsv** [comment]
Done by #1844. If something is missing we still can open a new issue. I think about fit configuration, which is very special i think.
