### ISSUE TITLE
ipython will not import sx without an Xserver

### ISSUE THREAD

**Issue by jonwright** [silx-kit/silx#1747]
I cannot import sx into ipython without having an Xserver connection:

``` 
rnice8-0103:~ % ipython -c 'import silx.sx'
 : cannot connect to X server 
```

**Comment by t20100** [comment]
We can add a check of the `DISPLAY` environment variable on linux to enable/disable loading the gui part.

BTW, you get the same behavior if you run `%pylab qt` in the same condition.
