### ISSUE TITLE
[CI] Add running GUI tests on Travis-CI

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#176]
For now, GUI tests only run with AppVeyor.
Add them to Travis for:
- [ ] Linux
- [ ] Mac OS X

**Comment by vasole** [comment]
Can this issue can be closed? GUI tests are certainly run on linux. It is not the case for the Mac but I do not know if it is just our choice.

**Comment by vallsv** [comment]
Thomas is working on, as i understand

**Comment by t20100** [comment]
Yes coming soon
