### ISSUE TITLE
hdf5 extension in Silx view when opening hdf5 files 

### ISSUE THREAD

**Issue by mrosanes** [silx-kit/silx#1762]
In Silx View, in the 'open' window files, for choosing the hdf5 file to be opened, the filter is finding the files with extensions 'h5' and 'hdf', but not the files with extensions 'hdf5' files.

In order to open 'hdf5' files, now the 'all files (*)' filter has to be chosen in order to see the files with 'hdf5' extension in the 'open' window of Silx view. 

It should be good if hdf5 files were visible from the beginning in this 'Open' window.

**Comment by vallsv** [comment]
It have to be fixed. Thanks for the feedback.
