### ISSUE TITLE
silx view aborts when opening IPython console

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1763]
With silx 0.7.0 on debian8 (rnice8 at least) silx view aborts when one tries to open the embedded IPython console from the GUI.

To reproduce: visualize some curves with silx view and open IPython console (Options->Console).

Error message:
```
QWidget: Must construct a QApplication before a QPaintDevice
Aborted
```

On another debian8 computer silx view breaks while loading IPython widget tries to load PyQt4 while silx view loads PyQt5.

**Comment by t20100** [comment]
Even if I don't like it, I think it is worth doing true lazy-loading of `silx.gui.console`.
On one side we would loose is disabling the console action if it cannot be used.
On the other side, problems related to IPython widget would only arise when actually requesting the console.

**Comment by PiRK** [comment]
Debugging is made very difficult by the wide range of supported versions of qtconsole/IPython versions. 
Ideally I would like to have no `try` / `except` in the imports, and only import `qtconsole` (not IPython). 
If this solves your issue, I think it would be preferable to risking to crash the application when someone tries to open the console.
It would just be a matter of teaching users to add a hard dependency on a recent version of `qtconsole`, in their applications.

**Comment by t20100** [comment]
Those issues looks to be due to `silx view` using PyQt5 while IPython v2.3.0 (on debian8) loads PyQt4 and does not check for PyQt5 being loaded...

The option to drop support of old versions of IPython/qtconsole would solve this issue as newer versions support PyQt5.
Are we just OK to drop the console widget on debian8?

To me it seems necessary as we now use PyQt5 as the preferred binding...
