### ISSUE TITLE
[silx.gui.plot] Unnecessary warning

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1764]
It seems silx.gui.plot issues a warning without checking if Qt is already loaded or if matplotlib is using the appropriate backend. See the two examples below

![image](https://user-images.githubusercontent.com/5636251/38164771-a8f295d8-3509-11e8-884e-30af3d04c640.png)

**Comment by vallsv** [comment]
I did this patch on pyFAi recently. It can be maybe useful.
https://github.com/silx-kit/pyFAI/commit/265926a2ad5c6f70ec11c9fe4a6bc78863959bc5#diff-3b577f2d23372c30173d8aaa06e18f48
(BTW it introduce an issue, it have to be merge with the following patch)

**Comment by vasole** [comment]
The patch seems worth to be added to silx.
