### ISSUE TITLE
[mask] getSelectionMask returns an array where there is no mask

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1765]
```
In [1]: from silx import sx

In [2]: plot = sx.imshow()
Out[2]: <silx.gui.plot.PlotWindow.Plot2D at 0x7f70a67c4218>

In [3]: plot.getMaskToolsDockWidget().getSelectionMask()
Out[3]: array([], dtype=uint8)
```

I am supposed to work with images, and here i have to test an array with a dim==1. It would be more convenient to return `None` if there is no mask.

**Comment by vasole** [comment]
The safe approach is to return an array with non-selected points everywhere and with the same shape as the active image(or item). The problem in your case seems to be that there is no active item, not the fact of having an empty array.

**Comment by t20100** [comment]
I though we were always returning a 2D array (even if empty), but it is not the case, so indeed None would be convenient if there is no image to draw the mask on.

**Comment by vasole** [comment]
As I see things:

- If there is no active item, None is much better than an empty array
- If there is an active item, the safest approach is to have the returned mask with the same shape (and size) as the active item shape.

In PyMca I ended up accepting None as equivalent of a mask with zeros everywhere so, an array with same size as the item but zero filled.

**Comment by vasole** [comment]
Added the 0.8 milestone to make sure we decide something as coding does not seem to be the problem.

**Comment by t20100** [comment]
PR #1867 makes sure a 2D array is always returned.
Anyway it is better to do it this way internally, and personally I expected it this way.

Now we have to choose for the API between an empty 2D array and None.

**Comment by t20100** [comment]
We decided to return None and accept None in `setSelectionMask`.
