### ISSUE TITLE
Wrong results when plotting small x-range with large offset with Open GL backend

### ISSUE THREAD

**Issue by titusjan** [silx-kit/silx#1772]
When making PR #1770 I ran into the issue that many values are grouped together when plotting a data with a small (x) range and a large offset. The problem only occurs when using the OpenGL backend, the Matplotlib backend works fine. 

The following code demonstrates the problem:
```

import datetime as dt
import numpy as np

from PyQt5.QtWidgets import QApplication
from silx.gui.plot import Plot1D

if 1:
    BACKEND = 'gl' # this gives incorrect results
else:
    BACKEND = 'mpl' # this works

def makePlot1D():

    # Make large value with a relatively small range by creating POSIX time stamps.
    base = dt.datetime.today()
    dates = [base - dt.timedelta(seconds=x) for x in range(0, 2500, 20)]

    x = np.array([d.timestamp() for d in dates], dtype=np.uint64)
    np.random.seed(seed=1)
    y = np.random.random(x.shape) * 12 - 3

    print('x[0:10]: {}'.format(x[0:10]))

    plot1D = Plot1D(backend=BACKEND)
    xAxis = plot1D.getXAxis()

    curve = plot1D.addCurve(x=x, y=y, legend='curve', symbol='o')
    plot1D.show()


def main():
    app = QApplication([])
    makePlot1D()
    app.exec_()

if __name__ == "__main__":
    main()

```

When using the `gl` backend the output looks as follows.

![silx_opengl](https://user-images.githubusercontent.com/3320415/38546720-aeea21ee-3cad-11e8-9b62-c187c5ce58f0.png)

The `mpl` backend *does* give the correct results.

![silx_matplotlib](https://user-images.githubusercontent.com/3320415/38546793-e08b7f0e-3cad-11e8-9488-8eb97914de8d.png)

I suspect that somewhere in the `gl` backend 32-bits floats are used instead of 64-bit floats.

**Comment by t20100** [comment]
Yes coordinates are converted to float32 before sending them to OpenGL.
I'll look at ways to circumvent this.

**Comment by UUSim** [comment]
The conversion occurs in `gui/plot/backends/BackendOpenGL.py:957`:
```
x = numpy.array(x, dtype=numpy.float32, copy=False, order='C')
y = numpy.array(y, dtype=numpy.float32, copy=False, order='C')
```

Not all video hardware/drivers support `GL_DOUBLE`, so a solution might be to normalize the data before is sent to the vertex buffers.

**Comment by vallsv** [comment]
Exactly. @t20100 planed to rework the backend like that. Maybe for the coming release, but i don't remember what he said.

**Comment by t20100** [comment]
double vertex buffers are available as a core feature in OpenGL4.1, and so far we are only using OpenGL2.1 features for compatibility (mostly to work through ssh).
Normalization would workaround this, we were also thinking of using an offset.
This need a bit of care to refactor the OpenGL backend as currently there is no separation between data coordinates and display coordinates.
