### ISSUE TITLE
[IO] Extra character added to EDF header keys

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1777]
A curly bracket is added to the HeaderID key of EDF files.

That can already be seen with silx view. The ``HeaderID`` key is usually shown as ``{HeaderID``.

The problem is that it is also reflected using silx convert.

**Comment by PiRK** [comment]
A possible patch:
```
diff --git a/silx/io/fabioh5.py b/silx/io/fabioh5.py
index 95eef23..d9a87f3 100644
--- a/silx/io/fabioh5.py
+++ b/silx/io/fabioh5.py
@@ -173,6 +173,7 @@ class MetadataGroup(commonh5.LazyLoadableGroup):
         keys = self.__metadata_reader.get_keys(self.__kind)
         for name in keys:
             data = self.__metadata_reader.get_value(self.__kind, name)
+            name = name.lstrip("{\n")
             dataset = commonh5.Dataset(name, data)
             self.add_node(dataset)
```

That's if we want to fix the issue in silx. We should first discuss whether or not it should be fixed at a lower level.

**Comment by PiRK** [comment]
It has been fixed in the master branch of fabio in february:  https://github.com/silx-kit/fabio/pull/196/files

**Comment by t20100** [comment]
Or a bug fix release of fabio, which would also fix the issue with already released code.

**Comment by t20100** [comment]
@kif ?

**Comment by vasole** [comment]
A bug fix release of fabio seems to me overkill if it is just made because of that bug...

**Comment by t20100** [comment]
If there is a release of fabio before there is one of silx, then the issue will be fixed.
Otherwise, to me if it is just for the display, it can wait for a fix in fabio, but if it ends up producing erroneous hdf5 files we can have a workaround in silx (with an issue opened to remove it).

**Comment by vasole** [comment]
The problem has been reported by a user that was silx converting EDF stacks to hdf5. If it only affects HeaderID is not critical, but I guess it can affect any key found at the first position in the header.

**Comment by vallsv** [comment]
I send a mail on the silx mailing list a long time ago. Here is the issue on fabio: https://github.com/silx-kit/fabio/issues/195. It is fixed but not yet released.

I guess we could release a version of fabio before the comming silx release. I am clearly not very happy with this bug in the last release of fabio.

**Comment by vasole** [comment]
Assigned the milestone 0.8 just to be sure we decide something (PiRK patch and/or do nothing and wait))

**Comment by vallsv** [comment]
Requirement to fabio 0.7 have to be updated.
