### ISSUE TITLE
[project] gitignore cythonized files

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1822]
As we removed the cythonized files, now it pollute the list of untracked files.

It could be interesting to add them to gitignore.

That's not a very clean solution, but there is no others.

Or we could generate it to the tmp build directory, but it's much more difficult task.

Here is the list of files:
```
silx/image/bilinear.c
silx/image/marchingsquares/_mergeimpl.cpp
silx/image/shapes.c
silx/io/specfile.c
silx/math/chistogramnd.c
silx/math/chistogramnd_lut.c
silx/math/combo.c
silx/math/fit/filters.c
silx/math/fit/functions.c
silx/math/fit/peaks.c
silx/math/marchingcubes.cpp
silx/math/medianfilter/medianfilter.cpp
silx/third_party/_local/scipy_spatial/qhull.c
```

**Comment by t20100** [comment]
+1
