### ISSUE TITLE
[NXdataView] Too strict condition to decide scatter or image?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1823]
When checking if an NXdata is to be shown as scatter or as image, it seems we are too strict concerning the axes interval what leads to problems when using float32 data. I guess we could have some tolerance there.

**Comment by vasole** [comment]
We could work with a relative tolerance. In that case 0.001 % relative seems quite a lot. Furthermore, if the dataset is specified as an image, we should be able to "trust" the person writing the file and just deduce the scale (for instance from the provided maximum and minimum and dimension or any other similar thing)

**Comment by t20100** [comment]
For the future, couldn't nexus allows to define an image axis by an offset and a scale?

**Comment by vasole** [comment]
@rayosborn

I though there was already a way to specify scales in NeXus but I cannot find it.

NeXus already have offset and scaling_factor that could probably be used but I'm not aware about software supporting it nor if that was the intended use.

HDF5 itself supports to associate dimension scales to datasets and h5py is supposed to support the associated H5DS API. The problem with that is that then the scale is associated to a dataset and you run into the old problems the NeXus community encountered when tagging datasets and not groups: a dataset can only be used for one thing.
