### ISSUE TITLE
[io] fabioh5 conversion to float does not check the exponent

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1830]
In `fabioh5`, the conversion from string to the appropriate floating type takes into account the number of digits but not the value of the exponent to decide which floating type should be used.

**Comment by vallsv** [comment]
Interesting, yes the parsing will be a little more complex. Do you have a use case?

> it is better to use longdouble rather that float128

I dont see why but we can talk about

> anyway the actual precision is platform dependent

Yes, in this case we only can try do the best. Is there any other solution?

**Comment by t20100** [comment]
Some info on longdouble/float128: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html#extended-precision

**Comment by t20100** [comment]
BTW, I don't have specific use case for it
