### ISSUE TITLE
[silx view] Cannot use menu "File > Open"  if fabio is missing

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1843]
```
ERROR:silx.gui.qt._qt:<type 'exceptions.ImportError'> No module named fabio   File "/users/knobel/.local/lib/python2.7/site-packages/silx/app/view/Viewer.py", line 365, in open
    dialog = self.createFileDialog()
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/app/view/Viewer.py", line 394, in createFileDialog
    import fabio
```

**Comment by t20100** [comment]
Should we add fabio and h5py as strong dependencies of silx? or at least of `silx view` and `silx convert`. We heavily relies on them and they meet our requirements in terms of packaging...

There is support for "extra dependencies" and even entry point dependencies but I don't how much this solves issues: http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by vallsv** [comment]
`h5py` is for sure mandatory now. Most widget and convert functions can't work without. Especially cause of the use of h5py "special types".
