### ISSUE TITLE
[plot] Context menu option for closing polygon in mask tool

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1845]
The tooltip of the polygon tool in the mask says to close the polygon with a right click, which is no more possible due to support of context menu.

Initially raised in https://github.com/silx-kit/pyFAI/issues/838

**Comment by vallsv** [comment]
It case, it could be good to add an option in the tooltip to allow to close the polygon.

**Comment by t20100** [comment]
You mean an option in the context menu?

**Comment by vallsv** [comment]
Yes, sorry :-)

**Comment by t20100** [comment]
PR #1860 fixes the tooltip, and to me it is enough for v0.8 so I would leave the context menu option for later: dropping the 0.8 milestone and renaming issue for the context menu.

**Comment by t20100** [comment]
There is a "close polygon" menu in the context menu.
