### ISSUE TITLE
[silx view] Remove hdf5plugin not present warning

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1871]
Remove hdf5plugin not present warning and only warn when cannot load a dataset

**Comment by vallsv** [comment]
![lz4-filter-is-missing](https://user-images.githubusercontent.com/7579321/40976441-b9eb8966-68bd-11e8-8c6c-e3fd7874e181.png)
From python 2, Debian 8; same for Python 3.5 and up-to-date libraries.

It is easy to remove the warning. But the exception returned when the filter is not available is not usable (we have already complain about that), then it will be difficult to provide a meaningful message.

The issue #1064 is about to fix this problem with an up-to-date hdf5 library, checking if the filter is available.
