### ISSUE TITLE
[Plot] Add support of scatter plot given value and colormap

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#190]
Plot.addCurve allows to display a scatter plot given x, y and colors, but not given x, y, values and colormap...
Proposal: Add a addScatter method which supports both... and that can also supports different sizes.

**Comment by vasole** [comment]
Let me check if I understand. 

Now it is implemented as in the PyMca API where the color could be a sequence of the same length as the input data.

Now you would like to provide x, y and an additional value and calculate the color applying the colormap to the the additinal value.

Did I properly understood?

**Comment by t20100** [comment]
Yes that's the idea @dnaudet will probably need this.

**Comment by t20100** [comment]
Closed by PR #697
