### ISSUE TITLE
Low resolution icons on macOS

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#1924]
Even if the .svg files are used, the icons look pixelated on high resolution displays. It seems that packing them in a pixmap is the cause, since using the .svg file directly in getQIcon, solves the problem.

Two screenshots for the non-believers :smiley:

<img width="158" alt="screen shot 2018-06-18 at 11 29 15" src="https://user-images.githubusercontent.com/93124/41528667-fd0eb90c-72ea-11e8-9ce7-19caa573efe1.png">

<img width="163" alt="screen shot 2018-06-18 at 11 28 33" src="https://user-images.githubusercontent.com/93124/41528681-04ab9e96-72eb-11e8-8e24-135ff055cbc1.png">

**Comment by payno** [comment]
Looks like in the getQIcon function (silx.gui.icons) passing by a QPixmap bring the 'pixalisation'
First screen shot is obtained by

`pixmap = qt.QPixmap(qfile.fileName())`
`icon = qt.QIcon(pixmap)`

And second one by 

`icon = qt.QIcon(qfile.fileName())`
