### ISSUE TITLE
[roi] Implement starting and endding user interaction

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1964]
For efficiency it is very important to implement signals for begging and the endding of the user interaction.

PyQtGraph provides
```
sigRegionChangeStarted
sigRegionChangeFinished
```

**Comment by vasole** [comment]
I guess we'll also need the signals associated to the markers representing the anchors.

**Comment by t20100** [comment]
Closing since `silx.gui.plot.items._roi_base.RegionOfInterest` provides the 2 following signals: `sigEditingStarted` and `sigEditingFinished`.
