### ISSUE TITLE
[roi] Move the implementation to an abstract class

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1972]
Most of the implementation could be moved to an `_AbstractROI` class.
All our ROIs inherite from that.

It would allow to inherit others from a ROI class without using the same implemented concepts.

**Comment by t20100** [comment]
I'm closing it.
ROIs went through a lot of reworks since this issue was opened and there is now a hierarchy of class to support ROIs.
Reopen if you think this is still needed.
