### ISSUE TITLE
Pymca-like display of legends?

### ISSUE THREAD

**Issue by mguijarr** [silx-kit/silx#2009]
Users would like to see legends like in PyMCA, under Plot1D without the need to click on 'options' then 'legends', and with a compact view.

**Comment by vasole** [comment]
If that can be called programmatically I guess it is the instantiating program the one that has to take the responsibility to show the legends dockwidget.

**Comment by vasole** [comment]
@mguijarr 

Plot1D behaves **exactly** like PyMca so you users should be used to it.

**Comment by mguijarr** [comment]
@vallsv We appreciate a lot silx, and we are already doing integration with the toolkit... However we
are also at the forefront of remarks from users, and this issue (and the previous one I added) is an
attempt to tell you what users are asking to us. Please don't blame the messenger.

So, about legends display, I took a picture of pymca from the web and you can see the compact
representation of the legend below the graph (you can see Data, Fit, Continuum, etc) :

![detail-de-la-fenetre-pymca-mcaadvancedfit-onglet-graph ppm](https://user-images.githubusercontent.com/2834952/42596520-3e91e688-8556-11e8-9915-73c44630aa58.png)

I think we can agree the Plot1D widget at the moment displays legends very differently ?

@sole: maybe behaviour is the same, but it does not look the same and I report to you our users prefer the pymca look and feel. Don't forget our users are your users too ;)

**Comment by vasole** [comment]
That behavior was lost when dropping PyQwt. That means something like four years ago!!!

 Current silx behavior is the same as PyMca. 

The only thing silx is not respecting concerning the legends it is what I have reflected in issue #2011

**Comment by vasole** [comment]
This is how it looks now in PyMca.

![image](https://user-images.githubusercontent.com/5636251/42598074-56eb5656-855b-11e8-89b1-cce31016f6be.png)

**Comment by vasole** [comment]
The Qwt look and feel was nice when having a few curves. However, when having many curves, the legends were eating most of the plot space. Current way is safer in that sense besides paving the way to future improvements like replacing the contents of the legends widget by a tree widget with access to all the properties of the curves (as it is done with the 3D objects in the silx 3D visualization widgets)

**Comment by vallsv** [comment]
Then this issue is about embedding legends in the plot? Is that a duplication with #1447?

**Comment by t20100** [comment]
@mguijarr thanks for the feedback. We do need feedback from users.
I think we all first misunderstood as the legend display in silx comes from the one in the current version of PyMca... the screenshot makes it clear.

Anyway, there is a need for a compact legend display (2nd issue on the subject with #1447)

**Comment by mretegan** [comment]
+1 for as an alternative way to display the legend 

I believe it is a natural to expect the legend to be on the plot canvas; think about how most plots are displayed in publications. This would also help when the plot is saved to file.
