### ISSUE TITLE
[plot] curve X data shape changes unexpectedly

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2014]
To reproduce

```
>>> from silx import sx
>>> p = sx.plot([0, 1], [2, 3])
>>> c = p.getCurve()
>>> c.getXData()
array([0, 1])
```

Then use  save action in the toolbar to save "Curve as Specfile (*.dat)", then use the same action again  to save "All curves as SpecFile (*dat)". This causes the following error:

```
Traceback (most recent call last):
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/plot/actions/io.py", line 604, in _actionTriggered
    return func(self.plot, filename, nameFilter)
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/plot/actions/io.py", line 339, in _saveCurves
    close_file=False)
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/io/utils.py", line 337, in savespec
    raise IndexError("X and Y columns must have the same length")
IndexError: X and Y columns must have the same length

```
If we add the line `print(curve.getXData(copy=False).shape)` in `SaveAction._saveCurves()`, we can see that XData has a shape `(1, 2)` instead of `(2,)`.

This issue can only be reproduced with PR #2013 (enables both SpecFile save options at the same time), but it could indicate a deeper problem that needs to be investigated.

Interestingly, in the ipython terminal, we cannot see a shape change
```
In [8]: c.getXData().shape
Out[8]: (2,)
```

**Comment by t20100** [comment]
Issue is in silx.io, there is a change of shape of the input array:

This should fix the issue:

diff --git a/silx/io/utils.py b/silx/io/utils.py
index 0a51f76..b4c09ea 100644
--- a/silx/io/utils.py
+++ b/silx/io/utils.py
@@ -204,7 +204,7 @@ def save1D(fname, x, y, xlabel=None, ylabels=None, filetype=None,
 
         # make sure y_array is a 2D array even for a single curve
         if len(y_array.shape) == 1:
-            y_array.shape = (1, y_array.shape[0])
+            y_array = y_array.reshape(1, y_array.shape[0])
         elif len(y_array.shape) > 2 or len(y_array.shape) < 1:
             raise IndexError("y must be a 1D or 2D array")
