### ISSUE TITLE
silx view is slow when opening hdf5 files

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2017]
With a hdf5 file with almost 200 scans (25GB) on rnice, silx view takes about 30 seconds to open the first level of the file hierarchy.
With the file locally stored on my PC the same is in the order of 2 seconds...

While the slow opening is most probably due to NFS, opening the same file with h5py, and getting all scans names and their start_time is in the order of 2 seconds... compared to the 30 taken by silx view.
So it is worth looking how we can improve the speed.

**Comment by vasole** [comment]
How long does it take to PyMca? It is to see if I also have to do things at my side.

**Comment by t20100** [comment]
pymca's fine (tested v5.3.1 on rnice), it takes something like 2 seconds or so (i.e., about the same as getting the start_time from h5py.
So there is really something to investigate in silx

**Comment by vallsv** [comment]
Where can we doanload this data?

**Comment by vallsv** [comment]
It looks like `QSortFilterProxyModel` with `sort(0, qt.Qt.AscendingOrder)` expect to populate child of the last visible items. I don't really understand what for. Without the sort function the result looks to be fast.

I have to check Qt deeply, there is maybe a magic flag.

**Comment by vallsv** [comment]
Well, there is a strange use of the API on my side too. I don't see why `sort` is called there as a configuration function.

**Comment by vallsv** [comment]
Then, for information, when using a proxy model, `hasChildren` and `rowCount` must be reimplemented, else the default behaviour is used and children are populated.
