### ISSUE TITLE
[plot] Pan image with keep aspect ratio is slow

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2053]
I use a 4096x4096 image.

- Try to pan it using keep aspect ratio
- Try to pan it after disabling keep aspect ratio
- Zoom is fast on both mode

I suspect that there is more redraw than expected when keep aspect ratio is enabled

**Comment by t20100** [comment]
Yes it is possible that there is more redraw than needed.
The thing is when keeping aspect ratio, you can only retrieve the right plot limits from matplotlib after redraw...
To options:
- check the code and avoid getting the plot limits or whatever which results in intermediate redraw
- implement the aspect ratio ourself (as done in the OpenGL backend).

**Comment by vallsv** [comment]
Long time ago.
I close that one
