### ISSUE TITLE
[doc][debian]  File not found

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#2066]
Hello, while trying to read the documentation[1]  I got the file not found error

[1] file:///usr/share/doc/python-silx-doc/html/changelog.html

do you know what is special with this file ?

**Comment by picca** [comment]
Ok, I found the problem this file is automatically compressed by the Debian build process, in order to save space.

I need to unactive this mechanism.

Cheers

**Comment by vallsv** [comment]
Maybe we should implement less features in order to reduce the size of this file ;-)
