### ISSUE TITLE
Problem at Debian side or at our side?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2070]
@picca 

Unless we have made a mistake, pyopencl is an optional dependency for silx. However, it seems to have been set somewhere as a hard dependency thus leading to unavailability of depending packages on some platforms:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905348

**Comment by picca** [comment]
Hello Armando, now that pymca depends on silx, it also depends on pyopencl transitively

**Comment by vasole** [comment]
Yes, but the point is that silx should not have a hard dependency on pyopencl if that prevents its availability on all debian platforms.

**Comment by vasole** [comment]
At our side we should make use of sys.platform and platform.machine to make clear the dependencies

**Comment by vasole** [comment]
Simpler -> Put PyOpenCL related dependencies only on verified platforms (i386 and x86_64).
