### ISSUE TITLE
[GUI] Taurus needs additional api settings

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2101]
Applications using taurus and silx have to import taurus first in order to make sure the sip API 2 is completely used. We are currently setting QString and QVariant but we need more:

                    import sip
                    sip.setapi('QString', 2)
                    sip.setapi('QVariant', 2)
                    sip.setapi('QDate', 2)
                    sip.setapi('QDateTime', 2)
                    sip.setapi('QTextStream', 2)
                    sip.setapi('QTime', 2)
                    sip.setapi('QUrl', 2)

**Comment by t20100** [comment]
silx doesn't need more, but indeed other might need those.
