### ISSUE TITLE
[NXdata] and histogram

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#2109]
There are two bug, the first one is easy, the second more nasty:
* [ ] The histogram button exists in the default image viewer but not in the NXdata image viewer. It would be nice it could be consistent.
* [ ] The histogram only applies when it is called for the first time. It gets updated when changing the image to another image, but not when changing to an NXdata image display.

**Comment by PiRK** [comment]
The first point can easily be fixed by just displaying the histogram action in the NXdata image widget. 
But synchronizing the NXdata image widget with the regular image widget requires some refactoring, because currently the different views are mostly independent.

**Comment by PiRK** [comment]
The stack view also misses the histogram action.
