### ISSUE TITLE
[opencl] Should this be info level? 

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2118]
Vs-MacBook-Pro:GIT sole$ pymcaroitool --imagestack=1 ~/Desktop/LENA/lena_FFT_shifted_00.edf 
WARNING:silx.opencl.common:For Apple's OpenCL on CPU: Measuring actual valid max_work_goup_size.

**Comment by kif** [comment]
On Tue, 18 Sep 2018 16:13:48 +0000 (UTC)
V. Armando Solé <notifications@github.com> wrote:

> WARNING:silx.opencl.common:For Apple's OpenCL on CPU: Measuring actual valid max_work_goup_size.

We are now able to measure this explicitely ... it is related to old code

**Comment by vasole** [comment]
That warning is still in current silx code code. To me the logging should be at the INFO level.

THe same with the warning concerning PyOpencl being disabled by the environment variable. If it has been decided to disable it we are not talking about a warning but about a choice and it should also be at INFO level.

**Comment by t20100** [comment]
Decided to move it to INFO and improve probing of max work group size (which depends on the kernel) later.
