### ISSUE TITLE
[plot] Need for different ways to hightlight active curve.

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2119]
Discussed long ago.

Need of alternative methods to highlight the active curve: for instance active color could be set to None and line width could be expressed as an integer factor to be applied to the line width to achieve highlight without change of color. However, line symbol has to be modified too (if the curve has no line it can be difficult to know it is the active curve).

**Comment by vasole** [comment]
Well, this issue addresses those points. 

Where I disagree with you is about being a problem to change the color when there is only one curve. It is enough to set the active curve color to the one you would like one there is only one curve to have the problem disappear.

Concerning the difficulty to implement, it is not difficult but there are other priorities. Just take a look at the amount of issues associated to the 0.9 milestone initially expected mid October. You are welcome to submit a pull request.

**Comment by vasole** [comment]
Are your users aware that a click on an empty region deselects the active curve?

Concerning the implementation I do not think one needs to deal with signals. As far as I understand it basically one needs a setter for the style and the maker in a similar way as for the color. Allow 'none' to both and to color and implement the tiny bit of code below. As I said, not difficult but...

..code:

                # Curve specific: handle highlight
                if kind == 'curve':
                    item.setHighlightedColor(self.getActiveCurveColor())
                    item.setHighlighted(True)

**Comment by t20100** [comment]
The API of `PlotWidget` and of the `Curve` item needs to be extended.
By default, I would keep the current behavior for backward compatibility.

**Comment by t20100** [comment]
@maurov if you want to do it, we can first discuss it, so you know where to look at.
