### ISSUE TITLE
Using a non-default profile window for the profile toolbar 

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#2126]
I'm trying to set a non-default profile window using the profileWindow argument:

```
_profileWindow = PlotWidget()
self._profileToolBar = ProfileToolBar(plot=self, profileWindow=_profileWindow)
self.addToolBar(self._profileToolBar)
```

However when I close the main plot window, the profile window remains open. Any ideas how to fix this?

**Comment by vasole** [comment]
One possibility is to re-implement the main window close event. A brute force approach used with PyMca:

code: 
 
    def closeEvent(self, event):
        if __name__ == "__main__":
            app = qt.QApplication.instance()
            allWidgets = app.allWidgets()
            for widget in allWidgets:
                try:
                    # we cannot afford to crash here
                    if id(widget) != id(self):
                        if widget.parent() is None:
                            widget.close()
                except:
                    _logger.debug("Error closing widget")
        return PyMcaMdi.PyMcaMdi.closeEvent(self, event)

**Comment by t20100** [comment]
If you set the parent of your `_profileWindow` to the profile toolbar, it should be destroyed when your main plot window and the profile toolbar is destroyed.

Oherwise, as an alternative to overrriding `closeEvent`, you can install an event filter to get the close event: http://doc.qt.io/qt-5/qobject.html#installEventFilter

**Comment by t20100** [comment]
Actually, you could have provided your main plot window as the parent of the profile plot, but there is some code in `PlotWidget` which changes the `PlotWidget` behavior from a main window to a widget when a parent is provided to `__init__`.... which prevents to simply use Qt parenting to handle the closing.

You are left with overriding `closeEvent` or using an event filter.

**Comment by vasole** [comment]
Using event filters used to be discouraged because it could slow down applications quite a bit (all events going though python code instead of C++ code)

**Comment by mretegan** [comment]
Just for future reference, I've ended up using the `closeEvent` of my plot widget to close the _profileWindow.

```
def closeEvent(self, event):
    self._profileWindow.close()
    event.accept()
```

**Comment by vasole** [comment]
Unless you are absolutely sure nobody else can be connected, it is preferable to forward the event instead of event.accept()
