### ISSUE TITLE
[doc] silx view should be able to access documentation

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2163]
Look for the documentation locally and if not available open the URL.

Preferable to use the predefined browser.

**Comment by vallsv** [comment]
It was needed for this release?

**Comment by t20100** [comment]
To me, we should stop adding features for 0.9 and only do bug fixes.

**Comment by vasole** [comment]
I thought it was clear because I did not put the 0.9 milestone and the issue was added during our last meeting in which we decided not to add any new feature.
