### ISSUE TITLE
Testing the same image with sift but get different number of feature points

### ISSUE THREAD

**Issue by curry1990** [silx-kit/silx#2165]
Hi, I am testing the same image with Sift. And I get different number of feature points each time.
devicetype = "GPU"
sift_ocl = sift.SiftPlan(template=marker, devicetype=devicetype) 
keypoints = sift_ocl.keypoints(marker)
print("Number of keypoints: %s" % len(keypoints))
I am trying to figure it out.

**Comment by curry1990** [comment]
Thank you @kif.
I agree that it is due to rounding errors.

I have print the feature points in format '%cols, %rows, %scale, %angle' as follows.
1045.382690, 1015.630920, 6.142435, -0.320477
1045.382690, 1015.630920, 6.142435, -2.011887
vs
1045.382690, 1015.630920, 6.142435, -0.333625
1045.382690, 1015.630920, 6.142435, -2.011887
1045.382690, 1015.630920, 6.142435, 1.767684

It seems the value of angle varies and "val >= 80%*maxval" shows different result.

Then, I try to modify the 0.8f to 1.0f in kernel named 'orientation_gpu' as follows,
if (hist_curr > hist_prev  &&  hist_curr > hist_next && hist_curr >= 0.8f * maxval)
{
    ...
} //end "val >= 80%*maxval"
After that, the number of feature points is invariant.

Then, I try 0.99f instead of 1.0f, the number of feature points varies. Seems that it is not due to rounding error.

**Comment by curry1990** [comment]
Thank you @kif.
I am glad to submit a pull-request, but 0.8f is a recommend param instead of 1.0f. It will make sift more robust.
Anything helpful for sift cl will try to submit a pull-request.

**Comment by curry1990** [comment]
Hi, @kif .
Have you ever run sift cl on Mali GPU? I just wonder whether sift cl can run real time on Mali or not.

**Comment by curry1990** [comment]
Thanks @kif . I have measured 80ms per 512x512 image using my Mac.
I don't have a board to test sift directly on Mali. Using Asus tinker-board with Mali-T764 GPU to test sift is a good choice. Are you conveniences and willing to test sift on Asus tinker-board? I'm looking forward to it. Thanks again.

**Comment by kif** [comment]
I have re-installed "armbian" on the tinkerboard and managed to install OpenCL from: https://github.com/rockchip-linux/rk-rootfs-build/tree/master/packages/armhf/libmali without major issue.

According to clpeak, the GPU (4 core) is running at 400MHz. The bandwidth available to the GPU is 4.5GBps and 3.5 GFLops (up to 21 using float8 !). It is better than what I got from linaro but not impressive. From the CPU single threaded memory BW is ~800Mbyte/s, and 4.05  with all cores.
It may take a while before having the whole python stack rebuilt on the device.

Nota: apparently there is no support for the CSI-camera with armbian (yet) while the kernel is much more recent (4.14)

**Comment by curry1990** [comment]
Thank you very much for this test. I am very appreciated.

**Comment by kif** [comment]
I just managed to install all programs. PyFAI is running 2x faster on GPU than the CPU (which is already decent on the tinkerboard)
The SIFT-keypoint extraction for an image of 512x512 takes ~600ms with the GPU at 400MHz. So it is not real-time but not too bad neither.

**Comment by curry1990** [comment]
Thank you very much @kif . Nice result for some embedded system, slightly ahead of expectations. 
It's really nice of you to help me! Thanks again.
