### ISSUE TITLE
[Gui] Hdf5TreeView

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#220]
Provide a tree to display HDF5 files.

Can be checked here https://github.com/vallsv/silx/tree/hdf5widget

- [x] Qt-API
- [x] Qt-like events
- [x] Icons
- [x] Drag and drop to reorder files
- [x] Drop external file
- [x] Easy to create with specific columns
- [x] Auto column size
- [x] Support files with broken links
- IO
    - [x] HDF5
    - [x] Spec file
    - [x] fabio
- [x] Fast enough for file containing 100000 datasets
    - Right now the main node is displayed instantly
    - Expending the node containing 100000 datasets takes 7.5 secondes (the second time it takes 2 secondes)
    - Expending a node containing 100000 groups may be longer
- Context menu
    - [ ] Close file
    - [ ] Resync file
- [x] Example
- @t20100 brainstorming
   - [ ] Update model to support weakref
   - [ ] Create signals for fileLoaded, beforeFileClosed (can abort close), fileClosed, fileSynchronized
   - [x] Create methods to remove h5py object, 
   - [x] Update context menu API (should provide something more consistent with the plot)
- [x] Sorting nexus items (starttime, endtime, name)
    - Naive code using proxy model. Horribly slow with a lot of items
- [ ] Can be used in PyMCA
- [x] Cache icons in the tree model

![screenshot from 2016-08-31 15 39 43](https://cloud.githubusercontent.com/assets/7579321/18130987/6e83e576-6f91-11e6-987b-e7af7c9bb52e.png)

**Comment by vasole** [comment]
- Your +/- 5 seconds looks fast enough to me
- The Qt like events are fine for software engineers. I consider one should also offer the possibility to generate  "digested events" to minimize the knowledge of Qt requested by other customers. For instance, one could provide a programmable callback and, in that case, call that callback with the digested information (a dictionary in the lines of what PyMca is doing: file, type of event, child, ...).

**Comment by vallsv** [comment]
- I check the real amount of time of loading a file with 100000 datasets.
      - 10 seconds for loading
      - 3 seconds to expand the group containing this
      - i still have to check with a profiler, and then with with a cython object
- For events, i really think that dictionaries are not a maintainable pattern. If we do it for this widget we have to do it for all our widgets. Then i really don't like that idea.

Everything is exposed as h5py objects. If it is not enough simple, we should provide our own H5 model, which is i guess not a good idea.

The example of the current version (https://github.com/vallsv/silx/blob/hdf5widget/examples/hdf5widget.py) shows that it is not so difficult to extract what you want on the `displayEvent` function. If it is really needed by PyMCA, there is no problem to create a class wrapper in PyMCA.

**Comment by vasole** [comment]
- My experience with dictionaries is just the opposite :) Whenever I had a signal sending a dictionary, I had no troubles when going from Qt2 to Qt3 to Q4 to Qt5. However, if I was using a Qt-like object, things changed from version to version (particularly with tree-like widgets).

**Comment by vasole** [comment]
- Don't you think that code like the one in the displayEvent function will have to be reproduced by almost any customer of the Hdf5Widget?

**Comment by vallsv** [comment]
- There is no difference between a class and a dict. The difference i see is you create and manage your own event, or you use the Qt events. We can manage our own signals with an own class. But will we are using Qt, we should provide Qt concepts.
- The callback provides the object stored on the tree, and no more. A common pattern for this kind of widget is a pass-through: i get the h5py object from the signal and i set it to another widget which manage this kind of objects. Sure the last widget have to manage a h5py object: that's his job. But a pass-through should not taste the dish.

I will work with Thomas on the API if possible.

**Comment by vasole** [comment]
Just to keep track:

- When widget is provided with an instance and not with a path to a file, it is convenient to have a weakref proxy instead of a "hard" reference.
- Widget should be "smart" enough to sort the contents of the file if that support is requested (with default set to True).

**Comment by vallsv** [comment]
I have updated the description with that

**Comment by vasole** [comment]
A test suite should be added. For widgets, the very minimum is import and creation of an instance but we should do more. The test suite should also check the support of SPEC files in the widget (generating a SPEC file withing the test suite).

**Comment by vallsv** [comment]
Splited into several issues
