### ISSUE TITLE
[gui] DockWidgets (again)

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2213]
Applications should be able to decide where DockWidgets should appear. The current default is good for PyMca (obviously because it was PyMca's default) but I think it is not for silx view.

I'm afraid silx view (or NXdataView) should always show the sliders under the plot irrespective of plot size.

![image](https://user-images.githubusercontent.com/5636251/47440157-e5d42600-d7ad-11e8-968b-b70a270daf07.png)

**Comment by vasole** [comment]
Should this be considered closed by #2214 ?

**Comment by vallsv** [comment]
Yes, there is not much things we can do.
