### ISSUE TITLE
Colormap: getColormapLUT is not working for our own colormaps

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2217]
- `colormap.getNColors(None)` is working but could have the wrong number of colors
- cause `getColormapLUT` returns `None`
- then 256 colors are requested

Then there is no way to access to the stored raw LUT.

It's a small issue, mostly with no consequences.

**Comment by t20100** [comment]
`colormap.getNColors(None)` actually returns the right number of colors.
Code could be improved though.
