### ISSUE TITLE
[plot] API to custom background color

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2220]
Could it be possible to provide an API to custom 2 different background colors?

```
import matplotlib.pyplot as plt
fig = plt.figure()
fig.patch.set_facecolor('cyan')
ax = fig.add_subplot(1, 1, 1)
ax.set_facecolor('blue')
```
![screenshot from 2018-10-30 13-32-18](https://user-images.githubusercontent.com/7579321/47718465-c96e3880-dc48-11e8-8bc6-03071d309ce6.png)

**Comment by t20100** [comment]
It should not be too hard to do, you already gave the code for the matplotlib backend....

**Comment by t20100** [comment]
We discussed 2 options:
- Using `QWidget` palette
- Adding  specific methods for it.

In the plot3d widgets, I added some specific methods for background and foreground colors, one of the reason was that I needed signals when the colors change to synchronize the associated parameter tree widget.

**Comment by titusjan** [comment]
The background color doesn't seem to work on the color legend (see screen shot). I used the following test program.

    plot = Plot2D(backend=BACKEND)

    colormap = Colormap(name='viridis', normalization='linear', vmin=0.0, vmax=2.0)
    plot.setDefaultColormap(colormap)

    data = np.random.random(512 * 512).reshape(512, -1)
    plot.addImage(data, legend='random', replace=False)

    plot.setBackgroundColor(QColor(80, 80, 80))

    data = np.arange(512 * 512.).reshape(512, -1)
    plot.addImage(data, legend='arange', replace=False, origin=(512, 512))

![screen shot 2018-12-19 at 15 03 20](https://user-images.githubusercontent.com/3320415/50224908-5eff8c00-039f-11e9-9f2a-b7ddf4a2d585.png)

**Comment by vallsv** [comment]
If it is easy to do, i can take a look.

**Comment by t20100** [comment]
The `ColorBarWidget` is a different widget and its background is not sync with the `PlotWidget`.

Here is some code to set the `ColorBarWidget` background:
```
from silx.gui import qt

colorbar = plot.getColorBarWidget()
palette = colorbar.palette()
palette.setColor(qt.QPalette.Background, qt.QColor(80, 80, 80))
palette.setColor(qt.QPalette.Window, qt.QColor(80, 80, 80))
colorbar.setPalette(palette)
```

To sync it automatically, it means adding a signal when the plot background is changed that the color bar action is listening to in order to update the ColorBarWidget background...
