### ISSUE TITLE
[Plot] Saving a txt file

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#223]
I get the following error when I try to save the txt file:

```python
Traceback (most recent call last):
  File "E:\build\exe.win-amd64-3.5\silx\gui\plot\PlotActions.py", line 739, in _actionTriggered
    return self._saveCurve(filename, nameFilter)
  File "E:\build\exe.win-amd64-3.5\silx\gui\plot\PlotActions.py", line 605, in _saveCurve
    autoheader=autoheader)
  File "E:\build\exe.win-amd64-3.5\silx\io\utils.py", line 151, in save1D
    autoheader_line = xlabel + csvdelim + csvdelim.join(ylabels)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Also the fact that `xlabel` and `ylabel` are `None` is a weird as I set them both using `setGraphXLabel` and `setGraphYLabel`.

**Comment by PiRK** [comment]
I can simply set `xlabel="x"` and `ylabel=["y1", "y2"…]` to prevent the crash. Alternatively I can change the behavior of `silx.utils.save1D` to not add a header line when `xlabel` or `ylabel` are `None`. I'm not sure which solution is the best. 

Regarding the intrinsic reason why `xlabel` and `ylabels` are `None`, this needs to be investigated. 
It seems the information is not passed along in the return values of `plot.getActiveCurves` or `plot.getAllCurves`. I would expect that even when the legends are not explicitly specified, the default values `"curve_0, curve_1…"` would be returned.

**Comment by t20100** [comment]
This was introduced by PR #162 when fixing #139.
Before curves always had their own labels.
I'm fixing it.

**Comment by PiRK** [comment]
It seems that the labels of curves can be set once, when initially adding curves with `plot.addCurve`. When labels are not specified in this methods' parameters, they are set to `None`. 

`setGraphXLabel` and `setGraphYLabel` only set the default values displayed next to the labels when the currently selected curve does not have a label. It does not update ylabels of any curve.
