### ISSUE TITLE
ColormapDialog: Use log scale for histogram for log scale colormaps

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2235]
It's probably better to use a log scale X axis for log-scaled colormap in the histogram plot of the ColormapDialog.. at least worth trying....

An issue will arise when we provide more colormap scales (arsinh, sqrt, pow) then plot axis also need to provide those scales....

**Comment by vallsv** [comment]
I try it. The result is not very good with the current implementation.

- We are using a curve to constrain the reset zoom. As result, in X log scale there is a lot of limitations. The same could be tested with `setDataMargins`.
- On pyFAI with log scale, we still do not see the data, i don't understand why. maybe the image i used was not very nice.
