### ISSUE TITLE
[plot] Wrong autozoom with histogram and log axis

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2237]
The autozoom with histogram is done well (left image), while axis is not switched to log scale (right image).

- The negative part on the X-axis is not display (that's ok)
- But the part between 0..22 on the y-axis should be displayed

![screenshot from 2018-11-09 13-22-32](https://user-images.githubusercontent.com/7579321/48262513-0a253900-e423-11e8-95c3-0b80914ea170.png)

**Comment by t20100** [comment]
You cannot display 0 on the log axis, so what is done is to clip the limits to the first strictly positive X value (I guess 22 in your case)... if you take the smallest float positive value (5e-324) as the lower limit you would no more see your histogram.

**Comment by vallsv** [comment]
To be clear, the problem is on the Y axis. The linear one.

**Comment by t20100** [comment]
OK then it's a problem.. it's probably due to the fact that histograms are handled as a curves to compute their range while they should include 0.

**Comment by t20100** [comment]
Probably better to add a baseline value for histograms which is 0 by default but can be changed and is included in the bounding box calculation.
