### ISSUE TITLE
[plot] Add a threshold to avoid to zoom when we click

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2261]
On GUI which requesting clicking a lot people often zoom when while they would like to click.

A threshold in delta mouse position already exists.

A temporal one could fix the problem (when the zoom option is activated). 200 or 500ms (between mouse down and mouse up) is enough i think.

**Comment by t20100** [comment]
Worth trying it.
A temporal threshold during which the mouse position threshold is larger might also be an option.
