### ISSUE TITLE
py3-violating exception in silx/third_party/_local/concurrent_futures/_base.py, line 414

### ISSUE THREAD

**Issue by newville** [silx-kit/silx#2274]
I am trying to build a conda package for silx 0.9.0, and doing that runs into a problem of:

```
compiling .pyc files...
  File "lib/python3.6/site-packages/silx/third_party/_local/concurrent_futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

To be clear, `silx` 0.9.0 imports and appears to run fine for me.

I'm left wonderign how others have created a conda package,  but it seeems like this should be fixed by replacing this with `raise exception_type(self._exception, self._traceback)`, I  believe.

**Comment by t20100** [comment]
Hi,

This file is only used with Python2 as a backport of python3 features.
If you are packaging silx for python3 only, you can remove this file, everything will continue to work.
We can make the syntax python3 compatible for cases were every module is blindly compiled.

BTW, `silx.third_party` embeds some dependencies of silx (including python3 backports among others).
Provided that the corresponding dependencies are available, `silx.third_party._local` can be removed.
This is done for Debian packaging.

**Comment by newville** [comment]
@t20100 yeah, it looks like it is not really used, or at least the limited parts of silx (basically, reading spec files) seem to never have a problem.   But,  when I try to build a conda package from 0.9.0 without modifying the source tree at all, it wants to byte-compile all the files, and so fails.  I'm sort of puzzled how others managed to build a conda package.  

I guess I can fork and fix or remove this code before creating a package, but it seems like an issue you all would want to be aware of.

**Comment by PiRK** [comment]
Thanks for letting us know. I'm not familiar with conda packaging, and I did not know that there was byte-compilation in the packaging process. I suppose the current conda packagers must have a script that gets rid of the problematic third-party directories.

Do we know who is doing the packaging at present? I can't find any information about the uploader on conda-forge.

**Comment by vasole** [comment]
I think we should modify the code to solve the issue.

**Comment by t20100** [comment]
We can make it py2/py3 compatible by either not providing the traceback to the exception or using `six.reraise` to maintain the very same feature.

I'm fine with first option, anyway this code is used at a single place in `silx` and for python2 support... so we'll get rid of it in the future.

**Comment by vasole** [comment]
@t20100 

Since that code is going to be actually executed (if ever) under Python2, the simplest solution seems to me something in the lines of replacing the offending line by:

``exec("raise exception_type, self._exception, self._traceback")``

That should work under Python2 while making Python3 happy.

**Comment by vasole** [comment]
@newville 

The alternative way of preventing the issue when building the package could be to skip the generation of .pyc files.

https://github.com/conda/conda-docs/pull/365/commits/58fe1166d8270dc45e815f60ad9ce46582fb4e07

Unless the conda machinery ignores it, an even simpler solution would be to set the environment variable PYTHONDONTWRITEBYTECODE when building the package.

**Comment by newville** [comment]
@vasole @t20100 Well, `raise exception_type(self._exception, self._traceback)`  is valid syntax for both Python3 and Python2.  I don't know if it does what you intend.... perhaps you test that?  Anyway,  that works for me to make conda packages for Python3.6, at least for linux and macos (haven't tried windows yet).

I'd be willing to make a PR if that seems like a desirable solution.  Using `exec()` or preventing byte compilation seem like attempts to avoid triggering a known problem in the code in place of actually fixing the code.  I'm not eager to take that approach.

I have to admit being completely baffled by the `third_party` stuff here.  Why do you include your own copy of `six` and use complicated import statements that prefer your own version over the "normal" package?  Why don't you just require six>=0.10?   Similarly, why not just use scipy.spatial instead of your own copy?  I really don't get why any of this exists... Isn't it just extra work for you?  It certainly is work for me now.

Any chance that the code to read spec files could be a separate library?

**Comment by vasole** [comment]
- Are you sure that syntax is valid? I'm saying it because if you take a look at six.reraise they follow the exec approach instead of following your proposed solution:

https://github.com/benjaminp/six/blob/master/six.py

- own copy of some modules. Those modules are not available as packages on all the distributions used at the ESRF.

**Comment by vasole** [comment]
As t20100 pointed out in his very first reply, you can just get rid of the _local directory.
