### ISSUE TITLE
[mask] State of the mask inconsistent when loaded from numerical values

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2284]
I try to load a mask from an image containing `[[0,1,2,3,4,5,6,7,8,9,10]]`.

Using the pencil with set or unset sometimes do not change anything.

The rendering looks strange.

Maybe i am wrong.

**Comment by t20100** [comment]
I cannot reproduce, can you show me?

**Comment by vallsv** [comment]
Yes, here is what i have.

I dont have the same look and feed when i load the mask or when i do it manually.

![mask-inconsistency](https://user-images.githubusercontent.com/7579321/50142553-b4a63c80-02aa-11e9-8908-0b46b517cba9.png)

**Comment by vasole** [comment]
It seems to be due to using different mask levels.
