### ISSUE TITLE
NX_class name decoding error

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#2292]
I get this traceback when trying to open a file with silx view: 

```
'utf-8' codec can't decode byte 0xb2 in position 1: invalid start byte   File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5TreeModel.py", line 515, in data
    return node.dataType(role)
  File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5Item.py", line 401, in dataType
    text = self.nexusClassName
  File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5Item.py", line 375, in nexusClassName
    self.__nx_class = str(self.__nx_class, "UTF-8")
```

The type of the self.__nx_class object is <class 'numpy.ndarray'>.

**Comment by vasole** [comment]
Independently of having to avoid the error, what program wrote that file?

strings
    NX_CHAR: The preferred string representation is UTF-8. Both fixed-length strings and variable-length strings are valid. String arrays cannot be used where only a string is expected (title, start_time, end_time, NX_class attribute,…). Fields or attributes requiring the use of string arrays will be clearly marked as such (like the NXdata attribute auxiliary_signals).

**Comment by PiRK** [comment]
Same issue as #2170 

I'm sure that we discussed the issue, and I think it might be fixed in the current master, but I have not been able to find a related pull request or a commit.

Is it possible for you to send me the file so that I can try to replicate the issue?
Which version/branch of silx are you using?

**Comment by mretegan** [comment]
I am using the current master. Here is the file https://cloud.esrf.fr/index.php/s/FyfLLfdMuT3wo2a.

**Comment by PiRK** [comment]
Nevermind, I'm able to replicate the issue with another file.

**Comment by PiRK** [comment]
Python 3:
```
In [1]: from silx.io import open as sopen

In [2]: f = sopen("oleg.dat")

In [3]: f.attrs["NX_class"][()]
Out[3]: 'NXroot'

In [4]: f.attrs["NX_class"]
Out[4]: array('NXroot', dtype=object)

In [5]: str(f.attrs["NX_class"])
Out[5]: 'NXroot'

In [6]: str(f.attrs["NX_class"], "UTF-8")
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-41890cb849f6> in <module>()
----> 1 str(f.attrs["NX_class"], "UTF-8")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 0: invalid continuation byte

In [7]: str(f.attrs["NX_class"][()], "UTF-8")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-1bc6f55ab70f> in <module>()
----> 1 str(f.attrs["NX_class"][()], "UTF-8")

TypeError: decoding str is not supported

In [8]: type(f.attrs["NX_class"][()])
Out[8]: str

```

**Comment by vasole** [comment]
It seems normal, no? One can decode bytes but one cannot decode strings.

**Comment by mretegan** [comment]
So the type column in silx view should display the NeXus type or the type of Python object?

**Comment by mretegan** [comment]
There are some issues with the `humanReadableValue` method. Traceback for a NeXus file created using this tutorial http://download.nexusformat.org/doc/html/examples/h5py/index.html.

```
ERROR:silx.gui.qt._qt:<class 'AttributeError'> 'str' object has no attribute 'shape'   File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5TreeModel.py", line 515, in data
    return node.dataType(role)
  File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5Item.py", line 398, in dataType
    text = self.nexusClassName
  File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5Item.py", line 371, in nexusClassName
    text = self._getFormatter().humanReadableValue(obj)
  File "/Users/marius/Library/Python/3.7/lib/python/site-packages/silx/gui/hdf5/Hdf5Formatter.py", line 99, in humanReadableValue
    if dataset.shape is None:
```

**Comment by PiRK** [comment]
Thanks for testing. Now it should also work for attributes written as unicode `nxentry.attrs[u'NX_class'] = u'NXentry'`

**Comment by vasole** [comment]
That in addition it is the recommended way in order to avoid different readout when using python2 or python3.
