### ISSUE TITLE
Support foreground color

### ISSUE THREAD

**Issue by titusjan** [silx-kit/silx#2296]
I would like to make plots with white axes, lables, and grid lines on a black background. I noted that in issue #2220 a `setBackgroundColor` method was added to the `PlotWidget` class, but I can't  find a corresponding `setForegroundColor` to set the color of the axes, labels and grid lines. 

Is it currently possible to set the foreground color? If not, could you please implement this?

**Comment by vallsv** [comment]
Hi,

I am pretty sure it is not possible to change the text color yet. I will not have time to do anything around, but maybe somebody else?

**Comment by t20100** [comment]
No foreground color yet, but it should be not to hard to do:
- Adding `BackendBase.setForegroundColor` method and implementing it for both backend
- For the OpenGL backend, the color parameter is already coded in the shader but it is set to black in `GLPlotFrame.py`. It's possible to make it settable and use it in  `GLPlotFrame.render` and also set the color of all `Text2D` instance and then call this from `setForegroundColor`.
- For the matplotlib backend calling the right matplotlib methods to set axes, tick, labels and title color.

@titusjan if you feel like doing it it will be welcomed, I also have quite some stuff already planed for next release.

**Comment by titusjan** [comment]
I had some free time so I made a PR. Please take a look.

**Comment by t20100** [comment]
closed by #2317
