### ISSUE TITLE
[Gui] Add uic to the list of components

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#230]
In PyQt4 and PyQt5 there is a uic module which can be used to load .ui file created with Qt Designer (there is something similar in PySide). Would it be possible to have this under silx.gui?

**Comment by t20100** [comment]
This was looked up in #155, but not implemented.
As it is a recurrent demand, I think we should add uic.loadUi to silx.gui.qt.

The rational not to add it was that there is no uic module in PySide and that PyQt4.Qt does not provide a uic module.
We can provide a loadUi for PySide: https://gist.github.com/cpbotha/1b42a20c8f3eb9bb7cb8 (used in PyFAI).

**Comment by vasole** [comment]
From the point of view of the library the uic module is not needed because the application using the library can make the choice. However, if there is an existing solution I'm not against.
