### ISSUE TITLE
[PriintPreview] Comment position left alignment not respected

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2316]
One obtains

![image](https://user-images.githubusercontent.com/5636251/50688484-f31b5580-1025-11e9-97f9-c9f05bd0d4ce.png)

instead of

![image](https://user-images.githubusercontent.com/5636251/50688443-ce26e280-1025-11e9-90d9-3b4f2c58ccd6.png)

**Comment by vallsv** [comment]
Closed by #2315
