### ISSUE TITLE
Roadmap for dropping python 2.7 (... and 3.4)

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2342]
Official end of life of python 2.7 is in less than a year (https://pythonclock.org/), main projects have already dropped python 2.7 - and 3.4 (with a LTS version with bug fixes for this year).

We should advertise a date for dropping python2.7 in next release notes...

**Comment by vasole** [comment]
Agreed to document that python 2.7 support can be dropped prior to the end of the year.
