### ISSUE TITLE
[doc] silx/dev doc broken

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2344]
http://www.silx.org/pub/doc/silx/dev/  is empty

**Comment by t20100** [comment]
Probably because nightly build has failed... We should check that build succeed before updating the doc in the nightly build scripts....
BTW, next nightly build should be fine

**Comment by vallsv** [comment]
Ok i see, then it's not a big issue.
It's maybe better to have nothing? Instead of an unsynchronized thing?
Up to you.

**Comment by t20100** [comment]
I'm OK with it as it is.
The documentation of the releases is there anyway and we usually fix CI/nightly build quickly.

**Comment by vallsv** [comment]
Ok. Let's close it then
