### ISSUE TITLE
[stats] create 'line' stats widget

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#2358]
pymca like widget which display the statistic on one or two lines with stat name and value.

**Comment by payno** [comment]
This kind of widget is dedicated to the active item. But we have several active item.
So I guess it will be specific to kind defined by the user. Otherwise it will be  mess.

**Comment by t20100** [comment]
Yes...
Unless we rework the active item stuff: having a selection as Qt usual way would be simpler: 0 or 1 current item and option for multiple selected items.
But this needs a major rework of the plot such as using items as uid rather than (legend. kind)

**Comment by t20100** [comment]
closed by #2360
