### ISSUE TITLE
For scatter plot3d please add alpha for depth

### ISSUE THREAD

**Issue by jonwright** [silx-kit/silx#2414]
When viewing points on a 3D scatter plot it is difficult to see the 3D depth. Can you add an "alpha" color for the depth so the points that are further away from the viewer are fainter (e.g. like distance fog : https://en.wikipedia.org/wiki/Distance_fog )

Thanks!

**Comment by t20100** [comment]
PR #2486 provides a first implementation of linear fog effect in silx plot3d.

For know it is only an on/off option, but more control can be added if needed such as setting the range where to apply the fog, using a different mapping function (currently linear) or setting the color of the fog.
