### ISSUE TITLE
[silx view] Add a NXdata 3d view

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2415]
So that for a NXdata with 3D data, one has 2 views: the current NXdata view with a stack viewer and a 2nd view with a 3D view.

**Comment by vallsv** [comment]
The better thing to do is to create a new main feature: A view that can expose sub views. In this way, i would be really clean to filter the views. I could do that.

```
3D data -> is catched by an abstract 3D nx view -> which provide a 2D view and a 3D view
```

**Comment by vallsv** [comment]
After some tests, the patch is bigger than expected (and not yet ready).
It's safer to provide it for the 0.11 release.

If the feature is needed for 0.10, we still can implement it using a dedicated view (as proposed first):
- The 3D on the NXview
- The 2D (based on 3D data) and another view
