### ISSUE TITLE
[scatter view] bad limits in the color bar

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#2424]
When starting the ScatterView widget, the color bar is systematically set in the interval [0,1] and does not consider the array limits. 
However clicking the "colormap" dialog, I see the limits are correctly calculated, and the color bar updates to its right values when I uncheck "auto" 
![image](https://user-images.githubusercontent.com/502315/52624929-2ae0ad00-2eb0-11e9-984d-f24fb9f98af6.png)

![image](https://user-images.githubusercontent.com/502315/52624975-42b83100-2eb0-11e9-9ab1-42c7e3e023a3.png)

**Comment by t20100** [comment]
I cannot reproduce it, can you share the code that is used?

**Comment by srio** [comment]
Try this: 

'''

    from PyQt5.QtWidgets import QApplication
    import numpy
    n = 100
    x = (numpy.random.random(n) - 0.5) * 100
    y = (numpy.random.random(n) - 0.5) * 100

    print(x.shape,y.shape)
    use_backend = 'matplotlib'
    # use_backend = 'gl'

    app = QApplication(sys.argv)

    plot_canvas = ScatterView(backend=use_backend)

    color_array = x


    plot_canvas.setData(x,y,color_array,alpha=numpy.linspace(0.,1,n))

    plot_canvas.resetZoom()
    plot_canvas.setGraphTitle("title")
    plot_canvas.setColormap(Colormap('viridis'))

    ax = plot_canvas.getPlotWidget().getXAxis()
    # if self.x_range == 1:
    #     ax.setLimits(self.x_range_min, self.x_range_max)
    ax.setLabel("xtitle")

    ay = plot_canvas.getPlotWidget().getYAxis()
    # if self.y_range == 1:
    #     ay.setLimits(self.y_range_min, self.y_range_max)
    ay.setLabel("ytitle")

    plot_canvas.show()
    app.exec()

'''
Look at the color bar, it is assigned to x, so the limits must be [-50,50]: 

![image](https://user-images.githubusercontent.com/502315/52639565-d69bf400-2ed4-11e9-8a5b-e35358989ed0.png)

When I open colormap dialog and uncheck auto, I get what I think should be displayed since the beginning: 

![image](https://user-images.githubusercontent.com/502315/52639629-f8957680-2ed4-11e9-8cec-e2b2cda7bbee.png)

**Comment by t20100** [comment]
Thanks for code to reproduce.

Until we fix the issue, as a workaround, moving:
`plot_canvas.setColormap(Colormap('viridis'))`
before:
`plot_canvas.setData(x,y,color_array,alpha=numpy.linspace(0.,1,n))`
makes it work.
