### ISSUE TITLE
[ColormapDialog/PlotWidget] Add an option to set colormap range from visible data

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2429]
It would be convenient to have a button in the ColormapDialog to set the colormap range from the currently visible data when displaying an image (or a scatter plot), so one can adjust the contrast to what currently displayed.

**Comment by t20100** [comment]
Feedback from beamline: +1

**Comment by payno** [comment]
IT could be also generalize for other Items (curve...). But will bring some complexity. Let's focus on image / scatter plot from a RegionOfInterestManager (let's here also only focus on a rectangular ROI). In fact some of those development should / could be related with computing statistics on ROI.
