### ISSUE TITLE
[plot] Right axis handling

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2432]
Something has changed in current master. With silx0.8.0 and 0.9.0 taking a derivative with PyMca shows the derivative on the plot. With silx 0.10.0 the right axis is set but the curve is not seen. Most likely the right axis curve is hidden under the plot.

**Comment by vasole** [comment]
ipython --gui=qt

from silx import sx
p = sx.plot([1, 2], [1, 4])
p.addCurve([1, 2], [0.5, 0.5], legend="dummy", yaxis="right")

The second curve is not shown despite the right axis being adjusted.

**Comment by t20100** [comment]
Bad issue, nice to have catch it before the release!
