### ISSUE TITLE
[0.10 release] InterpolatorInitThread

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#2459]
Bring a segfault on macos, python3.5 and pyside2 (several version of it (11.2 and latest at least))

**Comment by payno** [comment]
Seems to come from the latest scipy release (1.2.0 / 1.2.1 in February 9) and the LinearNDInterpolator.

On our mac the folowing sentence generate the same seg fault:

```python
from scipy.interpolate import LinearNDInterpolator
import numpy
n_points = 10 * 10
l = LinearNDInterpolator(points=numpy.arange(n_points).reashape(10, 10), values=numpy.arange(n_points).reshape(10, 10))
```

**Comment by payno** [comment]
Silx test seems ok with the 1.1.0 version at least

**Comment by t20100** [comment]
Issue is with `macOS` <= 10.12 and `scipy`'s wheel >= 1.2.0

Workaround: Either update `macOS` or downgrade `scipy`.
