### ISSUE TITLE
[Plot] Let's plot events be objects

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#246]
Plot events are currently dict.

Proposition: Make them instance of some Event class with attributes or methods to access their content and a **getitem** for backward compatibility with dict events

**Comment by vasole** [comment]
The ``__getitem__`` approach seems a good way to keep backwards compatibility while allowing for extension.

**Comment by t20100** [comment]
Closing as not being contemplated in 5 years.
Please, reopen if needed.
