### ISSUE TITLE
[ROI] sigROISignal no longer emitted when changing ROI in the ROI table?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2468]
Really, what is the point of making a widget that behaves like the one in PyMca to later on deprecate everything in it?

It would have been better to develop a totally different one.

Please define the policy you are going to adopt so that I can decide what path to follow.

**Comment by vasole** [comment]
https://github.com/vasole/pymca/issues/427

**Comment by payno** [comment]
the ROI objects have a 'sigChanged' signal, which should be listen by the ROITable in order to emit a 'sigROISignal'.

**Comment by vasole** [comment]
The table was emitting that signal when changing the selected ROI.

**Comment by vasole** [comment]
That means when selecting a different row in the table irrespectively of changing the associated ROI parameters.

**Comment by vasole** [comment]
That signal was properly emitted either when changing the ROI parameters or the selected row in versions 0.8.0 and 0.9.0
