### ISSUE TITLE
[Plot] Return objects instead lists for Plot getCurve|Image methods

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#247]
Methods to get curves and images returns a list with data and dicts.
The returned data is the 'internal copy' used by the plot.

Proposition: Return an object with accessors (e.g., getX(copy=True) for curve) that returns by default a copy of the data and a **getitem** for backward compatibility with list.
This would also document the available information.

**Comment by vasole** [comment]
Agreed in today's meeting we can go ahead.

**Comment by t20100** [comment]
Closed by PR #621.
