### ISSUE TITLE
[compareImages] add an option to skip resetZoom in setData, setImage1...

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#2471]
Having an option to skip resetzoom in setData, setImage1...

**Comment by t20100** [comment]
I don't know well the API of this widget, but what about adding a `resetZoom` method and not doing reset zoom as part of `set*` methods unless nothing was displayed before ?

**Comment by payno** [comment]
Yes, it might be less constraining.

**Comment by payno** [comment]
closed by #2475
