### ISSUE TITLE
[Plot] Use fabio to load/save image

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#248]
If available, use fabio from plot widgets (maskTool, saveAction) to load/save image data.

**Comment by vasole** [comment]
No problem. However, I would:

- Keep in mind that saving of image data in TIFF format should always be available independently of FabIO being installed or not.

- Profit from having FabIO to offer other formats than just TIFF.

**Comment by vasole** [comment]
Can this be closed?

**Comment by t20100** [comment]
No this has not been done

**Comment by t20100** [comment]
Now that fabio is a strong dependency, this really make sense.

**Comment by t20100** [comment]
We can replace the use of `silx.third_party.EdfFile` and `silx.third_party.TiffIO` with `fabio` throughout the project.
