### ISSUE TITLE
[fit widget] Improvements

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#249]
- [x] move configuration parameters into the customizable configuration dialog (`AutoFwhm` checkbox), because they are specific to the selected fit theory (duplicate with #241)
- [x] address warning generated by `leastsq` when running a gaussian estimation
- [x] make the fit curve use the same `xlabel` and `ylabel` as the original data
- [x] try to replace `QScriptOption` with a simpler configuration dialog widget

**Comment by PiRK** [comment]
[ ] handle background functions the same way as regular fit functions / theories (handle adding custom functions, custom configuration dialog…)

**Comment by vasole** [comment]
That last feature I would put it as a separate enhancement issue for a later milestone.
