### ISSUE TITLE
pyopencl._cl.MemoryError: clEnqueueNDRangeKernel failed: MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by caibojun** [silx-kit/silx#2510]
i use two different images to test LinearAlign, and it failed with pyopencl memory error. But how can lena image work well? so weird.

**Comment by vasole** [comment]
It could just be a memory problem.

What is the size of the image?
What device are you using and how much memory does it have?
You can use clinfo to grab that information.

**Comment by caibojun** [comment]
images size are 460×640 and 960×1260，big one is template image ，my device is Nvidia GTX1080Ti ，memory is 12GB.

**Comment by vallsv** [comment]
I think both images must have the same size. The could add a padding to the second one.

I think it would be better to fix it on our side, but as i think it is not one of our use case, no one will do it :-)

**Comment by vallsv** [comment]
If it's the problem you encounter, the error message could be undated, at least.

**Comment by caibojun** [comment]
I tried padding images into same size, but got
`Traceback (most recent call last):
  File "test.py", line 11, in <module>
    rerotate = sa.align(rotated)
  File "/home/caibojun/anaconda2/lib/python2.7/site-packages/silx/opencl/sift/alignment.py", line 228, in ali
    cpy = pyopencl.enqueue_copy(self.queue, self.cl_mem["input"].data, data)
  File "/home/caibojun/anaconda2/lib/python2.7/site-packages/pyopencl/__init__.py", line 1669, in enqueue_cop
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
pyopencl._cl.LogicError: clEnqueueWriteBuffer failed: INVALID_VALUE` 
Is that anathor problem?

**Comment by pierrepaleo** [comment]
@caibojun can you give us a sample code you are using, so that we try to reproduce the bug ?
