### ISSUE TITLE
Script to generate HDF5 samples. Irreproducible results.

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2516]
The code generates different output under Python 2 and Python 3. It should aim at generating utf-8 strings, not bytes.

Generated with Python 2:

![image](https://user-images.githubusercontent.com/5636251/54819782-40aa7480-4c9d-11e9-9688-f4d043916f88.png)

Generated with Python 3:

![image](https://user-images.githubusercontent.com/5636251/54819810-5881f880-4c9d-11e9-8228-68fa5014640f.png)

Example of appropriate output (no bytes anywhere):

![image](https://user-images.githubusercontent.com/5636251/54819922-b6aedb80-4c9d-11e9-8194-dfeb5099a10c.png)

**Comment by t20100** [comment]
I would say support of Python 2 is useless here, as it's a tool for internal use...
The list of str still need to be fixed thought.
