### ISSUE TITLE
Profile exception in silx view 0.10.1

### ISSUE THREAD

**Issue by CaptainNemoz** [silx-kit/silx#2526]
I start silx viewer in oar with the following command.

gpu2-1403:/data/id19/inhouse/nemoz/45.48_129keV_PIN4541-12_030_] silx view 45.48_129keV_PIN4541-12_030_slice_0039.edf
The I get error message when I attempt to drag an oblique profile.
The edf file has been copied in /tmp_14_days/nem

ERROR:silx.gui.qt._qt:<class 'TypeError'> linspace() got an unexpected keyword argument 'dtype'   File "/usr/lib/python3/dist-packages/silx/gui/plot/Profile.py", line 617, in _plotWindowSlot
    self.updateProfile()
  File "/usr/lib/python3/dist-packages/silx/gui/plot/Profile.py", line 659, in updateProfile
    method=self.getProfileMethod())
  File "/usr/lib/python3/dist-packages/silx/gui/plot/Profile.py", line 682, in _createProfile
    method=method)
  File "/usr/lib/python3/dist-packages/silx/gui/plot/Profile.py", line 357, in createProfile
    dtype=numpy.float32)

**Comment by vasole** [comment]
dtype was introduced in numpy 1.9.0 The default debian 8 supports 1.8 

It seems we forgot to ask TID to install the numpy backup available for Debian 8.

@CaptainNemoz Use rnice9.

**Comment by t20100** [comment]
This incompatibility with ``numpy`` 1.8.2 went through.
I asked to upgrade the installed version of ``numpy``.

**Comment by vallsv** [comment]
So we can close it?

**Comment by t20100** [comment]
We don't support debian8 any longer.
