### ISSUE TITLE
[silx view] Config file broken

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/silx#2545]
Hello.

Today, an issue came up using silx view.
I couldn't open nxs, edf or hdf5 file anymore.
We figured out that the /.config/silx file changed.
Moving it to another file to get silx recreate one worked fine. 
Here is the file : 

```
[colormap]
default=@ByteArray(\0\0\0\x10\0\x43\0o\0l\0o\0r\0m\0\x61\0p\0\0\0\x1\0\0\0\xe\0v\0i\0r\0i\0\x64\0i\0s\x1\x1\0\0\0\x6\0l\0o\0g)

[library]
plot-image.y-axis-orientation=upward
plot.backend=matplotlib

[mainlayout]
custom-nxdata-window-visible=false
spliter=0, 938
spliter2=973, 0

[mainwindow]
full-screen=false
pos=@Point(0 27)
size=@Size(960 1016)

[recent-files]
path1=XRD_18keV_259.nxs
path10=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/ConvertedImages/United_Cirpad_Img.hdf5
path2=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/NXS-2019-02-20/XRD_18keV_260.nxs
path3=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/NXS-2019-02-20/XRD_18keV_439.nxs
path4=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/ConvertedImages/Cirpad_Img.hdf5
path5=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/ConvertedImages/Grouped2_Cirpad_Img.hdf5
path6=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/NXS-2019-02-20/XRD_18keV_244.nxs
path7=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/NXS-2019-02-20/XRD_18keV_288.nxs
path8=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/NXS-2019-02-20/XRD_18keV_282.nxs
path9=/home/experiences/diffabs/mariea/CirPAD/DataForCirpad/ConvertedImages/Grouped_Cirpad_Img.hdf5
```

Cheers.

**Comment by vallsv** [comment]
Maybe cause you switch from PyQt4 to PyQt5?

The code was designed to be robust, but maybe not enough.

You also can try `silx view --fresh`. But I don't remember if in this case the preference file is ignored or erased.

**Comment by vallsv** [comment]
I tried here without any problems (PyQt5)

Are you talking about the recent paths? I mean if this files are not anymore reachable with this path it's normal. Or what do you mean by "couldn't open nxs, edf or hdf5 file anymore"? File > Open, there was exceptions?

**Comment by t20100** [comment]
I'm closing expecting it to be fixed, please reopen if it's not the case.
