### ISSUE TITLE
[GUI] Remove warning concerning the use of PySide2

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2565]
Can we get rid of the warning? Today I do not see a reason to "mistreat" PySide2 compared to PySide. Furthermore, our module attempts to load PySide2 prior to PySide.

**Comment by t20100** [comment]
Tests didn't pass with the previous version of `PySide2`.
Also, `PySide2` is way less manually tested by us than `PyQt5`, but that's not a reason to "mistreat" it... we just need to use it more during development.
