### ISSUE TITLE
[plot] Rework ROI signal

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2587]
PR #2584 adds a `setVisible` to ROI items with no signal associated.
Plot ROI items signals needs to be reworked at least to add a signal for the visibility (and eventually at a larger scale to provide the different kind of updates).

Some ideas for the visibility (initially proposed in PR #2584): Either a `sigItemChanged` as for other plot items (maybe the best), or a `sigVisibleChanged`, or eventually through the already exisiting `sigRegionChanged`...

**Comment by vallsv** [comment]
BTW inheriting from plot item could make sense. Which could be taken into account to decide what to do with the signal.

**Comment by t20100** [comment]
Yes, that's what I had in mind.

**Comment by PiRK** [comment]
`setEditable` also has no associated signal, btw. I noticed that a programmatic call of this method does not update the checkbox in `RegionOfInterestTableWidget`

I'm reporting this just for info. I personally don't need this feature.

**Comment by t20100** [comment]
Thaks for the report, I've opened a separate issue for it : #2595
