### ISSUE TITLE
[convert] write_to_h5 not keeping the order of groups

### ISSUE THREAD

**Issue by maurov** [silx-kit/silx#2589]
I think there is a **bug** in `write_to_h5` because the order of groups is not kept, even when `track_order` is passed to h5py.

```python
import tempfile
import h5py
from silx.io.commonh5 import Group
from silx.io.convert import write_to_h5
#: create a group and write to file
g = Group("")
g['z'] = 10
g['a'] = 5
g['b'] = 6
g['c'] = -1
ft = tempfile.mktemp(suffix='.hdf5')
write_to_h5(g, ft, create_dataset_args=dict(track_order=True))
#: read back the file
h5 = h5py.File(ft, mode='r')
#: check the order of groups in the initial object and the read-back one
g.keys()
# Out: odict_keys(['z', 'a', 'b', 'c'])
h5.keys()
# Out: <KeysViewHDF5 ['a', 'b', 'c', 'z']>
```

I have tried a couple of things in this branch : https://github.com/maurov/silx/tree/hdf5writer_track_order

Unfortunately, it still does not work...

Any help is welcome.

**Comment by maurov** [comment]
I forgot to add that `track_order` should be added also here:

https://github.com/silx-kit/silx/blob/e55044960d203eacf81033802cef060814339714/silx/io/commonh5.py#L909

**Comment by vallsv** [comment]
Hi. I will try to check your problem.

But i think it would be better for the writer to check that `g` was using `track_order` (which is then the case by default for our `commons.Group`), instead of forcing a configuration for the full tree. But a public h5py API have to exists to check the track order state.

**Comment by vallsv** [comment]
Hi again. Your problem is tricky cause i guess the root group pre-exists. Maybe it is also possible to create a file with track_order option.

Then if you use:
```
g['foo/z'] = 10
g['foo/a'] = 5
g['foo/b'] = 6
g['foo/c'] = -1
```

and
```
h5["foo"].keys()
```
your will see that you have already fixed the problem.

I guess your main use case is not relative to tracking order on the root?

**Comment by vallsv** [comment]
I check h5py. A `File` is a `Group`.
- You could use `track_order` at the file creating, it should track the order for the root.
- A note about `track_order` in `create_dataset_args`. As it is used for the dataset factory, this is used to track the creation of the attributes. That's maybe not what you want.

**Comment by vallsv** [comment]
As reminder
```
def get_track_order(group):
    v = group.id.get_create_plist().get_link_creation_order()
    is_tracked = (v & h5p.CRT_ORDER_TRACKED) == h5p.CRT_ORDER_TRACKED
    is_indexed = (v & h5p.CRT_ORDER_INDEXED) == h5p.CRT_ORDER_INDEXED
    if is_tracked and is_indexed:
        return True
    elif not is_tracked and not is_indexed:
        return False
    else:
        # In between, unsupported by h5py hi-level API
        return None

filename = tempfile.mktemp(suffix='.h5')
with h5py.File(filename, mode='w') as h5:
    a = h5.create_group("a", track_order=True)
    track_order = get_track_order(a)
    print(track_order)
    b = h5.create_group("b", track_order=False)
    track_order = get_track_order(b)
    print(track_order)
```

**Comment by maurov** [comment]
@vallsv thanks for the comments. Well, I would like to keep `track_order=True` also in the root group. Unfortunately, even with `h5py`, I do not understand why when reading back the file, the order of the root group is lost:

```python
import tempfile
import h5py
ft = tempfile.mktemp(suffix='.hdf5')
h5 = h5py.File(ft, mode='w', track_order=True)
h5.create_group('z')
h5.create_group('a')
h5.keys()
# Out: <KeysViewHDF5 ['z', 'a']>
h5.close()
h5 = h5py.File(ft, mode='r', track_order=True)
h5.keys()
# Out: <KeysViewHDF5 ['a', 'z']>
```

By the way, the order is correctly kept in subgroups created with `track_order=True`. Maybe I am doing something fundamentally wrong with the root group...

PS: what is  `h5p` in  `get_track_order` definition?

**Comment by vasole** [comment]
@maurov 

I guess your comment is worth opening an issue at the h5py repository.

**Comment by vallsv** [comment]
Yes it looks like a bug on there side. BTW, you can remove the `track_order` on the read part.

Sorry, `h5p` come from `h5py`
```
from h5py import  h5p
```

**Comment by maurov** [comment]
No feedback from `h5py`, just closing the issue as this is not related to `silx` anymore.
