### ISSUE TITLE
ImportError: cannot import name sift

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#2605]
Hello, I put this here, in order to discuss with you.
sift can not be distributed by Debian, due to the pattent, So I would like a way to fix this properly with you.

maybe the best is to use a ski if we can not import the sift module.
It is neverthless strange because, I can not remmerber this kind of faillure with the previous silx.

```
autopkgtest [08:18:12]: test command1: set -efu ; for py in $(pyversions -r 2>/dev/null) ; do cd "$AUTOPKGTEST_TMP" ; echo "Testing with $py:" ; xvfb-run -a --server-args="-screen 0 1024x768x24" $py -c "import silx.test; silx.test.run_tests()" 2>&1 ; done
autopkgtest [08:18:12]: test command1: [-----------------------
Testing with python2.7:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/silx/test/__init__.py", line 96, in run_tests
    if not runner.run(suite()).wasSuccessful():
  File "/usr/lib/python2.7/dist-packages/silx/test/__init__.py", line 78, in suite
    test_suite.addTest(test_gui.suite())
  File "/usr/lib/python2.7/dist-packages/silx/gui/test/__init__.py", line 70, in suite
    from ..plot import test as test_plot
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/test/__init__.py", line 55, in <module>
    from . import testCompareImages
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/test/testCompareImages.py", line 36, in <module>
    from silx.gui.plot.CompareImages import CompareImages
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/CompareImages.py", line 51, in <module>
    from silx.opencl import sift
ImportError: cannot import name sift
```

**Comment by t20100** [comment]
This was changed to avoid loading sift if we know OpenCL is not available, but we can update it to handle the case it is removed.

**Comment by picca** [comment]
Yes I found the cuprite in the gui/plot/CompareImage.py

+from silx.opencl import ocl
+if ocl is not None:
+    from silx.opencl import sift
+else:  # No OpenCL device or no pyopencl
+    sift = None

it should handle also the missing sift even if opencl is available :)

**Comment by picca** [comment]
for info there is also errors during the autopkgtests

https://salsa.debian.org/science-team/silx/-/jobs/183459

**Comment by picca** [comment]
new version whcih seems to pass, but there is errors and is is really verbose.

https://salsa.debian.org/science-team/silx/-/jobs/183495

**Comment by t20100** [comment]
BTW, we should prepare a 0.11 release in the coming weeks.
