### ISSUE TITLE
[HDF5 Widget] Example not working (at least under windows)

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#262]
- It does not recognize valid SPEC files. It says file cannot be read as  HDF5, fabio or SpecFile.
- File drop does not work either

**Comment by vallsv** [comment]
It is fixed in the last master

**Comment by vallsv** [comment]
DnD is still not working on windows

**Comment by vallsv** [comment]
DnD is fixed by https://github.com/silx-kit/silx/pull/279

**Comment by vallsv** [comment]
But Spec files are not supported. Some changes on https://github.com/silx-kit/silx/pull/251 are expected.
I can split this pull request to merge the part concerning Spec.

**Comment by vasole** [comment]
You can split the pull request, however, the raised exception should not say "file cannot be read as HDF5, fabio or SpecFile" if you only support HDF5 at this point It should say "file cannot be read as HDF5".

**Comment by vallsv** [comment]
Sounds fine

**Comment by vasole** [comment]
Closed by #251
