### ISSUE TITLE
issue OSX 10.10 + Python3.5 + Qt5

### ISSUE THREAD

**Issue by cicciodevoto** [silx-kit/silx#266]
locks on :
testDialog (silx.gui.plot.test.testLegendSelector.TestRenameCurveDialog)
Create dialog, change name and press OK ...

**Comment by payno** [comment]
Have been patched by @t20100 need validation from @cicciodevoto
[patch_devoto.txt](https://github.com/silx-kit/silx/files/521241/patch_devoto.txt)
