### ISSUE TITLE
PlotWidget doesn't use available screen space

### ISSUE THREAD

**Issue by UUSim** [silx-kit/silx#2681]
I'm using the `PlotWidget`, integrated into one of our applications.

However, I find that the available screen space is not efficiently used. There is too much empty space around the data and axes, as displayed below:
![silx-widget-space](https://user-images.githubusercontent.com/9439166/61305072-76461100-a7ea-11e9-8fb0-f3d0c246a117.png)

The blue is the widget background color, as set via `PlotWidget.setBackgroundColor`.

Is there any way to improve this?

**Comment by t20100** [comment]
There is currently no way to set it from the API, but that could be added.

Here is how to make it by going through private attributes:

With the matplotlib backend:
```
from silx import sx
w = sx.plot()
# Margins as ratios of figure, order: left, bottom, width, height
w._backend.ax.set_position((.1, .1, .9, .9))
w._setDirtyPlot()
```

With the OpenGL backend:
```
from silx import sx
w = sx.Plot1D(backend='gl')
w.show()
# Margins in pixels, order: left, right, top, bottom
w._backend._plotFrame._margins = w._backend._plotFrame._Margins(30, 5, 5, 30)
w._backend._plotFrame._dirty()
w._setDirtyPlot()
```

There is are differences between the 2 backends: 
- Using ratio vs pixels
- Order of margins parameters

But that can be worked out.

**Comment by UUSim** [comment]
That was quick. I'll see if I can make something nice out of this (the `PlotWidget` function would have to accept 1 set of arguments and convert them based on the backend).

**Comment by t20100** [comment]
Great!

The way the OpenGl backend works can also be updated to match the way matplotlib works (that should not be to much modifications).

I don't know what's best between setting pixels and ratios.
I personally prefer setting margins in pixels (so they remain fixed upon resize), but using ratios is certainly simpler (straight forward with matplotlib and the OpenGL backend can be adapted).
Aiming at margins in pixels with matplotlib means to call `set_position` upon resize of the plot widget.

Anyway, one mode can be implemented first, and the second one added later if needed with an extra parameter to the method.
