### ISSUE TITLE
h5todict always returns arrays even for scalar

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2689]
For single values, `h5todict` returns `numpy.ndarray`.

To reproduce:
```
from silx.io.dictdump import dicttoh5, h5todict
dicttoh5({'test': 1.}, 'test.h5')

In [19]: h5todict('test2.h5')                                                   
Out[19]: {'test': array(1.)}
```

The reason is the use of `[...]` rather than `[()]` here: https://github.com/silx-kit/silx/blob/master/silx/io/dictdump.py#L315

```
In [16]: f2 = h5py.File('test2.h5', 'r')    
In [23]: f2['test'][()]                                                         
Out[23]: 1.0
In [24]: f2['test'][...]                                                        
Out[24]: array(1.)
```

To me, it is best to returns scalar in this case... yet this will break the behaviour of `h5todict`.
Adding an `asarrays=True` argument to `h5todict` would allow to keep the legacy behavior and enable the "correct" way of handling it.

Do we want to break the behaviour?

**Comment by maurov** [comment]
+1 for adding an extra argument to `h5todict` in order to control `dataset[()]` or `dataset[...]` output.

**Comment by t20100** [comment]
The difference of behavior is in `Dataset.__getitem__`:
https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L539-L549
and here:
https://github.com/h5py/h5py/blob/master/h5py/_hl/selections2.py#L83-L86

What actually changes is the returned statement (https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L547-L549):
- `dataset[...] => return arr`
- `dataset[()] => return arr[()]`

h5py doc says:
> To retrieve the contents of a scalar dataset, you can use the same syntax as in NumPy: `result = dset[()]`. In other words, index into the dataset using an empty tuple.

http://docs.h5py.org/en/stable/high/dataset.html#reading-writing-data

**Comment by mretegan** [comment]
@t20100 
I've noticed that if the `path` argument of `h5pytodict()` is no set the conversion to arrays is still done. Is this the expected behavior?
