### ISSUE TITLE
[Hdf5Widget] Support weakref

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#269]

**Comment by t20100** [comment]
From looking at the code with @vallsv, as it is now one can get from the object provided in signals either the h5py object or the file name and path in the file.
So, one can perfectly use the tree without having to access provided h5py objects.
I would be convenient to add an API to get the corresponding Url object.

**Comment by t20100** [comment]
PR #2355 adds an API to get the corresponding URL, making it easy to use the hdf5 tree without keeping reference on the HDF5 objects, so functionality is there.
 
Reopen if disagree.
