### ISSUE TITLE
[plot] Plot axis limits change when the widget is hidden

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2690]
I'm seeing a strange behavior when I try to alternatively show and hide 2 plot widgets, with the gl backend.  With the following example, if I toggled the visibility via the action, the images keep getting smaller.

```
from silx.gui import qt
from silx.gui.plot import PlotWidget
import numpy

backend = "gl"
img_rgb1 = (numpy.random.rand(1000, 700, 3) * 255).astype(numpy.uint8)
img_rgb2 = (numpy.random.rand(1000, 700, 3) * 255).astype(numpy.uint8)


app = qt.QApplication([])
win = qt.QMainWindow()
toolbar = qt.QToolBar()
win.addToolBar(toolbar)

widg = qt.QWidget()
layout = qt.QHBoxLayout()
widg.setLayout(layout)
win.setCentralWidget(widg)

plot1 = PlotWidget(backend=backend)
plot1.setKeepDataAspectRatio(True)
plot1.addImage(img_rgb1)
plot1.setVisible(False)
layout.addWidget(plot1)

plot2 = PlotWidget(backend=backend)
plot2.setKeepDataAspectRatio(True)
plot2.addImage(img_rgb2)
layout.addWidget(plot2)


def togglePlots(checked):
    print(checked)
    plot1.setVisible(checked)
    plot2.setVisible(not checked)


act = qt.QAction()
act.setCheckable(True)
act.triggered.connect(togglePlots)
toolbar.addAction(act)

win.show()

app.exec_()
```

If I remove line 23 (plot1.setVisible(False)), then I don't see the behavior. The zoom is not affected by hiding and showing.

If I replace both img shapes by (100, 700, 3), I don't see the resizing problem, but the plot initially hidden is not shown with the same zoom level as the plot initially shown.

It seems that the images affected by resizing are the ones that have more rows than columns.

With the mpl backend, I don't see the issue. But I notice a difference in behavior: with mpl the zoom is initially  adjusted to show the entire image, but not with gl.

**Comment by PiRK** [comment]
Using a QStackedWidget and calling `addImage` with `resetzoom=True` works fine. I'm using it now, as a workaround.

**Comment by PiRK** [comment]
I think my mistake is to show the first widget before hiding the second. That most likely causes unnecessary resizing.

**Comment by t20100** [comment]
It is not possible to round trip the plot limits when resizing while keeping aspect ratio.
It is best if you can avoid resizing.

**Comment by t20100** [comment]
Closing: It is due to resizing (through the use of `QHBoxLayout` and `setVisible`) with keep aspect ratio.
Using a `QStackedLayout` would make it work.
