### ISSUE TITLE
dicttoh5 convert all strings to fixed length ascii

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2693]
`dicttoh5` converts all strings to fixed-length ASCII by converting them to `numpy.string_`.
The following is explained for Python3 only.

So it does not support unicode `str`.

And  `dicttoh5`/`h5todict` does not round-trip as everything (`bytes`, `str`, `numpy.string_`) is saved as fixed-length ASCII and read back as `bytes`.

To me, we should support unicode, and `str` should round-trip and so be saved as variable-length UTF-8 an read-back as `str`.

We could provide this with an extra argument, e.g., `encoding='ascii'` which by default keeps the current behavior, and `encoding='utf-8'` to store `str` as vlen utf-8.
Alternative naming: `str_dtype=numpy.string_ | h5py.special_dtype(vlen=str)`.
Better alternative naming welcome...

**Comment by t20100** [comment]
Ideas for "text" related datasets:

- `h5todict` should return what `h5py` is returning (i.e., `numpy.string_`, `bytes` or `str`) by default, but I would add an option to convert fixed ASCII, vlen ASCII and vlen UTF8 to `str` provided that raw data should be stored in a different way (http://docs.h5py.org/en/stable/strings.html#how-to-store-raw-binary-data).

- `dicttoh5` should by default provide the behavior of h5py (i.e., supporting  `numpy.string_`, `bytes` and `str`) instead of converting `str` to `numpy.string_` as it is the case now. We can eventually think of a "maximum compatibility" mode where `str` is stored as fixed length ASCII whenever possible and else as vlen UTF8.

With this `numpy.string_`, `bytes` and `str` will round-trip, and the `h5todict` options allows to handle all texts as `str`.

**Comment by woutdenolf** [comment]
This was dealt with in #3240. Regardless of the h5py version, dicttoh5/h5todict round-trips for `str` and `bytes`. This goes for datasets and attributes. In addition `dicttoh5` saves variable length `str` or `bytes`.

@t20100 I think this can be closed then?

**Comment by woutdenolf** [comment]
To illustrate the current behavior:

```python
from silx.io import dictdump
from pprint import pprint

adict = {"str":"str",
         "bytes":b"bytes",
         "str_arr":["str"]*2,
         "bytes_arr":[b"bytes"]*2,
         ("", "str"):"str",
         ("", "bytes"):b"bytes",
         ("", "str_arr"):["str"]*2,
         ("", "bytes_arr"):[b"bytes"]*2}

dictdump.dicttoh5(adict, h5file="test.h5")
pprint(dictdump.h5todict("test.h5", include_attributes=True, asarray=False))
```

For any h5py version that supports variable length dtype's (>=2.0 I think) this gives:

```python
{'bytes': b'bytes',
 'bytes_arr': array([b'bytes', b'bytes'], dtype=object),
 'str': 'str',
 'str_arr': array(['str', 'str'], dtype=object),
 ('', 'bytes'): b'bytes',
 ('', 'bytes_arr'): array([b'bytes', b'bytes'], dtype=object),
 ('', 'str'): 'str',
 ('', 'str_arr'): array(['str', 'str'], dtype=object)}
```
