### ISSUE TITLE
[Plot] addScatter missing xlabel and ylabel keywords

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2711]
They present in addCurve and addImage. Should them be added to addScatter?

**Comment by vallsv** [comment]
I think it was there for compatibility.
But now we prefer to set it to the axis themselves.

**Comment by t20100** [comment]
I'm not in favor of adding `xlabel`, `ylabel` to `addScatter`.
One should easily achieve the same behavior by listening to active scatter changes and update the plot labels.

**Comment by t20100** [comment]
This would avoid adding some automated behaviors that can be miss-leading.
Also, while for curves the user knows which one is active, for scatter plots (and images) there is no visual change.
