### ISSUE TITLE
[silx view] show NXentry title

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#2713]
Could Silx show the NXentry title in the viewer? NXentry names are typically chosen for easy access by software (e.g. just a number) but are not very informative for humans.
![2019-08-09_16-18-04](https://user-images.githubusercontent.com/7264703/62785697-766fbe80-bac1-11e9-8357-fc4c8d993c86.png)

**Comment by vasole** [comment]
It is enough to replace NXentry in the type column by the title dataset if present.

**Comment by vasole** [comment]
Done. Let's see if it gets approved. For the ESRF perhaps is better to append it to the entry name. However for the other facilities using longer entry names it can be a problem.
