### ISSUE TITLE
[scatter view] Can set default colormap but not default symbol

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2718]
ScatterView provides a setColormap method but not a setSymbol method.

The method setData supposed to be called does not allow to pass the symbol either.

The only way I find to overcome this limitation is to inherit ScatterView and to overload setData in order to replace it by a method retrieving the parameters of the scatter item in order to send the item back using addScatter.

**Comment by vallsv** [comment]
Did you try `setVisualization` from the scatter item itself?

```
view.getScatterItem().setVisualization()
```

**Comment by vasole** [comment]
That is equivalent to what I mentioned but without inheriting.

**Comment by vasole** [comment]
@t20100 

I can manage with the solution proposed by vallsv.
