### ISSUE TITLE
qt: Event names

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2720]
In order to help debugging Qt i sometime display event types.

But there is no API from Qt to display the name of the event types.

Would you like to integrate a mapping of the event types? `int->str`. Maybe inside `silx.gui.qt.utils`

It is basically a python version of the table you can find here: https://doc.qt.io/archives/qt-4.8/qevent.html

The implementation is already done on my side.

**Comment by t20100** [comment]
+1 
Nice to have.

**Comment by t20100** [comment]
closed by #2725
