### ISSUE TITLE
Precision lost when casting to float16

### ISSUE THREAD

**Issue by juliagarriga** [silx-kit/silx#2736]
When calling the function ``min_numerical_convertible_type`` from ``silx.utils.number`` there is a use case where the precision gets lost and a float32 is wrongly cast to float16.
```
from silx.utils.number import min_numerical_convertible_type
c = "-23.172"
type = min_numerical_convertible_type(c)
print(type(c))
>>> -23.17
```

**Comment by payno** [comment]
PR #2735 try to solve this.
