### ISSUE TITLE
[colormap] Add 3*std autoscale mode

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2739]
The idea is to design it simple (without over-engineering). Then just another specific autoscale.

Basically an function `setAutoScaleMode` enum with `MIN_MAX` or `PLUS_MINUS_3_TIME_STANDARD_DEVIATION`.

If a real need is expressed we can grow the API with objects to allow to custom the values  (3 or something else), or the computation.

**Comment by t20100** [comment]
+1 to keep it simple (and extensible).
