### ISSUE TITLE
[plot] Allow to custom line style of vline/hline

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2741]
Vertical lines and horizontal lines are special markers which displays lines.

As it uses markers style, the line style is not part of it.

**Comment by t20100** [comment]
Not sure I get what this is about?
Line marker style should be available through #2112 and/or #2306

**Comment by vallsv** [comment]
It's not part of the `PlotWidget` API.

I am fine with it anyway. I don't use anymore this API for serious business.

**Comment by t20100** [comment]
OK, then let's keep the `PlotWidget` API as it is, one can set the linestyle through the marker item API.
