### ISSUE TITLE
[silx view] NXdata image/scatter consistancy

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2748]
Feed back from @woutdenolf 

Using the same axes order in NXdata (example `axes = ['x', 'y']`) for image or for xy-value scatter will display inverted axes (vertical became horizontal, horizontal became vertical).

Is there any reason? Or is it save to switch the scatter one? In order to have consistency?

**Comment by vasole** [comment]
The scatter one is correct. It should remain unchanged.

What is wrong is to call x and y to the rows and columns of an image.

**Comment by vallsv** [comment]
It's about display.

The first axis from image will be vertical while the first axis from the scatter will be horizontal (or the reverse, i don't check).

**Comment by vallsv** [comment]
Sorry, i called them "x" and "y", but i could call it "ä", and "b".

**Comment by vasole** [comment]
That is the convention for visualizing images. I have not invented that.

OpenGL had the default origin at the lower left corner as it is usual for data. However, people dealing with images decided to take the origin on the top while people dealing with data kept using the conventional way.

That ends up with images being different from anything else and having to provide the vertical coordinates (if any) first.

https://dsp.stackexchange.com/questions/35925/why-do-we-use-the-top-left-corner-as-the-origin-in-image-processing

**Comment by t20100** [comment]
For the y axis orientation, that's convention, check `imshow` and `plot` from matplotib, there is the same inconsistency between image and the rest....

As for order of axes, image is a 2D array with (row, column) order convention while scatter is using curve-like convention (i.e., x, y order...).

I'm used to it, moving from one to the other between bumpy array, Qt, OpenGL... but I understand that's disturbing, though I have no solution.

**Comment by vallsv** [comment]
Ok. Let's close it then.

**Comment by woutdenolf** [comment]
So what do I need to do when writing data with axes = ['axfast', 'axslow'] and data shape (nfast, nslow) or (nfast*nslow,)? Right now I have the same axes order, whether the data is flat (scatter plot) or not (image).

**Comment by vasole** [comment]
Since you are expected to have the interpretation attribute, what you have to account for is that when preparing NXdata for an image, the axes coordinates correspond to the rows and the columns in that order. For everything else (= not images) you just provide the things as generated. There is no fast or slow axis for generic data. They are (npoints, whatever). Take a look at the SPEC documentation to decide https://certif.com/spec_help/mesh.html which one you put first.

If you are taking shortcuts for regular data, then you are in a different case and then you have to provide the data for each dimension in the dimension order.

signal = data[nrows, ncolumns, whatever]
axes = dim0[nrows], dim1[ncolumns]

or, more generic:

signal = data[shape[0], shape[1], shape[2], shape[...]]
axes = dim0[shape[0]], dim1[shape[1], dim2[shape[2],...

**Comment by vasole** [comment]
I would say the first motor is expected to be the X and the second the Y.

**Comment by vasole** [comment]
@woutdenolf 

The correct answer is to compare an hklmesh from SPEC and a mesh scan from SPEC. The hklmesh has h as motor1 and k as motor2 and spects h at the X axis.

**Comment by woutdenolf** [comment]
Anyway, in all the libraries where I added Nexus writing (Bliss, pymca, spectrocrunch) I do:

NXdata (signals have no interpretation):
signal = data[npoints, ...]
axes = fast[npoints], slow[npoints]

or

NXdata (signals have interpretation=image):
signal = data[nrows, ncolumns, ...]
axes = fast[nrows], slow[ncolumns]

where fast/slow == inner/outer loop in case I'm saving mesh-like data (e.g. "mesh fast 0 10 10 slow 0 20 20 100"). If this is a problem, let me know. If you would save the same data both ways (flat or as image) the resulting plots in silx are each others transpose. Just saying.

**Comment by vasole** [comment]
I think what you wrote for the image interpretation is not correct and you meant

axes = slow[nrows], fast[ncolumns]

**Comment by woutdenolf** [comment]
I wrote it correctly so that means I;m doing it wrong.

**Comment by vasole** [comment]
If you want to check if you are doing things correctly is very easy. Take a non-square matrix A[nrows, ncolumns] with the interpretation attribute set to image.

You should obtain the same visualization when you create an NXdata group just specifying the signal and when you create an NXdata group with the signal set to A and the axes set to dim0 and dim1 (in that order) with:

dim0 = numpy.arange(nrows)
dim1 = numpy.arange(ncolumns)
