### ISSUE TITLE
Loading json file and dumping hdf5

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#2768]
The snippet below returns `TypeError: list indices must be integers or slices, not collections.OrderedDict`:

```code: python
from silx.io import dictdump

data = dictdump.load("model.json")
dictdump.dump(data, "model.h5")
```

**Comment by payno** [comment]
This at least work, could you send us your model.json please ?

``` python3
l = OrderedDict(dict({'a': 1, 'b':2}))                                                                                                                                                                    
dictdump.dump(l, "model.h5")
```

**Comment by mretegan** [comment]
Sorry for being so vague before. Actually, if you have the same dictionary as a JSON file, dumping the hdf5 will not work. This is because of the structured of the object return by the two approaches. Reading from file returns `[OrderedDict([('a', 1)]), OrderedDict([('b', 2)])]`, while simply using OrderedDict returns `OrderedDict([('a', 1), ('b', 2)])`.

**Comment by mretegan** [comment]
Actually the JSON file is different :expressionless:

```
[
    {
        "a": 1
    },
    {
        "b": 2
    }
]
```

**Comment by payno** [comment]
The `dicttoh5`, (call from dictdump.dump) should:

* raise an error if the data is not a dict (which is the case in the example)
* Accept also list and cast elements as OrderedDict ? ... because it can read it from json.

**Comment by mretegan** [comment]
BTW, this also fails for dictionaries that have lists of dictionaries as values.

```
model = {"a": [{"a1": 1, "a2": 2}], "b": 2}
dictdump.dump(model, "model.h5")
```

**Comment by t20100** [comment]
Following discussions: `dicttoh5` should raise a meaningful error when provided with a `list` of `dict` at some point in the hierarchy.

**Comment by t20100** [comment]
For me, regarding conversion from json to hdf5 with `silx.io.dictdump` `load` and `dump` functions, if a conversion of `list` of `dict` needs to be done, it should be done early (i.e., when loading json rather than when writing hdf5).

**Comment by woutdenolf** [comment]
Not every dictionary can be represented by an HDF5 tree. Consequently not all JSON files can be converted to HDF5. Forcing some exceptions (like lists of dictionaries) is not very helpful imo. Everything that can't be round-tripped should not be supported.

**Comment by vasole** [comment]
>Not every dictionary can be represented by an HDF5 tree

Even with some SILX_xxxxx attribute stating what the original stuff was?

**Comment by woutdenolf** [comment]
> Even with some SILX_xxxxx attribute stating what the original stuff was?

And then pickle everything and/or use opaque types?

**Comment by vasole** [comment]
My take on this is that mapping of dictionaries is easy but mapping of lists it is not. If one would be allowed to reinterpret the list as a dictionary it could be easily dumped and when reading it back the containing group would have to be reinterpreted as a list.

I see no need to do anything obscure or more special than:

SILX_original_container = "list" or "tuple"
SILX_original_container_items = "item0_name", "item1_name", .... 

If those attributes are not present in a group, the group is interpreted as now. No incompatibility introduced.

If there is no wish/interest to implement this I understand it but I do not find it difficult.

**Comment by vasole** [comment]
The above was for a generic thing.

If the goal is to dump a json file, then even Nexus provides an answer:

https://manual.nexusformat.org/classes/base_classes/NXnote.html#nxnote

One just needs to dump the json string one can do it as an NXnote with the string as (binary) **data** and the **type** set to "application/json" that seems to be the official MIME type.

**Comment by woutdenolf** [comment]
> If one would be allowed to reinterpret the list as a dictionary

This means `dicttoh5` needs to check every element of every array or sequence to check whether it can be saved as an array or whether it has to be reinterpret as a dictionary.

@mretegan What is the use case? Maybe saving the json as a string is good enough for you (i.e. NXnote as Armando said)? You will not be able to access part of the json structure through the h5py API but this is also the case when reinterpreting sequences as dictionaries (because it destroys the original json structure: a list is no longer a list).

**Comment by vasole** [comment]
>This means dicttoh5 needs to check every element of every array or sequence to check whether it can be saved as an array or >whether it has to be reinterpret as a dictionary.

Only when something is not originally a dictionary, not on every sequence. We are not checking now every element of an array now either and I doubt we support compound arrays.

**Comment by mretegan** [comment]
@woutdenolf It has been a while since I needed this, and honestly I don't remember the precise use case. From my side, I don't see any need to have this implemented in any form. As you said, there are items in a JSON file that cannot be represented in an HDF5 tree and vice-versa. 

I leave it up to you and @vasole to judge if this is needed. If not, I can close the issue.

**Comment by woutdenolf** [comment]
I would close the issue

**Comment by vasole** [comment]
I am currently using the NXnote approach because needing to distinguish lists and dictionaries.

Besides inefficient (and dangerous) conversion from binary to ASCII and back, that prevents any access to the items by standard programs. I have survived for quite long without dumping the individual keys of the dictionary, but I do see an interest on being able to dump things to HDF5 instead of json or ini files.

**Comment by vasole** [comment]
The original request is already handled by standard Nexus NXnote.
