### ISSUE TITLE
[plot] Hi-DPI support for OpenGL backend

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2773]
There is a slightly difference between symbol size of OpenGL and Matplotlib backend.

As result, if i tune the scatter symbol size for one, i could have a too big or too small marker for the other backend. It would be good to reduce the difference here.

Here is the result with a size of 2.0.

OpenGL:
![Screenshot (98)](https://user-images.githubusercontent.com/7579321/66190571-9f10d080-e68c-11e9-984a-42bcf54f5265.png)

Matplotlib:
![Screenshot (99)](https://user-images.githubusercontent.com/7579321/66190572-9f10d080-e68c-11e9-842f-cbad9f650139.png)

**Comment by t20100** [comment]
related to #792
