### ISSUE TITLE
[widget] Improve LegendIcon widget

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2774]
Here is few proposal to improve the `LegendIcon` widget.

- Support symbol size
- Support colormap lut
- Move it to an own module (``silx.gui.widgets.something`)

Right now the widget provides display for lines and symbols:
![Screenshot (100)](https://user-images.githubusercontent.com/7579321/66191021-9967ba80-e68d-11e9-8bf6-e0b73510e49e.png)

Here is my current result, created by inheritance:
![Screenshot (101)](https://user-images.githubusercontent.com/7579321/66191040-a1bff580-e68d-11e9-88e5-a06b171a08b3.png)

My aim is to be able to display the style of images and scatters. And i agree the current result for scatter symbol with colormap is not very nice.

If you like i can create a PR for that.

**Comment by t20100** [comment]
OK, it should be in `silx.gui.widgets` only if it does not depend on  `silx.gui.plot`, but I think it is the case.

We need to find something for the scatter plot with colormap.

**Comment by vallsv** [comment]
I though about using textured circle, but the result will not be nice, and it will not be readable for other shapes like arrows.

**Comment by t20100** [comment]
Maybe separate both: the marker and then the colormap.

**Comment by vallsv** [comment]
I merged both. Let's talk on the merge request.
