### ISSUE TITLE
Installing silx in editable mode

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#2777]
pip allows installing packages in editable mode ([pip-install-editable](https://pip-python3.readthedocs.io/en/latest/reference/pip_install.html#install-editable)). This way it is possible to work directly on the source code without having to use `python bootstrap.py` (at least for the Python part of the code that does not require recompilation). 

However, the code in the `__init__.py` raises the following exception:`RuntimeError: Do NOT use silx from its sources: build it and use the built version`. Would it be possible to relax this?

**Comment by mretegan** [comment]
I just noticed that `bootstrap.py` takes a script name as a positional argument, so I can easily run my tests.

**Comment by mretegan** [comment]
Update CONTRIBUTING to include some of this information #2779.

**Comment by vallsv** [comment]
It's because silx uses binary compiled modules. Then the `-e` can't work in this case. Cause there is no way to compile an up to date version of the modules.
