### ISSUE TITLE
[plot] Undocking OpenGL plot with image switch it to black

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2788]
For flint i uses a lot of docks.

I notice that if i play with docks, while an image in displayed in a plot with the OpenGL backend, at one point it became black.

I am testing it through X, using mobaxterm. Maybe testing it in real conditions (debian local machine) will not react the same.

**Comment by vallsv** [comment]
I can provide a test example if you like.

**Comment by vallsv** [comment]
Here we have
```
from silx.gui.plot.ImageView import ImageView
from silx.gui import qt
import numpy


def main():
    data = numpy.arange(1024 * 1024.).reshape(1024, 1024)
    app = qt.QApplication([])

    mainWindow = qt.QMainWindow()
    mainWindow.setAttribute(qt.Qt.WA_DeleteOnClose)

    dock = qt.QDockWidget(mainWindow)

    plot = ImageView(parent=dock, backend="opengl")
    plot.setImage(data)
    dock.setWidget(plot)

    mainWindow.show()
    return app.exec_()


if __name__ == "__main__":
    import sys

    result = main()
    sys.exit(result)
```

**Comment by vallsv** [comment]
Tested with @t20100.

- On a local Debian machine, the result is the same, the image is black but a zoom in/out redraw the plot. Then it looks to be a simple repaint to do
- Unfortunately, I tested that on my remote env. It looks to be fine when the plot is on the main window, but when the plot is floating, the image is always black

**Comment by t20100** [comment]
Calling `qt.QCoreApplication.setAttribute(qt.Qt.AA_ShareOpenGLContexts)` **BEFORE** creating the Qt application looks to fix the black widgets from what I can test.

**Comment by t20100** [comment]
Setting `qt.Qt.AA_ShareOpenGLContexts` is the best way as it will reuses the same resource when the dock state change, butit wouldbe good to make it work even without it..
This means dealing with the OpenGL context being changed during the life cycle of the `PlotWidget`.

**Comment by t20100** [comment]
I'm moving this issue to next milestone, there is a workaround with  `qt.QCoreApplication.setAttribute(qt.Qt.AA_ShareOpenGLContexts)` and probably quite a bit of work and tests to make it works in all conditions.

@vallsv, move it back to 0.12 if you disagree.

**Comment by vallsv** [comment]
It's fine for me, i prefer to share the contexts.

**Comment by t20100** [comment]
Yes, that's best.

**Comment by vallsv** [comment]
I close the issue, feel free to open it if you want to work on OpenGL context sharing. But on my side, the proposed solution is fine.
