### ISSUE TITLE
silx cannot be built on python 3.8

### ISSUE THREAD

**Issue by tschoonj** [silx-kit/silx#2793]
Hi,

Conda-forge is currently doing a mass rebuild for python 3.8 and it turns out that silx [cannot](https://github.com/conda-forge/silx-feedstock/pull/24) be built with it. This would appear to be related to [this issue](https://github.com/cython/cython/issues/2938).

I managed to fix it through using `--force-cython` to the setup.py argument list, but you may want to make a new release soon with regenerated c and c++ source code from the cython files.

**Comment by t20100** [comment]
Hi, thanks for the report!
The tarball on pypi contains the generated cython files.

Do we want to quickly make a 0.11.1 with no change but the regeneration of cython code and wheels for python 3.8? That shouldn't take too much time. Or do we want to wait for 0.12?

I would be for a 0.11.1 now.

**Comment by vallsv** [comment]
This problem will append again and again, for every new version of Python. No?
The `--force cython` option on the conda side is i think much better. Or we have to set cython as a strong dependency for the build.

**Comment by t20100** [comment]
Provided that there are wheels on pypi, it's packaged in conda and there are Debian packages, I expect most people are installing from binary packages...
So, I would go for adding `cython` as a build dependency and stop adding the cython generated files into the source tarball.
Yet that would be for 0.12, and in the meantime, I would make a 0.11.1 with only rebuilt cython files.

**Comment by vasole** [comment]
Besides that we'd also need the python 3.8 wheels but without the fabio and h5py wheels for 3.8 the binary wheels for 3.8 will not be very useful.

**Comment by t20100** [comment]
`fabio` shouldn't be a problem (https://github.com/silx-kit/fabio/issues/352)
`h5py` already provides Windows wheels and the other wheels are on the way (https://github.com/h5py/h5py/issues/1410).

**Comment by kif** [comment]
I wonder why the `pip install fabio` worked out of the box while the
one for silx did not re-trigger the cythonization.
Is there anything special in fitfunctions.pyx ?

**Comment by t20100** [comment]
Nothing special, `PyCode_New` occurs all over the place.. From a look at the generated C code, it seems to be related to defining python functions in cython.

**Comment by vasole** [comment]
closed by #2795
