### ISSUE TITLE
Default data location

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#28]
I'm creating this issue to discuss data packaging.

Initially we could gather all the data in a ``silx/data`` directory and make ``setup.py`` include it with the build. Having all the data (for the moment only GUI icons, but possibly also calibration data in the future, and maybe test related data) in a a single directory will make it easier to separate data and code for Debian packaging. Accessing data in our code could be done using ``from silx.resources import data_dir``. 

This is a draft for ``resources.py``:  https://github.com/PiRK/silx/blob/master/silx/resources.py

One alternative way of doing, instead of gathering all data in a sub-directory of the package, would be to store data together with the modules using it (e.g. putting icons in a subfolder of  ``silx/gui``) and setting  ``data_dir`` to the root package directory by default. And when we need to separate data and code, we could replicate the project structure in the data directory (e.g. ``/usr/share/silx/gui/icons``). It would make separating data and code slightly more complicated.

**Comment by vasole** [comment]
I am more in favor of silx/data containing the different data.

However, I would like to foresee a similar mechanism to the one used to install the different subpackages where each subpackage can be told the prefix to be used when trying to find its own data. Example module A that stores its data in directory A/data whould be told that its data are to be found into data_dir/A/data
