### ISSUE TITLE
[gui] First parameter of widget must be parent widget

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#280]
- When using the QtDesigner and promote widget, Qt expect to have parent widget as the first param

**Comment by t20100** [comment]
Following discussions, when the widget's __init__ takes additional parameters we propose to handle this by having parent=None as the first argument of widget's `def __init__(self, parent=None, ....)`.
This is in contradiction with Qt convention (where parent is the last argument), but allows to promote widgets in the QtDesigner.
Anyway, it would be good to have a consistent approach for all widgets in silx.

**Comment by PiRK** [comment]
For the widgets I have added to silx, the ones not following that convention are:

 - silx.gui.fit.FitConfig
    
    - ConstraintsPage
    -  BackgroundPage

- silx.gui.console

    - IPythonWidget
    - IPythonDockWidget

**Comment by t20100** [comment]
I'm doing it for the widgets of the plot package
