### ISSUE TITLE
[fit] Wrong height when estimating gaussian

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#281]
It seems that in some cases the peak amplitude is not correctly estimated. 

In the example that caused the problem, it was a  case where no peak is detected, but the user selected the  `ForcePeakPresence` option (one peak positioned on the max value of the curve). Another specificity was that the curve data had  a limited X range  centered on the peak, so only the tip of the peak was in the data. Maybe there is a problem in the amplitude estimation when only a small fraction of the total Y range is sampled, to be investigated (check background estimation).

**Comment by PiRK** [comment]
Maybe disable "Strip background" by default. It solves the problem in our example.

**Comment by vasole** [comment]
Bad idea. It is much, really much more common to have a peak on background than just a portion of a peak as it was the case on the offending example. Default should not be changed. The user must understand how the estimation works. Either we find other algorithm for estimating the peak height either we clearly document the estimation algoritm.

**Comment by vasole** [comment]
Tooltips added.
