### ISSUE TITLE
[plot] Do not change resetZoom when changing the log scale

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2825]
When we switch to log scale the plot view is updated.

It would be good to try to restitute the same view by clicking twice.

When ever it is possible it would be good to change the log scale and reuse the same limits.

**Comment by vasole** [comment]
If the user wants to achieve that, (s)he just have to disable the autoscale of the axis to be locked.

**Comment by vallsv** [comment]
I see, i always fall in the same problem, then the problem is the autoscale.
I will try to thing about it. I have to anyway.

**Comment by t20100** [comment]
That sounds reasonable to me not to do a reset zoom when switching axes scale.

**Comment by vasole** [comment]
That sounds reasonable until you deal with data that mix positive and negative numbers. You go to log you filter out the negative. You come back to linear and your data are cropped and you need to reset the zoom.

For 15 years I have let the user decide to use autoscale or not with no complaints.
