### ISSUE TITLE
[plot] Allow to add custom item in the plot

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2830]
This proposal is there to improve OO programming with the plot.

- The current way to manage "legend" creates a lot of overhead in the code
   - `addThing` sometimes updates an existing item, sometimes not
   - Then a legend always have to be provided, which have to be unique
   - The kind is also always needed to remove an item
   - Some parameters are not provided by the functional API, then the item anyway have to be created with the functional API, then the object have to be reached using the legend, then the item can be updated with the desired arguments
- The "kind" limiting custom third party objects (exception if nothing fit)
- There is no public API to dead with plot items (`add` and `remove` are private)

Few changes could make the life easier.
- [x] Create `addItem(item)` and `removeItem(item)`. This 2 functions will not deal with legend/kind. An object is unique.
- But `addItem` is already used for shapes, then...
- [x] Copy `addItem` as `addShape`
- [x] Update `addItem` to support both single item or shape arguments
   - The shape arguments can be deprecated in the next release
   - And can be removed the release after
- [ ] Create public `setActiveItem` which takes an item

This should be enough to provide a cleaner API, without breaking the legend for the functional API.

Here what i expect to have
```
item = MyShape()
item.setThing()
plot.addItem(item)
self._item = item  # store the item somewhere for further use
...
plot.removeItem(self._item)
```

**Comment by vasole** [comment]
Well, the uniqueness of the legend is not a problem. The id of the item is unique so, it is enough to set the legend to the item's id to solve most of your caveats.

**Comment by t20100** [comment]
This deserves a reference to #2

**Comment by vallsv** [comment]
For me the last missing thing is a global signal for the active item. I will create a dedicated issue for that.
