### ISSUE TITLE
[plot] Rework StackView colormap

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2835]
There are inconsitencies in the `StackView` colormap handling (see #2809, PR #2832).
The problem is linked with the need for autoscale on current image and autoscale on the whole stack.
An idea is to have autoscale on the image so colormap handling is as usual, and to add a button to autoscale on the stack on demand (which removes autoscale and sets the colormap range to that of the stack).

**Comment by vallsv** [comment]
Now we can implement that really easily.

- Create a boolean attribute `stackMode`/`fullMode` (something like that) in colormap (that's really ad hoc, but if it is useful)
    - This commit could be used as template 8abb23cf2eca3b49ecfb7a42ef6c78b6b5cdc05d
- Update the autoscale min/max computation
    - If the item is `ImageStack`, add `stackMode` is enabled, the result but be computed using `item.getStackDate` 
- Update the colormap dialog to allow to custom this attribute
    - It could can be displayed in the bottom on the scale --> [x] [auto scale] [3D] [x]
    - It should only be displayed when a `ImageStack` item is selected

**Comment by vallsv** [comment]
Oh, maybe `getColormappedData` itself can be patched, and all the computation is done

**Comment by vallsv** [comment]
Another approach, which looks much easier, could be to create a `ImageStack` property, and to not change at all the `Colormap`.
- `getColormappedData` could be customed for this item
- In this case switching from one one to another could be done with a `StackView` action, and could not be done with a colormap dialog button.

**Comment by vallsv** [comment]
So, sorry, difficult to brainstorm remotely...

Now i think i prefer the second approach, cause it is not an ad hoc solution.

But it would be better to displayed the button in the colormap dialog. Like in the first approach. It is doable, cause the colormap dialog knows the item (in this case). That's kind of border line, in this case, it makes sens to edit in the dialog this specific property of the `ImageStack`.

What do you think?

**Comment by t20100** [comment]
I will need to set it from the dialog.
An item mix-in for this makes the dialog only care about a single kind of class to take into account (be it an `ImageStack` item or something else).

**Comment by t20100** [comment]
Can be fixed by dropping full stack autoscale
