### ISSUE TITLE
[resources] Enable default_directory use for external resources

### ISSUE THREAD

**Issue by juliagarriga** [silx-kit/silx#2842]
In `silx.resources` function `get_package_and_resource` it would be nice to be able to use the parameter `default_directory` for external projects besides of silx. 
```
def _get_package_and_resource(resource, default_directory=None)
```

Furthemore the `default_directory` parameter could also be available from the public function `resource_filename`.
This way projects could have different directories inside resource and use them like in silx by, for example, having a `gui.icons` folder.
Maybe also adding the `default_directory` parameter to some public functions like `icons.getQFile`.

Anyway, it is just an idea, for me it would be a nice feature for not having to always put the `gui/icons` path in the icons.

**Comment by vallsv** [comment]
Are you searching for `register_resource_directory`?

It is used by pyFAI and flint, at least.

I use to do that
```
# bliss.flint.resources.__init__.py
silx.resources.register_resource_directory("flint", __name__, _RESOURCES_DIR)
```
Then i can use my resources this way:
```
icon = icons.getQIcon("flint:icons/remove-item")
```

**Comment by juliagarriga** [comment]
Yes! I already use this, now I am using it like you.
 The thing is to be able to remove the 'icons/' path.
```
icon = icons.getQIcon("flint:remove-item")
```

**Comment by vallsv** [comment]
It was part of the first proposal, and was rejected.

I would say it complexity the API for something which should be really simple, reaching a resource. Then i don't really see the need. I mean do you really care about this 5 extra bytes?

In feel like, silx should use absolute everywhere to avoid mistakes.

**Comment by juliagarriga** [comment]
Ok no problem!! I close then.
