### ISSUE TITLE
[plot] I am using _pickTopMost

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2846]
I am using `_pickTopMost` in my code.

Could it be switched to public? Or should i do something else?

**Comment by t20100** [comment]
Yes it can be moved to public.
It was private initially because it was not returning object, but this is now the case, so it can be public.

**Comment by t20100** [comment]
You can also use `PlotWidget.pickItems` and only get the first one (`_pickTopMost` is very little code)

**Comment by vallsv** [comment]
I am fine with `pickItems` then. I will check it.

**Comment by vallsv** [comment]
I have fixed my code.
