### ISSUE TITLE
[colormap dialog] Few small improvements

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2847]
Here is the current state of the colormap dialog
![Screenshot from 2019-12-19 12-45-22](https://user-images.githubusercontent.com/7579321/71172775-6d59df80-2261-11ea-9946-b45636efd40c.png)

- the line between min/max is under the histogram (could be moved on top)
- vertical min/max markers could be displayed blue only if editable
- a scatter/image could be used to display the colormap within the graph (the histogram itself could be colorized, in case it works)

**Comment by t20100** [comment]
The line between min/max is under the histogram is maybe a regression in 0.12, I've open issue #2850 to check it.
The rest is enhancement, so for later.

**Comment by t20100** [comment]
The line between min/max is under the histogram is fixed by: #2851
