### ISSUE TITLE
silx.io is polluting symbols which prevents silx.opencl to be imported (with POCL driver)

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#2848]
Thanks for the Debian team for sorting out this:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946422

**Comment by vallsv** [comment]
Then is it the same issue as the one with `crc32` with pyFAI ?

Was'nt it fixed on silx with compilation flags? Maybe the compilation flags are compiler/compiler-version/platform dependant.

**Comment by vasole** [comment]
Despite what @kif says in the debian bug report, no specfile related stuff is imported by just importing silx.io. No spech5, no specfile and no specfilewrapper in sys.modules

What is imported is h5py. We should look into that direction.

Furthermore, the debian thread also gives that hint:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946422#69

Downgrading to python3-h5py from buster makes the problem go away. But
it also removes mpi from the loop.

**Comment by kif** [comment]
The latest investigations suggest it is indeed a symbol leak between OpenMPI (h5py is since recently  compiled against OpenMPI it in debian) which interferes with the POCL opencl driver. Silx.test being just the meeting point of those two.
