### ISSUE TITLE
[plot] API to reach the size of a pixel in the screen

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2856]
This could allow to display things according to the zoom.

I am pretty sure it is already available, using the picking transformation API, but an easier API could be useful.

I don't know. Size (in pixel of the screen) of the axis, bounding box (in pixel of the screen) of an item

**Comment by t20100** [comment]
You can already get the size in pixels of the plot area [`PlotWidget.getPlotBoundsInPixels()`](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.getPlotBoundsInPixels).

It is also already possible to get the bounding box of a plot item in data coordinates with [`Item.getBounds()`](http://www.silx.org/doc/silx/latest/modules/gui/plot/items.html#silx.gui.plot.items.Item.getBounds).
You can then convert it with [`PlotWidget.pixelToData`](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.pixelToData).

We can eventually add an argument to `Item,getBounds` or another method to `Item` to get the bounding box to retrieve directly the extend in pixels (knowing that if the item expands outside the plot area, the pixel coordinates can be negative).

As for the size of a pixel in data coordinates, if it is needed, it can be a good to have a helper method in `PlotWidget` for it. BTW, we need to support log scales, where the size of a pixel in data coordinates is not the same depending on the pixel....

**Comment by vallsv** [comment]
On my side it is maybe enough, i will try.
Thanks.

**Comment by t20100** [comment]
@vallsv, do you still need this?

**Comment by vallsv** [comment]
With the item bounding box + dataToPixel it is maybe enough.

But this issue was maybe more to be able to reach this information at low cost inside a derivative item.

I can close it anyway.
