### ISSUE TITLE
[specfile] Multiple MCAs header information handling

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#286]
`silx.io.SpecFile` currently cannot handle the case of multiple MCA devices in a single scan when each device has its own header block. 
Currently, the decoding of `#@CHANN` assumes there are 4 values in that header. (https://github.com/silx-kit/silx/blob/4a9a1cd7004c58254dd6b53b34b5f665cb28dd68/silx/io/specfile/specfile.pyx#L196)

In case of multiple headers, we actually have several blocks of 4 values to parse:
```
In [15]: sc3.mca_header_dict
Out[15]: 
{u'CALIB': u'1 2 3\n3.4 5.6 7.8\n3.5 2.1 0.6',
 u'CHANN': u'20 0 19 1\n20 0 19 1\n20 0 19 1',
 u'CTIME': u'123.4 234.5 345.6\n56.4 23.4 234.5\n13.4 34.5 34.6',
 u'MCA': u'%16C\n%16C\n%16C',
 u'MCADEV': u'1\n2\n3'}

```

**Comment by vasole** [comment]
Please edit the title (something like [specfile] Multiple MCAs header information handling).
