### ISSUE TITLE
How do I check if I can use the gl backend?

### ISSUE THREAD

**Issue by jonwright** [silx-kit/silx#2866]
Before requesting the a plot backend (gl or matplotlib), how should I check if the machine has opengl 2.1 ? There are a couple of cases of lower GL version that are causing problems (e.g. rnice -> X-Win32 and windows remote desktop).

**Comment by vasole** [comment]
Sometimes using the OpenGL binding already blocks the application. The quick and dirty solution I use prior to try to access OpenGL is:
```
OPENGL_DRIVERS_OK = True
if sys.platform.startswith("linux"):
    import subprocess
    if subprocess.call("which glxinfo > /dev/null", shell=True) == 0:
        if subprocess.call("glxinfo > /dev/null", shell=True):
            OPENGL_DRIVERS_OK = False
            isSilxGLAvailable = False
            _logger.warning("OpenGL disabled. Errors using glxinfo command")
```

If that works, then you can afford to import the OpenGL binding and to test the version.

**Comment by t20100** [comment]
You can check with `glxinfo | grep OpenGL` and look for the line:
```
OpenGL [core profile] version string: ...
```

There is a bit of doc on this here: http://www.silx.org/doc/silx/latest/troubleshooting.html

**Comment by jonwright** [comment]
This comes up for windows too but there is no glxinfo command (e.g. remote desktop workarounds). See:

https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote

I think I would need to try to create an appropriate context with qt and see if it works? There is code to do something like this, but there is an underscore in the path so I guess it is not in the silx API:

https://github.com/silx-kit/silx/blob/master/silx/gui/_glutils/OpenGLWidget.py

I found some code in initialiseGL (line 187) that is detecting the problem. Poking around it seems that I can do this:
```
        self.scatter_widget = silx.gui.plot.ScatterView( backend=('gl','matplotlib'))
        if not self.scatter_widget.getPlotWidget()._backend.isValid():
            self.scatter_widget = silx.gui.plot.ScatterView( backend='matplotlib' )
```
Shall I use that as a workaround or is it doing something horrible like leaking opengl contexts? 

My feeling is that this is a bug and I shouldn't be using an underscore variable, but I don't see how to get _backend.isValid() otherwise? If I give a pair of backend options and PlotWidget.__getBackendClass takes them, then when one of them is not valid I think it could do better taking the next one in the list. Does that make sense? Otherwise I don't see what the list/tuple option is for...

When silx realises an opengl context is not valid, perhaps it should stop trying to create them? Seems to be a hard problem if these widgets are embedded into another application and you do not control the window creation (e.g. multiple windows on different screens that have different gl).

**Comment by t20100** [comment]
A few things:

- First, from Windows, mobaxterm should provide remote OpenGL >= 2.1.
- Use private method prefixed with `_` if you want, but don't blame us if we change it at some point, that's the purpose of it.

`silx.gui._glutils.OpenGLWidget` tries to detect whether it can use OpenGL or not to avoid failure, yet it is not possible to detect all failure (e.g., with ssh -X, remote OpenGL disabled (default on Debian) and pyqt5, I didn't find a way to check that OpenGL is not available and when the widget is display, Qt just hang...):
- We could provide a function to check if OpenGL is available or not, but that's probably going to be ugly if we want to cover all cases: starting a subprocess trying to display an OpenGL widget and waiting to see if it returns....
- For the `PlotWidget`, I agree we should have a possibility to fallback to matplotib if OpenGL is not available. The tricky part is that the detection is done when initializing the OpenGL context, so no early check possible. I started to work some time ago on switching the rendering backend of a `PlotWidget` (without giving it much priority). I think that would be needed for supporting the fallback.

**Comment by jonwright** [comment]
Seems like a problem for everyone. This might be a workaround:
https://wiki.octave.org/OSMesa

**Comment by vallsv** [comment]
I could be very useful to package the @vasole solution in a public method of silx. It looks to be useful for many people.

**Comment by t20100** [comment]
Initially, in PyMca, I made an OSMesa backend (https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaGraph/backends/OSMesaGLBackend.py)... that can be ported to `silx`, but then OS mesa is required... For 2D I don't see much interest compared to matplotlib.

I agree that a function checking the availability of OpenGL should be added to `silx` as it seems to be needed by many.

**Comment by t20100** [comment]
I made PR #2878 to provide `silx.gui.utils.glutils.isOpenGLAvailable` function to test for OpenGL, testers welcomed!
