### ISSUE TITLE
[Plot] PlotWindow: button for changing X and Y limits

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#287]
It would be nice to have a new button to allow entering the exact X and Y limits. This is important when comparing plots from different windows.

**Comment by t20100** [comment]
@srio There is a LimitsToolBar in silx.gui.plot.PlotTools which does that as in PyMca. (http://www.silx.org/doc/silx/modules/gui/plot/dev.html#silx.gui.plot.PlotTools.LimitsToolBar)

It is used when you start the ImageView widget from the command line: python -m silx.gui.plot.ImageView <file>
