### ISSUE TITLE
[Plot] ImageView: possibility to display X and Y profiles instead histograms

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#288]
For some applications it will be interesting for me to customize ImageView (or to have another widget with similar aspect) in order to display the X and Y profiles when crossing the mouse on the image. 

I know it is possible to use the profile tool, but sometimes is easier and quicker like that.

**Comment by andygotz** [comment]
I vote for this feature too. The most useful would be to have the possibility to choose what the X+Y profiles should show - a single line of pixels or the sum of all pixels.

**Comment by vasole** [comment]
I would couple that option to the use of of the cross-hair cursor. If the user chooses the cross-hair cursor on a 2D plot, the histograms are replaced by the profiles.
