### ISSUE TITLE
[plot] y-crossair can be displayed at the wrong place

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2899]
I did not found example how to use time zome.

Then i enabled the datetime axis using
```
plot.getXAxis().setTimeZone("UTC")
```
I used epoch timestamps (which looks to not work properly)

As result the cross-air mouse was not displayed at the proper location (x was right, y was wrong).

Can it be reproducible? Any idea?

**Comment by t20100** [comment]
Can you provide a sample code, from what I tested it looks to be OK.

**Comment by vallsv** [comment]
Yes, it have nothing to do with the timezome.

Iv got a random location for the y-crossair time to time, i still dig into the code

**Comment by vallsv** [comment]
It's about yaxis. I still have create a small sample to reproduce the pbm

**Comment by vallsv** [comment]
Here is a small example to hilight the problem

The horizontal line of the crossair is not displayed, cause i guess it is displayed on the right axis using the left axis location.
```
    nb = 200
    datatime = 10 * numpy.arange(nb) / nb
    value = numpy.cos(datatime)

    plot = Plot1D()
    plot.addCurve(x=datatime, y=-value, yaxis="left", legend="foo2")
    plot.addCurve(x=datatime, y=value+5000, yaxis="right", legend="foo1")
    plot.show()
```
