### ISSUE TITLE
[plot] Visualize compound data

### ISSUE THREAD

**Issue by jln-ho** [silx-kit/silx#2911]
I have a ton of HDF5 files containing compound arrays where the first field is a timestamp and the second field/column is a sensor value sampled at that time.

It would be really nice if two-dimensional, numeric compound arrays could be visualized as a time series line graph in the "Curve" tab. Or basically any combination of two columns of a compound array. [HDFView](https://www.hdfgroup.org/downloads/hdfview/) already does this, albeit poorly (no zooming, takes forever with larger datasets, no grid lines ... the list goes on).

I could try to add this functionality and submit a PR...
Any pointers as to where the best place to start could be?

**Comment by vallsv** [comment]
Hi Julian,

We have a set of `DataView` to deal with different kind of visualization (you can check `silx.gui.data.DataViews`). It receives the raw dataset and check if it can be displayed with, then provides a factory method to create the widget and to feed the data.

You can try to copy-past  `_Plot1dView` with your own name. You also can check `examples/customDataView`.

I dont know if it is generic enough to be merge in silx, but you could be able to create your own viewer based on this.

For the time, How plot X axis provides a time based.
```
plot.getXAxis().setTickMode(TickMode.TIME_SERIES)
```

Hope it can help.

**Comment by jln-ho** [comment]
I'll look into it, thanks!

**Comment by jln-ho** [comment]
So I got a first version that can detect compound arrays. It creates a custom ``PlotWindow`` with a small toolbar where the user can select the field for the X and Y axis respectively (only numeric fields will be selectable).

To me it seems like this could be generic enough to be merged into ``master``. Would you be willing to review a PR later this week? Just asking because, frankly, if you're not interested at all, I'll just keep using my quick and dirty solution for now without refactoring, comments, etc.

**Comment by vallsv** [comment]
Nice :-) You could at least provide a screenshot, and push it somewhere so that it can be tested. Just think about creating an example or recipe to generate a dataset. With git and github, you can clean up the stuff later, there is no problem.

I will not have time to review anything this week, but there is other people around.

**Comment by jln-ho** [comment]
My colleague just submitted a PR incl. some test data. I'd be glad to hear your (or anyone else's) thoughts on this.

**Comment by t20100** [comment]
closed by #2948
