### ISSUE TITLE
[plot] pixelToData do not work in hi-DPI mac

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2914]
`plot.pixelToData` is supposed to use the Qt pixel to return the data position.

In Mac OS hi-DPI it looks like it is not the case, which make the API difficult to use with Qt mouse events.

pixel provided by the plot events and pixel provided by the Qt mouse event are i guess not consistent.

**Comment by t20100** [comment]
This was fixed for the OpenGL backend, but not for the matplotlib one.

**Comment by t20100** [comment]
closed by #3318
