### ISSUE TITLE
[view] Hints to plot/display data in linear or logarithmic scale

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#2928]
Can we agree within the *silx* project to define an attribute to tell the plotting tool to set certain axis in log/linear scale when read from a nexus file ? What about 
@scale="log" or "linear" 

The nexus group officially stated this is not their business:
https://github.com/nexusformat/definitions/issues/755#issuecomment-587019174

**Comment by vallsv** [comment]
`css` have nomenclature for private attributes before standardisation. Like `-webkit-min-device-pixel-ratio:0`.

It would be good, at least, to prefix things in this case.

**Comment by vasole** [comment]
@kif 

The suggestion we got and that I support is to use a single attribute for everything and not an attribute for each thing. We could just put a json string into a single ``@plot_attributes``  where you could put scale, colormap, whatever and the visualization software could interpret up to its desired level.

**Comment by vasole** [comment]
It could be a json string, a set of comma-separated key=value pairs, an array of key=value pairs, whatever you want. Just use a single attribute to encompass all the plot customization.

**Comment by vallsv** [comment]
I really can't agree with this proposal. Using json, is like saying HDF5 is not structured. It will create another language inside the language, which will request it's own normalization, it's own validation. It's own way to display the raw. attrbute The double of work, for something which take 5 minutes to implement.

Plus it's not only about visualization or a matter of tast, it's about the kind of data you deal with.

For example if you have radian values between -pi..pi and -pi ==pi, that's the way the data is structured. You can display it with a cyclic colormap with fixed range, that's matter of tast. That's the same for diffraction images, the log scale is part of the structure of the data.

**Comment by kif** [comment]
On Tue, 18 Feb 2020 18:56:18 -0800
V. Armando Solé <notifications@github.com> wrote:

> It could be a json string, a set of comma-separated key=value pairs, an array of key=value pairs, whatever you want. Just use a single attribute to encompass all the plot customization. 

It seams reasonable to me

**Comment by t20100** [comment]
To me key thing is to prefix the attribute name as @vallsv  proposed, e.g., `@silx_<name>` to avoid conflicts (See https://github.com/nexusformat/definitions/issues/757).

Taking prefix as granted, there is no need for minimizing the number of attributes we define, so for me no need for a sub-format.

**Comment by vasole** [comment]
From a programmer point of view I would not like to have to yet check for a plethora of optional plot attributes (scales, symbols, sizes, colormaps....) If I am looking for attributes for displaying a plot, I would like to check at just one place.

**Comment by t20100** [comment]
I agree but that place can be the attributes of the NXData group as it is already a mapping.

**Comment by vasole** [comment]
Yes, what I mean is that I would prefer to have a single silx_plot attribute containing all the plot configuration rather than silx_scale, silx_colormap, silx_colormap_scale, silx_symbol, silx_symbol_size, silx_symbol_color, silx_plot_limits, ....

**Comment by kif** [comment]
On Thu, 20 Feb 2020 12:54:00 -0800
V. Armando Solé <notifications@github.com> wrote:

> Yes, what I mean is that I would prefer to have a single silx_plot attribute containing all the plot configuration rather than silx_scale, silx_colormap, silx_colormap_scale, silx_symbol, silx_symbol_size, silx_symbol_color, silx_plot_limits, ....

In principle I'ld rather agree with Thomas ... but I recently did
profiling of applications playing with h5py and the attribute handling
turn out to be one of the black-spot.
So maybe limiting the number of requests that needs to be performed on
the HDF5 file would allow to keep the GUI more responsive ...

Of course, fixing h5py would be an even better solution ...

**Comment by vallsv** [comment]
We are talking about displaying a plot.
This configuration have to be read a single time, and not often.
You do not switch from an `NXdata` every ms. I don't think there is anything about responsiveness here.

Or are you talking about writing efficiency?
In this case, maybe it make sense. But still, that's a problem that should be fixed in hdf5.

**Comment by t20100** [comment]
If there's a performance issue for accessing attributes, that should better be fixed in `h5py` or HDF5...

**Comment by vasole** [comment]
Using a single attribute allows any application to take a single attribute and to pass it to silx. 

Basically one application just needs to store a plot configuration and to pass a plot configuration to silx. In your way, the application will have to pass the NXdata group itself and it will therefore be limited to NXdata support thus not offering support for other plot usages.

What I really dislike is to pollute an NXdata subespace with many attributes but it seems I am the only one thinking that. You are going to end up with more extra attributes than original ones.

**Comment by t20100** [comment]
My opinion is to make it as if it was NeXus, except adding a `silx_` prefix to attribute names.
And I think if it was included in NeXus it would be with multiple attributes.

**Comment by vasole** [comment]
Objectively I can tell is that in the NIAC 2018 it was suggested to use just one attribute.

**Comment by t20100** [comment]
Then let's look at what was proposed, is the discussion available somewhere.

**Comment by vasole** [comment]
https://www.nexusformat.org/NIAC2018Minutes.html

NXdata Plottype Attribute

This is about describing in more detail how the data is to be plotted. Color maps, linear or logarithmic axis etc. This could be achieved by having a plottype attribute at group level which contains keywords hinting at the intended presentation style.

After some discussion the NIAC came up with this
proposal: NeXus is about how to find and annotate the data to be plotted but not to describe how the data is to be plotted.

Voting results: All in favor

This is to be placed into the documentation.

**Comment by t20100** [comment]
It was decided to use a `silx_style` attribute storing a json dict to store information about NXdata that is not available in the NeXus specification.

**Comment by t20100** [comment]
FYI, I asked NeXus to reserve the `SILX_` name prefix (https://github.com/nexusformat/definitions/issues/781)

**Comment by vallsv** [comment]
upper case?

**Comment by t20100** [comment]
Yes, that's what is recommended: https://github.com/nexusformat/definitions/issues/757#issuecomment-619033258

**Comment by vallsv** [comment]
Sad world...

**Comment by t20100** [comment]
After discussions, PR  #3092 proposes to use `axes_scale_types` and `signal_scale_type` to match NeXus `axes` and `signal`.
A few examples:

* To use a colormap with log normalization:
  `@SILX_style = {"signal_scale_type": "log"}`
* To display curves with loglog axes:
  `@SILX_style = {"axes_scale_types": ["log"], "signal_scale_type": "log"}`
* To display curves with semilogy axes:
  `@SILX_style = {"axes_scale_types": ["linear"], "signal_scale_type": "log"}`
* To display a scatter plot with semilogy axes:
  `@SILX_style = {"axes_scale_types": ["linear", "log"]}`
