### ISSUE TITLE
[plot] Switch profile windows as dialog

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2935]
I think it would be better to set our side windows (like the profile window) always over there main parent window.

This can be achieved by using `windowFlags` with `qt.Qt.Dialog` + hint for minimize/maximize.

I guess there is not only the profile window to patch.

Could we do it in silx?

**Comment by t20100** [comment]
I can only think of the image/stack and scatter profile windows, I'd expect others "tools" to be either  dock widgets or dialogs.

It seems reasonable to me to do it in silx.
