### ISSUE TITLE
[silx view] Cannot install on Windows 10 with pyinstall

### ISSUE THREAD

**Issue by JuliusHarald** [silx-kit/silx#2951]
I used the README.rst file form the silx/package/windows directory to install silx view from source on a Windows 10 VM with pyinstaller. 
When I try to start the programm I get the follwoing error message:

Failed to execute script bootstrap-silx-view

The REAME.rst file is from 2018 is there already any newer way to install silx view with pyinstaller?

**Comment by t20100** [comment]
I'm not sure it is really used, so I am not surprised it is broken, generating fat binaries is quite fragile with Python.
I had a first look at it: I get some other errors than yours.... but it's not working anyway. I'll look further into it.
