### ISSUE TITLE
[fit] The fit dialog do not take care of the current available curves

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2953]
The fit action only take care of the curve at the time the dialog was open.

But the dialog can stay open, the user can select something else, the curves can be replaced by something else (open another dataset), the dialog still compute estimation and fit on the very first curve selected.

**Comment by vasole** [comment]
Not a bug but a feature. The user decided to perform a fit, potentially setting a configuration and so on to fit a curve. If that curve disappears from the source, it is not its business.

**Comment by vallsv** [comment]
From a discussion with @t20100, one of the good idea could be to setup a mode to the `FitAction` in order to request to trig the plot selection.

**Comment by vallsv** [comment]
> The user decided to perform a fit, potentially setting a configuration and so on to fit a curve

In this case, the dialog should be modal. A specific use at a specific time.

**Comment by t20100** [comment]
From feedback @vallsv got, users expect that the fit is done on what's currently visible, not what's been selected when the widget was opened.

I think we can implement both behavior in the `FitAction`.

**Comment by vasole** [comment]
Those must be new users... They just need to request the fit from the main plot to get the fit on whatever they want. I would hate to be working on a curve and then when I am ready I perform a fit on something different perhaps with no possibility to go back.

It's up to you, but I would not do it.

**Comment by vallsv** [comment]
There is BTW a missing step on this dialog: the peak search.

This step is not redone when you open the dialog for the second time. It should be.

**Comment by vasole** [comment]
Why should be? You do it when you do the Estimate. Sometimes you want to perform a fit without performing an estimate. For instance, when you have entered the estimation manually and you want to apply it to the next curve.

**Comment by vallsv** [comment]
Cause i don't think it is needed to display this 14 gaussian descriptions to fit this curve.

![Screenshot from 2020-03-12 16-56-21](https://user-images.githubusercontent.com/7579321/76540551-92d24000-6482-11ea-852e-e5a6293a9110.png)

But i see. The estimation clean up everything, that's already not so bad.

**Comment by vasole** [comment]
Either you do not ask to fit Gaussians either you adjust the peak search parameters.

**Comment by vallsv** [comment]
So the dialog should be cleaned up every time we open it. In fact it should be destroyed and recreated, which should remove a lot of issues i noticed.
