### ISSUE TITLE
Possible memory leak in OpenGL backend

### ISSUE THREAD

**Issue by UUSim** [silx-kit/silx#2956]
Last week we have upgraded from silx 0.10.0 to silx 0.12.0.
Since then our application crashes after plotting for a while.

In our scenario there is a time-series plotted at approximately 1Hz. Each second, an extra sample is added to the time series.

The crash happens after some 45 minutes.
So the length of the final time-series being plot is ~2700 samples.

Since the time series is growing by 1 sample everyting, the total number of sampled that were plotted is approximately: 3643650 (``3643650=sum(np.arange(2700)``)

This is the stack trace provided:
``` python
2020-03-12 17:44:33,966                   misc.py:88   : ERROR  : pid=31125: Bug: uncaught RuntimeError: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/_glutils/OpenGLWidget.py", line 239, in paintGL
    parent.paintGL()
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/BackendOpenGL.py", line 419, in paintGL
    self._paintFBOGL()
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/BackendOpenGL.py", line 369, in _paintFBOGL
    self._renderPlotAreaGL()
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/BackendOpenGL.py", line 676, in _renderPlotAreaGL
    self._renderItems(overlay=False)
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/BackendOpenGL.py", line 459, in _renderItems
    isXLog, isYLog)
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/glutils/GLPlotCurve.py", line 1237, in render
    self.lines.render(matrix)
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/plot/backends/glutils/GLPlotCurve.py", line 419, in render
    program.use()
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/_glutils/Program.py", line 158, in use
    self._attrib0)
  File "/usr/local/lib/python3.5/dist-packages/silx/gui/_glutils/Program.py", line 91, in _compileGL
    raise RuntimeError(gl.glGetProgramInfoLog(program))
RuntimeError
libpng warning: Out of memory
libpng error: insufficient memory
QImage: out of memory, returning null image
QImage: out of memory, returning null image
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

Do you have any idea what could be causing this?

**Comment by t20100** [comment]
Sounds weird.

There has been a few changes in the `PlotWidget` but there has been not much changes in the way the OpenGL backend works.

The error from libpng and QImage sounds funny. Did you try to grab the widget content?

I'm looking at what can go wrong in `silx`.

**Comment by vasole** [comment]
@UUSim Was silx the only change? I mean, no change of Qt binding or version?

**Comment by t20100** [comment]
I was about to ask the same question.
Looking at it, some refactoring of the `PlotWidget` also affected the OpenGL backend.

**Comment by t20100** [comment]
That might be related to PR #2539.

**Comment by t20100** [comment]
From a quick test, `_compileGL` in `silx.gui._glutils.Program.py` is called way to often.

**Comment by UUSim** [comment]
We have not changed Qt binding and or version.

We are using Debian Stretch, and use debian packages for all our dependencies. Only silx is installed via pip.

These are our versions:
```
Qt: 5.7.1
PyQt: 5.7
Python: 3.5.3
```

**Comment by t20100** [comment]
Early patch that avoid calling `_compileGL` all the time and seems to avoid memory leak:
```
silx/gui/_glutils/OpenGLWidget.py
@@ -270,6 +270,8 @@ class OpenGLWidget(qt.QWidget):
         layout.setContentsMargins(0, 0, 0, 0)
         self.setLayout(layout)
 
+        self.__context = None
+
         _check = isOpenGLAvailable(version=version, runtimeCheck=False)
         if _OpenGLWidget is None or not _check:
             _logger.error('OpenGL-based widget disabled: %s', _check.error)
@@ -357,7 +359,9 @@ class OpenGLWidget(qt.QWidget):
         if self.__openGLWidget is None:
             return None
         else:
-            return self.__openGLWidget.context()
+            if self.__context is None or not self.__context.isValid():
+                self.__context = self.__openGLWidget.context()
+            return self.__context
```

The wrapping object around the context returned by PyQt5 is a new one each time... and it is used in `silx` as a key in `WeakKeyDictionary` to manage resources... pretty bad.
I'm checking a bit more, but that's probably the root of the issue.

**Comment by t20100** [comment]
Yes, it looks like that's it.

`PySide2` behaves differently, asking the context always returns the same python object (which is nice).
And I guess I did that at the time I was developing with `PySide2` as default.

**Comment by vallsv** [comment]
Can you just check that your changes still allow to dock and undock plots using OpenGL, without releasing resources (an image for example). Maybe it was related somehow, i don't remember.

**Comment by t20100** [comment]
This change doesn't change the behavior regarding dock widgets (though it does not behave nicely by default at least on my PC: missing redraw + issue when dock is not within the main window).

**Comment by UUSim** [comment]
This is terrific!
We will still have to wait for a new pip release where this merge is included, and then we can upgrade to 0.13.0 (for now we have rolled back to 0.10.0).

Thanks for your support, and keep up the good work.

**Comment by vasole** [comment]
@UUSim Just in case, we produce unofficial Debian 9 packages on our nightly builds:

http://www.silx.org/pub/debian/

**Comment by t20100** [comment]
There is also a richer repo with weekly builds for Debian 9, 10 and Ubuntu 20.04: http://www.silx.org/pub/linux-repo/ that we set up recently.

**Comment by t20100** [comment]
And wheels from the weekly builds: https://silx.gitlab-pages.esrf.fr/bob/silx/
