### ISSUE TITLE
[3D] Is scaling possible?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2959]
Is it possible to have an option to scale the different axes in order to have the same physical display length for each dimension:

https://stackoverflow.com/questions/46366461/matplotlib-3d-waterfall-plot-with-colored-heights

Nothing happens when I click on Scale in the scene:

![image](https://user-images.githubusercontent.com/5636251/76847979-36d13800-6843-11ea-97ce-0a966dd5d989.png)

**Comment by vasole** [comment]
Basically an autoscale in 3D.

**Comment by t20100** [comment]
There is no autoscale, but you should be able to set the scale for each axis.
In the "Object parameters"
`Data` -> `Transform` -> `Scale`, click on the `Value` column `(x: 1; y: 1, z: 1)` (hidden because of the horizontal scroll in your screenshot) to edit it.

**Comment by vasole** [comment]
Dammed. I did not realize the horizontal scroll.

OK, basically what is needed is an action to adjust each scale to the delta in each dimension.

**Comment by t20100** [comment]
Yes, that should be straight forward to set the scale so that it is displayed as a cube.
