### ISSUE TITLE
[plot] Data background is not used when plot do not display the axes

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2967]
I think it is a regression.

- Set both background with a different color
- One is displayed outside the data view (beyond the axes)
- Another one is dislayed under the data (inside the axes)
- Switch the plot mode to hide the axes
- The data background is not anymore used (i think we expect it to be used)

**Comment by t20100** [comment]
A matplotlib backend only issue, probably due to the use of `set_frame_on`.
