### ISSUE TITLE
[silx view] VARIABLE_errors not handled in NXdata plots.

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2975]
![image](https://user-images.githubusercontent.com/5636251/77425375-ec1b6700-6dd2-11ea-810d-a3a9a0ef155a.png)

**Comment by kif** [comment]
I thought those error-bars were for the "horizontal" direction ?!

Nexus is faaaar too obfuscated for me :(

**Comment by vasole** [comment]
The _errors approach serves to associate uncertainties to any dataset irrespective of being used as signal, as axis or not used for a plot.

**Comment by kif** [comment]
On Tue, 24 Mar 2020 05:51:34 -0700
V. Armando Solé <notifications@github.com> wrote:

> The _errors approach serves to associate uncertainties to any dataset irrespective of being used as signal, as axis or not used for a plot. 

Does this mean I should use this way of storing data for BM29 ? as there is a strong correlation with `silx view` in order to visualize the data on this beamline ?

**Comment by vasole** [comment]
You should use it for everything. See uncertainties or errors under:

https://manual.nexusformat.org/datarules.html
