### ISSUE TITLE
segfault when adding cutting plane

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#2985]
I'm trying to learn about 3D plotting with `ScalarFieldView`. With version 0.12.0, running the sample code, I get a segfault when adding a `CutPlane`.

Running the sample code...

```
python viewer3DVolume.py 
WARNING:__main__:Not data file provided, creating dummy data
```
...then when I click "Visible" to show the cut plane, I get one of these two errors (it varies which I get).
```
corrupted double-linked list
Aborted (core dumped)
```

```
free(): invalid next size (fast)
Aborted (core dumped)
```

**Comment by t20100** [comment]
Hi,

I could not reproduce.
What is your OS and versions of python, pyopengl, pyqt5/pyside2, (and eventually matplotlib)?
Do you run locally or remotely?

**Comment by alexbjorling** [comment]
No I can imagine this is hard to reproduce. I'm running locally on:
* Ubuntu 19.04
* python 3.7.3
* PyOpenGL 3.1.0
* matplotlib 3.1.1, and
* PyQT5 version "5.12.1" according to silx.gui.qt.PYQT_VERSION_STR
So this is not something that anyone recognizes from development or so?

**Comment by t20100** [comment]
No! We usually run all the examples when we make a release, and this is the kind of crash that looks pretty bad!
Are the other examples with 3D doing the same? (You can try the `examples/plot3dSceneWindow.py` and `examples\plot3dUpdateScatterFromThread.py`).

**Comment by alexbjorling** [comment]
Yep, these fail without showing a window even.
```
$ python plot3dSceneWindow.py 
Segmentation fault (core dumped)

$ python plot3dUpdateScatterFromThread.py 
free(): invalid next size (fast)
Aborted (core dumped)
```

**Comment by t20100** [comment]
OK.... Any issue with other 3D visualization tools or `glxinfo`, `glxgears` tools?

Does this basic script works? What does it prints to the terminal? 
```
from PyQt5 import QtCore, QtWidgets
from OpenGL.GL import *
import numpy as np


square = np.array(((-1, -1), (-1, 1), (1, -1), (1, 1)), dtype=np.float32)

class Test(QtWidgets.QOpenGLWidget):
    _rotate = 0

    def dumpInfo(self):
        print('GL_VERSION: %s' % glGetString(GL_VERSION))
        print('GL_SHADING_LANGUAGE_VERSION: %s' % glGetString(GL_SHADING_LANGUAGE_VERSION))


    def initializeGL(self):
        self.dumpInfo()
        glClearColor(1.,1.,1.,0.)
        glEnableClientState(GL_VERTEX_ARRAY)
        glVertexPointer(2, GL_FLOAT, 0, square)
        glColor4f(1., 0., 0., 1.)

    def paintGL(self):
        glClear(GL_COLOR_BUFFER_BIT)
        glPushMatrix()
        glRotate(self._rotate, 0, 0, 1)
        glScale(10, 10, 1)
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
        glPopMatrix()

    def resizeGL(self, w, h):
        print('resize', w, h)
        glViewport(0, 0, w, h)
        glMatrixMode(GL_PROJECTION)
        glOrtho(0, w, h, 0, -1, 1)
        glMatrixMode(GL_MODELVIEW)
        glTranslate(w//2, h//2, 0)

    def mousePressEvent(self, *args):
        self._rotate += 10
        self.update()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication([])
    widget = Test()
    widget.show()

    sys.exit(app.exec_())
```

**Comment by alexbjorling** [comment]
Thanks for looking into this, I've never had anything to do with OpenGL so can't investigate much myself (that's why I went for the silx widgets...).

`gxlgears` looks ok, `glxinfo` prints a lot of info as attached.

[glxinfo.txt](https://github.com/silx-kit/silx/files/4439227/glxinfo.txt)

Your script above produces a red square which rotates on mouse clicks, and prints this

```
GL_VERSION: b'3.0 Mesa 19.0.2'
GL_SHADING_LANGUAGE_VERSION: b'1.30'
resize 640 480
```

**Comment by t20100** [comment]
OK... Hard to say what it is. I would suspect a crash when using an OpenGL feature, but it could be something else (e.g., in Qt).

To be sure that it does not come from the tree view, could you try `plot3dSceneWindow.py` with  this patch:

```examples/plot3dSceneWindow.py
@@ -50,7 +50,7 @@ import sys
 import numpy
 
 from silx.gui import qt
-from silx.gui.plot3d.SceneWindow import SceneWindow, items
+from silx.gui.plot3d.SceneWidget import SceneWidget, items
 
 SIZE = 1024
 
@@ -58,10 +58,10 @@ SIZE = 1024
 qapp = qt.QApplication.instance() or qt.QApplication([])
 
 # Create a SceneWindow widget
-window = SceneWindow()
+# window = SceneWindow()
 
 # Get the SceneWidget contained in the window and set its colors
-sceneWidget = window.getSceneWidget()
+sceneWidget = SceneWidget() #  window.getSceneWidget()
 sceneWidget.setBackgroundColor((0.8, 0.8, 0.8, 1.))
 sceneWidget.setForegroundColor((1., 1., 1., 1.))
 sceneWidget.setTextColor((0.1, 0.1, 0.1, 1.))
@@ -194,7 +194,7 @@ cutPlane.moveToCenter()  # Place the cut plane at the center of the volume
 sceneWidget.addItem(group)  # Add the group as an item of the scene
 
 # Show the SceneWidget widget
-window.show()
+sceneWidget.show()
```

You could also try with commenting the cut plane:
```
cutPlane = volume.getCutPlanes()[0]  # Get the volume's cut plane
cutPlane.setVisible(True)  # Set it to be visible
cutPlane.getColormap().setName('jet')  # Set cut plane's colormap
cutPlane.setNormal((0., 0., 1.))  # Set cut plane's normal
cutPlane.moveToCenter()  # Place the cut plane at the center of the volume
```
... and other elements in the example to see which one makes things break.

**Comment by alexbjorling** [comment]
The first patch does not change the behaviour, still get this:

```
$ python plot3dSceneWindow.py 
free(): invalid next size (fast)
Aborted (core dumped)
```

**Comment by alexbjorling** [comment]
Regarding what to comment out, there's such a lot. The first (RGBa) image works. The second image only works if I make it RGB and convert to float.
```
@@ -82,9 +82,9 @@ imageRgba.setRotationCenter('center', 'center', 0.)
 imageRgba.setRotation(45., axis=(0., 0., 1.))
 imageRgba.setScale(0.7, 0.7, 0.7)  # Scale down image
 
-
 # Add a data image
-data = numpy.arange(SIZE ** 2).reshape(SIZE, SIZE)  # Dummy data
+data = numpy.arange(SIZE ** 2).reshape(SIZE, SIZE, 1)  # Dummy data
+data = numpy.tile(data, (1, 1, 3)).astype(float)
 imageData = sceneWidget.addImage(data)  # Add ImageData item to the scene
 
 # Set imageData transform
@@ -94,7 +94,6 @@ imageData.setTranslation(0., SIZE, 0.)  # Translate the image
```

Then, `add2DScatter` segfaults.

**Comment by t20100** [comment]
Common feature of what seems to fail is the use of a colormap.
To narrow the test, here is a code that access directly the inner rendering:

```
from PyQt5 import QtCore, QtWidgets
from OpenGL.GL import *
from silx.gui import _glutils as glu
from silx.gui.plot3d import scene
from silx.gui.plot3d.scene import function, primitives
import numpy


data = numpy.array(((0, 2.5), (7.5, 10)), dtype=numpy.float32)
rgb = numpy.array((
    ((0, 0, 0), (0, 1, 0)),
    ((0, 0, 1), (1, 1, 1))), dtype=numpy.float32)


class Test(glu.OpenGLWidget):

    def __init__(self):
        super().__init__(
            None,
            alphaBufferSize=8,
            depthBufferSize=0,
            stencilBufferSize=0,
            version=(2, 1))
        self.viewport = scene.Viewport()
        self.viewport.background = 'red'
        if 1: # TOGGLE TO TEST
            # No colormap
            scatter = primitives.ColorPoints((0., 1., 2.), (0., 1., 2.), (0., 0., 0.), size=20., color=(1., 1., 0., 1.))
            image = primitives.ImageRgba(rgb)
        else:
            # With colormap
            scatter = primitives.Points((0., 1., 2.), (0., 1., 2.), (0., 0., 0.), size=20., value=(0., 5., 10.), colormap=function.Colormap(
                colormap=numpy.array(((255, 255, 0), (0, 255, 0), (0, 255, 255)), dtype=numpy.uint8)))
            image = primitives.ImageData(data)

        self.viewport.scene.children = [image, scatter]
        self._window = scene.Window(mode='direct')
        self._window.viewports = [self.viewport]

    def sizeHint(self):
        return QtCore.QSize(400, 300)

    def initializeGL(self):
        pass

    def paintGL(self):
        self.viewport.adjustCameraDepthExtent()
        self._window.render(self.context(), self.getDevicePixelRatio())
        self.viewport.resetCamera()

    def resizeGL(self, width, height):
        width *= self.getDevicePixelRatio()
        height *= self.getDevicePixelRatio()
        self._window.size = width, height
        self.viewport.size = self._window.size


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication([])
    widget = Test()
    widget.show()

    sys.exit(app.exec_())
```

You can toggle the `if 1:` to test scatter and image with and without colormap.
I would hope that with `if 1:` it works but with `if 0:` it fails... If so, keeping the `if 0:`, could you try to change this line:
`self.viewport.scene.children = [image, scatter]`
with 
`self.viewport.scene.children = [image]`
and 
`self.viewport.scene.children = [scatter]`
I would expect both to fail but that would narrow down to the code handling the colormap.

**Comment by alexbjorling** [comment]
> I would hope that with if 1: it works but with if 0: it fails...

You are absolutely right, that's what happens.

> I would expect both to fail

Yes, both
`self.viewport.scene.children = [image,]`
and
`
self.viewport.scene.children = [scatter,]
`
fail with a core dump.

**Comment by t20100** [comment]
Good, that's narrowing down to the colormap rendering part.
I'll look at the code to see what might go wrong there and prepare a version with some logs to find the issue.

**Comment by t20100** [comment]
Hi,

I prepared a branch of silx https://github.com/t20100/silx/tree/debug-plot3d with some logging in the rendering part of scatter plots with colormap (changes are in `silx/gui/plot3d/scene/function.py` and `silx/gui/plot3d/scene/primitives.py`).
Could you try the previous script with only the scatter plot with colormap with this version of silx? That would hopefully point-out where the segfault occurs.

**Comment by alexbjorling** [comment]
Ok, couldn't work out how to make the logger log anythiing, but replacing by prints I get this output,

```
Cast array to float32
Cast array to float32
Cast array to float32
Cast array to float32
Cast array to float32
Cast array to float32
>>> _Points.renderGL2
_Points.renderGL2: retrieve/create program
_Points.renderGL2: program.use
free(): invalid next size (fast)
Aborted (core dumped)
```

**Comment by t20100** [comment]
OK, that's hopefully in the shader compilation.
I added a few more logs with `print` in the `debug-plot3d` branch (changed file it `silx/gui/_glutils/Program.py`).

**Comment by t20100** [comment]
Could you try again with those new logs?

**Comment by alexbjorling** [comment]
Sure! Here we go.

```
>>> Program.use
Program.use: start compile
>>> Program._compileGL
Program.use: glBindAttribLocation
Program.use: glCreateShader(gl.GL_VERTEX_SHADER)
Program.use: glCreateShader(gl.GL_FRAGMENT_SHADER)
Program.use: glLinkProgram
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by t20100** [comment]
Thanks.
This looks very similar to https://bugs.freedesktop.org/show_bug.cgi?id=110541
In this case, an update of the mesa driver should fix it.

It looks to be related to uniform struct containing a sampler (as for the colormap), I'll make a patch of the shader to see if it is really the case.

**Comment by t20100** [comment]
I added a patch (https://github.com/silx-kit/silx/commit/575c353d2b2b7a0e30a8de96e35c9edf0bb040a6) to `silx/gui/plot3d/scene/function.py` to avoid using uniform struct.
It is worth trying, please let me know how it goes.
I hope it will do the job...

**Comment by alexbjorling** [comment]
The test script above runs with this new patch!
![image](https://user-images.githubusercontent.com/20105820/80204363-01c9b980-8629-11ea-9e95-93298d6b8ec6.png)

**Comment by t20100** [comment]
Good to hear!
That was a hard one to catch!
I'll make a PR with the workaround for this issue.

**Comment by alexbjorling** [comment]
Fantastic, thanks for all the testing.
