### ISSUE TITLE
[plot] Width of the Plot2D widget really big

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2997]
As you can see in the screenshot the smallest size of the Plot2D is much bigger than the Plot1D.

Cause of the statusbar, and the recent add of the image size.

It would be good to improve that
- Position:
    - X/Y could be displayed together
    - It's an image, we know the max size of this and so the max size it can take
    - Could be displayed in integer
- Use elided text
- On pyfai i have created cells which can grow up according to the size needed
- BTW, what about "Size" instead of "Dims"?

![Capture d’écran de 2020-04-08 21-27-19](https://user-images.githubusercontent.com/7579321/78825449-4bd35e00-79e0-11ea-8a53-f2c006c105b6.png)

**Comment by t20100** [comment]
Yes, that would be good to reduce the size of bottom bar to allow reduction.

About `Dims` and `Size`, what about `Shape`? I use `shape` for `(height, width)` and `size` for `(width, height)`, but that's probably just me....

**Comment by vasole** [comment]
The position is not necessarily an integer.

**Comment by vallsv** [comment]
But for images you really care about the location of the mouse between 2 pixels? And do we care about the position outside the image?

**Comment by vasole** [comment]
You are confusing pixels with positions. Your pixel positions (not your pixel indices) can certainly by floating point values. One can have an image 1000x1000 where the x and y dimensions go from 1.5 to 2.5 mm for instance.

**Comment by vallsv** [comment]
I have never used a Plot2D with an origin and a scale, but that's maybe a use case.

**Comment by vasole** [comment]
![image](https://user-images.githubusercontent.com/5636251/78888412-d8723080-7a61-11ea-9b23-2e64df3c65f2.png)

**Comment by vallsv** [comment]
Nice rainbow, it should be displayed with PyMca ;-)

**Comment by t20100** [comment]
Image origin and scale are used (e.g., in NXdata).

**Comment by vasole** [comment]
When looking at the above example, I am a bit puzzled by having "Image with scales" and "image_data" at the title. I would expect one or the other (default or specified by the title dataset) but not both. Bug or feature?

**Comment by vallsv** [comment]
The idea was to be able to print the name of the dataset. It can be tuned.
Maybe prefixed by `Dataset: `?

**Comment by vallsv** [comment]
Oh, i see, you specified the title in the NXdata. In this case, i think we should use it as it was requested, and not edit anything.

**Comment by vasole** [comment]
Exact. I was expecting to get the specified title.
