### ISSUE TITLE
extend dicttoh5 to handle h5 attributes

### ISSUE THREAD

**Issue by linupi** [silx-kit/silx#3005]
How about extending `silx.io.dictdump.dicttoh5` to be able to handle h5 attributes?

Here is a small example:
```python
import h5py
import numpy
 
with h5py.File("myfile.h5",mode='a') as f:
    f.create_group("my_dataset")
    f["my_dataset/x"]=numpy.arange(20)
    f["my_dataset/y"]=numpy.random.rand(20)
    f["my_dataset"].attrs["NX_class"] = "NXdata"
    f["my_dataset"].attrs["signal"] = "y"
    f["my_dataset"].attrs["axes"] = "x
```

generates a file that works well with `silx view` as it displays a default plot. Couldn't  `dicttoh5` be extended to be able to achieve something similar? I imagine something in this direction:

```python
from silx.io.dictdump import dicttoh5

mydataset = {"x":numpy.arange(20),"y":numpy.random.rand(20)}

mydict=dict()
mydict["my_dataset"]=mydataset
mydict["my_dataset@NX_class"]="NXdata"
mydict["my_dataset@signal"]="y"
mydict["my_dataset@axes"]="x"

dicttoh5(mydict,"myfile.h5",mode='a')
```
where `dicttoh5` would e.g. interpret an `@` character in the keys to create the corresponding `attrs`. What do you think?

**Comment by t20100** [comment]
It would be nice to enable writing attributes, but since `@` is a valid character for dataset name, there can be conflicts.

**Comment by t20100** [comment]
One option could be to have interpretation of `@` as an option (e.g., through a `with_attributes=True` argument).
Another could be to provide an `attributesdict` agument separated from the dataset tree, but that's probably cumbersome and error prone.

**Comment by vasole** [comment]
The with_attributes solution is fine with me.
We could even offer a proxy so that the user does not have to specify any keyword and use it as a dict dump.

**Comment by linupi** [comment]
one could also imagine to use tuples as keys to avoid an additional keyword argument. something like 

```python
mydict["my_dataset"]=mydataset
mydict[("my_dataset","NX_class")]="NXdata"
mydict[("my_dataset","signal")]="y"
```

**Comment by vallsv** [comment]
BTW in this case you don't need the parenthesis. And maybe you still could use `@`for readability. But no idea if it already have a meaning in h5py.
```
mydict["my_dataset", "@NX_class"] = "NXdata"
```

**Comment by vallsv** [comment]
Anybody knows the h5py path specification charset? I guess that's ASCII/Unicode like other strings, but i dont know.

**Comment by vasole** [comment]
Given that the usual approach in NeXus to specify attributes is the use group_or_dataset_name@attribute_name, I would aim at implementing the original proposal by providing a **dicttonx** that includes the interpretation of the @ symbol. It does not break anything and who uses it knows what (s)he wants.

**Comment by t20100** [comment]
I find the tuple option pretty neat, it can even be integrated in `dicttoh5` to extend it with breaking the current behaviour.
I would not add a leading `@` character, I checked with `h5py`, `@` is a valid character for both dataset and attribute names.
Attributes is a HDF5 feature, not a NeXus one (even if it is used heavily there).

If using `name@attr_name` is really convenient, it can easily be provided by a helper function on top of that, in the end it is just a `rsplit`.

**Comment by vasole** [comment]
I was not talking about a leading ``@`` character. Since all the NeXus documentation uses that approach it seems natural to use it. Furthermore ``@`` is not recommended as dataset or attribute name by NeXus. Therefore, to have a dicttonx based on that approach should not shock anybody.

**Comment by vasole** [comment]
@t20100 NeXus has been using attributes even before HDF5 existed.

**Comment by t20100** [comment]
@vasole, I would be in favor of extending `dicttoh5` to take tuple to define attributes as a generic feature and add a helper (e.g., `dicttonx`) based on it which splits `name@attr_name` before calling `dicttoh5`.

**Comment by vallsv** [comment]
Yes, i think you talk about providing the same thing in the end. The @t20100 inheritance with helper is a very good idea.

**Comment by vallsv** [comment]
Recreating a new dictionary just for that looks to me overkill. But i don't care much.

**Comment by t20100** [comment]
I don't think duplicating the `dict` would cost a lot as long as the data is not copied, and I doubt it's a place where optimization matters, or you'd better call `h5py` directly.
