### ISSUE TITLE
Silx release 0.13?

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3032]
I would like to know if it is could be possible to create a release of silx before the end of the month?

Is there any expectation?

There was big rework, so i think it would be nice to stabilize a version.

What do you think.

**Comment by vallsv** [comment]
On my side i only expect the profile/roi PR to be merged. It's already a lot of new features i can provide to Flint with.

**Comment by t20100** [comment]
0.13 is on it way, to be expected by the end of June.
