### ISSUE TITLE
Cross profile minor interaction inconsistency

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3039]
I noticed a minor interaction behaviour glitch with the cross profile, each line of the cross is not draggable, but the mouse cursor changes (probably because they are selectable).
It would be best if the lines are draggable (or at least not selectable).

**Comment by mretegan** [comment]
I would have expected all the lines to be draggable is some of them are; the horizontal line is, but not the "free" line and the cross.

**Comment by vallsv** [comment]
Yes, we can't select shapes, like the free line, or rect. Let say it is a ROI/plot issue.

And for the cross it was intentional. I think it is better to enforce to move this the anchor. To reduce the things we can drag on the plot. But we can argue about that.

**Comment by t20100** [comment]
@mretegan, the free line should be draggable from its center.

@vallsv, for the cross, I had the same expectation to drag each line, to me it would be better to be able to drag each line separetely.

**Comment by t20100** [comment]
We can consider making shapes selectable/draggable but not now.

**Comment by vallsv** [comment]
Ok, in this case i will switch them back to movable.

**Comment by t20100** [comment]
Closing, this is fixed in master.
