### ISSUE TITLE
problem with handles on ROIs

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#3043]
I get an error when I try to move a handle / anchor on any type of editable ROI. Tested with circle ROI (#3041) and RetangleRoi.

```
Traceback (most recent call last):
  File "D:\git\silx\build\lib.win-amd64-3.7\silx\gui\plot\items\roi.py", line 590, in __editingStarted
    self._posOrigin = numpy.array(handle.getPosition())
AttributeError: 'NoneType' object has no attribute 'getPosition'
Traceback (most recent call last):
  File "D:\git\silx\build\lib.win-amd64-3.7\silx\gui\plot\items\roi.py", line 605, in __editingFinished
    current = numpy.array(handle.getPosition())
AttributeError: 'NoneType' object has no attribute 'getPosition'
```

The error reminds me of https://github.com/silx-kit/silx/issues/2655#issuecomment-507677306

**Comment by PiRK** [comment]
The result on the plot is that the point moves but the shape is not updated

**Comment by vallsv** [comment]
Hi PiRK, I tested with both PySide and PyQt5 without problem.

**Comment by vallsv** [comment]
The handle come from the sender. Maybe @t20100 have an idea for the bug. But could you try to update PySide2 first?
```
        handle = self.sender()
        self._posOrigin = numpy.array(handle.getPosition())
```

**Comment by vallsv** [comment]
My env was corrupted, so tesed with PySide2, iv got the same exception.
```
In [4]: QtCore.qVersion()                                                                                                             
Out[4]: '5.12.5'

In [5]: PySide2.__version_info__                                                                                                      
Out[5]: (5, 13, 2, '', '')
```

Easy to fix, but i would prefer to use `sender`.

**Comment by vallsv** [comment]
The first commit breaking the ROI interaction is the one introducing the `_HandleBasedROI`., so it is not very helpful.

**Comment by t20100** [comment]
@vallsv issue with inheritance and signals?

**Comment by vallsv** [comment]
I checked it first, removing `_Foo`. But it is not related. But i luckily found a work around.

**Comment by vallsv** [comment]
I have created https://bugreports.qt.io/browse/PYSIDE-1295
