### ISSUE TITLE
Expose the plotting backend

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#3046]
At the moment the backend is a private attribute of the ``PlotWidget`` class. Are there any reasons not to have a getter for it? I think that there are cases where being able to alter it might be useful.

**Comment by vallsv** [comment]
Hi Marius,

The backend is private cause we don't want to maintain it's public API (it can change without warn between 2 versions).

So, there is no problem to use it, but you have to know your code is not safe here.

**Comment by t20100** [comment]
It's fine for me to add a `getBackend` provided that the documentation clearly states that the backend object might change at any moment.

**Comment by vallsv** [comment]
So what is the point to expose it?

**Comment by vasole** [comment]
@mretegan Can the getWidgetHandle method be used for your purposes? It is what people use to access matplotlib directly if there is something missing in silx.

**Comment by t20100** [comment]
@vallsv because there is a couple of people accessing it anyway.

**Comment by vallsv** [comment]
@t20100 yes, but that's there problem.

**Comment by mretegan** [comment]
Thanks a lot for the replies. 

As @t20100 mentioned, this is mostly to do simple things on the Matplotlib backend. 

@vasole ``getWidgetHandle`` does the job in my case, and it seems to only work for the Matplotlib backend which is fine.

**Comment by vallsv** [comment]
What kind of matplotlib things are you doing btw?

**Comment by mretegan** [comment]
I'm using it to put the legend on the canvas.

**Comment by t20100** [comment]
If `getWidgetHandle` is doing the job, can we close this issue then?

**Comment by mretegan** [comment]
Sure, I will close it.
