### ISSUE TITLE
Some requests about the new profile toolbar

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#3047]
If I am not mistaken this part of the library has gone to some major changes recently. Because I do some customization on the plot widget toolbar, I wanted to see how the behavior changed. I use the widget to plot both curves and images. This is a minimal working example to illustrate my points:

```python
import sys
import numpy as np

from silx.gui.qt import QApplication, QMainWindow
from silx.gui.plot import PlotWidget
from silx.gui.plot.Profile import ProfileToolBar, manager


class BasePlotWidget(PlotWidget):
    def __init__(self, parent=None, **kwargs):
        super(BasePlotWidget, self).__init__(parent, **kwargs)


def main():
    app = QApplication([])

    window = QMainWindow()
    widget = BasePlotWidget(parent=window)
    toolBar = ProfileToolBar(plot=widget)
    toolBar.clear()

    profileManager = manager.ProfileManager(parent=widget, plot=widget)
    # profileManager.setItemType(scatter=True)
    # profileManager.setActiveItemTracking(True)

    for action in profileManager.createImageActions(toolBar):
        toolBar.addAction(action)

    cleanAction = profileManager.createClearAction(toolBar)
    toolBar.addAction(cleanAction)
    editorAction = profileManager.createEditorAction(toolBar)
    toolBar.addAction(editorAction)

    # Plot a curve.
    # widget.addToolBar(toolBar)
    # x = np.linspace(-10, 10, 200)
    # widget.addCurve(x, np.sin(x))

    x = np.outer(np.linspace(-10, 10, 200), np.linspace(-10, 5, 150))
    data = np.sin(x) / x
    widget.addImage(data)

    window.setCentralWidget(widget)
    widget.addToolBar(toolBar)
    window.show()

    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
```

Here are a few comments:

1. Before, the actions would only be enabled if there were applicable to things plotted in the widget. For example if I had a 1D curve they would be disabled.
2. In the example above the ``profileWindow`` is not displayed. If I use the default toolbar, it works as expected.
3. Would it be possible to programmatically change/disable the default label of the profile? Now it is "Profile".
4. Is it possible to change the default of the last button to "Compute profile sum"?

**Comment by vallsv** [comment]
Could you please take a screenshot?

I think you could take a look at `silx.gui.plot.tools.profile.toolbar.ToolBar`. This class could take care of the 1 i guess (it have to be done). It was designed for, but it is not yet done. The idea was to provide all in one in this toolbar (it owns the manager) and could be updated according to the selected plot item.

For the 2, i think it is because you have to trig the active item. There is a setter for that `setItemType`. But i suggest you to use `silx.gui.plot.tools.profile.toolbar.ToolBar`.

For the 3, yes. This name is a property part of the ROIs. You can have signal on new ROI creation, and at this time you can set something else, or nothing. The signal is on of the RoiManager which is part of the ProfileManager. But we could expose it (the signal) to the profile manager, it makes sense.

For the 4, you also can do it on your own. This property is also part of the ROIs now. We also could add a default values in the `ProfileManager` API if @t20100  think it is a good idea. But i would prefer not to extend too much the APIs (as it is already available with a different approach).

About the 4, on a side note, the default behavior (on my branch #3048) is to store the last profile properties used by the user in this session and to apply it to the new profiles. So you only have to set it once. Could it be already fine for you?

Maybe it could be easier to talk in #3048 so what i can update few other things that you could test. I expect it to be the last PR. Contact me on our chat if you like, i can help you with the API.

**Comment by mretegan** [comment]
@vallsv Thanks for the reply; I will have a look at the modules you mentioned.

I know that not everyone customizes the toolbars, and most of the time they use the default ones that come with the predefined widgets. However, in case one wants to do such customizations, in my opinion, the API should easily allow selecting specific actions. Personally I don't mind if I have to be verbose and write code for each of the actions individually, as long as I can do it the way I want. Most of the actions are already grouped in `silx.gui.plot.actions`. If **possible** it would be very nice to have them all there. Using the manager to build a toolbar is a bit convoluted. 

It would also be very nice to have the actions enabled only when they can act on the plot and to allow as much customization as possible when they are instantiated (see my comment above about the text displayed alongside the profile).

It is late, I hope I didn't ask for too much in one go 😄

**Comment by vallsv** [comment]
> If possible it would be very nice to have them all there. Using the manager to build a toolbar is a bit convoluted.

That's already the case. The functions returning groups are only helpers. If you look at the code, it uses a public API to create the set of actions.

**Comment by vallsv** [comment]
> actions enabled only when they can act on the plot

I think that's use case specific. In my case the plot contains a huge amount of items. And maybe i want the profile to be created before the image, or what. Flexibility + already defined behavior have a cost.

All the things you have asked are already doable on your side. The question is how much effort we can spend on creating helpers that we don't know if somebody will use it maybe at one point. My answer is none.

**Comment by mretegan** [comment]
> > If possible it would be very nice to have them all there. Using the manager to build a toolbar is a bit convoluted.
> 
> That's already the case. The functions returning groups are only helpers. If you look at the code, it uses a public API to create the set of actions.

This is however different from how the other actions (ZoomModeAction, SaveAction, etc...) are made available. In any case, I think I'll stick to using the profile manager just to be on the safe side.

> > actions enabled only when they can act on the plot
> 
> I think that's use case specific. In my case the plot contains a huge amount of items. And maybe i want the profile to be created before the image, or what. Flexibility + already defined behavior have a cost.
> 
> All the things you have asked are already doable on your side. The question is how much effort we can spend on creating helpers that we don't know if somebody will use it maybe at one point. My answer is none.

Sure I can take care of this at my side, but what I was asking before was that this is different from the previous behavior of the actions.

**Comment by vallsv** [comment]
> hat this is different from the previous behavior of the actions.

I just checked the source cause i was pretty sure it was not the case. In fact it was implemented by disabling the full toolbar. This behavior can be set back on the previous `ProfileToolBar`, but i will only disable the mode actions.

**Comment by mretegan** [comment]
> > hat this is different from the previous behavior of the actions.
> 
> I just checked the source cause i was pretty sure it was not the case. In fact it was implemented by disabling the full toolbar. This behavior can be set back on the previous `ProfileToolBar`, but i will only disable the mode actions.
> 
> Cause if there is still a ROI, it would be good to be able to remove it.

Ok, I see.

Regarding setting the name of the ROI, I've looked at the ROIManager and I could not find the signal you mentioned. Could you please give me a minimal example?

**Comment by vallsv** [comment]
Yes sure, you can take a look at `examples/plotInteractiveImageROI.py`.

But i suggest you to use `sigInteractiveRoiCreated`
```
def configureMyRois(roi):
    roi.setName("I prefer writing more things here")

roiManager = profile.getRoiManager()
roiManager.sigInteractiveRoiCreated.connect(configureMyRois)
```

**Comment by vallsv** [comment]
Image profile ROIs will also provide to you `setProfileMethod`, and `setProfileLineWIdth`, that you also can setup at the same place.

**Comment by vallsv** [comment]
In this case you maybe have to disable `profile._storeProperties = None` cause it will try to do the same. That is what i tried to explain about default behaviors. Let me know it it works without.

**Comment by mretegan** [comment]
> Yes sure, you can take a look at `examples/plotInteractiveImageROI.py`.
> 
> But i suggest you to use `sigInteractiveRoiCreated`
> 
> ```
> def configureMyRois(roi):
>     roi.setName("I prefer writing more things here")
> 
> roiManager = profile.getRoiManager()
> roiManager.sigInteractiveRoiCreated.connect(configureMyRois)
> ```

This worked as expected, and I will use it to configure the ROIs. I will continue the discussion about the 4th point in the #3048.

**Comment by vallsv** [comment]
You can test it btw, i just pushed something to solve that.
