### ISSUE TITLE
ScalarFieldView complex equivalent?

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#3049]
I am trying to display a complex volume as an amplitude isosurface with a phase colormap, as is easily and nicely done with `silx view`. But `ScalarFieldView.setData` explicitly converts to `float32`, so that must be the wrong class to use.

I can see that `SceneWidget.addVolume` has a switch for complex data which is probably what gives `silx view` its `ComplexField3D` volume, but I don\t understand which `QtMainWindow` child I am supposed to use to access this.

**Comment by t20100** [comment]
`ScalarFieldView` does not support complex numbers. It will remains as it is, but it is kind of legacy.

`SceneWindow`/`SceneWidget` provides a more generic 3D view with multiple items including the `ComplexField3D`.
You can check the sample code: https://github.com/silx-kit/silx/blob/master/examples/plot3dSceneWindow.py
but basically it's:
```
window = SceneWindow()
sceneWidget = window.getSceneWidget()
sceneWidget.addVolume(data, copy=False)
```

**Comment by alexbjorling** [comment]
Ah, I was barking up the wrong tree then. Got it, thanks!
