### ISSUE TITLE
rotating the view in script

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#3050]
With no knowledge of the underlying OpenGL workings, how can I programmatiically set the camera angle (by which I mean the orientation normally controlled by dragging the mouse) on a `SceneWidget`?

**Comment by t20100** [comment]
- To move to predefined viewpoint (e.g., top, front, ...), you can use `resetZoom` (http://www.silx.org/doc/silx/latest/modules/gui/plot3d/plot3dwidget.html?highlight=resetzoom#silx.gui.plot3d.Plot3DWidget.Plot3DWidget.resetZoom)

- More control of the camera is not (yet) available in the public API, but you can control the camera by using internal objects:
```
sceneWidget.viewport.camera.extrinsic.setOrientation(direction=(0, 1, 0), up=(1, 0, 0))
# Where direction is the line of sight of the camera and up is the direction pointing upward in the screen plane 
sceneWidget.centerScene()
```

- Finally, you can also change the rotation of the whole scene with: `sceneWidget.getSceneGroup().setRotation(angle=45, axis=(0, 0, 1))`. In this case, it will be displayed and controlled in the `Object parameters` tree through: Data->Transform->Rotation

**Comment by alexbjorling** [comment]
Perfect, thank you!

**Comment by alexbjorling** [comment]
On the same note, I guess the `SceneWidget` is missing axis label setters also. Found this way but it does not look very public...

```
sceneWidget._sceneGroup.setAxesLabels('x', 'y', 'z')
```

**Comment by t20100** [comment]
`_sceneGroup` is actually publicly exposed: `SceneWidget.getSceneGroup()` https://github.com/silx-kit/silx/blob/master/silx/gui/plot3d/SceneWidget.py#L97
