### ISSUE TITLE
error when clearing RegionOfInterestManager after clearing parent plot

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#3065]
If I try to clear a RegionOfInterestManager after clearing its parent plot, I get the folowing error:

```
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages\silx\
gui\plot\tools\roi.py", line 415, in clear
    roi.setParent(None)
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages\silx\
gui\plot\items\roi.py", line 173, in setParent
    self._disconnectFromPlot(previousPlot)
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages\silx\
gui\plot\items\roi.py", line 152, in _disconnectFromPlot
    plot.removeItem(item)
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages\silx\
gui\plot\PlotWidget.py", line 696, in removeItem
    raise ValueError('Item not in the plot')
ValueError: Item not in the plot
```

I’m not sure what the right fix is.

Should the RegionOfInterestManager implicitely delete ROIs when they are cleared from the parent plot, or should we just check that a ROI still belongs to the plot before trying to disconnect it?

**Comment by PiRK** [comment]
Maybe the plot should setParent(None) on it’s items before dropping them?

**Comment by vallsv** [comment]
I feel like, for now, we should not use clear, without clearing the ROIs before.

We have talked many times about it with @t20100. I think it is about ownership of ROIs. And definitely, in my point, a ROI must be owned by the plot. Which is not the case right now.

As result you could use `plot.addItem(roi)`, and then `plot.clear()` became an obvious behavior for the ROIs.

In the mean time there is few alternatives.
1. You can manage it on your own
2. The plot can remove ROIs which own removed plot items (now it is doable without a huge cost, but the implementation will not satisfy me)
3. (as you said) we can check when the roi manager remove the items
4. (as you said) the ROI manager should not remove plot item. (this one is definitely not an good idea)

For now i prefer the first, cause i would like a release soon. Else i can implement the second.

**Comment by vallsv** [comment]
A last one:

5. `clear` could remove everything from the plot, except item from ROIs.

It makes sens if we think that the ROIs do not belong to the plot.

**Comment by PiRK** [comment]
I added a workaround on my side, for now. 

My difficulty is that the plot widget is "far" from the ROI manager, in my application. The plot is in a different window, and can be updated from various signals coming from different screens in the main window. It made sense for me to have the ROI managers for each image be the owners of their respective ROIs, independantly of which image is currently displayed in the PlotWidget.

But I’m OK with changing my architecture in the future if you refactor this.

**Comment by vallsv** [comment]
But in your case, if you clear the plot, do you think you want to ROIs to be removed from there managers? Or all the stuffs of the plot are removed, except the ROIs?

**Comment by PiRK** [comment]
In my previous implementation, I did not want the ROIs to be removed from the manager when clearing the plot. I used to instantiate multiple managers, one for each image of the project, all sharing the same plot.

Luckily, I refactored my code recently, and I changed it to a single ROI manager that gets cleared when the image changes. So now it is OK to remove ROI when clearing the plot, my only problem is how to be sure that the ROI manager gets the "imageChanged" signal before the plot.

In the worst case, I can refrain from using `clear `on the plot, and implement a more precise way of removing all images / image tiles and mask from the plot.

**Comment by vallsv** [comment]
I will take a look then. I think that is consistent with what we should target.
And we will anyway have the problem with the profiles.

**Comment by t20100** [comment]
@PiRK, to delete all images : `PlotWidget.remove(kind='image')`

**Comment by vallsv** [comment]
I created a PR, but this should really be tested, cause i am not fully satisfyed with this implementation.

But i feel like while there is no real groups in the plot, it will stay tricky.

**Comment by t20100** [comment]
@PiRK I just merged PR #3074 which should fix it, could you check that it's working for you?

**Comment by PiRK** [comment]
I need to hurry to fix a few other  problems with silx in my code (non public API changes) to make the master work again, before I can test. I will try to do it today.

**Comment by PiRK** [comment]
In some situations, I lose my current ROIs when the plot is cleared. But that was expected. I will stop using PlotWidget.clear()

**Comment by t20100** [comment]
Yes that's the idea of PR #3074 : if you remove ROI's items from the plot, the ROI is removed.
