### ISSUE TITLE
[silx view] Support for RegionReference

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#3067]
It would be interesting to have support for hdf5 region references (http://docs.h5py.org/en/stable/refs.html) in silx viewer.
Right now any reference is just shown as 'REG'.

One example application would be to choose a region as 'signal' for the display of a NXdata object.

In my case I have a multi-layered (3D) object, displayed as a 2D image, but I want to also show auxiliary_signals which are 2D. The only way I can do this would be by linking the 2D layers and using them as signal.

**Comment by vasole** [comment]
I think (untested) you should be able to achieve what you want using virtual data sets and that would make things work properly for every code.

**Comment by vasole** [comment]
Region reference were more or less "abandoned" in early days of h5py because they were not keeping the shape. By using virtual data sets you can provide the desired target/region shape even if different from the source.

**Comment by vincefn** [comment]
I had looked at VDS, which would indeed do the job, but this was introduced in hdf5 1.10 ? OK, that's already 4 years ago, but some systems e.g. debian8 don't support it so it's a little dangerous to rely on it (though at ESRF 1.10 is back-ported).

Using recent python libraries is ok, since they are easily installable in an environnement, but system libraries are more annoying :-/

Anyway if region references are _de facto_ obsolete let's forget that

**Comment by t20100** [comment]
`h5py` wheels comes with `libhdf5` included (I think 1.10.x currently), so with virtual environments you can use a recent `libhdf5` this way.

**Comment by vincefn** [comment]
Thanks for both your comments - indeed if h5py packs its own libhdf5, I can use VDS.
