### ISSUE TITLE
CI broken with latest version of pyside 5.15.0

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3080]
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/home/travis/.travis/functions: line 109:  4582 Aborted                 (core dumped) python run_tests.py --installed -v --qt-binding=$QT_BINDING

The command "if [ -n "$QT_BINDING" ]; then python run_tests.py --installed -v --qt-binding=$QT_BINDING; else python run_tests.py --installed -v --no-gui; fi" exited with 134.
```

**Comment by t20100** [comment]
Same issue with PyQt5 5.15.0: https://travis-ci.org/github/silx-kit/silx/jobs/693810189

**Comment by t20100** [comment]
I could not reproduce this locally on debian10 for both PyQt5 and PySide2.

**Comment by t20100** [comment]
Might be due to ubuntu16.04 used in CI being too old...

**Comment by vasole** [comment]
You can easily replace dist: xenial by dist: bionic in travis.yml

**Comment by vasole** [comment]
closed by #3086

**Comment by t20100** [comment]
This is not closed PR #386 didn't solved anything on travis.

**Comment by vasole** [comment]
Sorry, I saw "all the test passed" without realizing that only AppVeyor had actually carried out the tests. Travis was not even marked as being on progress. Therefore my "black magic" comment and the approval of the PR. I would not have merged it.

**Comment by t20100** [comment]
No worries, it was needed anyway to move to bionic (minimal requirement of Qt...).
PR #3087 should really fix this issue.... well if CI is happy.
