### ISSUE TITLE
[examples] cryptic dropzone doc

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3100]
![2020-06-05_16-13-08](https://user-images.githubusercontent.com/7264703/83886686-b508f080-a747-11ea-8419-8792eb09fbc9.png)

I know now that a dataset from silx view can be dropped, but what in general?

**Comment by t20100** [comment]
That should support a URI string, but there is nowhere you can find this information.

**Comment by vallsv** [comment]
You can drag and drop the tree items from silx view.

**Comment by t20100** [comment]
closed by PR #3138 on branch 0.13
