### ISSUE TITLE
Use of several GPU

### ISSUE THREAD

**Issue by vedmed85** [silx-kit/silx#3105]
I use PC with 2 GPU. Can i specify wich card i want to use?

**Comment by kif** [comment]
On Sun, 07 Jun 2020 13:53:35 -0700
vedmed85 <notifications@github.com> wrote:

> I use PC with 2 GPU. Can i specify wich card i want to use?

You can use the feature of pyOpenCL which allows you to select one specific device like:
export PYOPENCL_CTX='0:1'

Use `clinfo` to know the ordering of the platforms and devices
