### ISSUE TITLE
[examples] pyqt5 issue on mac sierra

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3109]
```python
python bootstrap.py examples/compositeline.py
```
Set Y-axis in log:

Mac 10.12, python 3.7 (pyqt 5.13.2)

![mac_pyqt5_13_2](https://user-images.githubusercontent.com/7264703/84029483-c0039100-a992-11ea-99f2-555d3b544eba.png)

Windows 10, python 3.8 (pyqt 5.15.0)

![win_pyqt5_15_0](https://user-images.githubusercontent.com/7264703/84029469-b8dc8300-a992-11ea-9c95-dc87a8731d30.png)

**Comment by vallsv** [comment]
THat's athe OpenGL backend. It looks like the 0->NaN in Mac is buggy, and as result a line is anyway displayed.

**Comment by t20100** [comment]
I can't debug it now, I don't have access to a mac.

**Comment by t20100** [comment]
I can't reproduce with Mac 10.12, python 3.7 and pyqt 5.13.2 with current tip of master.

**Comment by woutdenolf** [comment]
Too obscure. I close.
