### ISSUE TITLE
Improving management of changelog

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3141]
It's quite tedious to prepare the changelog for the release and some features are not ideally described.
I see a few ways to improve this:

1. Updating the changelog for each important PR.
2. Writing a "news fragment" file for each PR and using a tool to concatenate them (e.g., https://regro.github.io/rever-docs/, https://github.com/twisted/towncrier as numpy) as other projects do (e.g., h5py, numpy). 
3. Adding a PR template which advertise adding a `# changelog` section in the PR description. Then for the release we can extract those to build the final changelog.

- We wanted to do `1.` but it never happened.
- `2.` basically adds one file per PR and you still need to think about doing it or while reviewing it... or add a CI service to check it (e.g., https://github.com/pypa/browntruck)
- `3.` seems to me the simplest way both when making PR and to generate the changelog for the release (and it's easy to set up).

What do you think?

**Comment by t20100** [comment]
PR #3142 enables option `3.`

**Comment by vallsv** [comment]
I guess that's a constrain for the person who merge a PR. But i don't think there is an easy way to update the changelog in this case. Maybe for coming release there will be less contribution anyway?

**Comment by t20100** [comment]
With proposition in PR #3142, that would be more a "constraint" (writing a meaningful PR title + optionally a changelog) on the person who proposes the PR. And if you don't put anything, it does not show up in the changelog summary...

**Comment by vallsv** [comment]
Oh ok, i see. That's smart proposal.

**Comment by vallsv** [comment]
We also found that with Matias: https://github.com/github-changelog-generator/github-changelog-generator

**Comment by t20100** [comment]
Looks to be the same idea, they use PR/issue titles and also the leverage the tags to sort PRs into sections.
Starting point is the same: you need to consider the PR title as an entry in the changelog.

Personally, I don't mind a bit of manual editing of the changelog to do the sorting.
