### ISSUE TITLE
[ci] Travis-CI result no longer showing in github

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3146]
For whatever reason, travis-ci tests are run but they are no longer reported in github PRs...

**Comment by kif** [comment]
On Wed, 01 Jul 2020 04:03:30 -0700
Thomas VINCENT <notifications@github.com> wrote:

> For whatever reason, travis-ci tests are run but they are no longer reported in github PRs...
Same on pyFAI since last week.

**Comment by t20100** [comment]
Closing, looks to be fixed: see #3147
