### ISSUE TITLE
cythonization failure

### ISSUE THREAD

**Issue by tacaswell** [silx-kit/silx#3161]
I am seeing cythonizing issues with the current master branch of cython and cpython (the full error is below) the crux of issue is

```
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            output = compute_cmap_with_lut(
                data, colors, normalized_vmin, normalized_vmax,
                nan_color, scale_func)
    
        elif data_types in default_types:  # Use default implementation
            output = compute_cmap(
           ^
    ------------------------------------------------------------
    
    silx/math/colormap.pyx:322:8: Invalid use of fused types, type cannot be specialized
    
```

I suspect that this is cython getting stricter.

There are also a number of

```
    /home/tcaswell/.virtualenvs/bleeding/lib/python3.10/site-packages/Cython/Compiler/Main.py:344: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-req-build-0zqurbxg/silx/image/shapes.pyx
```

which you can silenced by setting details in setup.py

Full log: [notes.txt](https://github.com/silx-kit/silx/files/4950748/notes.txt)

**Comment by t20100** [comment]
Thanks for the catch, we run CI with pre-releases but do not test with the tip of projects.

As for the `FutureWarning` it should be fixed on master and in 0.13.0 release, from the line number in the log you are using an older version of `silx`.

**Comment by tacaswell** [comment]
:facepalm: my local checkout was tracking a very old branch, sorry about that!

I can confirm that with the branch in #3164 it is compiling again, thank you for the quick turn around.

**Comment by t20100** [comment]
Good to hear!
We were about to make a bug fix release, so better to fix it beforehand.
