### ISSUE TITLE
[silx view] The right panel can be hidden for users

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3169]
The right panel can be hidden (drag the panel and hide it on the side).

The layout configuration is saved.

As result, the next user can be surprised not to found the right panel. And reach it back is kind of magic.

Feed back from scientists.

Proposal: Add an option in the `Window` menu to hide and show the right panel using the same layout feature used to hide it with the mouse. So what it became obvious to hide/show the right panel.

**Comment by vallsv** [comment]
This feature could also just be disabled.

That's a layout property, AFAIR.

**Comment by t20100** [comment]
If we decide not to disable it, can't the right panel be shown at application restart no matter of the saved layout?

**Comment by vasole** [comment]
In PyMca I have the option -f to start fresh and bypass any saved configuration. Among other things, it solves saved layout issues.

**Comment by t20100** [comment]
There is a similar `--fresh` in silx view which does the job (though it is not in the doc).

**Comment by vasole** [comment]
Pity the shortcut -f was not kept for silx view. People got used to -f because it was what they had to type to start SPEC from fresh (spec -f).

BTW, I find too verbose the qualifier to start silx view with the OpenGL backend.

**Comment by vallsv** [comment]
The problem here is not the command line arguments but the feedback provided to the user

**Comment by vasole** [comment]
That has already been solved by #3173. 

I found appropriate to discuss here. As a former user of ESRF software I would have expected to have the shortcut -f.

**Comment by t20100** [comment]
It should be pretty easy to add the `-f` along with `--fresh`.

Still, not having the browser at start-up is disturbing (especially with hdf5 files...). I remind starting looking for a bug when I first encounter it. Also `silx view` can be started from an icon.
So to me this needs to be tackled + it's users feedback.
