### ISSUE TITLE
[plot] Middle-click panning is not used for roi edition

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3178]
It would be good to be consistent with this behaviour

**Comment by vallsv** [comment]
The problem is with `select-draw` when creating a new ROI. Except for points, cause it uses `select` instead.

**Comment by vallsv** [comment]
Sounds like `FocusManager` do not dispatch events on something else than left click.

As result `ItemsInteractionForCombo(ItemsInteraction)` which is implemented by `DrawSelectMode`, never receive the middle click while it could manage it.

**Comment by vallsv** [comment]
Could it be possible to find a solution for it?

Anyway it is not done in the proper way, i guess this should not be so difficult? Is it? (i did not check it again)

**Comment by t20100** [comment]
I remind spending a bit of time on it without a clean solution, I'll check it again.
