### ISSUE TITLE
Can not start silx view 

### ISSUE THREAD

**Issue by mjjank** [silx-kit/silx#3181]
We can not start silx view.

(bliss_dev) max:~ % silx view
/users/blissadm/conda/miniconda/envs/bliss_dev/lib/python3.7/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping

**Comment by vallsv** [comment]
I tried it from `max` on your `bliss_dev` env. Everything is working.
I suspect `silx view` is displayed somewhere on one of your screen, hidden by some stuffs.

In case, you can use `silx view --fresh` to reset all the local configuration. As result the location of the window will be set by the window manager. But you will lose all your user preferences.

**Comment by t20100** [comment]
The warning will be fixed in next version (see #3145).
Let us know if the `--fresh` didn't fixed the issue.

**Comment by t20100** [comment]
I'm closing it expecting it to be fixed, please reopen if needed.
