### ISSUE TITLE
[roi] setColor do not update the plot

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3191]
Sounds like from my test that the `setColor` from ROI object do not trigger a repaint of the plot.

As result the ROI color is updated at the next plot refresh, like a zoom in/out.

**Comment by vallsv** [comment]
The refresh color is in fact not applied if the ROI is actually selected. If it is not, the color looks to be fine.

**Comment by t20100** [comment]
To reproduce:
```python
from silx import sx
from silx.gui.plot.tools import roi
from silx.gui.plot.items import roi as roi_items

w = sx.plot()
m = roi.RegionOfInterestManager(w)
rect = roi_items.RectangleROI()
rect.setOrigin((10, 10))
rect.setSize((10, 10))
m.addRoi(rect)
m.setCurrentRoi(rect)
rect.setColor('blue')
```
