### ISSUE TITLE
Plot: AssertionError: Integer value or tickstep is 0

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3192]
I found that on a beamline.

No idea how to reproduce it.

No idea if it is from an image or a curve widget...

Maybe you have some more ideas.

![Screenshot from 2020-09-21 11-42-37](https://user-images.githubusercontent.com/7579321/93755330-60f51f80-fc03-11ea-97af-a99048afa12a.png)

**Comment by t20100** [comment]
It's with datetime axis, so it should be with curves.

The issue is with time range (x axis) smaller than 2.5 microseconds..

I managed to reproduce with this script:
```python
from silx import sx
from silx.gui.plot import TickMode

w = sx.PlotWidget()
w.getXAxis().setTickMode(TickMode.TIME_SERIES)
#w.addCurve((0, 1, 2), (0, 1, 2))
w.addCurve((0, 1e-6, 2e-6), (0, 1, 2))

w.show()

sx.qt.QApplication.instance().exec_()
```
