### ISSUE TITLE
Colormap dialog: Very small histogram in OpenGL

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3193]
Hi,

No idea if it is an issue, but i feel like if silx is setup to use OpenGL, the colormap dialog then provide a very small histogram which is not convenient to use. Or which could be improved.

Do you think there is easy way to optimize the space here?

Maybe disabling OpenGL for this specific plot?

![Screenshot from 2020-09-21 11-46-11](https://user-images.githubusercontent.com/7579321/93755749-1d4ee580-fc04-11ea-9166-c237c6a57bd8.png)

**Comment by t20100** [comment]
Plot margins with the OpenGL backend are set as a fixed number of pixels, while it is a percentage of available space in matplotlib.

Related issues: #2681 with sample code on how to set margins through the private API... It shouldn't be a big deal to add an API for that.

Using matplotlib for this plot sounds an easy fix and there is no need for some OpenGL rendering here.
