### ISSUE TITLE
Icons behavior

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#32]
- I expect an icon to reflect the action is going to apply and not the current status. To me the shown icons when toggling Y axis origin and when toggling aspect ratio are the wrong ones.

**Comment by t20100** [comment]
No strong opinion on this.
I did it statefull because it controls a bool state underneath (as for autoscale and log scale), but I'm fine with that too.

**Comment by vasole** [comment]
#35 closes this issue.
