### ISSUE TITLE
extend dicttoh5 to handle links

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3213]
In analogy to what we did for attributes (#3005) I need a syntax to specify links for dicttoh5 and h5todict. For example when doing data processing we often want to do this:

```python
{
    "@NX_class": "NXroot",
    "1.1": {
        "@NX_class": "NXentry",
        "instrument": {
            "@NX_class": "NXinstrument",
            "fx8_det0": {"@NX_class": "NXdetector", "data": [0, 1, 2, 3]},
        },
        "my_calc": {
            "@NX_class": "NXprocess",
            "configuration": {
                "@NX_class": "NXcollection",
                ">y": "../instrument/fx8_det0/data",  # SYNTAX FOR LINK
            },
        },
    },
}
```

So attributes start with "@" and links start with ">"? The library would automatically handle relative links and soft vs. external. For example `"scans/test.h5::/1.1/instrument/fx8_det0/data"` would be a relative external link and `"/1.1/instrument/fx8_det0/data"` would be an absolute softlink.

Before spending time on the implementation I'd like to know whether this idea finds enough support and what the appropriate syntax could be. For example `">linkname"` or `"linkname>"`.

**Comment by t20100** [comment]
I'd also be for a 2 levels approach as in #3005, #3013, i.e.:
- having `dictonx` supporting interpretation of keys as you propose.
- having `dicttoh5` supporting `h5py.ExternalLink` and `h5py.SoftLink` as keys, thus still allowing any names to be used.

As for the syntax, I'd be for ">" as a prefix for consistency with "@".

**Comment by woutdenolf** [comment]
> having `dicttoh5` supporting `h5py.ExternalLink` and `h5py.SoftLink` as keys

You mean that the key can be a tuple and the second element can be either a `str` (attribute) or a `SoftLink`/`ExternalLink` (link)?

For the `h5todict` we probably want the option `preserve_links=False` so that we don't break the default behavior.

**Comment by t20100** [comment]
Yes, I wanted to say the value, not key, sorry. It doesn't make sense otherwise.
