### ISSUE TITLE
Mask convention: 0 or 1 for masked value

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3217]
Not sure we can do anything in silx, but I still open it for discussion.
Apparently bliss is using the opposite convention that is used in silx regarding masks.
This forces users to invert the silx mask to be used.

**Comment by kif** [comment]
numpy.logical_not is their friend then. We can need multiple|overlapping masks

**Comment by vallsv** [comment]
That's about GUI and file. In fact people dont know anything about the way it is stored, nor read.

And Lima uses the reverse of silx.

Is that normalized in Nexus?

**Comment by vallsv** [comment]
BTW, thinking out loud, as it's about EDF mask, we could write the way the mask have to be read in the header.

So what Lima could read silx files properly.
I can take care of it.

What do you think?

**Comment by vasole** [comment]
If an array denotes a mask, typically 0 is not masked and any other value allows to specify different levels of masks.

**Comment by vasole** [comment]
If 0 is masked, then you are not in a good situation.

**Comment by vasole** [comment]
Are you confusing mask with pixel_mask_applied?

https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector

**Comment by vasole** [comment]
To me is crystal clear that 0 is a non-masked value. Dectris is following NeXus too. That should settle the question.

**Comment by vallsv** [comment]
I let you close it if you think #3310 is enough.

**Comment by vallsv** [comment]
Here is a MR on Lima to be able to properly read silx 0.14 masks without doing anything more: https://gitlab.esrf.fr/limagroup/Lima-tango-python/-/merge_requests/58

**Comment by t20100** [comment]
closed by PR #3310 on branch 0.14
