### ISSUE TITLE
dicttoh5: properly define update/overwrite behavior

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3226]
There are several inconsistencies in the overwrite behavior of `dicttoh5`. For example this one:

```python
from pprint import pprint
from silx.io import dictdump

ddict = {"group1": {"data1": 1}, "group1@attr": "attr"}
dictdump.dicttoh5(ddict, "test.h5", overwrite_data=True, mode="w")
pprint(dictdump.h5todict("test.h5"))

ddict = {"group1": {"data2": 2}}
dictdump.dicttoh5(ddict, "test.h5", overwrite_data=True, mode="a")
pprint(dictdump.h5todict("test.h5"))  # group1 has attr, data1 and data2

ddict = {"group1": {}}
dictdump.dicttoh5(ddict, "test.h5", overwrite_data=True, mode="a")
pprint(dictdump.h5todict("test.h5"))  # group1 has only attr
```

These inconsistencies need to be solved and the `overwrite_data` behavior needs to be clearly defined. In addition I need a way to "update" an existing HDF5 file.

For both issues I propose these three dump modes:
   * __overwrite__ (existing things may be overwritten): the HDF5 tree is **exactly** the dict tree
   * __update__ (existing things may be overwritten): the dict tree is a **subtree** of the HDF5 tree
   * __add__ (existing things are untouched): nodes from the dict tree are added to the HDF5 tree when the existing structure allows it

As for the existing `overwrite_data`: unfortunately it behaves sometimes like __overwrite__ and sometimes like __update__. As this behavior is confusing I don't think we need to preserve it.

@vasole @t20100 @vallsv Comments?

**Comment by vasole** [comment]
No problem with me.

**Comment by t20100** [comment]
If I understand well, the inconsistency is the difference between empty groups in the `dict` which are **overwritten** while groups that are not empty are **updated**.

From the doc and the `overwrite_data` arg name, I would expect that it **updates** the structure.
I would consider this as a bug and have no problem changing the behavior to **update** even for empty groups.

Else, your modes sounds good to me.

**Comment by woutdenolf** [comment]
Correct. There are other inconsistencies which I didn't show (e.g. nodes that change type). These things are a consequence of the fact that `overwrite_data` is not well defined (it also lacks tests).

I'll make a PR with what I suggested. I guess I'll deprecate the `overwrite_data` argument and have `True` work like __update__ and `False` like __add__. Then I'll add a new argument `existing=None` with `"add"` as default (the other options are `"overwrite"` and `"update"`).
