### ISSUE TITLE
Issue with running tests in a fresh virtualenv on ubuntu20.04

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3228]
With python3.8 on ubuntu20.04 and up-to-date dependancies, the following error occurs when running the tests:

```python
======================================================================
ERROR: testSynchonized (silx.gui.hdf5.test.test_hdf5.TestHdf5TreeModelSignals)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/test/test_hdf5.py", line 440, in testSynchonized
    self.model.synchronizeH5pyObject(self.h5)
  File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/Hdf5TreeModel.py", line 613, in synchronizeH5pyObject
    self.synchronizeIndex(qindex)
  File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/Hdf5TreeModel.py", line 591, in synchronizeIndex
    self.insertFileAsync(filename, index.row(), synchronizingNode=node)
  File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/Hdf5TreeModel.py", line 679, in insertFileAsync
    qt.silxGlobalThreadPool().start(runnable)
RuntimeError: wrapped C/C++ object of type QThreadPool has been deleted
```

 First mentioned in  #3225 by @woutdenolf

**Comment by t20100** [comment]
Doing a bit of digging, it occurs only if one or many of those 3 tests are run first:
- `TestHdf5TreeModel.testInsertFilenameAsync`
- `TestHdf5TreeModel.testSynchronizeObject`
- `TestHdf5TreeModel.testDropExternalFile`

**Comment by t20100** [comment]
Tests pass when using `qt.QThreadPool.globalInstance()`...

**Comment by t20100** [comment]
Also, avoiding deleting the QApplication instance [here](https://github.com/silx-kit/silx/blob/master/silx/gui/utils/testutils.py#L146) in TestCaseQt makes it works.

**Comment by vasole** [comment]
Unless you have patched matplotlib, it is not convenient to do such things. Matplotlib keeps a hard reference to the QApplication and not a weakref. Crashes on exit can arrive.

You could try to set ``matplotlib.backends.backend_qt5.qApp = None `` prior to doing ``cls._qapp = None`` to see if it helps.

My PR was not accepted in any of its forms.

https://github.com/matplotlib/matplotlib/pull/14179

**Comment by t20100** [comment]
Related to PR #2593 and issue #2592
