### ISSUE TITLE
Grid not showing for 2D data

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#3233]
As the title says, the grid is not visible for images. I've tested this using the `plotWidget.py` from the examples folder after adding the grid action.

```python
gridAction = actions.control.GridAction(parent=self, plot=self._plot)
toolBar.addAction(gridAction)
```

**Comment by vallsv** [comment]
Grids are under the image, but i think it is displayed. At least in Flint it is displayed.

**Comment by mretegan** [comment]
That's what I thought, but I think it makes more sense to have them above the image.

**Comment by t20100** [comment]
It was the case until silx 0.11.0 and it was changed in 0.12.0.
This regression is a side effect of "Improved and fixed PlotWidget and backends rendering and picking to guarantee rendering order of items" (see https://github.com/silx-kit/silx/releases/tag/v0.12.0) which played with matplotlib's item "z order".

I can have a look at it.
BTW, the OpenGL backend was already displaying the grid below everything, I'm not going to change that for now.
