### ISSUE TITLE
Requesting a minimum version of h5py

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3246]
I propose to set a minimum version of `h5py` required for silx, and to use that of debian 9 as a baseline, i.e., 2.7.0 (https://packages.debian.org/stretch/python3-h5py).

To me it is conservative enough since debian dropped support this summer except for LTS arch (https://www.debian.org/releases/stretch/index.html).

**Comment by woutdenolf** [comment]
Not urgent. The failure on Debian9 was already solved by #3251

**Comment by t20100** [comment]
OK, let's close it then.
