### ISSUE TITLE
[question] Stackview with several scatter plot

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/silx#3249]
Hello,

I am trying to use a Stackview widget, and I want to put a stack of scatter plot in it.

The issue is that we need to put numpy.ndarray or hdf5 dataset in the stack of the stackview widget, and I have three arrays for X, Y, and Intensity for one plot. 

I was guessing, is it possible to plot one scattered image in each view of the stack. And if it is possible, how to declare a stack size without giving images to the function ?

Moreover, I want to update the stack during runtime (to run the computation of the scattered images in background), so is it possible to refresh the stack while the widget is being used or not ?

Sorry, I might have missed some information in the silx documentation.

Alexandre Marie

**Comment by vallsv** [comment]
Hi,

I guess you better to create your own widget `ScatterStackView`? I don't think it was designed for incrementally add new data, and i think it is really specific to images.

It should not be a huge work. It is basically a combination of `ScatterView` and a `QSlider`. I suggest you to do it by composition.

**Comment by alexmarie78** [comment]
That is what I am trying to do, thanks for the suggestions !

**Comment by t20100** [comment]
Yes, `StackView` is dedicated for static stack of images.

**Comment by alexmarie78** [comment]
Hello again, thanks for your answers.

One last question, is this normal that, when we use StackView.setStack(), it clears the graph title, labels, and colormap, when they are already initialized ? 
Shall I set colormap, title, and labels AFTER setting the stack or not ?

**Comment by t20100** [comment]
Did you used `StackView.setGraphTitle`, and `StackView.setGraph[X|Y]Label`?

It seems there is an inconsistency in the `StackView`:
- On one side, [`StackView.setGraphTitle`](http://www.silx.org/doc/silx/latest/modules/gui/plot/stackview.html#silx.gui.plot.StackView.StackView.setGraphTitle), and `StackView.setGraph[X|Y]Label` directly set the title and labels of the plot, but
- On the other side: [`StackView.setLabels`](http://www.silx.org/doc/silx/latest/modules/gui/plot/stackview.html#silx.gui.plot.StackView.StackView.setLabels), [`StackView.setTitleCallback`](http://www.silx.org/doc/silx/latest/modules/gui/plot/stackview.html#silx.gui.plot.StackView.StackView.setTitleCallback) allows to control the title and labels... and this mechanism must override what you set.

It seems to me the `StackView.setGraphTitle`, and `StackView.setGraph[X|Y]Label` should be deprecated/removed here, and only `StackView.setLabels` and `StackView.setTitleCallback` should remain.
Any other opinion?

**Comment by t20100** [comment]
@alexmarie78, would that fix your issue to use `StackView.setLabels` and `StackView.setTitleCallback` ?

**Comment by alexmarie78** [comment]
> @alexmarie78, would that fix your issue to use `StackView.setLabels` and `StackView.setTitleCallback` ?

Yes that definitely did the job for labels and title, thanks a lot.

Still there is an issue on the colormap. When the stackview is initialized, I set the colormap with StackView.setColormap. Then when I use StackView.setStack(), the colormap is reseted to grey scale I think or the default one

**Comment by t20100** [comment]
From what I tested (with current master), I could not reproduce the colormap problem:
```python
import numpy
from silx import sx

w = sx.StackView()
w.show()
w.setColormap('viridis')
w.getColormap()                                                        
#Out[12]: <silx.gui.colors.Colormap at 0x12e076318>

w.setStack(numpy.arange(10**3).reshape(10, 10, 10))
w.getColormap()                                                        
#Out[14]: <silx.gui.colors.Colormap at 0x12e076318>
```

Do you have a sample code to reproduce?

**Comment by t20100** [comment]
BTW, there are some issues with colormap handling in the `StackView` (#2835)

**Comment by alexmarie78** [comment]
def __init__(self, parent):
        super().__init__(parent=parent, aspectRatio=True, yinverted=True)
        self.setColormap("viridis", autoscale=True, normalization='log')

Then I need to re-set colormap, just after setting the stack, because otherwise it is shown in black and white or greyscale:

 self.setStack(images)
 self.setColormap("viridis", autoscale=True, normalization='log')

**Comment by vallsv** [comment]
It was new cause it is part of the our `DataView` code: https://github.com/silx-kit/silx/blob/master/silx/gui/data/DataViews.py#L1271. Maybe it is too tricky to change?

**Comment by t20100** [comment]
Sorry, but I still can't reproduce your problem with current master.
This keeps the viridis colormap:

```python
import numpy
from silx import sx

class A(sx.StackView): 
    def __init__(self, parent): 
        super().__init__(parent=parent, aspectRatio=True, yinverted=True)
        self.setColormap("viridis", autoscale=True, normalization='log')

a = A()
a.setStack(numpy.arange(10**3).reshape(10, 10, 10)) 
```

Could you provide a full small example where it happens?
BTW, which version of silx do you use?

**Comment by alexmarie78** [comment]
I am using 0.11.0 verison of silx.
I think it comes from the version because I am using it exactly the way you are using it. I can't give you more than I did, because it is all I do to reproduce the error

**Comment by vallsv** [comment]
Is there any reason non to use silx 0.13 instead?

**Comment by alexmarie78** [comment]
There is no big reason. The device is not a personal computer, thus I don't have rights to update on my own packages.
Still, this little issue will be over when silx will be updated on my device.

Finally I can let the second "self.setColormap()" until then.

Thanks for helping !

**Comment by vallsv** [comment]
Yes sure, the thing is you could have other problems which was already been fixed.
