### ISSUE TITLE
[Hdf5Widget] Hdf5TreeModel::index : "parent" as a keyword.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#325]
The index method signature in Hdf5TreeModel is not the same as in its base class (QAbstractItemModel) : in the latter "parent" is a keyword, and the index returned is relative to the root item when omitted.

**Comment by vallsv** [comment]
Here is a patch. Let me know if it is enough https://github.com/silx-kit/silx/pull/328
