### ISSUE TITLE
Combining mask and profile in widgets/silx view

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3263]
Allowing to use current mask to compute profile.

Similar to #3124 but for profile.

Regarding how to connect mask tool to profile, any better idea than what I proposed in #3124, i.e., using:
```
def setSelectionMaskSource(self, source):
        """Set the source of the selection mask.

        :param source:
            QObject with sigMaskChanged signal and getSelectionMask method.
        """
```

An alternative I see is to attach the mask to the image at the item level, that might be more generic since it does not rely on the mask tool.

**Comment by kif** [comment]
The mask tool would be OK to me.

Needed for ID17

**Comment by vasole** [comment]
If the NeXus convention is respected, you should get the mask information together with the detector data.

**Comment by t20100** [comment]
I didn't even though of NeXus for pre-loading the mask...

**Comment by t20100** [comment]
The item-level way is probably best for supporting more than the mask tool... but it requires more internal rework.

**Comment by vasole** [comment]
> I didn't even though of NeXus for pre-loading the mask...

At a certain moment one has to profit from the information contained in the file.

One cannot ask the user to specify uncertainties, masks, calibrations, pixels sizes, motors, ... They should be read from the file if available.

**Comment by t20100** [comment]
`They should be read from the file if available.`

I completely agree but apparently so far people are asking for authoring masks or loading masks saved independently.

**Comment by vasole** [comment]
But that is already handled by the mask tool, isn't it?

**Comment by t20100** [comment]
I don't think so.

The mask tool in itself has nothing to do with NeXus, and I don't know if `silx view` is loading the mask (I would say no).
Anyway, if we're supporting the Nexus mask, we might not want users to edit it.

**Comment by vasole** [comment]
?????

The mask tool has nothing to do with NeXus, therefore should be able to load and to save masks.

Where is the problem?

**Comment by vasole** [comment]
What I am saying is:

- That you can take a lot of information directly from the file.

- That for the cases where the mask is not in the file, it can be read or saved by the mask tool itself.

**Comment by t20100** [comment]
Yes, I agree, but from a quick search there is no Nexus mask support in silx, so you first point is not implemented.
The second one is there since the beginning.

**Comment by kif** [comment]
Well, files generated by Lima are not really Nexus compliant. The mask is still given by a dummy value (4e9) which turns out to be more annoying than having the dummy at "-1".
One could argue the issue may be addressed by Nexus, the NexusWriter, ... but ID17 won't switch to Bliss in a foreseeable future, hence I am locked with LImA files.
