### ISSUE TITLE
Move back AdaptiveDecimalStepType to ColormapDIalog

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3264]
Reminder to move back `AdaptiveDecimalStepType` if availabe.

This really improve the gamma usability, cause this value is not linear.

https://github.com/silx-kit/silx/commit/015987a490e8ca7b78a521e49b398ed096e8caaf#diff-30fb5acf588a2358db61fc35834c51171e159bab43e2dcc75b2799375bed8122

**Comment by t20100** [comment]
Then let's check Qt version/`setStepType` availability.

**Comment by t20100** [comment]
This is already the case:
https://github.com/silx-kit/silx/blob/master/silx/gui/dialog/ColormapDialog.py#L876-L880

It was restored in #3133.

I'm closing, reopen if I missed something.

**Comment by vallsv** [comment]
Oh, nice, too fast for me.

**Comment by t20100** [comment]
You did it, apparently you are too fast for yourself ;)
