### ISSUE TITLE
Issue with DataUrl as string if provides `slice` with start and stop

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#3265]
the following url is find invalid: `url = DataUrl(path='silx:///data/visitor/ls2914/id19/set40_tomo_black_drum_LPJ21_6p5mu_unload/set40_tomo_black_drum_LPJ21_6p5mu_unload_0001/set40_tomo_black_drum_LPJ21_6p5mu_unload_0001_0000.nx?path=/entry0000/instrument/detector/data&slice=2000:2021')`

**Comment by vallsv** [comment]
What it designed for a range? I don't remember.

**Comment by vallsv** [comment]
Oh that's a feature request then

**Comment by payno** [comment]
In fact I thought it was already handled.
