### ISSUE TITLE
Hight cpu load when using Colormap.applyToData on a single value

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3268]
I am using this small code on a custom image item to display color of the hovered pixel value.

It uses a hi CPU load, maybe cause of OpenMP, but i only have a single value to convert.

Do you have any idea if this could be speeded up in this case?

Or maybe i could maybe do it on my own?

```
    def _getColoredChar(self, value):
        colormap = self.getColormap()
        data = numpy.array([float(value)])
        colors = colormap.applyToData(data, reference=self)
        cssColor = f"#{colors[0,0]:02X}{colors[0,1]:02X}{colors[0,2]:02X}"
        char = "■"
        return f"""<font color="{cssColor}">{char}</font>"""
```

**Comment by t20100** [comment]
The colormap computation (https://github.com/silx-kit/silx/blob/master/silx/math/colormap.pyx) was clearly not written with single value conversion in mind.

OpenMP might be an issue indeed.
Also, for (u)int8|16, you even end-up computing the LUT with 256 or 65536 values before using it to get the value you want...

We can easily add some tests for using this depending on the number of element to convert, but then which threshold to set for OpenMP?

**Comment by kif** [comment]
I recently fall into the same kind of bugs: Parallelized code (on just 4 cores) was 20% slower than sequential one. The more it goes, the more I consider the performance benefits of OpenMP is not worth the burden and having a clean single threaded function with optimal use of the cache is often better in performance (with nogil it is perfect).

**Comment by vasole** [comment]
I never needed to parallelize anything for display... In PyMca I do not use parallel code for median filters, colormaps,... I do not consider display a critical thing and resources should be allocated to acquisition.

**Comment by t20100** [comment]
I also have the feeling that OpenMP is not the right granularity most of the time and you easily get slower.

Yet, AFAIR, in this case, on large images you get the expected x4 speed-up (num threads <= 4 here).
The problem to me would be to set a reasonable threshold of number of elements when to enable OpenMP.

**Comment by kif** [comment]
The rule of thumb would probably be: parallelize when it no more fits the L3 cache (2-128Mo on today's standards)
Beside this, there are the environment variables:
`OMP_NUM_THREADS=4 OMP_PLACES=cores OMP_PROC_BIND=close`

**Comment by vallsv** [comment]
I feel like the problem of OpenMP is also that it is only really easy to setup properly. Or maybe that's the problem with the provided helpers. Cause as far as i remember it is not easy to provide with and without OpenMP without dup code.

Anyway maybe if the amount of values is =1 or less than 4x the number of max core, this could be skipped.

Or this could be optionally disabled with an argument.


> Also, for (u)int8|16, you even end-up computing the LUT with 256 or 65536 values before using it to get the value you want...

Is that only a cached problem?

**Comment by t20100** [comment]
>     Also, for (u)int8|16, you even end-up computing the LUT with 256 or 65536 values before using it to get the value you want...
> 
> Is that a problem we can fix with a cache?

No, but a threshold should be simple for this.

**Comment by t20100** [comment]
`%timeit` benchmark for an array of one float (`data= numpy.array([1.])`):
* With OpenMP:
  - `silx.math.colormap.cmap`: 13us
  - `silx.gui.colors.Colormap.applyToData(data)`: 51us
* Without OpenMP (`prange` replaced by `range`):
  - `silx.math.colormap.cmap`: 10us
  - `silx.gui.colors.Colormap.applyToData(data)`: 50us

This time OpenMP doesn't seems to be guilty, and 0.05ms sounds good for integration in GUI.
Maybe there is an issue with caching min/max? Is it the same with/without autoscale?
How often is it called? 

With (u)int8 or 16, it can be optimized since the LUT is always computed, but for float it is not the case.

Benchmark code:
```python
import numpy
from silx.math import colormap
from silx.gui.colors import Colormap

colors = numpy.zeros((256, 4), dtype=numpy.uint8)
colors[()] = numpy.arange(256, dtype=numpy.uint8).reshape(256, 1)

data = numpy.array([1.])

min_, max_ = data.min(), data.max()
%timeit colormap.cmap(data, colors, min_, max_)
colormap.cmap(data, colors, min_, max_)

cmap = Colormap()
%timeit cmap.applyToData(data)
```

**Comment by t20100** [comment]
While timing is the same, CPU usage in reported condition varies with usage or not of OPENMP even when computing one value.
