### ISSUE TITLE
[plot1d] issue when switching to log scale:

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#330]
```python
import numpy
from silx import sx
sx.plot(numpy.sin(numpy.linspace(-10, 10, 1000)))
#then switch to log-scale

%pylab
plot(numpy.sin(numpy.linspace(-10, 10, 1000))
yscale("log")
```
matplotlib gives a sensible graph (with discontinuities) while silx connects the last positive values.

**Comment by kif** [comment]
![sx](https://cloud.githubusercontent.com/assets/1018880/19120389/ee50047c-8b22-11e6-85e3-ec4762c668ff.png)
![pylab](https://cloud.githubusercontent.com/assets/1018880/19120390/ee5224fa-8b22-11e6-8372-ed76edd41121.png)

**Comment by t20100** [comment]
After a few checks for values <=0 with log scale, matplotlib shows discontinuities on debian 7, while on debian 8 values are actually clipped to 10e-301 but there is no discontinuities (even if it is not visible on the figure).
In silx with log scales, the values <= 0 are currently removed from the curve before displaying it, which leads to displaying a continuous curve.

I propose to replace values <= 0 with nan before displaying them. This displays such curves with discontinuities in a consistent way in both debian 7 and debian 8.

Display of matplotlib on Debian 7:
![ondebian7](https://cloud.githubusercontent.com/assets/9449698/19146024/ed25f6d0-8bb1-11e6-999d-6b00d6906d56.png)

**Comment by vasole** [comment]
No problem it only affects the display and not the data themselves.
