### ISSUE TITLE
mask: tag EDF with the interpretation of the mask

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3301]
The aim is to patch LIMA to properly use the mask from silx.

2 ways:
- Tag the EDF with a `application=silx` (or something similar)
- Tag the EDF with the mask interpretation `masked-when=1` (or something similar)

**Comment by t20100** [comment]
Sounds a simple way to say which convention is used to store the mask.

**Comment by vallsv** [comment]
Closed by #3310
