### ISSUE TITLE
[Hdf5TreeModel] Next available role value.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#331]
When subclassing or proxying Hdf5TreeModel there is no reliable way to know what role values are used by Hdf5TreeModel.

``` python
H5PY_ITEM_ROLE = qt.Qt.UserRole
"""Role to reach h5py item from an item index"""

H5PY_OBJECT_ROLE = qt.Qt.UserRole + 1
"""Role to reach h5py object from an item index"""
```

A subclass could use H5PY_OBJECT_ROLE + 1, but that is not reliable (breaks if a role is later added to Hdf5TreeModel).

Please provide something like MAX_ROLE = H5PY_OBJECT_ROLE.
(or H5PY_ITEM_ROLE, H5PY_OBJECT_ROLE, MAX_ROLE = range(qt.Qt.UserRole, qt.Qt.UserRole + 3)

**Comment by vallsv** [comment]
I guess it is unfortunately too late for this release, but BTW, do you prefer name a-la Qt? i.e. `H5pyObjectRole` and `H5pyItemRole`, i think it would be better to rename this attributes.

**Comment by dnaudet** [comment]
No worry, this is not urgent at all, I'll use whatever is available when it is available! ;)
For the names format I really don't mind, what do the others think?
