### ISSUE TITLE
Can't  import sift 

### ISSUE THREAD

**Issue by ericosmic** [silx-kit/silx#3337]
When I want to import sift , it will throw out the error lilke this :
![image](https://user-images.githubusercontent.com/35327931/101770462-70f60e80-3b23-11eb-9015-ab446c6033a4.png)
my silx and cv2 version:
![image](https://user-images.githubusercontent.com/35327931/101770629-ab5fab80-3b23-11eb-951b-f7eca4933069.png)

**Comment by vallsv** [comment]
Here the problem is on `pytools`. We can't do much.

You should probably try to use another version of `pytools`.

**Comment by vallsv** [comment]
Probably your python version du not support typing.
Are you using python 2?

**Comment by ericosmic** [comment]
wow, thanks,  it is successful
