### ISSUE TITLE
[Question] Silx FitWidget

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/silx#3344]
Hello, I was wondering if the FitWidget widget from silx has equivalents of signals and slots. I wanted to collect the "fit values" from the dialog in order to plot the result fitting.
I did not found that kind of thing in the FitWidget widget.

**Comment by alexmarie78** [comment]
Nevermind, I found out I was searching in an old version of the code, I found sigFitWidgetSignal. 
Sorry for the waste of time, I am closing this.

**Comment by vallsv** [comment]
You'r welcome
