### ISSUE TITLE
The LegendsDockWidget item in the PlotWindow blinks

### ISSUE THREAD

**Issue by physwkim** [silx-kit/silx#3345]
When updating the plot quickly(20 Hz), the LegendsDockWidget item in the PlotWindow blinks.

The code I used for the test is shown below.
```
import numpy as np

from silx.gui import qt
from silx.gui.plot.PlotWindow import PlotWindow
from silx.gui.utils.concurrent import submitToQtMainThread

class Graph(qt.QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.plot = PlotWindow(self)
        self.plot.getLegendsDockWidget().show()
        self.setLayout(qt.QVBoxLayout())
        self.layout().addWidget(self.plot)

        self.timer = qt.QTimer()
        self.timer.timeout.connect(self.update)
        self.timer.start(50)

    def update(self):
        y = np.random.random(1000)
        x = np.arange(1000)
        submitToQtMainThread(self.plot.addCurve, x, y, legend='plot0')

if __name__ == '__main__':
    app = qt.QApplication([])
    gui = Graph()
    gui.show()
    app.exec_()
```

![Blink](https://user-images.githubusercontent.com/51432966/102497123-9d79cf80-40bb-11eb-8e05-2ed6ac2d64b1.png)

**Comment by vallsv** [comment]
Hi,

Any idea if it was with the version 0.14.0? And if it was a regression?

**Comment by physwkim** [comment]
Hi, 

This is the same result not only for 0.14.0 but also for 0.11.0.

**Comment by physwkim** [comment]
Probably this symptom seems to be seen because all legends are erased every time points of the curve is updated.
Instead of erasing all legends, using a method of updating the model's data doesn't seem to blink.

Could you please review the pull request(#3346) ?

**Comment by vallsv** [comment]
Thanks a lot for the fix.

There is probably also a way to filter data update (which should not change anything to the legend).

But i am pretty sure your update method is anyway useful at some point.

Anyway this will probably not be reviewed before January.
