### ISSUE TITLE
Doc: broken link in specfile

### ISSUE THREAD

**Issue by pierrepaleo** [silx-kit/silx#3433]
The link to "specfile manual" is broken in the [specfile documentation](http://www.silx.org/doc/silx/latest/modules/io/specfile.html).

```
Documentation for the original C library SpecFile can be found on the ESRF website: The manual for the SpecFile Library
```

I don't know if it would be relevant to host the file `SpecFileManual.pdf` on our server.

**Comment by t20100** [comment]
It doesn't seems to be public available from ESRF any longer, so no choice but to host.
