### ISSUE TITLE
secondary x-axis in PlotWidget

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#3434]
Hello,

I'd like to draw a secondary x-axis in `PlotWidget`, similarly to [this example](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.secondary_xaxis.html#matplotlib.axes.Axes.secondary_xaxis). If I use the mpl backend, how do I get access to the PlotWidget's Axes object to utilize its method `secondary_xaxis()`? Is a secondary x-axis possible in other backends?

Thank you!

**Comment by t20100** [comment]
Hi,

There is no support for secondary xaxis in silx, there is only support for a second Y axis on the right.

That being said, as it is, you can manage it yourself by directly accessing matplotlib:
```
from silx import sx

w = sx.plot()   # Create a PlotWidget
axes = w.getBackend().ax  # Retrieve the matplotlib Axes
new_axes = axes.secondary_xaxis(location='top')  # Create matplotlib secondary axes
w._setDirtyPlot()  # Force redraw since changes at matplotlib level are not tracked
```

**Comment by kklmn** [comment]
Yes, this is it!
Thank you!
