### ISSUE TITLE
FIO file support

### ISSUE THREAD

**Issue by tifuchs** [silx-kit/silx#3438]
Hi everybody,

The *.fio file format is a default data recorder in the [Sardana controls](https://sardana-controls.org/) project, which is used by many synchrotrons (ALBA, DESY, MaxIV, Solaris and ESRF according to their web page). The fio file serves a similar role as the Nexus or Spec file. I.e. it is mainly used to save 1d data like motor positions and counter values during a measurement.
Neither silx nor pymca seem to support reading these files.

I am not sure about the scope of this library. Are you interested in enabling the support for this filetype?

I already wrote a fio -> NEXUS converter based on your spech5.py implementation for specfiles.
Reading the files and converting multiple fio files into one master hdf5 file (using silx convert) works already nicely with the files I have:
![silxview_fio](https://user-images.githubusercontent.com/50143413/114239730-bc5fe280-9986-11eb-8037-7adb521b1a2f.jpg)
You can find my silx fork [here](https://github.com/tifuchs/silx/tree/fio_support).

Fio seems to be a very open file "standard". For example, I wasn't able to find any proper documentation about the file specification. This might be a problem with any fio converter implementation. My current version is based on the fio file writer of [Spock/Sardana](https://github.com/sardana-org/sardana/blob/34bd40be3d316c5d6f0a88ac88ef9001c36a0143/src/sardana/macroserver/recorders/storage.py).

Cheers,
tifuchs

**Comment by vallsv** [comment]
I can't answer for @t20100 but at least your patch looks fine.

Anyway, to be merged there is probably a lack of tests, with a kind of `fio` file for reference.

**Comment by t20100** [comment]
Hi,

You are welcome to make a PR for it!
AFAIK, we have no need for *.fio support, but since it is a synchrotron related file format it can well fit in the silx package!

As @vallsv already said, some tests would be needed.
Also, it will probably be hard for us to maintain the support of this file format since we are not used to it, so help on the maintenance of this particular feature is also welcomed!

**Comment by tifuchs** [comment]
I have a beamtime the next two weeks at DESY, where I'll use the code in the field.
After that experience I'll add some test code and make a PR.
