### ISSUE TITLE
New line profiles in ImageView removed essential functionality for OASYS users

### ISSUE THREAD

**Issue by lucarebuffi** [silx-kit/silx#3454]
In the last release of silx, the line profile function of ImageView widget drastically changed behavior. When selecting a line profile (horizontal or vertical), the secondary windows with the 1D profile is no more visible, but the profile appears directly in the ImageView side histograms. 
I also noted that, when using other line profile options, the window with the 1D profile appears with minimal dimensions on the screen, requiring a manual resize to be visible.

This had a massive (and detrimental) impact on the OASYS users, that used that function to be able to do fits and other operations on the 1D profile. It is **very urgent** for the OASYS community the have the functionality restored as it was. 

![Screen Shot 2021-05-05 at 11 18 36 AM](https://user-images.githubusercontent.com/6713598/117174718-a382fb00-ad93-11eb-8ed6-fd6019deb022.png)

![Screen Shot 2021-05-05 at 4 45 50 PM](https://user-images.githubusercontent.com/6713598/117213687-91b84c80-adc1-11eb-87a2-e509c12986cd.png)

**Comment by lucarebuffi** [comment]
I also noted that, when using other line profile options, the window with the 1D profile appears with minimal dimensions on the screen, requiring a manual resize to be visible

**Comment by vasole** [comment]
You are reporting two issues? Because I understand two things that cannot happen simultaneously:

1 - the profiles where before in floating windows by default and now they are attached to the image widget
2 - when they are floating windows they are so small that need systematic resizing.

**Comment by t20100** [comment]
Quick fix: pin-point to silx 0.14.x versions.

Also, before each release of silx, we advertise a release candidate on the `silx@esrf.fr` mailing list for testing with software using it, I would encourage you do so in order to avoid **very urgent** situations.

**Comment by t20100** [comment]
For last release, profiles where integrated into the side widgets of `ImageView` to avoid too many pop-up windows, but this indeed prevents action like fitting.

If you want to restore the previous behaviour, you can replace the `ProfileToolBar` of  `ImageView` with the default one:
```python
from silx.gui.plot import ImageView
from silx.gui.plot.Profile import ProfileToolBar

class MyImageView(ImageView): 
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.removeToolBar(self.profile)
        self.profile = ProfileToolBar(plot=self) 
        self.addToolBar(self.profile)
```
This should solve both access to fit tool button AND pop-up window size since this looks to only occur for `ImageView`'s specific ProfileToolBar.

**Comment by t20100** [comment]
BTW, to reproduce the small window issue: `python bootstrap.py examples/imageview.py`
Then draw a horizonal line profile on the image and then draw a free line profile.

**Comment by srio** [comment]
Just my opinion as user:
- The new version includes nice things like the cross profile
- The old version is very useful because the 1D widget with the profile permits lots of postprocessing, that now is impossible. 

It could be nice for new versions to include both capabilities.... may be with a larger pulldown option menu?

I think an good improvement could also be a toggle button for switching the side plots between histograms (as now) and interactive cross profile (without clicking, just passing the mouse).

Thanks for your attention!!

**Comment by woutdenolf** [comment]
To reproduce locally:
```
conda install python==3.7.8  # doesn't work on 3.8
```

**Comment by srio** [comment]
> Each of these tools have widgets for X-ray sources. For example the undulator widgets have the 2D plots described in the issue. There appear to be 2 types of 1D profiles

In fact, it does not depend on the addon itself, but depends only (I think) if we use Plot2D widget (profiles in external window) or ImageView widget (with embedded profiles now, but before external window). 

In Wofry we can make the choice, but not in the other apps:
![image](https://user-images.githubusercontent.com/502315/117292216-3a24ea00-ae70-11eb-92f2-f6682fe746d7.png)


![image](https://user-images.githubusercontent.com/502315/117292293-53c63180-ae70-11eb-8c30-81d89f351026.png)

**Comment by woutdenolf** [comment]
That not what I get from WOFRY (silx 0.15.0). For me the 1D profile window pops up (type 1 as I called it):
![image](https://user-images.githubusercontent.com/7264703/117293500-bcfa7480-ae71-11eb-89e5-dd0a0e9e31a2.png)

**Comment by t20100** [comment]
Yes, the change in silx was only for the `ImageView` widget.

**Comment by woutdenolf** [comment]
Ok I see, so this behaves as before
```
python bootstrap.py examples/plotInteractiveImageROI.py
```
and this doesn't
```
python bootstrap.py examples/imageview.py
```

**Comment by srio** [comment]
> @srio That's not what I get from WOFRY (1.0.25) with silx (0.15.0). For me the 1D profile window pops up (type 1 as I called it). I guess we're using different versions?
> ![image](https://user-images.githubusercontent.com/7264703/117293500-bcfa7480-ae71-11eb-89e5-dd0a0e9e31a2.png)

Here you see Plot2D - If you select View Results: Yes (image+hist) you see ImageView...

**Comment by woutdenolf** [comment]
@srio Ok thanks for the feedback. It's clear now what's going on.

**Comment by t20100** [comment]
@srio, thanks for the feedbacks!

In order to avoid too many choices in the GUI, I'd leave the choice between always using a pop-up and using side profiles to the application developer rather than to the end user, which in the end is very few lines of code.

**Comment by woutdenolf** [comment]
@t20100 When you say you leave the choice to the developer, do you mean: https://github.com/silx-kit/silx/issues/3454#issuecomment-833408593? That's too patchy imo. I'm not very familiar with the API philosophy here be you could do either of these:
* provide an argument to `ImageView.__init__` to select the appropriate toolbar
* provide an `ImageView` to select the appropriate toolbar (equivalent to `ImageView.IMAGE_MIN_SIZE` and co)
* provide two `ImageView` classes, one for each toolbar (e.g. `ImageView` and `ImageSingleView` or whatever).

**Comment by t20100** [comment]
You can make a slightly nicer patch by hiding the provided profile and adding your own.
But it's probably best if we provide something neater.

Regarding classes, so far we kept different widget class for different kind of data and related interfaces (`ScatterView`, `ImageView`, `ComplexImageView` which comes with its specific toolbar, `StackView`, `Plot1D`, `Plot2D`) and not for different flavours of the same one (depends how you see `PlotWindow` though).

We could provide a getter/setter (`setProfileToolBarBehavior`, `setProfileToolBar` or whatever) which is more Qt-ish (we need to check if this is easy to do, but I think so).
What do you think of this option? (my vote goes to this one ;))

**Comment by lucarebuffi** [comment]
> Quick fix: pin-point to silx 0.14.x versions.
> 
> Also, before each release of silx, we advertise a release candidate on the `silx@esrf.fr` mailing list for testing with software using it, I would encourage you do so in order to avoid **very urgent** situations.

That is not possible, in order to revert the silx library to a previous version, I would have to reissue the core library with new requirements (in this moment is silx>=0.15.0) and ask the reinstallation of OASYS to all the users.

**Comment by lucarebuffi** [comment]
> To reproduce locally:
> 
> ```
> conda install python==3.7.8  # doesn't work on 3.8
> python -m pip install --upgrade pip setuptools wheel
> conda install -c conda-forge xraylib=3.3.0
> python -m pip install oasys1
> ```
> 
> Start the canvas:
> 
> ```
> python -m oasys.canvas --force-discovery
> ```
> 
> Under Options > Addons: install ShadowOui, SRW, XOPPY, WOFRY
> 
> Each of these tools have widgets for X-ray sources. For example the undulator widgets have the 2D plots described in the issue (drag the widget on the canvas, double-click and press "compute"). There appear to be 2 types of 1D profiles extracted from a 2D image:
> 
> 1. XOPPY, WOFRY, ShadowOui(free line only), SRW(free line only): the 1D profile appears as an external window (as before) but the first time the window size is minimized. Resizing it once is enough so not that urgent imo.
> 2. ShadowOui(horizontal, vertical or cross), SRW(horizontal, vertical or cross): the 1D profile appears inside the 2D plot (below or on the left in pink) so you are missing the toolbar to play with the 1D plot (e.g. fitting, save, ...). This is more important.
> 
> @lucarebuffi So why/how does type 2 exist for ShadowOui and SRW? The same widget type in WOFRY and XOPPY only hase type 1, no matter the profile option. Can you point us to the code. I'm trying to find it without success.
> 
> Edit: I don't really see a difference in code but maybe I'm looking in the wrong place
> 
> 1. XOPPY: https://github.com/oasys-kit/XOPPY/blob/3bd800e4059042c567abd979748491419a5aba3d/orangecontrib/xoppy/widgets/gui/ow_xoppy_widget.py#L376
> 2. ShadowOui: https://github.com/oasys-kit/ShadowOui/blob/a21c23564e29797a9c3b2d95526f0a26f84a1c0c/orangecontrib/shadow/widgets/sources/ow_undulator_full.py#L416

You manage to find things both coded by Manuel Sanchez del Rio, that use Plot2D and not ImageView.  :D

**Comment by lucarebuffi** [comment]
> For last release, profiles where integrated into the side widgets of `ImageView` to avoid too many pop-up windows, but this indeed prevents action like fitting.
> 
> If you want to restore the previous behaviour, you can replace the `ProfileToolBar` of `ImageView` with the default one:
> 
> ```python
> from silx.gui.plot import ImageView
> from silx.gui.plot.Profile import ProfileToolBar
> 
> class MyImageView(ImageView): 
>     def __init__(self, *args, **kwargs): 
>         super().__init__(*args, **kwargs) 
>         self.removeToolBar(self.profile)
>         self.profile = ProfileToolBar(plot=self) 
>         self.addToolBar(self.profile)
> ```
> 
> This should solve both access to fit tool button AND pop-up window size since this looks to only occur for `ImageView`'s specific ProfileToolBar.

This patch worked perfectly! Thank you!

**Comment by vasole** [comment]
>That is not possible, in order to revert the silx library to a previous version, I would have to reissue the core library with new requirements (in this moment is silx>=0.15.0) and ask the reinstallation of OASYS to all the users.

As a rule of thumb, you should not impose unneeded upgrades to your users. 

If you had tested your stuff and it was working with silx 0.14.x why to impose silx >= 0.15.0 (specially if you did not thouroughly tested agaist the latter as it seems to be the case)? It can only bite you back.

**Comment by lucarebuffi** [comment]
We try to keep the support libraries as updated as possible. 
Thank you for the lecture, but I did tested the new library before releasing it. 
This modification was as impacting as subtle to discover it and I just missed it.

**Comment by woutdenolf** [comment]
> You can make a slightly nicer patch by hiding the provided profile and adding your own.
> But it's probably best if we provide something neater.
> 
> Regarding classes, so far we kept different widget class for different kind of data and related interfaces (`ScatterView`, `ImageView`, `ComplexImageView` which comes with its specific toolbar, `StackView`, `Plot1D`, `Plot2D`) and not for different flavours of the same one (depends how you see `PlotWindow` though).
> 
> We could provide a getter/setter (`setProfileToolBarBehavior`, `setProfileToolBar` or whatever) which is more Qt-ish (we need to check if this is easy to do, but I think so).
> What do you think of this option? (my vote goes to this one ;))

I would be fine with anything that
* does not require deriving a class from `ImageView`
* does not require nasty patching like `removeToolBar/addToolBar` or at the very least hide this so the app devs don't need to deal with that

So yes a setter like `setProfileToolBarBehavior(self, detached=True)` equivalent to `setXAxisAutoScale`, `setKeepDataAspectRatio`, etc. would be ok.

**Comment by woutdenolf** [comment]
If we have a setter for the toolbar, the question is what would be the default. I would say detached profiles should be the default, like it was before.
