### ISSUE TITLE
[silx.io.open] fails reading ESRF-BM30 spec files

### ISSUE THREAD

**Issue by maurov** [silx-kit/silx#3459]
`silx.io.open` fails reading this Spec file from BM30 at ESRF: [testBM30.zip](https://github.com/silx-kit/silx/files/6442920/testBM30.zip) (unzip it).

It happens because the `#P` fields in the scan header do not fully corresponds to the `#O` fields of the file header. The old `specfilewrapper` is able to ignore this misformat in the Spec file. 

Old `specfilewrapper` works:

```python
from silx.io.specfilewrapper import Specfile
sf = Specfile('./testBM30.spec')
```
`specH5` fails:

```python
from silx.io.spech5 import SpecH5
sf = SpecH5('./testBM30.spec')
```

Would it be possible to have `spech5` ignoring it too ? It should not take too much work to fix this bug.

**Comment by vasole** [comment]
Nobody warrants the removed motor is the last one.

It is preferable to ignore all of them than to assign wrong values.
