### ISSUE TITLE
[silx.io.dictdump.dicttoh5] unexpected behavior using update_mode="modify"

### ISSUE THREAD

**Issue by jpcbertoldo** [silx-kit/silx#3462]
The function [`silx.io.dictdump.dicttoh5`](https://github.com/silx-kit/silx/blob/fe38fd3c712a311876ce8804e144621c9dad7c4f/src/silx/io/dictdump.py#L171) has an expected behavior when `update_mode="modify"` in the following scenario:

1. The file `mystuff.h5` already exists and has the following internal tree:

```
/A (Group)
/A/data (Group)
/A/data/a (Dataset)
/A/data/data (Dataset)
```

2. I want to flatten the structure, so I update it such that the second nested group's (`A/data`) content will be saved in the first one (`A`). Resulting in:

```
/A (Group)
/A/a (Dataset)
/A/data (Dataset)
```

But I'd like not to use `update_mode="replace` because other things might be updated as well during the same call.

Because of [this condition (L343)](https://github.com/silx-kit/silx/blob/fe38fd3c712a311876ce8804e144621c9dad7c4f/src/silx/io/dictdump.py#L343) , the update will not happen and no warning is yeilded.

**Comment by t20100** [comment]
Hi,

I'm seen that no one answered your issue so far, sorry for the late reply. 

Unless I missed something, the behaviour you describe corresponds to the documentation:
https://github.com/silx-kit/silx/blob/fe38fd3c712a311876ce8804e144621c9dad7c4f/src/silx/io/dictdump.py#L209-L218

With `update_mode="modify"`, a group is not replaced by a dataset.

However, we can add an info log when something is skipped.
