### ISSUE TITLE
Seamless support of HDF5 input file in write_to_h5

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3468]
Initially raised by @maurov: https://github.com/silx-kit/silx/issues/3354#issuecomment-768893312 but ignored so far:
One cannot use `write_to_h5` with a HDF5 input file since it raises errors when input is a HDF5 file

To workaround issue #1378, PR #1385 raised exceptions when the `infile` is a `h5py` object, e.g.: https://github.com/silx-kit/silx/blob/master/src/silx/io/convert.py#L300

It would be good to support it so one can open whatever file with `silx.io.open` and use seamlessly `write_to_h5`

**Comment by maurov** [comment]
@t20100 thanks for raising this issue back. I do not see any reason why one could not use `write_to_h5` when the source file is HDF5. I know that this could be done directly with `h5py`, but this is not a good reason, since `silx.io.open` supports HDF5.

**Comment by t20100** [comment]
I really prefer not to wrap `h5py` with an API that is supposed to be copied from it.

The first blocking point (hoepfully single) is `commonh5`'s `visititems` having one more argument than `h5py`'s `visititems` to handle links in `write_to_h5`:

https://github.com/silx-kit/silx/blob/61ce074b1b9c35a30271d20d0d58b3945c17cc6f/src/silx/io/commonh5.py#L872

If that is the only issue, it can be solved for `write_to_h5` by using a `visitall` function providing a visitor giving handling links.

@maurov, is `write_to_h5` your main issue or there are others?

**Comment by maurov** [comment]
> @maurov, is `write_to_h5` your main issue or there are others?

@t20100, my main issue is to use `write_to_h5` with a HDF5 source, that is the only blocking point I have seen so far. If this could be solved without wrapping `h5py`, it would be great, thanks!
