### ISSUE TITLE
Backports for 0.15.2

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3470]
Lists of PR to backports from master branch for a v0.15.2:

- #3469
- #3463 

Please add any PR to backport here or flag issues/PRs with milestone 0.15.2

**Comment by t20100** [comment]
Also backport #3476

**Comment by t20100** [comment]
Also fixing issue #3489

**Comment by t20100** [comment]
@kif, do you want to backport #3466 and #3472 in this micro release?

**Comment by t20100** [comment]
Also backport #3490

**Comment by maurov** [comment]
@t20100 when do you plan to release `0.15.2`?

**Comment by t20100** [comment]
> @t20100 when do you plan to release 0.15.2?

ASAP: if there is no last minute issue to fix, tomorrow sounds too optimistic and next week sounds realistic.

**Comment by t20100** [comment]
Closing: All backports were done.
