### ISSUE TITLE
Assert error on ArcRoi bigger then 2pi

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3489]
There is a validity check on arc ROI during `setGeometry`

```
assert numpy.abs(startAngle - endAngle) <= 2 * numpy.pi
```

This have failed on a beamline recently.

- As we deal with float, at least an epsilon should be added
- I think the GUI can manage ranges bigger than a full circle, then the assert could just be removed (this have to be checked)

Could be part of a bug fix release.

**Comment by t20100** [comment]
Yes and anyway better a warning and a clipping to a correct value rather than an assert.

**Comment by t20100** [comment]
Here is a way to reproduce:
```
import numpy
from silx import sx
from silx.gui.plot.tools.roi import RegionOfInterestManager
from silx.gui.plot.items.roi import ArcROI
r = ArcROI()
r.setGeometry((0, 0), 1, 2, 0, 3*numpy.pi)
w = sx.Plot2D()
m = RegionOfInterestManager(w)
m.addRoi(r)
w.show()
```
