### ISSUE TITLE
Assert error during resetZoom

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3501]
Hi,

Here is a problem found in beamline logs.

I did not try to reproduce it.

Maybe already fixed.

![Screenshot from 2021-07-07 14-43-07](https://user-images.githubusercontent.com/7579321/124881524-bacaa880-dfcf-11eb-81b7-5760f8eec51a.png)

**Comment by t20100** [comment]
This `assert` is still there so I guess it can occur again.
I'll check under which condition this could happen... and anyway replace the assert with a `if min_ < max_:`

**Comment by t20100** [comment]
OK, it can occur if limits are outside [-1e37, 1e37] or within [-1.1754944e-38, 1.1754944e-38]... i.e., float32 does not allow to do max-min.

**Comment by vallsv** [comment]
oh... nice to know...

**Comment by vallsv** [comment]
Which means the log value became `nan`?

**Comment by t20100** [comment]
Yes, and there is a hole in the clipping: the range is clipped during interaction but not when limits are changed through the API or when reseting the zoom.

A simple way to reproduce:
```python
from silx import sx
w = sx.plot((1e40, 1e41))                                              
w.setBackend("gl")
```

**Comment by t20100** [comment]
I can extend the range to most of the float64 range... but not the whole range or I get errors further down in tick computation with both matplotlib and opengl, so I'll:
- extend the range of limits to [-1e307, 1e307]
- clip the limits to this range even when set from the API... so if your data is above 1e307 you won't see it.
