### ISSUE TITLE
mask made from from ROIs

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#3502]
Hello,

I am scrutinizing your example `plotInteractiveImageROI.py`, it gives me what I want. I need to convert all merged ROIs into a 2D mask. I see that roi items (in gui/plot/items/roi.py ) have a method `contains()` that I potentially could use for this purpose, although the method seems to be designed for a single point (am I right?), not a 2D array.

Can you please advise a way one could create a mask from a roi or a list of rois?

Thank you!

**Comment by t20100** [comment]
`contains` is meant for single point (basically useful for picking), so you should be able to use to draw a mask, but I expect it will be really slow.

A faster option I see, would be to "draw" the ROIs to an array (like the mask tool is doing): silx provides a few function to draw some primitives: http://www.silx.org/doc/silx/latest/modules/image/shapes.html. In this case you'll have to use a specific draw function for each kind of ROI.

**Comment by t20100** [comment]
This is the internal class updating the mask from the mask tool: https://github.com/silx-kit/silx/blob/3ced0c00c66f6a1439fcde685ec1a32c87396b1f/src/silx/gui/plot/MaskToolsWidget.py#L84

It's using the `silx.image.shapes` functions I mentionned.

**Comment by kklmn** [comment]
Thank you 20.100!
`ImageMask` gives me what I want.
