### ISSUE TITLE
error reading spec file with silx.io.open()

### ISSUE THREAD

**Issue by newville** [silx-kit/silx#3506]
@maurov I think this is separate from #3459, but it might be related.

We're trying to use `silx.io.open` to read Spec files in xraylarch -- we're very happy to be able to support ESRF Bliss files!.  But a user posted a spec file:
   https://millenia.cars.aps.anl.gov/gsecars/data/Larch/datafiles/break_silx0152.spec

that breaks in a way I don't completely understand:

```
Python 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import silx
>>> silx.version
'0.15.2'
>>> from silx.io import open as silx_open
>>> f = silx_open('break_silx0152.spec')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/utils.py", line 590, in open
    h5_file = _open_local_file(url.file_path())
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/utils.py", line 504, in _open_local_file
    return spech5.SpecH5(filename)
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/spech5.py", line 574, in __init__
    scan_group = ScanGroup(scan_key, parent=self, scan=scan)
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/spech5.py", line 629, in __init__
    if _unit_cell_in_scan(scan) or _ub_matrix_in_scan(scan):
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/spech5.py", line 309, in _unit_cell_in_scan
    return numpy.any(_parse_unit_cell(scan.scan_header_dict["G1"]))
  File "/Users/Newville/xraylarch/lib/python3.8/site-packages/silx/io/spech5.py", line 298, in _parse_unit_cell
    return numpy.array(list(map(float, header_line.split()))[0:6]).reshape((1, 6))
ValueError: cannot reshape array of size 1 into shape (1,6)
>>>
```

The lines like `#G1 0` seem to be the problem. I have to admit, I don't know much about the origin of the file, or what those lines are meant to encode.  Is `#G1 0` always invalid?

Is there a way we could work around this? 

Thanks!

**Comment by maurov** [comment]
@newville here the standard data format of Spec files:

![image](https://user-images.githubusercontent.com/545294/126594718-e7b0f64e-e63d-4542-9e40-e3a53ce44c3a.png)

The file provided is somehow misformatted, because `#G1` should be an array, as expected by [_parse_unit_cell](https://github.com/silx-kit/silx/blob/70e462d9904250d703e08518f3691224b03dee11/src/silx/io/spech5.py#L296).

This said, we could easily catch it, as done by the *old* `specfile` library:

```python
from silx.io.spech5 import SpecFile
sf = SpecFile('break_silx0152.spec')
sf.keys()
sd = sf['1.1']
sd.motor_names
sd.labels
ene = sd.data_column_by_name('Energy')
mu = sd.data_column_by_name('Absorption')
import matplotlib.pyplot as plt
plt.plot(ene, mu)
plt.show()
```

@t20100 @vasole would be possible to have a quick fix (if the `#G1` line is not an array, simply raise a warning and ignore it) merged in master (in order to have it in the next minor release)?

**Comment by newville** [comment]
@t20100 @maurov Thanks for the quick fix!  Apparently, some users/beamlines give not-quite-compliant `#G` tags.

But also, if the Spec file spec says


```
   #G1 | parameters | Array G[] (geometry mode, sector, etc.)
```

I don't quite see why those would be assumed to have a known size or even be numerical. Wouldn't

```
#G1  kappa, six-circle   Facility Beamline (NickName), Singlet Mode, Beamline Mirror in. 
```

be perfectly acceptable?  

It does seem like `#G2` is intended to have six numbers, but the Spec file spec is not very specific (sorry!) about precisely what those are. 

I don't know how one would encode the orientation matrix (presumably 3x3, but no order specified) for a single line of ASCII text for `#G3` based on this format.  Like, is "row order" obvious?  It is not stated.

And `#G4` also has an 'etc'.... no idea if that means "2 or more numerical values", but also not very specific.


Anyway, thanks for fixing this immediate problem.

**Comment by t20100** [comment]
As it is now, interpretation of `#G1` and `#G3` are skipped if some values are not numerical or if there is not enough values, so it's resilient to a few more cases.

**Comment by t20100** [comment]
FYI, in another documentation, the [scans one](https://certif.com/spec_help/scans.html), you can find:

>    #G1
>    Specifies parameters associated with the diffractometer geometry. The parameters are those from the U[] array, which include lattice constants and orientation reflections.

We've checked what the macro does, and it saves the U[] array as `#G1`.
