### ISSUE TITLE
[help-wanted] group title

### ISSUE THREAD

**Issue by jpcbertoldo** [silx-kit/silx#3517]
I would like the title of a group in my h5 to show up at the `Description` column of `silx view`'s tree explorer, as in the second group below (group `1.1`'s description `""fscan diffrz 0 0.001 21 0.02 0.042166"` is visible when the group is closed). 

I tried adding a field `title` to my group `second-attempt`, but it does not work.

![image](https://user-images.githubusercontent.com/24547377/128312230-ae26492e-4cef-464e-88a8-815b84f6535e.png)

**Comment by payno** [comment]
You entry is defined as an [NXentry](https://manual.nexusformat.org/classes/base_classes/NXentry.html)
You can see on the documentation that the attribute 'default' is used to defined 'the group containing the data to be shown by default.'

So on your python code when writing the data you should have something like:

``` python
with h5py.File(xxx) as h5f:
   h5f["second-attempt"].attrs["default"] = "title"
```

**Comment by payno** [comment]
Sorry I was incorrect about my answer.
What is missing to 'second-attempt' is an `NX_class` attribute here. As [NXentry](https://manual.nexusformat.org/classes/base_classes/NXentry.html) if it represents your group.

And this is the simplest way to create it (for NXentry silx will automatically link the `title` dataset ):

```
import h5py

with h5py.File("test.h5", mode="a") as h5f:
	h5f["entry/title"] = "toto"
	h5f["entry"].attrs["NX_class"] = "Nxentry"
```
Sorry about the misleading previous answer.

**Comment by joaopcbertoldo** [comment]
Hi @payno, thanks for your help! I will try it out (:

**Comment by payno** [comment]
@jpcbertoldo can we close this issue ?

**Comment by jpcbertoldo** [comment]
Sure
