### ISSUE TITLE
silx view: slider resets legend selection

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3518]
When moving the sliders in the NXdata view below, the legend selection gets reset (e.g. in this case I wanted to uncheck "subtracted" but it gets re-checked every time I move the sliders):

![image](https://user-images.githubusercontent.com/7264703/129005698-09f5fd74-ae85-46f8-98f3-6f5e15a51edd.png)

**Comment by vallsv** [comment]
What is the selected view?

Depending on the way it is implemented, there is maybe a way to fix it.
But i do not handle very well the `PlotWidget` API.

Using `setData` on plot item, instead of using `addCurve` if such item already exists should fix the issue, i think.

**Comment by vallsv** [comment]
That's maybe this stuff here

https://github.com/silx-kit/silx/blob/master/src/silx/gui/data/NXdataWidgets.py#L153

There is always a `self._plot.remove(kind=("curve",))`. It would be good to test to only remove unneeded curves.

Just few hints, i dont have time to play around.

**Comment by t20100** [comment]
Even `addCurve` preserves the "active" curve, but if all curves are removed and added again, the "active" curve is not preserved.
