### ISSUE TITLE
ThreadPoolPushButton test fails

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#352]
I get this traceback:

```
ERROR:silx.gui.widgets.ThreadPoolPushButton:Error while executing callable silx.gui.widgets.test.test_threadpoolpushbutton._computeFail.
Traceback (most recent call last):
  File "/Users/marius/Software/silx/build/lib.macosx-10.11-x86_64-3.5/silx/gui/widgets/ThreadPoolPushButton.py", line 56, in run
    result = self.__callable(*self.__args, **self.__kwargs)
  File "/Users/marius/Software/silx/build/lib.macosx-10.11-x86_64-3.5/silx/gui/widgets/test/test_threadpoolpushbutton.py", line 54, in _computeFail
    raise Exception("exception")
Exception: exception
```

Is this error supposed to be logged at the end of the test? I get this:

```
----------------------------------------------------------------------
Ran 691 tests in 62.155s

OK (skipped=1)
```

**Comment by vallsv** [comment]
That's just a log. it is a normal behaviour.

It allow to see real execeptions from the ThreadPool. If we filter that, you can have hidden problems.

**Comment by t20100** [comment]
There is a TestLogging context class in https://github.com/silx-kit/silx/blob/master/silx/testutils.py which _hides_ log messages but can count the number of occurrence.
So you avoid displaying an ERROR message in the log which can be confusing and you make sure it occurs.

**Comment by vallsv** [comment]
Sounds fine

**Comment by vasole** [comment]
I got confused the same way as Marius
