### ISSUE TITLE
Line profile/fit action ease of use

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3531]
Line profile does not select active curve, then fit action has nothing to fit by default, thus adding an extra step of selection of the curve.
This can be avoided by setting the active curve in the profile window or by changing the fit action to use the first curve in the plot (or maybe better, if there is only one curve, just use it for fitting).

**Comment by vallsv** [comment]
While it is only part of the fit action, i think there is no problem to tune it.

But it could make sense to select the profile by default no? You talk about the dedicated poping plot widget containing profile, right?

**Comment by t20100** [comment]
@vallsv yes, it is the dedicated plot widget containing the profile.

**Comment by t20100** [comment]
To me either way are OK, but I think it is less behaviour change to select the profile by default in the dedicated profile plot widget.

**Comment by t20100** [comment]
Actually looking at it, the change of behaviour in the fit sounds OK to me, see #3532.
