### ISSUE TITLE
silx view: `AttributeError` error when opening a group containing external links

### ISSUE THREAD

**Issue by loichuder** [silx-kit/silx#3537]
### Reproduce
- Open the file `/data/id11/3dxrd/blc12852/id11/analysis/bmg_l1_bmg_dct2/difspots.h5`
- Try to open the group `difspots`
- Unhandled exception pop-up appears

I tried on slurm (nice) and locally with the same result.

### Error details 

```
'ExternalLink' object has no attribute 'attrs'   File "/usr/lib/python3/dist-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 89, in lessThan
  File "/usr/lib/python3/dist-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 106, in __isNXentry
```

### Post-scriptum

It takes some time but jupyterlab-h5web opens it fine :smirk:

**Comment by t20100** [comment]
`ulimit -Sn unlimited` fixed the issue, this is indeed a too many files opened issue
