### ISSUE TITLE
Graphical tool to measure distance in pixels in image

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3538]
Feedback from Flint users.

They would like to have a tool to measure distance in pixels in images.

Such tool is very generic and probably have to deal with internal plot modes to make it work, so i open an issue here.

This is not a priority, but could be useful sometime.

**Comment by t20100** [comment]
Distance info could be added to the line profile tool or as a separated tool with an interaction mode and a toolbutton to add to the toolbar.
What do you need for flint?

Since the profile tool is not a mode, I would go for a dedicated tool/mode.

**Comment by vallsv** [comment]
I dont think it's a good idea to talk about profile here.

Maybe it could have featured based on a ROI.

But it also could be implemented as a mouse interaction, and only be displayed during the mouse interaction.
I prefer this last solution.

**Comment by vallsv** [comment]
I don't need the ROI solution, cause i can implement it in flint without problem.

**Comment by payno** [comment]
For information I just have the same need for an application
