### ISSUE TITLE
Cython compilation fails on Debian7

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#354]
On Debian 7 (Cython 0.19.1), forcing cythonization fails: `python setup.py build --force-cython`
First errors are in silx/math/fit/functions/functions.pyx and silx/math/fit/functions/functions_wrapper.pxd.
This works on Debian 8 (Cython 0.21).

Do we want cythonization to work on Debian 7 or bump required Cython version to 0.21?

**Comment by vasole** [comment]
I would suggest bump required cython version. If we provide generated code is exactly to be able to solve this type of problems.
