### ISSUE TITLE
CI seg fault at the end with PySide2 on appveyor Windows

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3553]
Error message is:
```
[...]
======== 1957 passed, 281 skipped, 1975 warnings in 513.58s (0:08:33) =========
Windows fatal exception: access violation
Current thread 0x00000ee4 (most recent call first):
<no Python frame>
Command exited with code -1073741819
```
This does not occur all the time, but very often.

Not reproduced local so far, but there is some seg fault at the end of running a GUI using pyside2.

**Comment by t20100** [comment]
Re-testing locally with PR #3554 and cannot reproduce neither issue at the end of the test nor seg fault at the end.

**Comment by vasole** [comment]
Might be related to https://github.com/silx-kit/silx/pull/3588

**Comment by t20100** [comment]
This no longer seems to happen with current `master` and some PRs (#3588, #3639) should have improved this.
So closing for now.
