### ISSUE TITLE
Improve ROI labels rendering with OpenGL backend

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3564]
Depending on label and background color, the label can be unreadable.

First raised here:  https://gitlab.esrf.fr/bliss/bliss/-/issues/3115

**Comment by t20100** [comment]
@vallsv some screenshot with auto black/white selection for the background:
![roi-labels](https://user-images.githubusercontent.com/9449698/143411980-785c8d6a-83bf-4673-a255-3d1a5f40d02d.png)
What do you think?

**Comment by vallsv** [comment]
Sounds perfect to me
