### ISSUE TITLE
Silx view fails to open due to Qt5Agg and Backend warn

### ISSUE THREAD

**Issue by simone-1991** [silx-kit/silx#3567]
Dear All,

I get the following error -
```
_Traceback (most recent call last):
  File "/usr/bin/silx", line 11, in <module>
    load_entry_point('silx==0.11.0', 'console_scripts', 'silx')()_
  File "/usr/lib64/python3.6/site-packages/silx/__main__.py", line 65, in main
    status = launcher.execute(sys.argv)
  File "/usr/lib64/python3.6/site-packages/silx/utils/launcher.py", line 295, in execute
    return command.execute(command_argv)
  File "/usr/lib64/python3.6/site-packages/silx/utils/launcher.py", line 129, in execute
    status = func(argv)
  File "/usr/lib64/python3.6/site-packages/silx/app/view/main.py", line 150, in main
    mainQt(options)
  File "/usr/lib64/python3.6/site-packages/silx/app/view/main.py", line 89, in mainQt
    from silx.gui.plot import matplotlib
  File "/usr/lib64/python3.6/site-packages/silx/gui/plot/__init__.py", line 63, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/usr/lib64/python3.6/site-packages/silx/gui/plot/PlotWidget.py", line 59, in <module>
    from . import matplotlib
  File "/usr/lib64/python3.6/site-packages/silx/gui/plot/matplotlib/__init__.py", line 67, in <module>
    _matplotlib_use('Qt5Agg', warn=True, force=False)
  File "/usr/lib64/python3.6/site-packages/silx/gui/plot/matplotlib/__init__.py", line 59, in _matplotlib_use
    matplotlib.use(backend, warn=warn, force=force)
TypeError: use() got an unexpected keyword argument 'warn'_
```
I think this error is due to some files in the .local and bin that got deleted by mistake. I cannot figure out which files I need to install again to get it working. I tried pip install matplotlib, PyQt5, and it did not help much. Using python 3.6
Your help will be highly appreciated.

**Comment by vallsv** [comment]
Hi, I think it's the same as https://github.com/silx-kit/silx/issues/2966

Could you take a look at your dependency?

The versions of silx and matplotlib you use?

**Comment by t20100** [comment]
You are most probably using a too recent version of `matplotlib` with an old version of `silx` (0.11.0 from you logs).
Uprading `silx` to the latest version should fix your issue.
 
It is also related to  #2890

**Comment by simone-1991** [comment]
ok, I did not compare all the required dependencies. 
But upgrading silx to version 0.11.0 works now.
I now get only few warnings, do you guys happen to know where this comes from - _WARNING:hdf5plugin:lz4 filter already loaded, skip it.
WARNING:silx.gui.data.DataViews:Plot3dView is not available
WARNING:silx.gui.data.DataViews:NXdataVolumeView is not available
WARNING:silx.gui.data.DataViews:3D visualization is not available
WARNING:silx.gui.data.DataViewer:_ _Plot3dView instantiation failed. View is ignored_ ??

**Comment by t20100** [comment]
> It said Successfully installed silx-0.15.2 . But silx --version gives me silx version 0.11.0.

You might have different versions installed on the system and in your home directory (if installed with `--user`). That can cause issues.
You can check from where silx is run: `which silx` and from where it is loaded in python:
```python
>>> import silx; print(silx.__file__)
```

> WARNING:hdf5plugin:lz4 filter already loaded, skip it.

This comes from the `hdf5plugin` package which provides HDF5 file compression filters for use with `h5py`. This warning tells that this filter is already loaded from elsewhere, most probably from a filter installed on the operating system or in conda (if in use).

> WARNING:silx.gui.data.DataViews:Plot3dView is not available
> WARNING:silx.gui.data.DataViews:NXdataVolumeView is not available
> WARNING:silx.gui.data.DataViews:3D visualization is not available
> WARNING:silx.gui.data.DataViewer: Plot3dView instantiation failed. View is ignored

This comes from OpenGL display not being available where you run `silx` (running through ssh maybe?) so 3D visualization are disabled.

**Comment by simone-1991** [comment]
Somehow updating silx resolved the issue. So, I think we can close this issue.
Thanks guys for all your comments and suggestions.
