### ISSUE TITLE
Clean up Sift tests

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#357]
For the 0.3.0 release we find that the unittests for sift should be cleaned up
- Using -v request user input for some tests
- there is global const USE_LENA which allows to use or not content from home
- maybe `test_transform.py` is the only one

```
valls@linkdick:~/workspace/silx.git$ grep -r paleo
silx/image/sift/test/test_transform.py:            image = scipy.misc.imread("/home/paleo/Titanium/test/frame0.png")
silx/image/sift/test/test_transform.py:            image2 = scipy.misc.imread("/home/paleo/Titanium/test/frame1.png")
valls@linkdick:~/workspace/silx.git$ grep -r USE_LENA
silx/image/sift/test/test_transform.py:USE_LENA = True
silx/image/sift/test/test_transform.py:        if (USE_LENA):
```

**Comment by kif** [comment]
On Wed, 12 Oct 2016 08:10:39 -0700
Valentin Valls <notifications@github.com> wrote:

> For the 0.3.0 release we find that the unittests for sift should be cleaned up
> 
> - Using -v request user input for some tests
> - there is global const USE_LENA which allows to use or not content from home
> - maybe `test_transform.py` is the only one
> 
> ```
> valls@linkdick:~/workspace/silx.git$ grep -r paleo
> silx/image/sift/test/test_transform.py:            image = scipy.misc.imread("/home/paleo/Titanium/test/frame0.png")
> silx/image/sift/test/test_transform.py:            image2 = scipy.misc.imread("/home/paleo/Titanium/test/frame1.png")
> valls@linkdick:~/workspace/silx.git$ grep -r USE_LENA
> silx/image/sift/test/test_transform.py:USE_LENA = True
> silx/image/sift/test/test_transform.py:        if (USE_LENA):
> ```

I agree cleaning-up is needed...
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
Looks to be fixed
