### ISSUE TITLE
[plot] ValueError: year 0 is out of range

### ISSUE THREAD

**Issue by tobiasvos** [silx-kit/silx#3570]
Hi all,

We encountered an error for a `PlotWidget` with a datetime x-axis. The issue occurs when you zoom out too much. Sometimes this can happen when the mouse wheel is rotated too quickly.

A `ValueError` occurs when a year outside the range [1, 9999] is passed to this `datetime.datetime()` constructor: https://github.com/silx-kit/silx/blob/master/src/silx/gui/plot/_utils/dtime_ticklayout.py#L163.

This happens when on line 363 `niceSpacing` exceeds `dVal`. For example: if the lower limit of the x-axis is 1500 years, `niceSpacing` can be 1000 but it cannot become 2000 years. If the lower limit is 400 years, `niceSpacing` can be 200 but it cannot become 500 years. Such a condition occurs more rapidly if the plot widget is small (small `nTicks`).

Perhaps a similar solution could be used as for issue #3192.

I have included the traceback. I am using silx version 0.9.0 on Debian 10. For the time being, I have solved our issue by setting limits and range constraints for the x-axis.

[traceback.txt](https://github.com/silx-kit/silx/files/7661184/traceback.txt)

**Comment by t20100** [comment]
Thanks for the report!
There are indeed a couple of issues when getting out of `datetime` supported range.

**Comment by t20100** [comment]
The Pull Request https://github.com/silx-kit/silx/pull/3597 should fix this issue (and another one also concerning datetime range).

**Comment by tobiasvos** [comment]
Great, thanks for the fix!
