### ISSUE TITLE
[silx.math.fit] peak_search returns peak indices as float

### ISSUE THREAD

**Issue by loichuder** [silx-kit/silx#3579]
Not sure if that is intended.

The [doc of the peak_search function](http://www.silx.org/doc/silx/latest/modules/math/fit/peaksearch.html#silx.math.fit.peaks.peak_search) says it will return *peak indices*. 

I would therefore expect them to be `int` to be reused directly like `data[peak_index]`.

**Comment by vallsv** [comment]
Previously `numpy` was supporting float as index. That's many way this was not catched before.

**Comment by t20100** [comment]
From a quick look at the [C code underneath](https://github.com/silx-kit/silx/blob/master/src/silx/math/fit/peaks/src/peaks.c), it looks to convert `long` to `double` to store in peaks. It would need a second look but using `long int` all the way sounds better.

**Comment by vasole** [comment]
I guess it returns a float in order to allow some weighted mean at a certain point. For instance to use not just the max index but a weighted max of the two channels around. If that is never going to happen, it is another business.

**Comment by t20100** [comment]
OK, is that an issue to use integers here now that float can not longer be used as array indices, and to convert to floats when needing for weighted mean?

**Comment by vasole** [comment]
In PyMca is the caller who takes care of taking the int of the returned values thus working in current and in future implementations.

It looks to me more a problem of the documentation but take the approach you prefer. It will not break anything at my side.

**Comment by loichuder** [comment]
> It looks to me more a problem of the documentation

I agree. In the end, I don't mind much getting `int` or `float` but the return type should be clearly stated by the documentation.

**Comment by t20100** [comment]
OK, then let's clarify the documentation rather than updating the code, sounds safer since this was like that for years.
