### ISSUE TITLE
Some line style are not properly displayed in OpenGL

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3595]
No idea if it's a regression.

I don't expect a perfect compatibility, but here it's really unreadable.

### OpenGL
![image](https://user-images.githubusercontent.com/7579321/152353084-28ffcb78-57bf-4fda-a781-6c0d9a4b6955.png)

### Matplotlib
![image](https://user-images.githubusercontent.com/7579321/152353143-725c0f4c-d95d-4f86-a6be-0fa0e65a8719.png)

**Comment by t20100** [comment]
Pretty bad indeed... As it is currently with OpenGL, the rendering of curves is OK for an X/Y aspect ratio of 1, if too far from 1, it becomes rubbish.
Should be easy to fix.

Easy way to reproduce:
```
from silx import sx, config; import numpy
config.DEFAULT_PLOT_BACKEND = 'gl'
sx.plot(numpy.arange(100) * 1000, '-.')
```
