### ISSUE TITLE
plot1d: Autoscale does not take into account the error bar

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3606]
Tested together with @alejandrohomsp

With a dense data and huge error bar it looks like the plot is not fully included in the plot.

In fact It was only the error bar which was outside.

But, what about including the error bar as part of the data? The result should be better.

**Comment by t20100** [comment]
Yes, from what I recall the bounding box of curves and scatters does not includes error bars.

It sounds reasonable to me to include error bars in the computation of the bounding box.

**Comment by t20100** [comment]
https://github.com/silx-kit/silx/blob/bf182fd14eb79b0458220f79a5e3b6d27ed7475d/src/silx/gui/plot/items/core.py#L1494
