### ISSUE TITLE
roi label in a plot

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#3620]
Hi!

I'd like to have roi labels visible but can't find their objects to properly position them. Can you please point me in the right direction?
Here, the roi label is too low and hidden under the lower axis:
![image](https://user-images.githubusercontent.com/17322580/167293647-722f189e-346d-4311-a1c9-6a8026e315bf.png)
...when the roi becomes smaller, the label appears:
![image](https://user-images.githubusercontent.com/17322580/167293691-c78fb19d-9709-475e-8717-253d584a001f.png)

I have a roiManager object that has the rois and I have a slot for its sigRoiChanged signal where I want to re-position the labels.
Thank you in advance!

**Comment by vallsv** [comment]
Hi.

There is no public API to do that, but you could inherit the `ArcRoi` class and override `_updateShape`.

```
from silx.gui.plot import utils
    def _updateShape(self):
       ArcRoi._updateShape(self)
        with utils.blockSignals(self._handleLabel):
            self._handleLabel.setPosition(pos[0], pos[1])
```

Or use the callback you was talking about and update the stuff manually with the private `_handleLabel`.

```
    def _callback(self, *args, **kwargs):
        with utils.blockSignals(self._handleLabel):
            self._handleLabel.setPosition(mypos[0], mypos[1])
```

I think the silx ROI should provide a default API you could inherit in this case, for example `_updateLabelPosition`.

**Comment by vallsv** [comment]
A ROI also provide the signal `sigRegionChanged`, if you like.

**Comment by kklmn** [comment]
Thank you @vallsv!
`roi._handleLabel` it was that I was looking for!
Now I have it always in view.
