### ISSUE TITLE
Error while opening h5 files containing virtual datasets

### ISSUE THREAD

**Issue by Kharitok** [silx-kit/silx#3634]
Hi!

I'm getting the following errors while trying to open a .h5 file containing a virtual dataset in silx view.
This file opens fine with h5py package giving no errors or warnings.

<class 'AttributeError'> H5Node has no attribute physical_filename
Please report details

H5Node has no attribute physical_filename   File "/home/kharitok/.local/lib/python3.6/site-packages/silx/gui/data/Hdf5TableView.py", line 273, in data
    value = value(self.__obj)
  File "/home/kharitok/.local/lib/python3.6/site-packages/silx/gui/data/Hdf5TableView.py", line 425, in _physical_location
    return x.physical_filename + SEPARATOR + x.physical_name
  File "/home/kharitok/.local/lib/python3.6/site-packages/silx/gui/hdf5/_utils.py", line 161, in __getattr__
    raise AttributeError("H5Node has no attribute %s" % name)

**Comment by vallsv** [comment]
HI.

Which version of silx do you use?

Could it be possible to share your file? or a subset of it which still fail?

**Comment by Kharitok** [comment]
Hi it's version 1.0.0.

I've attached a .zip containing two example files one with a  dataset in 'data' which opens fine and another one containing a virtual dataset with a link to  the first one.  This on silx fails to open for me.  
The code to replicate the files is in .py file.


[example_virtual.zip](https://github.com/silx-kit/silx/files/9234942/example_virtual.zip)

**Comment by vasole** [comment]
I cannot reproduce the problem (under windows).

![image](https://user-images.githubusercontent.com/5636251/182181723-71ffd611-4fa5-41c8-b9cb-ac0f9e1459c4.png)

**Comment by vallsv** [comment]
Same as Armando on Linux.

Using both your files, or regenerated onces.

Could it be because of your version of python or h5py?

Here is what i use
```
h5py                      3.5.0           py37hd430a98_100  
numpy                     1.21.6           py37h976b520_0    conda-forge
python                    3.7.13               h12debd9_0  
silx-base                 1.0.0            py37hfb7772e_1    conda-forge
```

**Comment by Kharitok** [comment]
Update of h5py and numpy solved the problem.

Thanks!

**Comment by vallsv** [comment]
@t20100 there is maybe an extra constraint on `h5py` to put to the project now?

**Comment by vallsv** [comment]
@Kharitok in case, do you remember which `h5py` version you was using?

**Comment by Kharitok** [comment]
Previously it was 2.8.0 and I switched to  3.1.0

**Comment by t20100** [comment]
> @t20100 there is maybe an extra constraint on h5py to put to the project now?

Yes, maybe, and there is no minimal required version for h5py, so it is worth checking
