### ISSUE TITLE
Improve Windows installer and advertise it

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3636]
- Advertise Windows installer link in documentation
- Change the license displayed in the installer since the project `LICENSE` file is not suited for it... Main license is GPL (from PyQt), and probably licenses from all embedded softwares should be provided..

Thanks @andygotz for the feedback

**Comment by vasole** [comment]
What about shipping it with PySide6?

**Comment by t20100** [comment]
Yes, why not, but we've way less tested silx with PySide6 than with PyQt5.
