### ISSUE TITLE
inconsistent behaviour of toolTip for silx.gui.widgets.ElidedLabel and generic QWidget

### ISSUE THREAD

**Issue by malte-storm** [silx-kit/silx#3641]
Hi,

the silx.gui.widgets.ElidedLabel redefines the toolTip as a qt.Property which is inconsistent with the generic toolTip method (using Qt5).
Is there a reason for this behaviour? This raises exceptions when implementing an eventFilter for toolTips because the property is not callable.
As the ElidedLabel is a subclassed QLabel, I think the toolTip should be consistent in both child and parent.

The ElidedLabel is used as base class for the _PositionInfoLabel used in the PositionInfo widget in the Plot2D widget and I noticed the issue when implementing an eventFilter for an application with a Plot2D widget.

```
label = QtWidgets.QLabel()
elided_label = silx.gui.widgets.ElidedLabel.ElidedLabel()

type(label.toolTip)
Out: builtin_function_or_method

type(elided_label.toolTip)
Out: str
```

**Comment by vallsv** [comment]
It was probably to expose it into qtdesigner.

But it's true that as it's an already inherited  property, there is probably no need to define the property, and only need to override the default getter and setter.

There was problem at the time to define both function and property with the same name (which is probably always the case in Qt).

For other properties it would be good to check what is the result of the following code now-a-day.
```
    @pyqtProperty(int)
    def total(self):
        return self._total

    @total.setter
    def total(self, value):
        self._total = value
```

I probably have some times to take a look next week if you like.

**Comment by malte-storm** [comment]
I implemented a workaround for the time being in my eventFilter but, yes, I guess it would be nice to have this issue solved properly if you have the time.

**Comment by vallsv** [comment]
By the way, in silx we historicolly use to use `getProp()/setProp()` instead of the qt convention `prop()/setProp()`

**Comment by malte-storm** [comment]
Yes, that solves the issue for me. Thanks for looking into it.
