### ISSUE TITLE
Remove Qhull from third_party and use scipy

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3675]
What about removing the copy of scipy's QHull Delaunay wrapper in `silx.third_party` and use `scipy` directly?
`scipy` can be kept optional by disabling features based on its availability.

That would simplify `setup.py` and specific stripping for Linux packaging (see #3674).

**Comment by vasole** [comment]
But it would heavily impact scatter plot visualization, wouldn't it?

**Comment by vasole** [comment]
Is https://matplotlib.org/stable/api/tri_api.html#matplotlib-tri worthy? I think you already evaluated it.

**Comment by t20100** [comment]
If scipy is not present, it would remove the `SOLID` visualization mode out of:
https://github.com/silx-kit/silx/blob/65eeb0ecadd49666509c8ad92c365c4a49ce11ad/src/silx/gui/plot/items/scatter.py#L276-L280

Yes, I tried it, but it was some 5 years ago and I didn't documented the outcome enough at that time (#1326). I recall having trouble running it in a separated thread, but not sure.
