### ISSUE TITLE
[plot gl] ROIs not displayed with solid lines

### ISSUE THREAD

**Issue by tifuchs** [silx-kit/silx#3681]
Might be related to #3595.

![grafik](https://user-images.githubusercontent.com/50143413/192113824-ac0a78de-072f-47a4-8c68-5c71fea137fa.png)

![grafik](https://user-images.githubusercontent.com/50143413/192113878-78f62efd-67af-4d48-9a21-c5b656203e91.png)

### Way to reproduce:

1. Before running `examples/plotInteractiveImageROI.py`, change line https://github.com/silx-kit/silx/blob/1ae49bae6ef218a73b15e555563713bee06ed341/examples/plotInteractiveImageROI.py#L81 to `roi.setLineStyle('-')`.
2. Toggle on OpenGL rendering. Or create Plot2D directly with `backend='opengl'`

Sometimes the rois still appear with the opengl backend on, but only distorted.

### Reproduced:

on Win10, silx 1.0.0 and latest version 1ae49bae6ef218a73b15e555563713bee06ed341. On two machines.

**Comment by t20100** [comment]
Hi,

I could not reproduce on Windows10 neither with silx v1.0.0 nor with current tip of the project with python3.8.

It does work with `roi.setLineStyle('--') ` but not with `'-'`, right? Could you also try with `-.` and `:`?

Which Qt binding do you use? PyQt5?
Which version of python, pyopengl? (even if it shouldn't be an issue)
Is it a high resolution display or not?

**Comment by tifuchs** [comment]
Hi,

strange... I have tried on all three Win10 computers I have access to, with the same result.
`-.` and `:` are working fine.

At the moment I have only tried the PyQt5 (e.g. PyQt5=5.9.2 / 5.15.7) bindings delivered by a full anaconda install:

```bash
conda create -n py38 python=3.8 anaconda
pip install silx
pip install pyopengl
```
with python 3.9 and python 3.8 and tested all versions of pyopengl=3.1.* from pip.

The issue is present on high-dpi screens and on screens without dpi scaling.

**Comment by vasole** [comment]
I cannot reproduce it either, but I have not tried conda yet.

**Comment by vasole** [comment]
Same here. Used the very same commands as @t20100 with no problem.

**Comment by t20100** [comment]
This is strange.

Is there issues with line drawing with OpenGL (plotting curves, profile tool on images) in other parts of `silx`?

E.g., does this plot something?
```python
>>> from silx import sx, config
>>> config.DEFAULT_PLOT_BACKEND = 'gl'
>>> sx.plot([1, 2, 1])
```

Does the `examples\viewer3DVolume.py` shows a yellowish bounding box  and red/gree/blue axes?

**Comment by t20100** [comment]
Also what happens if you change the line width?
https://github.com/silx-kit/silx/blob/1ae49bae6ef218a73b15e555563713bee06ed341/examples/plotInteractiveImageROI.py#L80

**Comment by tifuchs** [comment]
Yes, this is the strange part. Everything else seems to work fine.

![grafik](https://user-images.githubusercontent.com/50143413/195373297-f14fc1be-5cde-41cb-a891-eed047d2d280.png)


![grafik](https://user-images.githubusercontent.com/50143413/195373125-908b1c30-e76d-4edb-ba41-71b3b7fc4e0c.png)

I will try to install the python environment only with the packages from pypi. Maybe it is related to some other dependency. 

<details><summary>test env</summary>
<p>

Name                    Version                   Build  Channel
_anaconda_depends         2022.05                  py38_0
aiohttp                   3.8.1            py38h2bbff1b_1
aiosignal                 1.2.0              pyhd3eb1b0_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda                  custom                   py38_1
anaconda-client           1.11.0           py38haa95532_0
anaconda-project          0.11.1           py38haa95532_0
anyio                     3.5.0            py38haa95532_0
aom                       3.5.0                h63175ca_0    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0
arrow                     1.2.2              pyhd3eb1b0_0
astroid                   2.11.7           py38haa95532_0
astropy                   5.1              py38h080aedc_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-timeout             4.0.1              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     21.4.0             pyhd3eb1b0_0
automat                   20.2.0                     py_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py38h2bbff1b_1
beautifulsoup4            4.11.1           py38haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
bitarray                  2.5.1            py38h2bbff1b_0
bkcharts                  0.2              py38haa95532_1
black                     22.6.0           py38haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.1               h74325e0_3    conda-forge
bokeh                     2.4.3            py38haa95532_0
boto3                     1.24.28          py38haa95532_0
botocore                  1.27.28          py38haa95532_0
bottleneck                1.3.5            py38h080aedc_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
c-blosc2                  2.4.1                h183a6f4_0    conda-forge
ca-certificates           2022.07.19           haa95532_0
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2022.9.14        py38haa95532_0
cffi                      1.15.1           py38h2bbff1b_0
cfitsio                   4.1.0                h5a969a9_0    conda-forge
chardet                   4.0.0           py38haa95532_1003
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py38haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
clyent                    1.2.2                    py38_1
colorama                  0.4.5            py38haa95532_0
colorcet                  3.0.0            py38haa95532_0
comtypes                  1.1.10          py38haa95532_1002
conda                     22.9.0           py38haa95532_0
conda-content-trust       0.1.3            py38haa95532_0
conda-pack                0.6.0              pyhd3eb1b0_0
conda-package-handling    1.9.0            py38h8cc25b3_0
conda-token               0.4.0              pyhd3eb1b0_0
console_shortcut          0.1.1                         4
constantly                15.1.0             pyh2b92418_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              37.0.1           py38h21b164f_0
cssselect                 1.1.0              pyhd3eb1b0_0
curl                      7.84.0               h2bbff1b_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    0.29.32          py38hd77b12b_0
cytoolz                   0.11.0           py38he774522_0
daal4py                   2021.5.0         py38h8cb3d55_0
dal                       2021.5.0           haa95532_796
dask                      2022.2.1           pyhd3eb1b0_0
dask-core                 2022.2.1           pyhd3eb1b0_0
dataclasses               0.8                pyh6d0b6a4_7
datashader                0.13.0             pyhd3eb1b0_1
datashape                 0.5.4            py38haa95532_1
dav1d                     1.0.0                h8ffe710_1    conda-forge
debugpy                   1.5.1            py38hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.4              pyhd3eb1b0_0
distributed               2022.2.1           pyhd3eb1b0_0
docutils                  0.18.1           py38haa95532_3
entrypoints               0.4              py38haa95532_0
et_xmlfile                1.1.0            py38haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
fabio                     0.14.0                   pypi_0    pypi
filelock                  3.6.0              pyhd3eb1b0_0
flake8                    4.0.1              pyhd3eb1b0_1
flask                     2.1.3            py38haa95532_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
frozenlist                1.2.0            py38h2bbff1b_0
fsspec                    2022.7.1         py38haa95532_0
future                    0.18.2                   py38_1
gensim                    4.1.2            py38hd77b12b_0
gettext                   0.19.8.1          h5728263_1009    conda-forge
giflib                    5.2.1                h62dcd97_0
glib                      2.74.0               h12be248_0    conda-forge
glib-tools                2.74.0               h12be248_0    conda-forge
glob2                     0.7                pyhd3eb1b0_0
google-api-core           2.10.1           py38haa95532_0
google-auth               2.6.0              pyhd3eb1b0_0
google-cloud-core         2.2.2              pyhd3eb1b0_0
google-cloud-storage      1.43.0           py38haa95532_0
google-crc32c             1.1.2            py38h2bbff1b_0
google-resumable-media    1.3.1              pyhd3eb1b0_1
googleapis-common-protos  1.56.4           py38haa95532_0
greenlet                  1.1.1            py38hd77b12b_0
grpcio                    1.42.0           py38hc60d5dd_0
gst-plugins-base          1.20.3               h001b923_2    conda-forge
gstreamer                 1.20.3               h6b5321d_2    conda-forge
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1              pyhd3eb1b0_0
holoviews                 1.15.0           py38haa95532_0
hvplot                    0.8.0            py38haa95532_0
hyperlink                 21.0.0             pyhd3eb1b0_0
icc_rt                    2022.1.0             h6049295_1
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd3eb1b0_0
imagecodecs               2022.9.26        py38h1fa618c_0    conda-forge
imageio                   2.19.3           py38haa95532_0
imagesize                 1.4.1            py38haa95532_0
importlib-metadata        4.11.3           py38haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
incremental               21.3.0             pyhd3eb1b0_0
inflection                0.5.1            py38haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intake                    0.6.5              pyhd3eb1b0_0
intel-openmp              2022.1.0          h59b6b97_3788
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.15.2           py38haa95532_0
ipython                   7.31.1           py38haa95532_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
itemadapter               0.3.0              pyhd3eb1b0_0
itemloaders               1.0.4              pyhd3eb1b0_1
itsdangerous              2.0.1              pyhd3eb1b0_0
jdcal                     1.4.1              pyhd3eb1b0_0
jedi                      0.18.1           py38haa95532_1
jellyfish                 0.9.0            py38h2bbff1b_0
jinja2                    3.0.3              pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jmespath                  0.10.0             pyhd3eb1b0_0
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9e                   h2bbff1b_0
jq                        1.6                  haa95532_1
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.16.0           py38haa95532_0
jupyter                   1.0.0            py38haa95532_8
jupyter_client            7.3.5            py38haa95532_0
jupyter_console           6.4.3              pyhd3eb1b0_0
jupyter_core              4.10.0           py38haa95532_0
jupyter_server            1.18.1           py38haa95532_0
jupyterlab                3.4.4            py38haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.12.0           py38haa95532_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
jxrlib                    1.1                  he774522_2
keyring                   23.4.0           py38haa95532_0
kiwisolver                1.4.2            py38hd77b12b_0
krb5                      1.19.3               h1176d77_0    conda-forge
lazy-object-proxy         1.6.0            py38h2bbff1b_0
lcms2                     2.12                 h83e58a3_0
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libarchive                3.6.1                hebabd0d_0
libavif                   0.10.1               h8f5c5bc_2    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  14.0.6          default_hf4acfee_0
libclang13                14.0.6          default_h8992b79_0
libcrc32c                 1.1.1                ha925a31_2
libcurl                   7.84.0               h86230a5_0
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                hd77b12b_4
libglib                   2.74.0               h79619a9_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
liblief                   0.11.5               hd77b12b_1
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.38               h19919ed_0    conda-forge
libprotobuf               3.20.1               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.4.0                h8a3f274_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                h8ffe710_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
libzlib                   1.2.12               hcfcfb64_3    conda-forge
libzopfli                 1.0.3                ha925a31_0
llvmlite                  0.39.1           py38h19421c1_0    conda-forge
locket                    1.0.0            py38haa95532_0
lxml                      4.9.1            py38h1985fb9_0
lz4-c                     1.9.3                h2bbff1b_1
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.4            py38haa95532_0
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.5.2            py38haa95532_0
matplotlib-base           3.5.2            py38hd77b12b_0
matplotlib-inline         0.1.6            py38haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
menuinst                  1.4.19           py38h59b6b97_0
mistune                   0.8.4           py38he774522_1000
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
mock                      4.0.3              pyhd3eb1b0_0
mpmath                    1.2.1            py38haa95532_0
msgpack-python            1.0.3            py38h59b6b97_0
msys2-conda-epoch         20160418                      1
multidict                 5.2.0            py38h2bbff1b_3
multipledispatch          0.6.0                    py38_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py38haa95532_1
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13           py38haa95532_0
nbconvert                 6.4.4            py38haa95532_0
nbformat                  5.5.0            py38haa95532_0
nest-asyncio              1.5.5            py38haa95532_0
networkx                  2.8.4            py38haa95532_0
nltk                      3.7                pyhd3eb1b0_0
nose                      1.3.7           pyhd3eb1b0_1008
notebook                  6.4.12           py38haa95532_0
numba                     0.56.2           py38h3873db4_0    conda-forge
numexpr                   2.8.3            py38hb80d3ca_0
numpy                     1.23.3                   pypi_0    pypi
numpydoc                  1.4.0            py38haa95532_0
olefile                   0.46               pyhd3eb1b0_0
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.10           py38h2bbff1b_0
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.4            py38hd77b12b_0
pandocfilters             1.5.0              pyhd3eb1b0_0
panel                     0.13.1           py38haa95532_0
param                     1.12.0             pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parsel                    1.6.0            py38haa95532_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_1
pathspec                  0.9.0            py38haa95532_0
patsy                     0.5.2            py38haa95532_1
pcre2                     10.37                h0ff8eda_1
pep8                      1.7.1            py38haa95532_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0            py38hdc2b20a_1
pip                       22.1.2           py38haa95532_0
pkginfo                   1.8.2              pyhd3eb1b0_0
pkgutil-resolve-name      1.3.10           py38haa95532_0
platformdirs              2.5.2            py38haa95532_0
plotly                    5.9.0            py38haa95532_0
pluggy                    1.0.0            py38haa95532_1
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1           py38haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
protego                   0.1.16                     py_0
protobuf                  3.20.1           py38hd77b12b_0
psutil                    5.9.0            py38h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0             pyhd3eb1b0_0
py-lief                   0.11.5           py38hd77b12b_1
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycodestyle               2.8.0              pyhd3eb1b0_0
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyct                      0.4.8            py38haa95532_1
pycurl                    7.45.1           py38hcd4344a_0
pydispatcher              2.0.5            py38haa95532_2
pydocstyle                6.1.1              pyhd3eb1b0_0
pyerfa                    2.0.0            py38h2bbff1b_0
pyflakes                  2.4.0              pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyhamcrest                2.0.2              pyhd3eb1b0_2
pylint                    2.14.5           py38haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.5.0            py38h8cc25b3_0
pyodbc                    4.0.34           py38hd77b12b_0
pyopengl                  3.1.6                    pypi_0    pypi
pyopengl-accelerate       3.1.6                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py38haa95532_0
pyqt                      5.15.7           py38h75e37d8_0    conda-forge
pyqt5-sip                 12.11.0          py38h885f38d_0    conda-forge
pyqtwebengine             5.15.7           py38h75e37d8_0    conda-forge
pyreadline                2.1                      py38_1
pyrsistent                0.18.0           py38h196d8e1_0
pysocks                   1.7.1            py38haa95532_0
pytables                  3.6.1            py38ha5be198_0
pytest                    7.1.2            py38haa95532_0
python                    3.8.13               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py38haa95532_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-lsp-black          1.2.1            py38haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.5.0            py38haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
python-snappy             0.6.0            py38hd77b12b_3
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1           py38haa95532_0
pyviz_comms               2.0.2              pyhd3eb1b0_0
pywavelets                1.3.0            py38h2bbff1b_0
pywin32                   302              py38h2bbff1b_2
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  2.0.2            py38h5da7b33_0
pyyaml                    6.0              py38h2bbff1b_1
pyzmq                     23.2.0           py38hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.15.4               h2d74725_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
qt-webengine              5.15.4               h7325c83_3    conda-forge
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.3.2            py38haa95532_0
qtpy                      2.2.0            py38haa95532_0
queuelib                  1.5.0            py38haa95532_0
regex                     2022.7.9         py38h2bbff1b_0
requests                  2.28.1           py38haa95532_0
requests-file             1.5.1              pyhd3eb1b0_0
rope                      0.22.0             pyhd3eb1b0_0
rsa                       4.7.2              pyhd3eb1b0_1
rtree                     0.9.7            py38h2eaa2aa_1
ruamel_yaml               0.15.100         py38h2bbff1b_0
s3transfer                0.6.0            py38haa95532_0
scikit-image              0.19.2           py38hf11a4ad_0
scikit-learn              1.1.1            py38hd77b12b_0
scikit-learn-intelex      2021.5.0         py38haa95532_0
scipy                     1.9.1            py38h91810f7_0    conda-forge
scrapy                    2.6.2            py38haa95532_0
seaborn                   0.11.2             pyhd3eb1b0_0
send2trash                1.8.0              pyhd3eb1b0_1
service_identity          18.1.0             pyhd3eb1b0_1
setuptools                63.4.1           py38haa95532_0
silx                      1.1.0a0                  pypi_0    pypi
sip                       6.6.2            py38hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smart_open                5.2.1            py38haa95532_0
snappy                    1.1.9                h6c2663c_0
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcollections         2.1.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.1              pyhd3eb1b0_0
sphinx                    5.0.2            py38haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.3.3            py38haa95532_0
spyder-kernels            2.3.3            py38haa95532_0
sqlalchemy                1.4.39           py38h2bbff1b_0
sqlite                    3.39.3               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.13.2           py38h2bbff1b_0
sympy                     1.10.1           py38haa95532_0
tabulate                  0.8.10           py38haa95532_0
tbb                       2021.5.0             h59b6b97_0
tbb4py                    2021.5.0         py38h59b6b97_0
tblib                     1.7.0              pyhd3eb1b0_0
tenacity                  8.0.1            py38haa95532_1
terminado                 0.13.1           py38haa95532_0
testpath                  0.6.0            py38haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.7.2           pyhd3eb1b0_2
tinycss                   0.4             pyhd3eb1b0_1002
tk                        8.6.12               h2bbff1b_0
tldextract                3.2.0              pyhd3eb1b0_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py38haa95532_0
tomlkit                   0.11.1           py38haa95532_0
toolz                     0.11.2             pyhd3eb1b0_0
tornado                   6.2              py38h2bbff1b_0
tqdm                      4.64.1           py38haa95532_0
traitlets                 5.1.1              pyhd3eb1b0_0
twisted                   22.2.0           py38h2bbff1b_1
twisted-iocpsupport       1.0.2            py38h2bbff1b_0
typed-ast                 1.4.3            py38h2bbff1b_1
typing-extensions         4.3.0            py38haa95532_0
typing_extensions         4.3.0            py38haa95532_0
ucrt                      10.0.20348.0         haa95532_0
ujson                     5.4.0            py38hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.11          py38haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
w3lib                     1.21.0             pyhd3eb1b0_0
watchdog                  2.1.6            py38haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
websocket-client          0.58.0           py38haa95532_4
werkzeug                  2.0.3              pyhd3eb1b0_0
whatthepatch              1.0.2            py38haa95532_0
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2            py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1           py38h2bbff1b_0
xarray                    0.20.1             pyhd3eb1b0_1
xlrd                      2.0.1              pyhd3eb1b0_0
xlsxwriter                3.0.3              pyhd3eb1b0_0
xlwings                   0.24.9           py38haa95532_0
xz                        5.2.6                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
yarl                      1.8.1            py38h2bbff1b_0
zeromq                    4.3.4                hd77b12b_0
zfp                       1.0.0                h0e60522_1    conda-forge
zict                      2.1.0            py38haa95532_0
zipp                      3.8.0            py38haa95532_0
zlib                      1.2.12               h8cc25b3_3
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zope                      1.0                      py38_1
zope.interface            5.4.0            py38h2bbff1b_0
zstd                      1.5.2                h19a0ad4_0

</p>
</details>

Or it is related to the graphics driver. Up to now I only encountered this issue on older AMD graphic units.  

I also asked my co-workers to test this issue. Neither of them can reproduce this issue.

**Comment by tifuchs** [comment]
Changing the line width also does not fix the issue.

**Comment by t20100** [comment]
OK, thanks for the testing!
This is really strange because it is the same code plotting curves and ROIs... only the transform matrix is different.

> on older AMD graphic units
Yes that could be a track to follow.

BTW, was it working with older version of `silx`?

**Comment by tifuchs** [comment]
One more hint :)
The lines reappear, if the markers for dragging of the rois are not on the display. 
![grafik](https://user-images.githubusercontent.com/50143413/195382574-af61d00c-bb09-47f2-add1-91016bd079c3.png)
![grafik](https://user-images.githubusercontent.com/50143413/195382728-3c457195-3f26-4351-abc3-cde50371494d.png)

**Comment by t20100** [comment]
Interesting! So, does this only displays the square markers?

```python
from silx import sx, config
config.DEFAULT_PLOT_BACKEND = 'gl'
sx.plot([1, 2, 1], 's-')
```

**Comment by tifuchs** [comment]
The plot is displayed correctly with lines and squares. 

It has something to do with the edit markers. 
Also if the roi center marker (+) is on screen, the lines are not drawn. 

If I disable editing and the lines are shown (no markers on screen), the lines disappear.
![grafik](https://user-images.githubusercontent.com/50143413/195388442-eb548c0a-e3f7-4868-935e-7a8ff85e0137.png)
![grafik](https://user-images.githubusercontent.com/50143413/195388496-99ff0338-872c-40a4-9033-dd1bed1053b4.png)

**Comment by t20100** [comment]
This is narrowing down..

If outside of the visible area, the rendering of the anchors is not done, and the anchors are rendered before the line, so it seems the anchor rendering is impairing the line rendering... and looking at it, there's a few issues in the code around that. However, there's also the issue when the anchors are disabled...

That might be related to PR #3203, could you try with silx v0.13.0?
You will need the example script from this release: https://raw.githubusercontent.com/silx-kit/silx/v0.13.2/examples/plotInteractiveImageROI.py

Also I'm preparing a patch to try by changing things in markers/lines rendering.

**Comment by tifuchs** [comment]
The issue is also present in version 0.13.0 and 0.13.2.

I made a mistake in the previous comment. I actually switched off the roi (as you can also see in the screenshots) instead of just disabling the edit mode. 

As long as no edit markers are on screen, the lines are present regardless of whether I switch on or off the edit mode.

**Comment by t20100** [comment]
OK, great, Thanks for the testing!

I made some changes in the marker rendering. Not sure it is fixing this issue, but it is worth checking if you don't mind:

It's in this branch: https://github.com/t20100/silx/tree/fix-plot-gl
This changes can be seen here: https://github.com/silx-kit/silx/compare/master...t20100:silx:fix-plot-gl?expand=1
You can download the corresponding .zip here: https://codeload.github.com/t20100/silx/zip/refs/heads/fix-plot-gl

**Comment by tifuchs** [comment]
Awesome, I think you've got it 👍
I tested the fix on two affected machines and this solves the problem on both of them.
Thanks for the support!

**Comment by t20100** [comment]
Good to hear!

That's kind of hard to track an issue without reproducing it!
