### ISSUE TITLE
ArrayTableWidget editing without clearing previous data

### ISSUE THREAD

**Issue by tifuchs** [silx-kit/silx#3682]
Hi everybody,

If the data in a cell of a `silx.gui.data.ArrayTableWidget` is about to be edited (for example by double clicking it), the current data in this cell is not shown in the editor:
![grafik](https://user-images.githubusercontent.com/50143413/192146816-78cd2df0-72aa-465c-a07c-84781f7a74e1.png)
![grafik](https://user-images.githubusercontent.com/50143413/192146839-12cee0b7-340b-4c76-b57c-3b9ab2b02c2b.png)

I'd say that it would be better if the editor would be filled with the current data:
![grafik](https://user-images.githubusercontent.com/50143413/192146859-d7647ddf-16c3-4964-a6e1-2ffced850e1f.png)

### Possible implementation
To enable this behaviour, the `silx.gui.data.ArrayTableWidget.data` method can return the data of the cell for the Qt.EditRole.

Here is my version, where I just return the data as str (since it is anyways converted back to the array dtype in `setData` ):
tifuchs@22158acc45b60b281b42ae162df29694002f50b7

Can I create a PR for this?

Cheers,
Timo

**Comment by t20100** [comment]
Hi,

Thanks for the issue report!

Yes, please, open a PR with the fix! We are planing a release in the near future so it will be included in it.

Best,
