### ISSUE TITLE
problems with matplotlib 3.6.0

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#3684]
Hello, 

I found problems updating to matplotlib 3.6.0. For example, using silx view:

![image](https://user-images.githubusercontent.com/502315/192825464-5bd5892b-1901-44ec-a98b-51f9a78d0743.png)

I used the file: /tmp_14_days/srio/case1_comsyl.h5

No problems with matplotlib 3.5.3

Thanks!

**Comment by t20100** [comment]
Hi,

Thanks for the report!

We fixed it in this commit https://github.com/silx-kit/silx/pull/3639/commits/e40f5aa3cbf74a51e9520d46d4538ed36faca0a3 and it will be available in the coming release.
