### ISSUE TITLE
`silx view` depends on `hdf5plugin`

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#3687]
`silx view` crashes at start-up when installed from a debian package:
```
pkg_resources.DistributionNotFound: The 'hdf5plugin' distribution was not found and is required by silx
```

**Comment by t20100** [comment]
Debian packaging removes this dependency with a patch: https://salsa.debian.org/science-team/silx/-/blob/master/debian/patches/0005-removed-hdf5plugin-from-full-dependencies.patch

For the coming release, there is now a `SILX_INSTALL_REQUIRES_STRIP` added for packaging purpose exactly for this:
https://github.com/silx-kit/silx/blob/20e963329d84cd677aba46164410ea939b782505/setup.py#L538-L543

**Comment by t20100** [comment]
It was unfortunately not added to the local Debian packaging configs...
