### ISSUE TITLE
Issue with Stack view profile window title and labels

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3696]
When using the 2D profile tool on a 3D stack, it seems to miss a string formatting as it displays `{ylabel}` and `{xlabel}`:

![profile-window](https://user-images.githubusercontent.com/9449698/195876901-e4dca616-8965-4a66-9cea-70bb9c929146.png)

1D profile is OK:

![profile-window-1d](https://user-images.githubusercontent.com/9449698/195877592-e7048e65-f39a-49f0-9299-94a77852963f.png)

**Comment by vallsv** [comment]
Do you want to add a milestone here?
