### ISSUE TITLE
silx view: Mask tool doesn't use actual pwd

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3703]
Feedback from ESRF, ID10.

If you start silx from the command line, the mask tool doesn't use the actual `pwd`, but the user home instead.

It's probably also the case for other io dialogs.

**Comment by t20100** [comment]
It's set like this by default:

https://github.com/silx-kit/silx/blob/882c65d88cea9d8d5320a557c9b810eba3d25e8d/src/silx/gui/plot/_BaseMaskToolsWidget.py#L418

No problem to change it for me.

**Comment by t20100** [comment]
closed by #3704
