### ISSUE TITLE
[MaskToolsWidget] load & save in Fit2D mask format

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#372]
Request by ID22 -> straight forward if FabIO is available.

**Comment by vasole** [comment]
I would put as a runtime dependency but not hidden. I mean, the option to save in that format explicitly shown, independently of FabIO being installed or not, and coupled with an exception informing the user to install FabIO if option activated without fulfilling the dependency.

**Comment by vallsv** [comment]
BTW,
- is there a way to know all supported extensions of FabIO
- Is there a function to check if a file is supported by FabIO

**Comment by kif** [comment]
On Tue, 18 Oct 2016 23:49:02 -0700
Valentin Valls <notifications@github.com> wrote:

> BTW,
> - is there a way to know all supported extensions of FabIO

this is defined here:
https://github.com/silx-kit/fabio/blob/master/fabio/fabioutils.py#L79

It would probably be better that every class registers itself the extension it supports but this is not yet done.

> - Is there a function to check if a file is supported by FabIO

try:
  fabio.open(filename)
except:
  pass

Typical example is Tiff where the overall format may be supported but not the compression scheme underlying.

Cheers, 

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
For a generic load/save, It would be nice to wait for the next fabio release, cause available formats are better structured.

But if we only consider loading/saving masks only (and obviously Fit2D .msk is a format for masks), maybe only a subset of formats are needed. Then is there a subset of FabIO formats we should support for masks only?

**Comment by t20100** [comment]
Do we need a settable list of supported formats? Or just provide a dialog that propose to save in all available format?

**Comment by vallsv** [comment]
I think, this issue is about a very specific part of the widget: the import/export of a mask. Then i think i will only try to add msk files. It is enough while there is not request.

But for the generic load/save dialog, i guess we can try to expose all supported formats.

**Comment by vallsv** [comment]
It have to be done for this release. I we check next week.
