### ISSUE TITLE
PlotWidget: black image

### ISSUE THREAD

**Issue by AlgorithmesAndCo** [silx-kit/silx#3720]
Hello,

**SILX versions:**
Tested with SILX v1.0 and v1.1

**Source code**
Actions: we have a PlotWidget and we call: setData(array) to display a picture

**Target computer**
Here we have a Linux server running virtualization software: we are installing it on Windows (as usual)
But we had the same bug on other (unimportant) platforms.
We believe it is related to some computers and/or some configurations.

**What we get**
A black picture is displayed (instead of the test picture: I made it in the code and I'm 100% the array is correct)

We've been struggling on this bug: the image were not displayed (black screen).
It took me some time to track it down, but I'm pretty confident now, and to me it comes from SILX.

**Urgency**
I'm afraid this is an urgent request because we're installing on a customer's computer.

I'd like to discuss with you how we can go further (is there a way to have more logs? how can we understand what is wrong?)
I do speak french and english.

Ludo

**Comment by vasole** [comment]
It would be preferable to have a very small piece of code reproducing the issue.

Also, you should mention the backend used (matplotlib, OpenGL) nor the Qt binding module (PySide6, PySide2, PyQt5, PyQt6...)

To check if it comes from silx (or from matplotlib for instance) it should be very straightforward.

Have you tried to run one of the silx examples with different backends?

For instance:

https://github.com/silx-kit/silx/blob/master/examples/plotWidget.py

Specifying the OpenGL backend or the (default) matplotlib backend.

self._plot = PlotWidget(parent=self, backend="matplotlib")

self._plot = PlotWidget(parent=self, backend="opengl")

**Comment by vasole** [comment]
> ==> Is there a way to set the backend once and for all?

If you did nothing, the default backend is matplotlib.

It's up to you to choose what backend you want. In our own programs typically we allow the user to choose backend via a start parameter (--backend=opengl or --backend=matplotlib). That allows testing is something is wrong at the silx side or at the backend side.

**Comment by vasole** [comment]
Ok. That should be equivalent to "openg".

If you change it to "matplotlib", does anything get displayed? The visualization can be much slower, but it should confirm if there is a problem.

**Comment by vasole** [comment]
You should also test the file example I mentioned above.

**Comment by vasole** [comment]
Just in case it helps:

https://answers.microsoft.com/en-us/windows/forum/all/opengl-drivers/9b52324e-1083-44e1-83f7-ff2e35bf07a2

**Comment by AlgorithmesAndCo** [comment]
Making progress: with mpl, it shows black & white picture correctly (and it really works).

**But**, I get strange exceptions when using a color picture.

Basically, I've got a class GLPlotRGBAImageCustom that inherits from GLPlotItem and it says two methods are missing:
get_zorder and remove...

I'm a bit confused... Should I use another base class if not using GL? Or is there a general class that wouldn't be binded to a backend?

Can I have somebody on the phone?

**Comment by vasole** [comment]
Why don't provide a small piece of code showing the problem?

> Can I have somebody on the phone?

I do not think that kind of support is to be expected according to the software license. 

That would be really crossing a red-line. We can continue here on a good-will basis.

Please contact industry@esrf.fr if you really want phone support and explain your issue.

**Comment by t20100** [comment]
Hi,

[`GLPlotItem`](https://github.com/silx-kit/silx/blob/2c32c11068f3e411664f3a334fd948d5e763650d/src/silx/gui/plot/backends/glutils/GLPlotItem.py) is from the low level internal APIs and is only for use with the OpenGL backend (as the `GL` prefix stands), so it is "normal" that your `GLPlotRGBAImageCustom` does not work with the matplotlib backend.

The PlotWidget OpenGL backend requires OpenGL >= 2.0 (+ a few extensions that are available in OpenGL >=3).

You should probably investigate whether OpenGL is available or not and which version is available? This is what I would suspect first provided the virtualized environment.
E.g., is it working with another OpenGL based application?
There is also a function in `silx` to probe the availability of OpenGL. It is not catching all errors, but that can be a start: https://github.com/silx-kit/silx/blob/2c32c11068f3e411664f3a334fd948d5e763650d/src/silx/gui/utils/glutils/__init__.py#L92-L107

Do you get some error messages? Could you share code or make a small script to reproduce as @vasole suggested, that would help understanding the issue.

**Comment by t20100** [comment]
> Or is there a general class that wouldn't be binded to a backend?

Yes, see the [PlotWidget's item documentation](http://www.silx.org/doc/silx/latest/modules/gui/plot/items.html)

**Comment by AlgorithmesAndCo** [comment]
Ok, first, I checked on the machine, and... isOpenGLAvailable() says TRUE

But it doesn't work for some reason

This computer has absolutely no other piece of software. So no way to check other OpenGL apps.

I can send you an extract of the code, but it is quite obvious that we need OpenGL (that looks like the simplest option) or that we need to reimplement a bit of code for matplotlib or even better a generic version.

I'll dig deeper

**Comment by t20100** [comment]
> Tested with SILX v1.0 and v1.1

Was it working with previous versions? or was it not tested?

> A black picture is displayed

Is it only the image you display or also the axes?

How a simple code snippet such as the following using `PlotWidget` and OpenGL backend is behaving?

```python
from silx.gui import qt
from silx.gui.plot import PlotWidget
import numpy

app = qt.QApplication([])

plot = PlotWidget(backend='gl')
plot.addImage(numpy.random.random(100).reshape(10, 10))

plot.show()
app.exec_()
```

If this is not working, does it work with commenting `# plot.addImage...` ?

**Comment by AlgorithmesAndCo** [comment]
First, thanks to your advice, I implemented a generic version of the OpenGL optimized class that we had. I have to say that it is much slower, but it works on my computer. We'll know if it works on the customer's computer on friday, but I'm pretty confident.

Then, I still have a question: how do I know if we need to unplug OpenGL optim. I've got the feeling that isOpenGLAvailable() is not working in our case. It says True, but I think it shouldn't.

Or should I use it with a (3, 0) version number as parameter? (it also says True and I think it shouldn't)

Thanks again, and... Crossing fingers for friday

**Comment by t20100** [comment]
Hi,

> I implemented a generic version of the OpenGL optimized class that we had. I have to say that it is much slower, but it works on my computer.

Good to hear! This is why we have two backends: `opengl` for optimised display, `matplotlib` for making sure it works everywhere.

We don't have a 100% sure method to probe if OpenGL is available with the required version/extensions.
`isOpenGLAvailable` tries to open an OpenGL widget, but it is not checking that something is actually displayed there, only if an error is reported at some point. There are situations where this is not enough.
Maybe you can add a command line option when starting the application to enable/disable OpenGL? or a menu/button in the interface to toggle it at runtime?
For example in `silx` there is a `QAction` for it : https://github.com/silx-kit/silx/blob/2c32c11068f3e411664f3a334fd948d5e763650d/src/silx/gui/plot/actions/control.py#L621

**Comment by AlgorithmesAndCo** [comment]
That makes sense. FYI, I implemented it as an option that you can switch off.

The installation went well. Again thanks so much for your advice. I'm not sure I would have make it on my own. :-)

**Comment by vasole** [comment]
Please feel free to open it if a followup is needed.
