### ISSUE TITLE
Support an index as color in `PlotWidget.addCurve`

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3755]
Since there is a list of default colors in `PlotWidget`, the idea is to leverage it by allowing to select colors from it in applications.

First raised here: https://gitlab.esrf.fr/bliss/bliss/-/issues/3665

Alternative: Makes sure there is an API for getting/setting the list of default colors and use it like:
```python
plot = PlotWidget()
plot.addCurve(x, y, color=plot.getDefaultColors(1))
```

Note: This is provided through PR #3835

**Comment by vallsv** [comment]
Also, make sure 0 is the first color, and that there is a modulo to always pick a color.

**Comment by vallsv** [comment]
Looking at the code with thomas, it sounds like better to use a string like `color1`.

This way the patch can be done in the function `colors.rgba(color)`, which can be independently used (not related to a plot item).
