### ISSUE TITLE
Cursors on 1D curve

### ISSUE THREAD

**Issue by MelnikovAP** [silx-kit/silx#3756]
Hi! 
I'm developing a software to control custom-made device. I'm using silx to access h5 files and for building GUI. 
I cannot find in the documentation, is there some way to add sticky cursors to 1D graph? 
For example, to interactively select two points on 1D curve and afterwards delete all the points between two cursors?

**Comment by t20100** [comment]
Hi,

There is no such sticky cursor readily available.
There is only a "sticky" feature in the [PositionInfo](http://www.silx.org/doc/silx/latest/modules/gui/plot/tools/index.html#silx.gui.plot.tools.PositionInfo.setSnappingMode) widget that displays the mouse coordinates.

You can add markers to the plot with [PlotWidget.addMarker](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.addMarker)
And you can get mouse events through [PlotWidget.sigPlotSignal](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.sigPlotSignal) and recover the `mouseClicked` events and so place markers upon user interaction.

There is also some machinery to handle Region of Interests, see:
- http://www.silx.org/doc/silx/latest/modules/gui/plot/tools/index.html#module-silx.gui.plot.tools.roi
- http://www.silx.org/doc/silx/latest/modules/gui/plot/items.html#module-silx.gui.plot.items.roi

Finally, to select a region of the plot and do some processing with it, you can use [PlotWidget.setInteractiveMode](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.setInteractiveMode), e.g.:
```python
plot.setInteractiveMode('draw', shape='rectangle', label='my-event', source='custom-interaction')
```
and process events from [PlotWidget.sigPlotSignal](http://www.silx.org/doc/silx/latest/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.sigPlotSignal).
The `drawingFinished` event will provide rectangle coordinates.

**Comment by MelnikovAP** [comment]
Hi, 
Thank you a lot! 
Actually what helped to me is using HorizontalRangeROI(). Since there was no method to catch the finishing of marker movement, I used method sigPlotSignal of the graph, accessed to the action "event": "markerMoved"

**Comment by vallsv** [comment]
Are you talking about `roi.sigEditingStarted/sigRegionChanged/sigEditingFinished`?

It was designed for.

**Comment by MelnikovAP** [comment]
> Are you talking about `roi.sigEditingStarted/sigRegionChanged/sigEditingFinished`?
> 
> It was designed for.

Hi! 
Can you give a link to docs, please? I cannot find these methods.

**Comment by vallsv** [comment]
There is no documentation except a comment in the changelog.

It is part of the base class `https://github.com/silx-kit/silx/blob/main/src/silx/gui/plot/items/_roi_base.py#L192`

It is supposed to be triggered when the user is changing the size, or moving the ROI.
