### ISSUE TITLE
[Plot] Copy of X, Y values from plot PositionInfo widget

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#376]
There seems to be a conflict between Ctrl-C on the PositionInfo text labels (to copy X Y values) and the plot to copy a snapshot of the plot.

**Comment by vallsv** [comment]
Here is a fix

```
diff --git a/silx/gui/plot/PlotActions.py b/silx/gui/plot/PlotActions.py
index 77e4e6b..03a3f8e 100644
--- a/silx/gui/plot/PlotActions.py
+++ b/silx/gui/plot/PlotActions.py
@@ -884,10 +884,12 @@ class CopyAction(PlotAction):
             triggered=self.copyPlot,
             checkable=False, parent=parent)
         self.setShortcut(qt.QKeySequence.Copy)
+        self.setShortcutContext(qt.Qt.WidgetShortcut)
 
     def copyPlot(self):
         """Copy plot content to the clipboard as a bitmap."""
         # Save Plot as PNG and make a QImage from it with default dpi
+        print("CopyAction")
         pngData = _plotAsPNG(self.plot)
         image = qt.QImage.fromData(pngData, 'png')
         qt.QApplication.clipboard().setImage(image)
diff --git a/silx/gui/plot/PlotWindow.py b/silx/gui/plot/PlotWindow.py
index e6cf872..cb22987 100644
--- a/silx/gui/plot/PlotWindow.py
+++ b/silx/gui/plot/PlotWindow.py
@@ -182,8 +182,9 @@ class PlotWindow(PlotWidget):
         self._separator.setSeparator(True)
         self.group.addAction(self._separator)
 
-        self.copyAction = self.group.addAction(PlotActions.CopyAction(self))
+        self.copyAction = self.group.addAction(PlotActions.CopyAction(self, self))
         self.copyAction.setVisible(copy)
+        self.addAction(self.copyAction)
 
         self.saveAction = self.group.addAction(PlotActions.SaveAction(self))
         self.saveAction.setVisible(save)
```

After few checks, as default a shortcut have a window context, which is not fine for a widget. Then the patch change the shortcut context and add the action to the widget (as is the shortcut is reachable from the widget). I also set a parent, it is always better.

This have to be done for all actions, that's why i think we should think about that. Is there any changes when the widget is used as a window?

BTW, i also see that all plot widgets inherit from `QMainWindow` at the very end, it is also not very fine. It would be nice to create an UML diagram.

**Comment by vasole** [comment]
@vallsv 

Plot widgets inherit from QMainWindow following request/recommendation from BCU (@tiagocoutinho).

If I remember well, that was not preventing it from being used as a QWidget while simplifying the use of other things (tool bars, dock widgets, ...). In particular, if I remember well, for Taurus to be able to use our tools, they need to be able to store the settings of the widgets and that is simplified by using QMainWindows (see restoreState and saveState).

**Comment by vallsv** [comment]
Fixed by https://github.com/silx-kit/silx/pull/594
