### ISSUE TITLE
[GUI] pyside6 broken on recent python

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#3778]
Reported in https://github.com/silx-kit/pyFAI/issues/1852

**Comment by t20100** [comment]
It's due to removal of [xml.etree.ElementTree.Element.getchildren](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren) in Python 3.9

**Comment by kif** [comment]
There is more to come. Sorry for the screenshot.
![image](https://user-images.githubusercontent.com/1018880/227906821-d89cef3c-1d04-4126-a10e-861479f318c7.png)

**Comment by kif** [comment]
Sorry, this one is specific to pyFAI.

**Comment by t20100** [comment]
It's probably time to update `_pyside_dynamic.py` from where we got it: https://github.com/spyder-ide/qtpy/blob/master/qtpy/uic.py
