### ISSUE TITLE
[doc] document the installation of a venv/virtualenv for working with silx

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#378]
1) install vitrualenv
2) create a vitualenv
3) upgrade pip
4) install setuptools & wheel
5) install numpy, cython, scipy & matplotlib
6) install h5py, fabio, and silx
7) install pyopencl, mako

Comes after a discussion with VincentF-N

**Comment by PiRK** [comment]
The PyQt dependency for silx.gui is a non-trivial issue, if we want to completely avoid using `sudo apt-get install`.

Even by adding Qt4 or Qt5 to the requirements to avoid having to explain how to install the Qt libraries, I'm stuck when trying to install PyQt, which requires SIP, which requires flex.

The most recent tutorial I found for installing PyQt in a virtualenv is https://www.metachris.com/2016/03/how-to-install-qt56-pyqt5-virtualenv-python3/ . It does not cover cases where ``apt-get install`` is not an option.

**Comment by PiRK** [comment]
After installing *silx* in my venv (without pyqt), 3 sift tests end with an error:

`======================================================================
ERROR: test_gradient (silx.image.sift.test.test_image.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/knobel/venvs/silx_venv/local/lib/python2.7/site-packages/silx/image/sift/test/test_image.py", line 94, in test_gradient
    border_dist, peakthresh, EdgeThresh, EdgeThresh0, octsize, scale, nb_keypoints, width, height, DOGS, g = local_maxmin_setup()
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_local_maxmin (silx.image.sift.test.test_image.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/knobel/venvs/silx_venv/local/lib/python2.7/site-packages/silx/image/sift/test/test_image.py", line 133, in test_local_maxmin
    border_dist, peakthresh, EdgeThresh, EdgeThresh0, octsize, s, nb_keypoints, width, height, DOGS, g = local_maxmin_setup()
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_interpolation (silx.image.sift.test.test_image.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/knobel/venvs/silx_venv/local/lib/python2.7/site-packages/silx/image/sift/test/test_image.py", line 194, in test_interpolation
    border_dist, peakthresh, EdgeThresh, EdgeThresh0, octsize, nb_keypoints, actual_nb_keypoints, width, height, DOGS, s, keypoints_prev, blur = interpolation_setup()
  File "/users/knobel/venvs/silx_venv/local/lib/python2.7/site-packages/silx/image/sift/test/test_image_setup.py", line 136, in interpolation_setup
    border_dist, peakthresh, EdgeThresh, EdgeThresh0, octsize, s, nb_keypoints, width, height, DOGS, g = local_maxmin_setup()
TypeError: 'NoneType' object is not iterable
`

**Comment by payno** [comment]
Looks like TestImage unit test is not skipped if scipy is not installed. 
But TestImage is calling a function 'local_maxmin_setup' which can return None if scipy is no installed. Might be your issue.

For information 'local_maxmin_setup' starts with :
def local_maxmin_setup():
    if not scipy:
        return

**Comment by PiRK** [comment]
Opening a new issue for this (tests failing if opencl installed but scipy not installed).

**Comment by PiRK** [comment]
Status update: The documentation is mostly ready and merged a long while ago, but I still haven't figured out how to get Qt to work inside a virtualenv without a system-wide install. So we can install most of silx in a virtualenv but not silx.gui.

**Comment by PiRK** [comment]
The documentation of how to add a symbolic link to the system package for PyQt4 was actually added in commit 1b17bf02758679df7ea1091eb2c24826575a6dbc in PR #655
