### ISSUE TITLE
[resources] Adding extra resource dirs.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#379]
The resources (icons, ...) system functions (getIcon, ...) in silx are very practical, but they don't allow (AFAIK) for a user to add its own folder(s) to the lookup path, which means that a client project has to duplicate silx code into its own project to use these functionalities (well that's what I did anyway).

So maybe it would be interesting to allow the user to register a folder and a namespace (to avoid conflicts) to the list of paths into which silx looks for resources?
And then you could get files like resource_filename('myNs:foo/myFile').

**Comment by vallsv** [comment]
Close by https://github.com/silx-kit/silx/pull/1054
