### ISSUE TITLE
move `_PlotWithWaitingLabel` to public

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#3807]
I would like to use this class from another project so it would be nice to have it in the public scope.

**Comment by vallsv** [comment]
I really suggest to use another component that you can add in any plot.

Here you are just stucked with a very specific plot no?

**Comment by payno** [comment]
Not sure to get what you mean. Create a new `plot object` like inheriting from `ItemMixInBase` or `DataItem3D` ?

**Comment by vallsv** [comment]
Or a pure Qt widget as an overlay (something that we could used at other places).

Just a proposal anyway, but that's something that i could reuse too.

**Comment by t20100** [comment]
Yes, it would be best if it is more generic/versatile.

**Comment by vallsv** [comment]
In pyFAI there is this small snipet
```
def createProcessingWidgetOverlay(parent):
    """Create a widget overlay to show that the application is processing data
    to update the plot.

    :param qt.QWidget widget: Widget containing the overlay
    :rtype: qt.QWidget
    """
    if hasattr(parent, "centralWidget"):
        parent = parent.centralWidget()
    button = WaitingPushButton(parent)
    button.setWaiting(True)
    button.setText("Processing...")
    button.setDown(True)
    position = parent.size()
    size = button.sizeHint()
    position = (position - size) / 2
    rect = qt.QRect(qt.QPoint(position.width(), position.height()), size)
    button.setGeometry(rect)
    button.setVisible(True)
    return button
```

![image](https://github.com/silx-kit/silx/assets/7579321/3960cfbb-4bbc-4db1-ba74-86bb61053e39)

This could be used as basis.

**Comment by payno** [comment]
Earlier prototype. But would it fit with your idea / requirements ?
For me this is the kind of think which has plenty of ways to be done so...

``` python

class WaiterOverlay:
    def __init__(self, underlying_widget: qt.QWidget, waiting_text: str="", with_border: bool=False, transparent=True) -> None:
        """
        :param qt.QWidget underlying_widget: widget on top of which we want to displat the "processing/waiting wheel"
        :param str waiting_text: text to apply near the processing wheel
        """
        if not isinstance(underlying_widget, qt.QWidget):
            raise TypeError
        self._baseWidget = weakref.ref(underlying_widget)
        self._waitingButton = WaitingPushButton(
            parent=underlying_widget,
            text=waiting_text,
        )
        self._waitingButton.setDown(True)
        self._waitingButton.setVisible(False)
        if not with_border and transparent:
            self._waitingButton.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        elif not with_border:
            self._waitingButton.setStyleSheet("QPushButton { border: 0px }")
        elif transparent:
            self._waitingButton.setStyleSheet("QPushButton { background-color: transparent; }")
        self.resize()
    
    def getBaseWidget(self) -> Optional[qt.QWidget]:
        return self._baseWidget()
    
    def setWaiting(self, activate=True):
        self._waitingButton.setWaiting(activate)
        self._waitingButton.setVisible(activate)
    
    def resize(self):
        # should be called by the widget when resized to keep displaying it in the middle
        parent = self.getBaseWidget()
        if parent is None:
            return
        
        position = parent.size()
        size = self._waitingButton.sizeHint()
        position = (position - size) / 2
        rect = qt.QRect(qt.QPoint(position.width(), position.height()), size)
        self._waitingButton.setGeometry(rect)
```

If this path seems correct I will need your help @vallsv  to see how to modify the icon of the WaitingPushButton size. Because looks like I cannot change it directly and there is some mechanism linked with "sizeHint" that I don't get.

**Comment by vallsv** [comment]
Will it is not port of the plot API it sounds good to me.

BTW the `resize` function could probably automatically registered from the original plot.

I also suggest to remove everything from the constructor (`, waiting_text: str="", with_border: bool=False, transparent=True`), add use setters lika any other components. Except `underlying_widget` obviously.

**Comment by payno** [comment]
```
BTW the resize function could probably automatically registered from the original plot.
```
I agree but the scope is wilder than Plots. We can do a special handling for PlotWidget like
```python
if isinstance(underlying_widget, PlotWidget):
    underlying_widget.sigPlotSignal.connect(....)
```
but then we get something specific for PlotWidget that I though we wanted to avoid.


```
I also suggest to remove everything from the constructor (, waiting_text: str="", with_border: bool=False, transparent=True), add use setters lika any other components. Except underlying_widget obviously.
```
I fully agree. Associated question is: should the default style-sheet be transparent without border ? From my appreciation this should be the 'default' style. But not sure you share the same vision.

**Comment by vallsv** [comment]
> We can do a special handling for PlotWidget like

You have have to. Qt provides events for that already.
We can take a look together if you like anyway.

**Comment by t20100** [comment]
For handling resize, QObject's [event filter](https://doc.qt.io/qt-6/qobject.html#installEventFilter) should do the work.

Can't the `underlying_widget` be the parent of the waiting widget?

**Comment by vallsv** [comment]
> For handling resize, QObject's [event filter](https://doc.qt.io/qt-6/qobject.html#installEventFilter) should do the work.

No because if you open or close a side window, the location of the widget will be wrong.
