### ISSUE TITLE
Using `black` formatting

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3819]
What about using [`black`](https://black.readthedocs.io/en/stable/) now that it is stable and a standard tool?

> By using Black, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

Personally, I'd make it checked by CI... but I'm also OK to convert the code base and fix it once in a while.

What do you think?

**Comment by vallsv** [comment]
Up to you.

I think it will be mostly fine expect at some places.

I also don't like CI check for such think, but it's up to you. You'r the main maintainer.

Finally it will also break the whole previous open PR, but there is not so much remaining ones.

**Comment by t20100** [comment]
> I also don't like CI check for such think

The issue when partly using black is ending with PRs polluted by some reformatting.

Now, in practice with the current activity of the project, that shouldn't be a big deal...
And even less if it is set on save in the IDE or as a pre-commit hook.
So as I said, it's OK not to have it in the CI.

> Finally it will also break the whole previous open PR

Yes, it's best to do so with no PRs opened.
