### ISSUE TITLE
Make `silx.app` and `silx.third_party` private

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3820]
Having `silx._app` and `silx._third_party` instead would be explicit about their usage.

**Comment by vallsv** [comment]
Do you think people use `python -m silx.app.view`? If we use such thing internally we could use the private package anyway.

Nowadays i think it is not needed anymore

**Comment by t20100** [comment]
> Do you think people use python -m silx.app.view?

Never sure indeed...

**Comment by t20100** [comment]
There is an example script importing `silx.app` to show how to make a custom silx view:

https://github.com/silx-kit/silx/blob/2279d94b444a10139bc5a4eac08e951afe84bd49/examples/customSilxView.py#L36-L37

So let's keep it as it is.
