### ISSUE TITLE
h5tree: Should like the DND URI is wrong

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3826]
If i drag and drop a node from the tree to my shell, it displays:

```
silx:///nobackup/lvalls1/valls/workspace/silx.git/ID16B_diatomee.h5?/scan1/instrument/data
```

Sounlds like a wrong URL?

Sould be:

```
silx:///nobackup/lvalls1/valls/workspace/silx.git/ID16B_diatomee.h5?path=/scan1/instrument/data
```

**Comment by vallsv** [comment]
Or at least if i concatenate it with `&slice=0`, the slice is not read.

Maybe it's normal.

**Comment by t20100** [comment]
`silx` can parse the URL, so at least it is self-consistent:

```python
>>> from  silx.io.url import DataUrl                                                                       
>>> DataUrl('silx:///nobackup/lvalls1/valls/workspace/silx.git/ID16B_diatomee.h5?/scan1/instrument/data')  
DataUrl(valid=True, scheme='silx', file_path='/nobackup/lvalls1/valls/workspace/silx.git/ID16B_diatomee.h5', data_path='/scan1/instrument/data', data_slice=None)
```

> Or at least if i concatenate it with &slice=0, the slice is not read.

Yes, that's expected, in this case you need to use `?path=...&slice=...`.
Query string does not seems to be necessarily `key=value` pairs, so it's up to us to decide what we support; and we currently support `filename.h5?/path/to/hdf5/entry` (in the same way as `filename.h5::/path/to/hdf5/entry`).

To me it is not worth changing now.
