### ISSUE TITLE
Update linewidth for the default style of a selected curve

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3849]
The actual style for the selected curve is setup with a selection color which is black.

I think that's not a very good idea, because it's a color like any others, and usually a desaturation means that the stuff is not selected or disabled.

As we are updating to 2.0 i propose to change the default to use the line width to show the selection (that's what i do in Flint), and let the original color of the curve.

- This could became the default to the library (it is still possible to change it programatically anyway)
- This could became the default to silx view only

What do you think?

## Actually

![image](https://github.com/silx-kit/silx/assets/7579321/7bdfe89d-4d41-4d81-8bff-57da4583d50a)

## Proposed

![image](https://github.com/silx-kit/silx/assets/7579321/036de1f9-da86-4f21-b842-341a2cb8c3a8)

**Comment by t20100** [comment]
I'm +1 for this change of default as long as there is a way to use the previous behaviour.

This is already the case from the API with `PlotWidget.setActiveCurveStyle`.
We can also add some fields in `silx.config` for it, e.g.: `DEFAULT_PLOT_ACTIVE_CURVE_COLOR = None` and `DEFAULT_PLOT_ACTIVE_CURVE_LINEWIDTH = 2`.
