### ISSUE TITLE
Update the default curve color palette

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3850]
The actual palette used to identify the curves have some lacks.

- It is mostly compound by saturated colors
- The yellow is not really readable on top of the white

A good palette is stricky. It have to match constraints which are not easy to solve.

- Colors have to be distinguishable but are the same time consistent
- It have to be distinguishable in a b&w print
- It have to take care of the common color vision deficiency

Luckily there is some research on that. So i propose to use the one i have selected for Flint:  The normal, 12 colors from http://tsitsul.in/blog/coloropt/

That's a convenient one because it provides 12 colors (which is already a lot), and silx use about 19 colors.

- This could became the default to the library (it is still possible to change it programmatically anyway)
- This could became the default to silx view only

What do you think?

## Actually

![image](https://github.com/silx-kit/silx/assets/7579321/7e0a15b7-00c4-42a5-9211-76849d1b5ae0)

```
    DEFAULT_PLOT_CURVE_COLORS = ['#000000',  # black
                                 '#0000ff',  # blue
                                 '#ff0000',  # red
                                 '#00ff00',  # green
                                 '#ff66ff',  # pink
                                 '#ffff00',  # yellow
                                 '#a52a2a',  # brown
                                 '#00ffff',  # cyan
                                 '#ff00ff',  # magenta
                                 '#ff9900',  # orange
                                 '#6600ff',  # violet
                                 '#a0a0a4',  # grey
                                 '#000080',  # darkBlue
                                 '#800000',  # darkRed
                                 '#008000',  # darkGreen
                                 '#008080',  # darkCyan
                                 '#800080',  # darkMagenta
                                 '#808000',  # darkYellow
                                 '#660000']  # darkBrown
```

## Proposed

![image](https://github.com/silx-kit/silx/assets/7579321/6285aae8-6281-40ef-bd41-027f2b7532a7)

Here is with a reorder (from Flint source code)
```
NORMAL_PALETTE_12 = [
    (87, 81, 212),
    (235, 171, 33),
    (176, 69, 0),
    (0, 197, 248),
    (207, 97, 230),
    (0, 166, 107),
    (184, 0, 87),
    (0, 138, 248),
    (0, 110, 0),
    (0, 186, 171),
    (255, 145, 133),
    (133, 133, 0),
]
```

**Comment by t20100** [comment]
+1 for using matplotlib default

**Comment by vallsv** [comment]
Thanks for your feedback.
It sounds good to me too.
Ill create a related PR.
