### ISSUE TITLE
This patch seems to be required in order to  work on Debian

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#3878]
https://sources.debian.org/src/silx/1.1.2+dfsg-1/debian/patches/0006-Tests-if-openCL-can-be-used.patch/

```
Date: Fri, 5 Jul 2019 16:52:20 +0200
Subject: Tests if openCL can be used

---
 src/silx/opencl/common.py | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/silx/opencl/common.py b/src/silx/opencl/common.py
index cf51406..5702f74 100644
--- a/src/silx/opencl/common.py
+++ b/src/silx/opencl/common.py
@@ -73,6 +73,8 @@ if pyopencl is None:
         WRITE_ONLY = 1
         READ_ONLY = 1
         READ_WRITE = 1
+else:
+    mf = pyopencl.mem_flags
 
 FLOP_PER_CORE = {"GPU": 64,  # GPU, Fermi at least perform 64 flops per cycle/multicore, G80 were at 24 or 48 ...
                  "CPU": 4,  # CPU, at least intel's have 4 operation per cycle
```

**Comment by t20100** [comment]
Looking at the code, if `pyopencl` is not `None`, `mf` should be defined:

https://github.com/silx-kit/silx/blob/d3bf376dca08a76524b0f4273c295b637d3fc26a/src/silx/opencl/common.py#L50-L76

Do you have some logs of the error without the patch?

I'll propose a change of this part to separate import of `pyopencl` and initializing `mf`, which should be clearer, but as it is I don't see why this patch is needed.
