### ISSUE TITLE
ColormapDialog exception

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3885]
Found at a beamline with the latest `1.something` silx.

Just as a reminder, in case there is an obvious problem or fix.

![Screenshot from 2023-06-26 09-19-55](https://github.com/silx-kit/silx/assets/7579321/4f39572e-c513-4a85-9317-ef6b9e964335)

**Comment by t20100** [comment]
Looks like `ColormapDialog._scaleToAreaGroup`'s C++ `QWidget` has been destroyed. It is a child of `ColormapDialog`, so I'd expect the `ColormapDialog`'s  C++ `QDialog` to have been deleted as well...

To me, we should not protect from this in `silx`.
Instead the caller code (https://gitlab.esrf.fr/bliss/bliss/-/blob/master/bliss/flint/widgets/colormap_widget.py#L69-83) should ensure that the `ColormapDialog` is still valid either by construction or using `silx.gui.qt.inspect.isValid`.
