### ISSUE TITLE
Glitch on OpenGL plot

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3886]
Depending on the width of the plot, the last pixel column sometimes blink.

It is easy to reproduce on my machine.

```
Debian 10
pyopengl                  3.1.5                      py_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
qt                        5.9.7                h0c104cb_3    conda-forge
```

![image](https://github.com/silx-kit/silx/assets/7579321/616dbdd7-ed0b-4876-9a75-15d6bc005e2a)

**Comment by t20100** [comment]
Could you send me the `env.yml` of your env so I can try it?

Do you have the same issue with a more recent version of Qt? 5.9 is rather old.
