### ISSUE TITLE
handle `pkg_resources` deprecation

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#3895]
looks like `pkg_resources` is deprecated. For parsing version `packaging` seems to the common solution

**Comment by t20100** [comment]
`pkg_resources.parse_version` is straight forward to replace with `packaging.Version`/`packaging.parse`.

For usage of `pkg_resources` here:
https://github.com/silx-kit/silx/blob/d3bf376dca08a76524b0f4273c295b637d3fc26a/package/windows/pyinstaller.spec#L151

It's possible to use [importlib.metadata.distributions](https://importlib-metadata.readthedocs.io/en/latest/api.html#importlib_metadata.distributions) with python>=3.8.
I'd be in favor to only build Windows fat binary with python>=3.8 and use it.
