### ISSUE TITLE
plot: Gigantic shape width with opengl

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3948]
At ID24 foucault, ubuntu, gnome shell, while switching to opengl, we have noticed that every markers of the application are displayed with a huge line width.

Lines and markers are impacted.

Here is for example a mouse selection on black
![image](https://github.com/silx-kit/silx/assets/7579321/4bb498b0-dd42-40d5-ac72-fe6e6a55c12a)

Any idea what could be wrong?

**Comment by t20100** [comment]
> Any idea what could be wrong?

I never saw that before, I would need to check directly on the computer it occurs on.

**Comment by vallsv** [comment]
Taking a look at that with @t20100 the screen we are using is described with wrong information in the 
```
opid24@tesla:~$ xrandr
...
DP-2 connected primary 5120x1440+344+1080 (normal left inverted right x axis y axis) 1mm x 1mm
...
```

Notice the `1mm x 1mm`, as result every pixel size information provided by Qt are wrong.

That's an config problem of this env. I close the issue.

**Comment by t20100** [comment]
If needed we can check if the resolution returned by Qt is realistic and provide a log warning and a fallback in that case.
