### ISSUE TITLE
plot: X-axis in OpenGL is difficult to read

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3949]
Thats maybe a regression?

Sounds like the trainling `0` are not removed

Here is with opengl
![image](https://github.com/silx-kit/silx/assets/7579321/43f11ca0-b21d-4541-8997-8f6a2568728c)

Here is the exact same plot with matplotlib
![image](https://github.com/silx-kit/silx/assets/7579321/3bd1ab52-5cab-49a4-ad64-7104b27bc3cf)

**Comment by t20100** [comment]
Do you have a way to reproduce this?

**Comment by t20100** [comment]
To reproduce:
```
from silx import sx, config

config.DEFAULT_PLOT_BACKEND = 'gl'

w = sx.plot((0, 1), (0, 1))
axis = w.getXAxis()
axis.setTickMode(sx.TickMode.TIME_SERIES)
```
