### ISSUE TITLE
3D visualization in pyFAI-calib2 cancelled upon different detectors

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/silx#3969]
The 3D visualization is cancelled in pyFAI-calib2 if the chosen detector is **Dectris Pilatus 1M:**

3D preview cancelled:
module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

On the other hand, it is working fine, for example, for the detector Rayonix LX255.

**Comment by loichuder** [comment]
If you opened this issue in `silx` and not in `pyFAI`, I guess it is because you traced back the error to a `silx` file ?

If so, do you know which one ?

**Comment by EdgarGF93** [comment]
Sorry, I thought it was something about silx.gui, but actually the bug is in pyFAI
