### ISSUE TITLE
Change `PlotWidget.add*` methods to return the corresponding `Item` instance 

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3990]
As it stands, `PlotWidget` add methods (namely `addCurve`, `addImage`, `addHistogram`, `addScatter`, `addShape`, `addMarker`, `addXMarker`, `addYMarker`) returns the legend of the add/updated item as a `str`.

This issue proposes to change those `add*` methods to return the added/updated item instance instead.

Pros:
- Since the `legend` is passed as input argument, returning it is only useful when using the default legend. So I would expect its usage to be limited. As a matter of fact, in the `silx` project, when the returned legend is used, it is only used to retrieve the corresponding `Item` object...
- The `legend` can be retrieved from the item through: `item.getName()`.
- The `legend` is not enough to retrieve the item, its `kind` (i.e., `curve`, `scatter`...) is also needed.

Cons:
- This would break the current API.

How would this affect your project?

**Comment by vasole** [comment]
In my projects I make use of removeCurve and removeImage using the returned handle (at this moment the legend)

If the proposed change is made, removeCurve, removeImage should be able to accept either the returned item or a string to keep backwards compatibility.

**Comment by t20100** [comment]
Yes, it makes sense. I did the same for `setActive*` methods which now supports both a legend `str` and an `Item`.

Thanks for the feedback!
