### ISSUE TITLE
Modernize documentation theme

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3993]
`silx` uses the python2.7 sphinx theme which has issues with names from the content tab overlapping the content.

IMO it's time to switch to an up-to-date theme. Any preferences from [available themes](https://sphinx-themes.readthedocs.io/en/latest/#themes)?

[Tomwer](https://tomotools.gitlab-pages.esrf.fr/tomwer/) uses [PyData](https://sphinx-themes.readthedocs.io/en/latest/sample-sites/pydata-sphinx-theme/) which sounds to fit the need for me.

**Comment by vasole** [comment]
I prefer the examples with an index on the left.
