### ISSUE TITLE
opengl: No minus sign in the axes

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#4018]
```
WARNING:matplotlib.mathtext:Font 'default' does not have a glyph for '\u2212' [U+2212], substituting with a dummy symbol.
```

No idea if it's a specificity of my env or a specificity of the master

One of the solution is to use the font packaged with matplotlib (see #4010)

![image](https://github.com/silx-kit/silx/assets/7579321/07b00190-545b-44bb-8d2f-790e9f3e632d)

**Comment by t20100** [comment]
It's probably related to #4007 which changed the rendering of tick labels.
It also depends on the default font so using the one from matplotlib really makes sense
