### ISSUE TITLE
[2.0.0] how to build  the man pages ?

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#4061]
The build_man target was removed. What is the new way to build the silxs manpages ?

Thansk

Fred

**Comment by t20100** [comment]
We removed the `build_man` command to comply with `setuptools` willing to stop supporting this in the long term.
Instead, there is now a [tools/build_man_page.py](https://github.com/silx-kit/silx/blob/main/tools/build_man_page.py) script that generates the man page.

This is how we use it to make the "unofficial" Debian package: https://github.com/silx-kit/silx/blob/6103895429b00e5820d8d05aeb07fb89ef4d3db3/package/debian12/rules#L40-L43

**Comment by picca** [comment]
thanks a lot

**Comment by t20100** [comment]
Closing, this was fixed in the [official Debian packaging](https://salsa.debian.org/science-team/silx/-/commit/5c6b12af2f6a008de8f40a8b1378a38643a0feb3)
