### ISSUE TITLE
[2.0.0] your are using the dead upstream sphinx-panels

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#4062]
It cause this kind of trouble

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1063326

could you migrate to 

https://tracker.debian.org/pkg/sphinx-design

Cheers

Fred

**Comment by t20100** [comment]
BTW, I don't recall having this issue when building the doc.

**Comment by t20100** [comment]
PR #4063 replaces `sphinx-panels` by `sphinx-design` in the documentation.
