### ISSUE TITLE
Auto expand in Hdf5TreeView

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#4067]
Hello,

At our beamline, several devices write their own h5 files that are soft-linked in the master file.
When we examine the files in silx view, we have to do multiple clicks to dig down to the actual data. When we do it on multiple data, this monkey business becomes annoying. This screenshot shows that each such file has multiple one-member groups:
![image](https://github.com/silx-kit/silx/assets/17322580/20380d87-051d-4339-8e0b-46495fcbee6e)

I propose to add an option "auto expand singular groups" (or "auto expand simple branches" or similar) that would require only one click at the top level and it would go down to a group that has multiple members in it. There the auto expansion stops.

In the implementation, the class Hdf5TreeView(qt.QTreeView) can react to its `expanded` signal like this:
```
    def expandFurther(self, index):
        """Further expand a tree node if it has only one child."""
        model = self.model()
        if model.rowCount(index) == 1:
            child = model.index(0, 0, index)
            self.expand(child)
```

Thank you!

**Comment by vallsv** [comment]
Hi.

Maybe i misunderstand something but what is the difference with the option `[+]` from the toolbar?

**Comment by kklmn** [comment]
D'oh!
I've never used those buttons, probably because one tries them when the viewer is empty and then they do nothing.
![image](https://github.com/silx-kit/silx/assets/17322580/4ed4c60f-1fde-4b76-8c80-060784c902ed)
