### ISSUE TITLE
[histogramnd] Wrong doc + inconsistency

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#407]
There is an error in the doc for the Histogramnd constructor :

The line :
```python
"""
:param wh_dtype: type of the weighted histogram array. If not provided, the
           weighted histogram array will contain values of the same type as
           *weights*. Allowed values are : `numpy.double` and `numpy.float32`
:type wh_dtype: *optional*, numpy data type
"""
```
should read instead :
```python
"""
:param wh_dtype: type of the weighted histogram array.
            If not provided, the weighted histogram array will contain values
            of type numpy.double. Allowed values are : `numpy.double` and
            `numpy.float32`
:type wh_dtype: *optional*, numpy data type
"""
```

By the way this brings up a difference between Histogramnd and HistogramndLut that maybe had gone unnoticed **(because of the aforementioned docstring error! my bad)**, and we might want to fix :
- Histogramnd : if the dtype parameter is not provided then the weighted histogram is an array of type numpy.double.
- HistogramndLut : if the dtype parameter is not provided then the weighted histogram is actually of the same type as the weights.
The difference is due to the fact that the underlying code is in C, and that it's a bit tedious to add supported type (we have 3 types for the sample, 3 types for the wieghts, 2 types for the histogram => 18 different signatures). HistogramndLut is using fused types, so supported types can be added at almost no cost (not counting the tests tho).

**Comment by PiRK** [comment]
closed by #419
