### ISSUE TITLE
[2.0.0][OpenCL] issue with pocl 5.0.2 -- help :)

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#4073]
Hello, I have this issue in the autopkgtest of silxs 2.0.0

https://ci.debian.net/packages/s/silx/testing/amd64/43428196/

here the buf report related to this issue

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1060318#10

I am not yet a specialiste of PyOpenCL/OpenCL/pocl  debugging.

Could you help me  debug this issue.

For information If I build the same code on Debian12 with pocl 3.x it works.

thanks for considering.

Fred.

PS: Next step would be to run this on this platform with real GPU hardware :)

https://ci.rocm.debian.net/packages/r/rocfft/

**Comment by kif** [comment]
I managed to get it crashing with: 
`OpenCL 3.0 PoCL 5.0  Linux, Debug+Asserts, RELOC, SPIR, SPIR-V, LLVM 16.0.6, SLEEF, POCL_DEBUG`

**Comment by kif** [comment]
So the regression appears to be more in LLVM than in PoCL ...

**Comment by t20100** [comment]
This has been fixed in pocl: https://github.com/pocl/pocl/issues/1435#issuecomment-2058726072

Please reopen if needed
