### ISSUE TITLE
Remove deprecated pkg_resources

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#4075]
```
/users/denolf/virtualenvs/pybox_Tssi3n/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/resources/__init__.py:73: in <module>
    import pkg_resources
/users/denolf/virtualenvs/pybox_Tssi3n/ubuntu_20_04/py38/lib/python3.8/site-packages/pkg_resources/__init__.py:104: in <module>
    warnings.warn(
E   DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

**Comment by t20100** [comment]
`pkg_resources` is only used with Python3.8:

https://github.com/silx-kit/silx/blob/0abd43eb9d15daa4cb764436856025cdf6eb1080/src/silx/resources/__init__.py#L72-L73


For newer versions of Python, [importlib.resources.files](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) and [importlib.resources.as_file](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.as_file) are used instead.

Complete removal of `pkg_resources` will be done when dropping Python3.8.

**Comment by woutdenolf** [comment]
We could use `importlib_resources` for python <3.9 like https://github.com/silx-kit/pyFAI/pull/2087/files. But you can close the issue if you think it is not worth it.

**Comment by t20100** [comment]
Python3.8 [end of life is in about 6 months](https://peps.python.org/pep-0569/#lifespan), at the same time it shouldn't be a big deal to use the backport lib.
