### ISSUE TITLE
issue doc

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#4076]
get some issue with the ![doc](https://www.silx.org/doc/silx/latest/modules/gui/plot/dev.html#silx.gui.plot.backends.BackendBase.BackendBase.addMarker). Looks like the 'download Windows installer' button is all over. (maybe it automatically detects this is windows ? :laughing: )

firefox version: 115.8.0esr

![image](https://github.com/silx-kit/silx/assets/12907796/ad312e46-f4fe-466e-a9e0-fadcdf001d27)

**Comment by payno** [comment]
In fact this work well with the current 'main'. Most likely an issue with `sphinx_panel` or something like this. Should desapear on the next release / update of the doc from main

**Comment by t20100** [comment]
This should be fixed by PR #4063
