### ISSUE TITLE
issue opencl - segfault

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#4077]
I have some issue on a beamline computer (iccid191) which end up with a segfault. Don't know if this is related to https://github.com/silx-kit/silx/issues/4073

If I do the following with silx 2.0 it fails
```bash
python -c "from silx.opencl import ocl"
Segmentation fault (core dumped)
```

But if I turn off opencl
```bash
export SILX_OPENCL=0
python -c "from silx.opencl import ocl"
```
then no more segfault

And it used to work with silx 1

**Comment by payno** [comment]
indeed it even seems that a simple call to `python -c "from silx.opencl.utils.ExternalRessources import ExternalRessources"` make it segfault. But the file on itself seems to have nothing 'exotic'

**Comment by t20100** [comment]
Replaced by more focused issue #4088
