### ISSUE TITLE
[0.3.0] issue without error. Win10 py27&35 anaconda

### ISSUE THREAD

**Issue by ohlssonm** [silx-kit/silx#408]
ERROR:silx.gui.widgets.ThreadPoolPushButton:Error while executing callable silx.gui.widgets.test.test_threadpoolpushbutton._computeFail.
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\site-packages\silx\gui\widgets\ThreadPoolPushButton.py", line 57, in run
    result = self.__callable(*self.__args, **self.__kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\silx\gui\widgets\test\test_threadpoolpushbutton.py", line 54, in _computeFail
    raise Exception("exception")
Exception: exception

**Comment by vallsv** [comment]
Thanks for the report. No time now, but i will take care of it.

**Comment by vallsv** [comment]
Which version do you use?
It any tests fails?
I think this is only a message log when we test exception in custom callback.
And since 0.3, we fix the test to display nothing on the logs (in fact we tests the logs).

**Comment by ohlssonm** [comment]
Dear Valentin,

I had this error during the course  on Silx and Jérôme told me to submit it...

I am sure this full trace will help you understand better.

C:\WINDOWS\system32>ipython
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import silx.test
WARNING:silx.opencl:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
WARNING:sift.match:No PyOpenCL, no sift
WARNING:sift.alignment:No PyOpenCL, no sift
WARNING:silx.image.sift.test.test_matching:feature module is not available to compare results with C++ implementation. Matching cannot be tested.

In [2]: silx.test.run_tests()
...........QWindowsWindow::setGeometry: Unable to set geometry 256x192+1280+610 on QWidgetWindow/'LegendListViewClassWindow'. Resulting geometry:  292x192+1280+610 (frame: 16, 72, 16, 16, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).
...............................................................................................ERROR:silx.gui.widgets.ThreadPoolPushButton:Error while executing callable silx.gui.widgets.test.test_threadpoolpushbutton._computeFail.
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\site-packages\silx\gui\widgets\ThreadPoolPushButton.py", line 57, in run
    result = self.__callable(*self.__args, **self.__kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\silx\gui\widgets\test\test_threadpoolpushbutton.py", line 54, in _computeFail
    raise Exception("exception")
Exception: exception
....ss.............................................................................s........................................................................................................................................................................................................................................................................................................................................................................................WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
.WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
.C:\Program Files\Anaconda2\lib\site-packages\silx\math\fit\test\test_fit.py:51: RuntimeWarning: invalid value encountered in multiply
  return numpy.exp(x*numpy.less(abs(x), 250)) - \
WARNING:silx.math.fit.leastsq:Supplied function does not return a proper array of floats.
Function should be rewritten to return a 1D array of floats.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function unable to handle non-finite x data
Attempting to filter out those x data values.
WARNING:silx.math.fit.leastsq:Need to reshape input xdata.
..........................................................................................ssssssssssssssssssssssssssss..
----------------------------------------------------------------------
Ran 688 tests in 52.805s

OK (skipped=31)
Test suite succeeded
Out[2]: 0

**Comment by ohlssonm** [comment]
If you want more info, you need to be patient, since this was seen on my "home PC".

Olof Svesson saw exactly the same on his "work PC" so just going to his office might be faster to solve this "problem" if it is one. For me personally I could not care less... All seem to work.. It is more a help to you guys.. When you do a silx.test.run_tests() and it gives you ERROR it does not really inspire confidence ;-)

Anyway, you told me about the latest version 0.30 that does not have this problem... What do I need to do?

Is "pip install silx" enough?

**Comment by ohlssonm** [comment]
Oops I did not want to close the issue... Newbie with github...

**Comment by vallsv** [comment]
Hi Staffan. Then it is only a log and it is normal. It is now filtered in the master branch, cause you are right it create confusion. Then i close this issue. Thanks a lot anyway for the feed back.
