### ISSUE TITLE
Scipy 1.13.0 removes scipy.signal.gaussian

### ISSUE THREAD

**Issue by pierrepaleo** [silx-kit/silx#4086]
Heads-up:

```
.. warning:: scipy.signal.gaussian is deprecated,
             use scipy.signal.windows.gaussian instead.
```

(thanks @kif for noticing)

**Comment by pierrepaleo** [comment]
In the end it looks like all usages of `scipy.signal.gaussian` is through comments.

Sould I still do a PR to replace `scipy.signal.gaussian` with `scipy.signal.windows.gaussian` in the comments ?

**Comment by t20100** [comment]
It's also used in the examples.

It changed in [scipy 1.1.0](https://docs.scipy.org/doc/scipy/release/1.1.0-notes.html#deprecated-features) (May 2018).

PR welcomed to replace with the up-to-date namespace in comments and examples.
