### ISSUE TITLE
Dead Links in README.rst

### ISSUE THREAD

**Issue by cchndl** [silx-kit/silx#4095]
In the README, there are four dead links that all link to http://www.silx.org/doc/silx/dev or below:

- Detailed installation instructions -> http://www.silx.org/doc/silx/dev/install.html
- the nightly build -> http://www.silx.org/doc/silx/dev
- documentation on testing -> http://www.silx.org/doc/silx/dev/install.html#testing
- silx documentation -> http://www.silx.org/doc/silx/dev/sample_code/index.html

The /dev is empty, so 1,3 and 4 result in 404 errors.

From what I can see I am not sure, if the /dev docs are no longer built. But I think all but the second one can also be moved to point to /latest, right?

**Comment by t20100** [comment]
> But I think all but the second one can also be moved to point to /latest, right?

That's right!
