### ISSUE TITLE
Freeze in Spyder

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#410]
When run in Spyder (win python - windows7), there is an python embedded console.
then: 
```
   %gui qt
   from six.gui.plot import Plot1D
```

just locks everything. looks like a dead lock.

**Comment by payno** [comment]
Did you wait until the '%gui qt' command ended ? 
We had some kermel crah under notebook sometime if the %gui qt is not on a separated cell

**Comment by PiRK** [comment]
This could be the same issue as described in #538 (ipython console widget related)

**Comment by t20100** [comment]
I could not reproduce this issue neither with Spyder nor with the notebook with WinPython-64bit-3.6.3.0Qt5 (latest version) and silx 0.6.1.

So I'm closing it.
