### ISSUE TITLE
How can I copy the data in Raw view?

### ISSUE THREAD

**Issue by DechinPhy** [silx-kit/silx#4116]
![2024-04-22 09-54-11 的屏幕截图](https://github.com/silx-kit/silx/assets/42831382/a3a37c81-10f0-492f-86d0-02439c76a96d)

Right click on the mouse dose not work. How can I copy the data in the raw?

**Comment by t20100** [comment]
Hi, `Ctrl-C` should work

**Comment by DechinPhy** [comment]
> Hi, `Ctrl-C` should work

It works, thank you!
