### ISSUE TITLE
[Plot1D] fit in zoomed area and in selected ROI

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#412]
The current fitting in plot1D seems to fit the whole data set.
It will be nice to be able to fit in the zoomed area (like PyMCA) or better yet, to fit the active ROI

**Comment by vasole** [comment]
If it is not able to fit just the zoomed area, I would consider it a bug.

To fit the active ROI it would make the fit to be an action of the ROI and not of the plot. I would not go that way.
