### ISSUE TITLE
[plot] ROI widget: add and document an API to get the ROI information

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#413]

**Comment by vasole** [comment]
To me this has been closed by #505 and #474

**Comment by vasole** [comment]
@PiRK 

Please, can you confirm this can be actually closed?

**Comment by PiRK** [comment]
There were a few missing links between `PlotWindow.getCurvesRoiDockWidget` and the actual ROI information, which currently is only accessible in `CurvesROIWidget`. I'm not sure that the API that my PR made public is supposed to be public, but it is the only option as far as I can tell.
