### ISSUE TITLE
Lineplot window doesn't open on Wayland

### ISSUE THREAD

**Issue by clemisch** [silx-kit/silx#4135]
When I use `silx view <file>`, look at an 2D image and do any line profile, the extra window with the line plot does not appear. No error is reported. 

When I use 

```
QT_QPA_PLATFORM=wayland silx view <file>
```

the extra window does pop up. 

What surprises me is that I'm used to `ipython3 --gui=qt5` working without any issues on Wayland, while silx appears to require the explicit QT flag. 

I'm on Fedora 40, Gnome on Wayland. silx is installed via pipx and running under Python 3.12.

**Comment by t20100** [comment]
Hi,

I don't have access to a machine to try this.

To be sure, can you check which version of Qt and which binding `silx view` is loading? You can see it from the `Help -> 
About` menu.
It would also be good to check which rendering backend is used (OpenGL or matplotlib). You can see it in the `Options -> Plot rendering backend: <backend>` menu.

Also, can you run the following code from `ipython3 --gui=qt5` and do a line profile as you do with `silx view`? This reproduces what you do in `silx view`, and would allow to check if the behavior is different. 

```python
from silx import sx; import numpy as np
w = sx.imshow(np.arange(100*100).reshape(100, 100))
```

To know which platform is used by default, you can run `QT_DEBUG_PLUGINS=1 silx view`.
It's quite verbose, but checking the `loaded library ...` lines allows to find which platform is used by default (`xcb` I guess).

**Comment by loichuder** [comment]
I am also on Gnome on Wayland (Ubuntu 22.04) and I cannot reproduce this, whether it is with Python 3.9 or 3.12.

I think further information is needed then: see the instructions given by @t20100

**Comment by clemisch** [comment]
Thanks for looking into this! Sorry for my delayed response.<br/><br/>

> can you check which version of Qt and which binding `silx view` is loading?

Qt version 5.15.2, Qt binding PyQt5 <br/><br/>

> It would also be good to check which rendering backend is used

At the moment it's matplotlib. Behavior is unchanged for opengl (after restart and confirming it's using opengl).   <br/><br/>

> Also, can you run the following code

The lineplot also doesn't show up here.   <br/><br/>

>  To know which platform is used by default, you can run `QT_DEBUG_PLUGINS=1 silx view`

It looks to me like that's also using qt5? Only in the first line it's `PyQt5/.../libqxcb.so`.

```
$ grep "loaded library" silx_log.txt 
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so"
loaded library "Xcursor"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/iconengines/libqsvgicon.so"
loaded library "/home/clem/.local/share/pipx/venvs/silx/lib/python3.12/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so"
```

**Comment by t20100** [comment]
Can you try to run this script? It reproduces what `silx view` profile does with regarding windows but without silx.
My guess is that there is an issue when opening a sub-window in an application, this would allow to check it.

```python
from PyQt5 import QtCore, QtGui, QtWidgets

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        btn = QtWidgets.QPushButton("Press")
        self.setCentralWidget(btn)
        btn.clicked.connect(self._clicked)

    def _clicked(self):
        print("new window")
        new_window = QtWidgets.QMainWindow(self)
        new_window.show()

app = QtWidgets.QApplication([])

window = MainWindow()
window.setAttribute(QtCore.Qt.WA_DeleteOnClose)
window.show()

app.exec()
```

You can also try with the latest version of PyQt5 (5.15.11) and with other Qt bindings: PyQt6 and/or PySide6 to see if it is better.
`silx` gives priority to PyQt5 if it is installed, so to try the other Qt bindings, you either need to set `QT_API=PyQt6` (or `PySide6`) or to uninstall `PyQt5`.

**Comment by clemisch** [comment]
Thanks! 

When I click "Press" the script does open a new window. This works both with `$ python script.py` and inside `$ ipython3 --gui=qt5`. 

It just occured to me that e.g. the histogram window inside `$ silx view` does open. It seems that only the line plot doesn't work.

**Comment by clemisch** [comment]
...but to me the lineplot is by far the most used feature! :smiley: 

I understand though that this is not high priority for you. The workaround with `QT_QPA_PLATFORM=wayland` is working for now. I mainly wanted to open an issue about it because I was confused at first and didn't know if the lineplot was working *at all*.

**Comment by t20100** [comment]
Thanks for opening the issue! It's the first time we hear about this issue.

I currently don't have much time to work on this project, but we'll figure out what is going wrong (It might take some time since we cannot reproduce it though).

I would still bet on an issue with sub-windows in your particular set-up:
The histogram uses a `QWidget`  with `flags=QtCore.Qt.Window` while the profile uses a `QMainWindow` with `flags=QtCore.Qt.Dialog`.

Did you try with the latest `PyQt5` and with `PyQt6` and `PySide6`? Do you have the same issue?

Could you try this code? It's almost the same as the previous one, except for `flags=QtCore.Qt.Dialog` which I missed the first time I checked the profile code:

```python
from PyQt5 import QtCore, QtGui, QtWidgets

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        btn = QtWidgets.QPushButton("Press")
        self.setCentralWidget(btn)
        btn.clicked.connect(self._clicked)

    def _clicked(self):
        print("new window")
        new_window = QtWidgets.QMainWindow(self, flags=QtCore.Qt.Dialog)
        new_window.show()

app = QtWidgets.QApplication([])

window = MainWindow()
window.setAttribute(QtCore.Qt.WA_DeleteOnClose)
window.show()

app.exec()
```

You can also try patching `silx` by removing `flags=QtCore.Qt.Dialog` here:

https://github.com/silx-kit/silx/blob/a7da2634a2a26e1b77ea3e4bdf080027da2a7c0a/src/silx/gui/plot/tools/profile/manager.py#L141-L142

**Comment by clemisch** [comment]
Thanks for coming back on this.

> Did you try with the latest PyQt5 and with PyQt6 and PySide6? Do you have the same issue?

Ha! It seems to work with `pyqt6`. I can either force it with `ipython3 --gui=qt6`, or I uninstall `pyqt5`, install `pyqt6`, and then `silx view file` uses qt6 (reported in *About*). 

I see no downside of switching my overall workflow to `--gui=qt6`.

The default of silx seems to be qt5, though? Installed with `pipx`, is uses `pyqt5` by default.

---

> Could you try this code? It's almost the same as the previous one, except for flags=QtCore.Qt.Dialog which I missed the first time I checked the profile code:

This code opens a new window on click. The previous version of is [also worked](https://github.com/silx-kit/silx/issues/4135#issuecomment-2246135638).

---

> You can also try patching silx by removing flags=QtCore.Qt.Dialog here:

Curiously, this does not change anything. Qt5 doesn't work, Qt6 works.

**Comment by t20100** [comment]
> I see no downside of switching my overall workflow to --gui=qt6.

+1

> The default of silx seems to be qt5, though? 

Yes, installing `silx[full]` installs `pyqt5` and it's been the main Qt binding in use (and tested) in the last years...

Qt5 has reaching the end of regular support and only receives updates under [extended commercial support](https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders), so it's timely to consider switching the default to Qt6.

I'm worried it will be tedious to find a workaround for this issue with pyqt5 since we are not able to reproduce it.
So, if you can live with it until we switch to use qt6 (probably pyside6) by default, that would be great.

**Comment by payno** [comment]
For information I can reproduce it from our 'LAPDAU' laptop and with the following environment:

- current main branch ( Silx version 2.1.1-a0)
- Qt version 5.15.15 
- Qt binding: PyQt5 
- Python version: 3.12.3


It seems there is some kind of weird behavior in https://github.com/t20100/silx/blob/main/src/silx/gui/plot/tools/profile/manager.py#L905-L914
Even if the code runs without errors no window is displayed...

**Comment by payno** [comment]
@clemisch : commit https://github.com/silx-kit/silx/commit/054c497aa63d2f6086c21a749b555dba25b00332 should fix your issue. If you have time could you please confirm this also work for you ? Thanks.

**Comment by clemisch** [comment]
I pulled https://github.com/silx-kit/silx/commit/054c497aa63d2f6086c21a749b555dba25b00332 and can confirm it does open the lineplot window now! Thanks :+1:

**Comment by t20100** [comment]
Thanks for the testing!
