### ISSUE TITLE
Silx view: Y log scale and limits

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#4152]
![image](https://github.com/user-attachments/assets/8c2267c8-5666-4296-ab3e-b5333b98bf51)

When looking at data with zero's in log scale, the Y-limits are messed up. When determines the Y-limits in log scale? Can non-finite numbers be ignored?

**Comment by t20100** [comment]
> When determines the Y-limits in log scale? Can non-finite numbers be ignored?

AFAIR, non-finite and negative numbers are ignored and not displayed. The limits are computed from min/max of finite strictly positive values.

Can you provide data to reproduce? What do you expect here?

**Comment by woutdenolf** [comment]
The primary signal are integers but the fit and residuals are not and they contain very small non-zero values. Sorry for the noise.
