### ISSUE TITLE
hdf5 widget drag and drop

### ISSUE THREAD

**Issue by danielzt12** [silx-kit/silx#418]
OSX 10.10
Error occurred when loading files:
Filename '/.file/id=6571367.131626049' must be a file path

after 
from silx.gui import qt
from silx.gui import hdf5
app = qt.QApplication([])
tree = hdf5.Hdf5TreeView()
tree.setVisible(True)
app.exec_()

**Comment by vallsv** [comment]
It looks to be a Qt issue. http://stackoverflow.com/questions/27093697/os-x-yosemite-qt-drag-and-drop-file-name-bug

**Comment by vallsv** [comment]
Would it be possible to know your Qt version? I can reproduce it in Qt4 but it looks to be impossible to fix it with this version. While with Qt5 it is maybe possible.

**Comment by danielzt12** [comment]
if I am not mistaken we used the qt from silx, right?

**Comment by vallsv** [comment]
It depend on the binding installed on your machine. It can be PyQt4, PyQt5, or PySide.

BTW there is finally a way to fix that issue. We will do it. I think PyQt5 is already fixed that's why i ass.

**Comment by danielzt12** [comment]
It is Qt4
