### ISSUE TITLE
[Plot] addImage origin argument has a different meaning than matplotlib

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#421]
In matplotlib origin is for 'upper' or 'lower' origin of the image.
In silx it is for the offset of the image from the origin.
So naming it offset or translate rather than origin would be more appropriate...
But does it worth an API change?

**Comment by payno** [comment]
From my point of view it not useful to change the API as it is well documented and a 'comprehensible' parameter

**Comment by t20100** [comment]
OK, so let's keep it this way.
I'm closing this issue.
