### ISSUE TITLE
[io] SpecH5 seg fault when the file is not spec file

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#424]
If possible test the file before opening it with the C code to check that it is spec and raise an IOError instead of set fault.

**Comment by PiRK** [comment]
We need to figure out a reasonable criterion for determining that a file is indeed a spec file, without having to read the complete file. Is it good enough to ensure that there is a "\n#S" or a "\n#F" within the first N lines ? N=100 or N=10?

Can there be exotic cases where the file starts with many comment lines (#C), or any other header or empty lines?

**Comment by vasole** [comment]
PyMca is just testing the first 2 lines to start by #F or #S and nobody has complained yet ...
