### ISSUE TITLE
[sx] sx does not load gui when in a notebook

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#426]
When sx is imported in a notebook it does not load gui stuff.
Do we want to change that?

In this case, ideally it would need to check if it is run locally or remotely...

**Comment by PiRK** [comment]
My opinion is that it would be a good feature to have. The notebook was really helpful for the training exercises, for the trainees who were lucky enough to have it installed on their laptops.

Having "sx.plot" available would allow us to skip the "%pylab inline" and "%gui qt" explanations.

**Comment by t20100** [comment]
Problem is that it would load qt even when logged remotely to the notebook.

It should print a message that it is not loading guy
