### ISSUE TITLE
Remove PyMca.PyMcaIO dependency from silx

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#440]
There is a dependency to MarCCD from PyMca. It would be better to remove it.
```
try:
    from PyMca5.PyMcaIO import MarCCD
    MARCCD_SUPPORT = True
except ImportError:
    #MarCCD
    MARCCD_SUPPORT = False
```

**Comment by vasole** [comment]
I would not call that a dependency but unused code that will disappear if the module is adapted to silx standards.
