### ISSUE TITLE
Plot2D pixel value when multiple images

### ISSUE THREAD

**Issue by WatierYves** [silx-kit/silx#464]
Hi,

When plotting multiple images with different origin (to have them side to side in this example) one cannot see the pixel value except for the first one ("data: -" displayed at the bottom left).

plot = Plot2D()
plot.show()

then for each file : 
plot.addImage(original.data, legend=file, replace=False, colormap=colormap, origin=(500*layer,0), z=layer)

Same without z parameter (wasn't sure of what it does yet).

Cheers,
Yves

PS: This time Damien look at it _before_ me issuing ;-)

**Comment by vasole** [comment]
Perhaps I do not remember it well but I think one has to make sure the image is active.

You can imagine having several overlapping images. In one way or another, you have to tell what image is the one you what the information from.

**Comment by t20100** [comment]
I also think it is only for the 'active' image now....
We can improve it and give the info for all images.
For overlapping images, we can display the data value from the top-most image.

**Comment by WatierYves** [comment]
Sounds legit ;-)

Also, the colormap dialog end with the same features.  

Maybe a feature request could be to have a way to select which image we want active, from within the plot2D widget, while having dialogs changing parameters by default on all images ?
Something like right click or a button, showing the list of images based on the legend parameter ?

Looks to me more natural when two images are side by side that the colormap action of the plot2d widget modify both.  Seems tedious to have to select individually all images and fill in colormaps dialogs one by one.
Nonetheless, having a way to select individually an image to change some specific parameters would be nice in the future too.

**Comment by vasole** [comment]
In the 3D module of PyMca, a single click on an object was turning that object "active". Also in same 3D module, one could apply a colormap to an object or to the complete scene. In the later all the objects were sharing the same colormap.

It looks to me that you are more interested on the specialized case of having a stack of images that you want to browse in 2D. We are preparing a widget for that. There the colormap will be shared among all the images, but onlyone will be displayed at a time.
