### ISSUE TITLE
Create a silx.gui.data

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#475]
Maybe we have enough widget about "data" in `silx.gui.widgets`. And i guess we will have more widget about that.

In order to have a stable API, it would be nice to decide to create `silx.gui.data` before the release of silx-0.4. silx-0.3 does not provides this kind of widget anyway.

**Comment by PiRK** [comment]
I agree. Most `silx.gui.widgets` modules could be regrouped in `silx.gui.data`.

```
gui
    data
        ArrayTableModel.py
        ArrayTableWidget.py
        DataViewerFrame.py
        DataViewer.py
        DataViewerSelector.py
        FrameBrowser.py (?)
        NumpyAxesSelector.py
    widgets
        PeriodicTable.py
        TableWidget.py
        ThreadPoolPushButton.py
        WaitingPushButton.py
```
