### ISSUE TITLE
addImage with negative scaling breaks the mask tool

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#478]
Hi, 

In a `Plot2D` widget, you can use negative values for `scale` when calling `addImage()`, but then the `MaskToolsWidget` doesn't work (as the following code shows). If `scale` is assumed to be positive, then `addImage()` should raise an error or a warning if otherwise.

~~~~
import PyQt4
import silx.gui.plot
import numpy as np

app = PyQt4.QtGui.QApplication([])

im = np.arange(100).reshape((10, 10))
plot = silx.gui.plot.Plot2D()
plot.addImage(im, scale=(-1, 1))
plot.show()

app.exec_()
~~~~

Thanks,
Alex

**Comment by t20100** [comment]
scale can be negative in the Plot, but it was not tested for the mask.
I'll look at it.
Ideally it should be supported, and if the mask do not support it, it should be disabled for such images.
