### ISSUE TITLE
specfile C library license is LGPL v2

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#5]
Can we change it to MIT?
Otherwise, add an entry for it in copyright file to remember it.

**Comment by vasole** [comment]
I do not see any major problem on changing the copyright.

**Comment by kif** [comment]
On Wed, 02 Mar 2016 03:17:40 -0800
V. Armando Solé <notifications@github.com> wrote:

> I do not see any major problem on changing the copyright.

copyright and license are the same thing.
One has to check if it is the author (V. Rey) or the copyright holder (ESRF)

**Comment by vasole** [comment]
On 08/03/2016 08:59, Jerome Kieffer wrote:
> On Wed, 02 Mar 2016 03:17:40 -0800
> V. Armando Solé <notifications@github.com> wrote:
>
> > I do not see any major problem on changing the copyright.
>
> copyright and license are the same thing.
> One has to check if it is the author (V. Rey) or the copyright holder 
> (ESRF)

Specfile is intellectual property of the ESRF. If the ESRF decides to 
change the license there is no problem at all.

**Comment by vasole** [comment]
Sorry to mix up copyright and license i my answer.

I meant I do not see any problem on changing the license. Obviously we are not going to change the author (V. Rey) and the copyright holder is the ESRF.

**Comment by vasole** [comment]
Is this really a bug? I am not against changing the license, but we said we would accept LGPL contributions.

**Comment by t20100** [comment]
The bug is that the copyright file at the root does not list specfile library as being LGPL

**Comment by vasole** [comment]
Closed by #42
