### ISSUE TITLE
[Plot] Plot ranges are changed when the widget is resized.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#507]
Plot something, then resize the widget : axis ranges should stay the same.

**Comment by t20100** [comment]
The plot lets matplotlib handling the resize.
When autoscale is on, matplotlib keeps the limits of the X axis and adjusts the Y limits.

**Comment by t20100** [comment]
Won't fix as we cannot support both resize and autoscale without changing limits.
See #911 for sending `limitsChanged` signal while resizing
