### ISSUE TITLE
[style] Signals 

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#514]
I like PyQtGraph approach of systematically prepending sig to attributes set to library signals.

For things released on previous versions I would not change it, but we could keep it in mind on things making its appearance in this release. That approach has the advantage of never colliding with any "native" Qt signal (current or future) or user set attribute.

**Comment by vasole** [comment]
@t20100 

Have you made your mind?

**Comment by t20100** [comment]
I've used the `sig` prefix for signals throughout `plot` and `plot3d` and I'm fine with it.
The only problem with this is when you want to mimic Qt API and reuse existing signal names.
