### ISSUE TITLE
[hdf5viewer] Default visualization should be more economical

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#529]
At the moment we have a number of dimensions of three, and in absence of any directive concerning the interpretation of the dataset, the default is to use the 3D plot. I would default to a stack of images or to a table view. Those two should easily handling dynamic loading of the data while the 3D plot at this point imposes loading the data into memory.

**Comment by vallsv** [comment]
I agree. I will fix that.

**Comment by vallsv** [comment]
I will display a 2D image while #489 is not fixed.

Right now, when we use the 2D stack from the dataviwer it is needed to copy the full cube. It can be fixed if `DatasetView` implement a `__getitem__` supporting `:`.

**Comment by vallsv** [comment]
Closed by 976f5d4
