### ISSUE TITLE
[opencl] silx.opencl tests are not executed, and they fail

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#537]
It looks like we forgot to run some of the tests. The  `__init__.py` in the main test package should probably include:
```
from ..opencl import test as test_ocl
test_suite.addTest(test_ocl.suite())
```

But the tests in silx.opencl.test seem to currently fail.

```
knobel@linsimak:~/git/silx$ python run_tests.py -i silx.opencl.test.suite
WARNING:run_tests:Building silx to /users/knobel/git/silx/build/lib.linux-x86_64-2.7
running build
running build_py
running build_ext
WARNING:run_tests:Patched sys.path, added: '/users/knobel/git/silx/build/lib.linux-x86_64-2.7'
WARNING:run_tests:Test silx 0.4.0-dev0 from /users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
Error clEnqueueNDRangeKernel failed: invalid work item size on WG=2048
.EMaximum valid workgroup size 1024 on device <pyopencl.Device 'Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz' on 'AMD Accelerated Parallel Processing' at 0x1299410>

======================================================================
ERROR: test_measurement (silx.opencl.test.test_addition.TestAddition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/opencl/test/test_addition.py", line 116, in test_measurement
    for pid, platform in ocl.platforms:
TypeError: 'Platform' object is not iterable

----------------------------------------------------------------------
Ran 2 tests in 0.010s

FAILED (errors=1)
WARNING:run_tests:Test suite failed
```

**Comment by payno** [comment]
The source code of test_measurement is not up to date. 

It seems like the source code should looks like something close to : 

`
    @unittest.skipUnless(ocl, "pyopencl is missing")
    def test_measurement(self):
        """
        tests that all devices are working properly ...
        """
        for platform in ocl.platforms:
            for did, device in enumerate(platform.devices):
                print(device)
                meas = measure_workgroup_size(device)
                self.assertEqual(meas, device.max_work_group_size,
                                 "Workgroup size for %s/%s: %s == %s" % (platform, device, meas, device.max_work_group_size))
`

But then an error occur in sopencl.__init__._measure_workgroup_size because the given device is not a pyopencl.Device but a silx.pyopencl.Device maybe we can just cast it but I am not sure the test_measurement function is still usefull ?
