### ISSUE TITLE
DataViewer: Display list of single element as Raw, and not Plot1D

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#541]
That's something which can be done for more dimensions

- An image of 1xn can be see as a curve
- A cube of 1xnxm  can be see as an image
- ...

**Comment by vasole** [comment]
I guess in PyMca I will offer raw as default unless the "interpretation" attribute is set, but it is just a guess.

**Comment by vallsv** [comment]
I really have no idea. I will only fix this case. I guess it is quite fine to display image.
