### ISSUE TITLE
[plot] PlotWindow backward compatibility

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#547]
PR #505 changed PlotWindow API from attributes/properties to getters.
@dnaudet noticed backward compatibility issues for properties:

- crosshairAction
- panWithArrowKeysAction

I think we should maintain backward compatibility as much as possible for previously documented attribute/properties and this worth a second check.

**Comment by PiRK** [comment]
Both of these attributes still exist, the only difference being that they are no longer properties.
Is the problem related to the fact that they are initially set to `None` until their getter is called for the first time?

**Comment by dnaudet** [comment]
Yes.
And by quickly looking at the diff of #505 i think you can add the **consoleAction** to the list (those three getters are called only when *control* is passed to the constructor it seems?).

=> maybe either make sure the actions are created when the plot constructor is called, or replace the attribute by a property that will call the getter?
