### ISSUE TITLE
[plot3d] Issue with color picker in parameter tree on MacOS

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#555]
On MacOS El Captain with python 3.4, PyQt4.8.7, there is a issue with the color picker: changing one color in the param tree changes other colors… Cancel and OK buttons are added to the dialog each time  the dialog is opened.

**Comment by vincefn** [comment]
Selecting colours works fine when only changing isosurface colors. The incorrect colour assignment only appears when trying to choose a foreground or background colour.

**Comment by t20100** [comment]
This is apparently due to the use of native color dialog on MacOS.
