### ISSUE TITLE
[PeriodicTable] improve documentation

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#558]
- currently there is no documentation on how to construct a custom list of elements and pass them to the widgets' constructor
- doc of getSelection is inconsistent (return type: list of symbols or list of items?)
- inconsistency: setSelection() takes a list of symbols, getSelection() return a list of objects (PeriodicTableItem). Maybe make getSelection() return list of symbols and add getSelectedItems() for items. Not sure we can change this, check legacy compatibility issues with PyMca widget

**Comment by CaptainNemoz** [comment]
I would like to use the Periodic table items to calculate the molecular weight of  a compound given its chemical formula. Currently it imposes dependencies on qt.

**Comment by vasole** [comment]
@CaptainNemoz 

There are other tools available for that. In particular the fisx library (http://github.com/vasole/fisx). At a certain point it will be moved under the silx-kit umbrella. You can try pip install fisx.
