### ISSUE TITLE
StackViewMainWindow in silx.gui.plot.StackView: unselect profile

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#564]
after working with profile tool, it remains active even when it is unselected, so the profile window appears when passing from one slice to another

**Comment by payno** [comment]
on it

**Comment by payno** [comment]
If the profile window is closed then the profile lines are cleared but the selection mode is not changing

**Comment by vasole** [comment]
@PiRK Check if solved by #577

**Comment by PiRK** [comment]
Closed by #577
