### ISSUE TITLE
hdf5widget: allow copying the data path in the clipboard

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#573]
It would be very useful to be able to copy the path string to the clipboard, e.g. by adding "copy path to clipboard" in the contextual (right-click) menu of entries in the tree view.
This can be used to copy the path in a python script.

**Comment by vallsv** [comment]
That's a good idea. We can do it when we will implement default close/synchronize options

**Comment by vallsv** [comment]
For the 0.4 release, (a pull request is in process) it will be possible to copy the path (with ctrl-c) from the HDF5 view. It can already be useful.

![screenshot from 2017-01-27 13 52 59](https://cloud.githubusercontent.com/assets/7579321/22371641/7b79140a-e498-11e6-809a-b1fa78b2f31e.png)

**Comment by vallsv** [comment]
Let us know it it is enough.

**Comment by vincefn** [comment]
Perfect !
