### ISSUE TITLE
[StackView] handle scale and origin

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#574]
Scale and origin parameters passed to `setStack` are currently lost when users change the perspective. We need to either handle them properly, or prevent users from changing the perspective when these arguments are not the  default ones.

Related to #567

**Comment by vasole** [comment]
I would rename the method as setImageStack to keep the functionality and to clearly state that origin and scale are to be used as for images.

**Comment by vasole** [comment]
silx meeting: A more generic calibration will be needed. It is preferable to drop origin and scale in this release and forget about modifying names.
