### ISSUE TITLE
[ci] Update CI systems setup to install dependencies

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#575]
Check that dependencies (like fabio) are installed during continuous integration so that as much test as possible are run.

**Comment by t20100** [comment]
Status after PR #607 (which adds fabio) gets merged:
- On appveyor (Windows): pyopencl, Mako and PyOpenGL (as well as drivers/mesa impementation) are not installed and related tests are not run.
- On travis (Linux and MacOS): All dependencies are installed and all tests are run (except GUI tests on Linux with python 2.7 and 3.4 which are missing a PyQt wheel to be enabled).

**Comment by vasole** [comment]
As far as I know PyOpenGL is a source package not requiring compilation.

What is the problem of having it for AppVeyor?

**Comment by t20100** [comment]
No problem... but it will also need OpenGL drivers or mesa lib.
I'll add it when I actually have some tests using OpenGL.
