### ISSUE TITLE
Fix silx.math setup.py paths.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#58]
Pointed out by @kif: in silx/silx/math/setup.py os.path.join should be used to generate the paths.

IIRC os.path.join wasn't used because distutils handles both slash and backslash on windows (I think...). But still, it's better to use os.path.join.

```python
histo_src = ['/'.join([histo_dir, srcf])
                 for srcf in ['histogramnd.pyx',
                              'src/histogramnd_c.c']]
histo_inc = ['/'.join([histo_dir, 'include']),
                 numpy.get_include()]
```

**Comment by vasole** [comment]
Closed by #27
