### ISSUE TITLE
Unreleased section on CHANGELOG

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#597]
CHANGELOG file as an Unreleased section which is never used until now.
Should we remove it to avoid any confusion ? Or to be more careful when creating more feature ?

**Comment by vasole** [comment]
Good question. I think to use it could simplify the task of the persons doing the actual release. However, if in any case we have to go through the git log I am not so sure about its utility.

**Comment by t20100** [comment]
Even if we fill the changelog at each PR, we'll have to get through the logs anyway to check that nothing is missing...

**Comment by vallsv** [comment]
I would prefer to remove it, it is not used and it is a wast of time for the release

**Comment by vasole** [comment]
Removed.
