### ISSUE TITLE
check fabio version

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#598]
A test on fabio version is probably missing.
If fabio version is too old, silx will be build and unit test runned.

fabio.fabioImage.OrderedDict
Issue is :  fabioimage has no attribute numpyimage (in this case fabio version was 0.1.4)

**Comment by t20100** [comment]
This can be 'documented' in the requirements.txt file: fabio >= 0.X.X

**Comment by vallsv** [comment]
It sounds better

**Comment by vallsv** [comment]
I check fabio revisions. numpyimage was introduced in fabio 0.3

**Comment by vallsv** [comment]
I cna take care of it if nobody do it before
