### ISSUE TITLE
[PlotWindow] separator in toolbar shown even when following actions hidden

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#599]
When a plot window is initialized without  `copy`, `save`, `print_` and `fit`, a separator is shown without icons. 

![screenshot - 01312017 - 03 12 19 pm](https://cloud.githubusercontent.com/assets/419570/22468190/bd8af0a2-e7c7-11e6-8110-fda5dba64bc8.png)

https://github.com/silx-kit/silx/blob/e90db8fd6dee0939965a2323eb29399ed59e8ad6/silx/gui/plot/PlotWindow.py#L177

Should we add a condition for adding the separator ?

        if copy or save or print_ or fit:
            self._separator = qt.QAction('separator', self)
            self._separator.setSeparator(True)
            self.group.addAction(self._separator)

**Comment by t20100** [comment]
This won't fix all situations as you can show/hide actions afterwards...

To fine-tune the toolbar, to me it is best to inherit from PlotWidget and only add the actions you need the way you want. It also avoids your toolbar to change in case someone adds an action to the PlotWindow...

**Comment by PiRK** [comment]
It turns out I probably will not hide all off these actions. And I agree that at some point if we want something very different from a default PlotWindow we should just not use the PlotWindow.

I'll close this issue.
