### ISSUE TITLE
Install error in virtualenv/python3.4 on debian8 using pip

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#601]
Installing silx in a brand-new virtualenv on debian8 with pip3.4 fails:
############
**favre@gpu2-1304:~$ export BASEDIR=~favre**
**favre@gpu2-1304:~$ cd $BASEDIR**
**favre@gpu2-1304:~$ mkdir -p test-env**
**favre@gpu2-1304:~$ virtualenv -p python3.4 test-env/**
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in test-env/bin/python3.4
Also creating executable in test-env/bin/python
Installing setuptools, pip...done.

**favre@gpu2-1304:~$ source test-env/bin/activate**

**(test-env)favre@gpu2-1304:~$ pip3.4 install --upgrade pip**

Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...

**(test-env)favre@gpu2-1304:~$ pip3.4 install numpy**

Collecting numpy
  Using cached numpy-1.12.0-cp34-cp34m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.12.0

**(test-env)favre@gpu2-1304:~$ pip3.4 install silx**

Collecting silx
  Using cached silx-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gw4145o3/silx/setup.py", line 505, in <module>
        long_description=get_readme(),
      File "/tmp/pip-build-gw4145o3/silx/setup.py", line 86, in get_readme
        long_description = fp.read()
      File "/mntdirect/_users/favre/test-env/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1401: ordinal not in range(128)
    silx.io.specfile WARNING:
    A cleaner locale independent implementation
    may be achieved setting SPECFILE_USE_GNU_SOURCE to 1
    For instance running this script as:
    SPECFILE_USE_GNU_SOURCE=1 python setup.py build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gw4145o3/silx/

    ----------------------------------------

**Comment by vincefn** [comment]
Sorry I was too quick - this is not a dependency to numpy. I've updated the description

**Comment by vincefn** [comment]
Exact steps to reproduce:
```bash
export BASEDIR=~favre
cd $BASEDIR
mkdir -p test-env
virtualenv -p python3.4 test-env/
source test-env/bin/activate
pip3.4 install --upgrade pip
pip3.4 install numpy
pip3.4 install silx
```

**Comment by vincefn** [comment]
NB: "`pip3.4 install -I silx==0.3.0`" works

**Comment by PiRK** [comment]
The word "egg" appearing at the end of your error log makes me think that you don't have `wheel`installed. Can you try 
```
pip install setuptools --upgrade
pip install wheel --upgrade
```

(http://www.silx.org/doc/silx/dev/virtualenv.html#upgrade-setuptools-and-wheel)

**Comment by vincefn** [comment]
Thanks. The following steps indeed work:
```
export BASEDIR=$PWD
cd $BASEDIR
mkdir -p test-env
virtualenv -p python3.4 test-env/
source test-env/bin/activate
pip3.4 install --upgrade pip
pip3.4 install numpy
pip3.4 install setuptools --upgrade
pip3.4 install wheel --upgrade
pip3.4 install silx
```

But it probably still should work with the non-wheel install (I don't know what the encoding error relates to), as it did for 0.3, or should install wheel & setuptools as a dependency.

**Comment by PiRK** [comment]
A test you could try to do is to delete the content of the README.rst file and see if you still get the same error.

There are non-ASCII characters in the README file (my fault), and maybe when the setup.py tries to extract information from it, it uses a different encoding than utf-8 because of your locales.

On my machine it works:
```

~/git/silx$ python3.4
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> def get_readme():
...     dirname = "/users/knobel/git/silx"
...     with open(os.path.join(dirname, "README.rst"), "r") as fp:
...         long_description = fp.read()
...     return long_description
... 
>>> import os
>>> get_readme()
'\nsilx toolkit\n============\n\...
```

**Comment by PiRK** [comment]
And this fails:
```
>>> def get_readme():
...     dirname = "/users/knobel/git/silx"
...     with open(os.path.join(dirname, "README.rst"), "r", encoding="ascii") as fp:
...         long_description = fp.read()
...     return long_description
... 
>>> get_readme()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in get_readme
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1401: ordinal not in range(128)
```

**Comment by vincefn** [comment]
Thanks for the quick fix !

**Comment by PiRK** [comment]
For future reference: the machine was configured with locale POSIX. So the built-in python 3.4 `open` expected to find only ASCII characters.
