### ISSUE TITLE
too many plot actions in PlotActions

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#605]
As the number of PlotActions are increasing and we would like to have plotactions module.
After a discussion with @t20100 it will be interesting to have silx.gui.plot.actions (or silx.gui.plot.plotactions) module grouping by type plot actions (fitactions, filteractions...)

This should also insure retro-compatibility with a deprecated warning

**Comment by vasole** [comment]
Perhaps it sounds crazy... What about a set of actions loading the desired set of actions? Something like a button able to replace itself by a set of actions.

**Comment by payno** [comment]
I propose the following division of the plot actions : 

- controlPlotActions
    class ResetZoomAction(PlotAction):
    class ZoomInAction(PlotAction):
    class ZoomOutAction(PlotAction):
    class XAxisAutoScaleAction(PlotAction):
    class YAxisAutoScaleAction(PlotAction):
    class XAxisLogarithmicAction(PlotAction):
    class YAxisLogarithmicAction(PlotAction):
    class GridAction(PlotAction):
    class CurveStyleAction(PlotAction):
    class ColormapAction(PlotAction):
    class KeepAspectRatioAction(PlotAction):
    class YAxisInvertedAction(PlotAction):
    class CrosshairAction(PlotAction):
    class PanWithArrowKeysAction(PlotAction):

- IOPlotAction
    class SaveAction(PlotAction):
    class PrintAction(PlotAction):
    class CopyAction(PlotAction):

- processingPlotActions (ou signalPlotAction mais Fit action ne rentre plus trop dedans)
    class PixelIntensitiesHistoAction(PlotAction):
    class MedianFilterAction(PlotAction):
    class MedianFilter1DAction(MedianFilterAction):
    class MedianFilter2DAction(MedianFilterAction):
    class FitAction(PlotAction):

**Comment by t20100** [comment]
Sounds good.
I would just split the last one depending on dependencies (histogram, median filter, fit) in order to avoid loading modules that are not used.

**Comment by t20100** [comment]
Also as we already are in silx.gui.plot.actions, maybe use shorter module names: e.g., control or controlActions

**Comment by t20100** [comment]
The problem with actions is also raising with other widgets that complements the plot: toolbuttons, and other widgets interacting with the plot

**Comment by t20100** [comment]
Closed by #853
