### ISSUE TITLE
[fabioh5] Test it with a generic "silx convert" to hdf5

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#609]
As discussed on 2017-02-01 at the Silx meeting

- We have to take care of SoftLink
- @pierrepaleo can be interested by this feature (it's good to have a beta tester)
- We can extract from edf metadata few nexus-normalized detector metadata if expected

**Comment by PiRK** [comment]
I will need to do some work on  `silx.io.spectoh5` to better handle soft links, without using hardcoded paths (https://github.com/silx-kit/silx/blob/38425072cbb19abb1eec603c0ad1b30fb72ecb93/silx/io/spectoh5.py#L188)
