### ISSUE TITLE
[spech5 & fabioh5] Should visit() and visititems() follow links?

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#614]
Currently `h5py.Group.visit` and `visititems` don't follow links when they recursively visit an HDF5 tree. So I also made `SpecH5Group.visit` ignore links.

But this `h5py` behavior could change in the future, see https://github.com/h5py/h5py/issues/671 (milestone 2.8). 

As the SPEC to h5 conversion relies on `visititems`, it would make our life easier if links were not ignored.  (see  #609). 

I don't expect that we will ever see a circular link in a SpecH5 or a FabioH5 object.

**Comment by carichte** [comment]
Closely related but probably another issue:
There is another discrepancy between `SpecH5Group.visit` and `h5py.Group.visit`:

while the former always returns absolute paths of the file, the latter returns relative paths within the group.
I mentioned this here: http://www.edna-site.org/lurker/message/20170424.143447.51ee80ca.en.html

Would it not be better to adapt the h5py behavior?

**Comment by PiRK** [comment]
Sorry, I believe I skipped your last message while processing all the mails when I came back from holidays.

I will investigate the discrepancy between `h5py.Group.visit` and `SpecH5Group.visit`. I suppose that when I first wrote SpecH5 my opinion was that we should include as much information as possible, and finding a relative path from an absolute path is easier than the opposite, but now I agree that we should mimic the `h5py` behavior as closely as possible.

Regarding the idea of accepting file handles as input for `SpecH5`, it will not be difficult to implement. But internally I will still need to find out the file name, in order to create a   `silx.io.specfile.SpecFile` object. So using an already open file handle will not optimize the processing in any way.

I definitely need to add a type test to prevent the segfault caused by passing a non-string to `silx.io.specfile.SpecFile`

**Comment by carichte** [comment]
Maybe it is enough to avoid a segfault and throw an error instead. 
It would be interesting, though, to change a bit the behavior of `write_spec_to_h5`, to accept also SpecH5Group next to SpecH5 and a file path.
But if I'm right, this is already possible when using `silx.io.spectoh5.SpecToHdf5Writer` instead, together with visit giving relative paths.

**Comment by PiRK** [comment]
I believe that you are right, `SpecToHdf5Writer.write` can already handle `SpecH5Group` objects.

I will modify `write_spec_to_h5` to accept groups. This should be trivial, it just needs to be added to the unit tests.

**Comment by PiRK** [comment]
I will close this issue. We improved our handling of links when we created the `commonh5` module, and `visit()` now takes an optional argument `visit_links` (False by default).

We just need to watch *h5py* for changes in the behavior of their implementation..
