### ISSUE TITLE
[icons] process-working icon is not available as png

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#616]
I encountered this issue with an installation where gif and mng image format plugins are not available:
```
silx/gui/icons.py, line 217, in getQFile
    raise ValueError('Not an icon name: %s' % name)
<type 'exceptions.ValueError'> Not an icon name: process-working
```
We should add a png (frozen image) just in case.

**Comment by vallsv** [comment]
I can try to do it with multi static png images :-)

Cause i also see the result with GIF, and that's ugly.

**Comment by t20100** [comment]
Sounds good
