### ISSUE TITLE
[FitAction] remove previous fit result from plot before starting new fit

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#619]
Comment by @CaptainNemoz : while calculating a new fit, the old fit result is still displayed on the plot, so the user might believe the fit is finished and didn't produce any visible change. 

The fitted curve should be removed from the plot prior to starting the new fitting. If possible, a wait cursor and/or a wait button should tell the user that the fit is being computed.

**Comment by vasole** [comment]
The fitted curve should be removed only if the "going-to-be-generated" legend is present. One can make a fit on a different curve.

**Comment by PiRK** [comment]
The way the action is implemented, the legend of the fitted or estimated curves are unique. So removing a fitted curve does remove the fit of a different curve.

**Comment by PiRK** [comment]
But maybe the legend of the fitted curve could even be more unique and mention the x range on which the data is fitted. This could allow the display of several fitted curves for a given origin curve.
Would this be useful?

**Comment by vasole** [comment]
I find it overkill. To solve that issue in PyMca, the user is offered to rename any curve so it does not get removed.
