### ISSUE TITLE
[mask] "Data" in the statusbar do not display the right value

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#620]
Data displayed in the status bar is the value of the pixel of the mask, not the value of the pixel of the image.

**Comment by t20100** [comment]
The default status bar displays the value of the top most image... which is the mask when making a mask....
The PlotTools.PositionInfo which is used in the status bar can be tuned by passing your own functions to provide the value to display... So you can make it display information about the image of the data only.

**Comment by vallsv** [comment]
I have to work on the mask soon. I can take care of it.
