### ISSUE TITLE
[plot] Set a fixed pixel-size ratio

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#633]
I will need to use a fixed aspect ratio for some detectors. PyQtGraph implement ```setAspectLocked``` (http://www.pyqtgraph.org/documentation/graphicsItems/viewbox.html#pyqtgraph.ViewBox.setAspectLocked) which is one way to fix my issue. is there an equivalent in our plot?

**Comment by t20100** [comment]
I think you're looking for setKeepDataAspectRatio: http://www.silx.org/doc/silx/dev/modules/gui/plot/plotwidget.html#silx.gui.plot.PlotWidget.PlotWidget.setKeepDataAspectRatio

**Comment by vallsv** [comment]
Ah yes i did not notice it. But how to set the ratio then? If i need a ratio of width/height = 0.8 or something like that?

**Comment by t20100** [comment]
As it is, it is done on an image by image basis by providing a scale=(scaleX, scaleY)

**Comment by vallsv** [comment]
Ok. The view ratio =1 and the image is stretched.
Then it is not exactly the same, but it will work for me.

**Comment by t20100** [comment]
Good, then can we close this issue?

**Comment by vallsv** [comment]
No problem
