### ISSUE TITLE
[PlotWindow] add tabified dock widget

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#646]
There is currently no public way to introduce a new dock widget tabified with existing dock widgets. 
`QMainWindow.tabifyDockWidget` takes an existing dockWidget as first parameter to place the new dock widget, and our own dock widget are lazy loaded and kept in a private attribute `_dockWidgets`.

Can we make the method `_introduceNewDockWidget` (https://github.com/silx-kit/silx/blob/master/silx/gui/plot/PlotWindow.py#L355) public? Is suggest we rename it `addNewDockWidget`.

**Comment by t20100** [comment]
Sounds reasonable, as there is some specific management of dock widgets in `PlotWindow` we cannot rely solely on `QMainWindow` API.
I would name it `addTabbedDockWidget`.
