### ISSUE TITLE
[PlotWindow] new tabbed dock widget not visible

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#657]
After adding the first dock widget, the subsequent ones are tabified but not selected. For example when opening "Legends" first, and "Mask" second, "legend" stays on top. 

A user might not notice the new tab and assume that the widget does not work. It would be better to ensure the tabs are selected after they are added.

**Comment by t20100** [comment]
PlotWindow's dock widgets are added before they are actually shown because we use the action provided by the DockWidget to show/hide them.

From a quick test, adding the following methods to those DockWidgets seems to fix the issue:
```
    def showEvent(self, event):
        self.raise_()
```
