### ISSUE TITLE
Log deprecation warning only once per deprecated function

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#659]
Now, deprecation warnings are logged each time a deprecated function is called.
To me it would be better to only log it once per deprecated function.

Also the way to silent deprecation warnings should be documented.

**Comment by vallsv** [comment]
In this case it would be better to log one time per caller, not only per called function.
It is usually more easy to fix projects while it should not be an ongoing task.

**Comment by vallsv** [comment]
BTW deprecation warnings are logger in the logger `DEPRECATION`.
It should be renamed with a `silx` prefix, for example `silx.deprecation`.

**Comment by t20100** [comment]
Yes, I completely agree.

**Comment by vallsv** [comment]
Both issue was fixed.
- Deprecation warning now have extra arguments to change the behaviour. By default it logged an only single time.
- And the logger was renamed.

See https://github.com/silx-kit/silx/blob/master/silx/utils/deprecation.py
