### ISSUE TITLE
Deprecation warnings when upgrading to 0.4.0 release

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#660]
I developed an application on top of the master branch in late December 2016. Now, when I upgraded to the 0.4.0 release (through pip), I get a large number of deprecation warnings, especially pertaining to `maskToolsDockWidget` and `curvesROIDockWidget`.

Should I replace these widgets by others, or will the functionality acually be deprecated?

Please let me know if I should provide the code or full output.

**Comment by alexbjorling** [comment]
This is now related to #658 and #659

**Comment by PiRK** [comment]
Hi Alex. 

The dock widgets atrributes and actions attributes were deprecated in #505 and #590, in favor of getter methods. 
 The new methods replacing the attributes you mentionned are:

- getMaskToolsDockWidget
- getCurvesRoiDockWidget

Thanks for spotting the issue. The changelog must be updated.

**Comment by vasole** [comment]
Closed by #655
