### ISSUE TITLE
[Plot] OO API Backwards compatibility

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#663]
The compatibility layer of the Object Oriented API misses some methods that could be easily added. PR #662 already addresses one of them.

I would expect item assignment for curve items that can be accessed through setters (x, y, and info).

![pymcasilxerror](https://cloud.githubusercontent.com/assets/5636251/23832507/d3194404-0735-11e7-974d-3ae1d09d2f0f.png)

**Comment by vasole** [comment]
@PiRK 

Independently of the decision at silx level, probably it can be handled at Plugin1DBase.py

**Comment by vasole** [comment]
@t20100 

It would be OK with me a huge warning stating that item assignment can lead to unexpected behavior.

**Comment by PiRK** [comment]
It would be easy to repack the data and return it as a list in `Plugin1DBase.getActiveCurve` and `Plugin1DBase.getAllCurves`. The drawback of doing this  would be that we will not be able to create new plugins that expect a CurveItem. 

Alternatively, we could add a simple CurveProxy object that adds a `__len__` and a `__setitem__` to the Curve item object.

My preference goes to implementing all of this directly in the silx objects, with loud warnings.

**Comment by t20100** [comment]
If we add `__setitem__` to `Curve`, then setting an item will change what is displayed in the plot as setters in PR #655...

In the case you mention (`Plugin1DBase.getMonotonicCurves`: https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaCore/Plugin1DBase.py#L213), it is not what is expected.
The returned curve data is changed but not its display on the plot...

In this code, you can avoid the in-place update:
```
allCurves = []
for curve in self.getAllCurves():
    x, y, legend, info = curve[0:4]
    allCurves.append([x, y, legend, info])
    [...]
    xproc = ...
    yproc = ...
    allCurves[-1][0:2] = xproc, yproc
return allCurves
```

**Comment by vasole** [comment]
@t20100 

So, you consider that would be equivalent to extending the functional API with a functionality that was not there and it should be avoided. It seems reasonable. 

However, in the old PyMca API, unnecessary copies were not made (use of "asarray"). In the new API, you have foreseen a _setData with the copy keyword set to True by the default. It is different but it is not a problem. Where I do see a problem is is that the addCurve method of Plot.py does not pass that keyword nor has a default set in the function signature.

**Comment by t20100** [comment]
I will change the add* methods in PR #652 so unnecessary copies are avoided.
For getters/setter of numpy array, I usually add a copy parameter with default set to True (the safest), so one explicitly disable the copy when he knows what he is doing with the array.

**Comment by vasole** [comment]
I think #652 closed this.
