### ISSUE TITLE
Implement typical usage cases or prepare demos

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#67]
I found very convenient to be able to execute a module in order to have an idea about its typical use. Most PyMca widgets where implementing if **name** ==  "**main**": and that was quite handy for both, documentation purposes and for testing the generation of signals.

For instance, I was expecting to be able to get something when doing python -m silx.gui.plot.PlotWindow but one gets absolutely nothing.

I would really prefer to have some modules, and particularly most of those implementing widgets, implementing a **def main()** function so that one could execute them as "silx ModuleName" without even having to know where they are located in the silx tree. For instance, "silx PlotWindow" would find the PlotWindow module and call its main function if present.

If none of those approaches is to be followed, a whole battery of demos is to be prepared.

**Comment by t20100** [comment]
+1 for the def main() and a generic launcher.

But I still think we will need a demos folder at some point when more than one demo will be needed for one module.

**Comment by vasole** [comment]
Following today's discussions we should aim for def main(argv=None) as function signature.

**Comment by t20100** [comment]
Closing as outdated. Issues #812 and #1364 supersede it.
Please reopen if you disagree.
