### ISSUE TITLE
How to run tests when silx is installed?

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#68]
I did not find a proper way to run the test suite using only installed modules.

I found I only could execute silx.test.test_version when I was expecting something like silx.test.test_all or similar to implement the equivalent of the run_tests.py script found with the sources.

Did I miss something?

**Comment by t20100** [comment]
Yes this is missing and  is being added.

**Comment by kif** [comment]
`import silx.test; silx.test.run_tests() ` 	
after merging d8bc2f8 (which is part of PR 70)
