### ISSUE TITLE
[fabioh5] other _mne and _pos metadata

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#682]
I notice `medipix.edf` we provide in tutorial contains `UB_mne` and `sample_mne` (see bellow).

What about unserializing in a generic way, as we do for `motor_mne` and `counter_mne`. And where should we generate it? inside `scan_0/detector_0/others/UB/...` and `scan_0/detector_0/others/sample/...`?
```
In [8]: f = fabio.open("./training.git/python/io/data/medipix.edf")

In [10]: f.header["UB_mne"]
Out[10]: 'UB0 UB1 UB2 UB3 UB4 UB5 UB6 UB7 UB8'

In [11]: f.header["UB_pos"]
Out[11]: '1.99593e-16 2.73682e-16 -1.54 -1.08894 1.08894 1.6083e-16 1.08894 1.08894 9.28619e-17'

\In [9]: f.header["sample_mne"]
Out[9]: 'U0 U1 U2 U3 U4 U5'

In [12]: f.header["sample_pos"]
Out[12]: '4.08 4.08 4.08 90 90 90'
```

**Comment by vasole** [comment]
The UB matrix is represented in different manners on different beamlines. I knew about the "UB" key and it is the first time I see the approach you show.

The UB matrix is also present in SPEC files.

Its place in the NeXus/HDF5 representation is inside entry/sample:

http://download.nexusformat.org/doc/html/classes/base_classes/NXsample.html#nxsample

The UB matrix, the user name, the beamline, ... are things to be parsed. Any other thing not being "standard" I am not sure about its utility. 

The case of the using two keys for the 9 values of the UB matrix is particularly ugly.

**Comment by vasole** [comment]
Also, the 6 values you have as "sample", in fact they correspond to the unit_cell_abc and unit_cell_alphabetagamma (also  described in the previous link).

@PiRK 

Those values (UB matrix and cell parameters) can also be present in SPEC files. They need to be properly shown under the NeXus convention into the sample group.

**Comment by vallsv** [comment]
My main topic was to at least unpack header which looks like `foo_mne`/`foo_pos`. Cause we can display it in a more easy and abstract (i mean not Nexus) way. But if you  think this pattern is not often used, it can stay like that. As you said it is anyway part of the header stored without modification.

For UB matrix, while we don't have requests, i think it is better to not implement that. As you said it is anyway part of the header stored without modification. Or you can help me.

I am afraid to create something which is not used, or wrong (cause i can't check that the result if fine).

**Comment by vasole** [comment]
The UB matrix and unit cell parameters are important and have to be written in the proper places if available. I will provide the information to both of you. For the SPEC case it is clear where to find it. For the EDF case we'll have to support (at least some of ) the existing approaches in ESRF beamlines.

**Comment by vallsv** [comment]
I close this issue. I create https://github.com/silx-kit/silx/issues/721 for the the implementation in spech5.
