### ISSUE TITLE
[plot] Split Curve class item into separated classes

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#688]
As is, histograms, scatters and curves are all defined in a single class.
The API would probably be clearer if they where separated objects in the OO API even if they share a common method to add them to the plot.

**Comment by vasole** [comment]
While I see the interest for the histogram, I really fail to see it for the scatter. To me a scatter is just a curve without line connecting the points.

**Comment by vallsv** [comment]
In this single case, if you want to create generic widget to custom styles of your items it will be already useful to split concepts.
And I guess if you want other display like voronoi or what, this class can be very useful.
BTW `PyQtGraph` provides `PlotCurveItem` and `ScatterPlotItem` (http://www.pyqtgraph.org/documentation/graphicsItems/scatterplotitem.html)

**Comment by vasole** [comment]
t20100 has clarified a point that had been escaped to me. The scatter object handles a third coordinate and it is indeed a representation of 3-dimensional data.

**Comment by t20100** [comment]
closed by #762
