### ISSUE TITLE
[mask] Split Mask and MaskToolsWidget in two classes

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#691]
It would be useful to have a BaseMask object that does not enforce a 2D mask array. We could inherit this to create an Mask2D (or ImageMask or just keep the current generic name Mask) and a Mask1D (or ScatterMask). 

Currently more than half of the Mask object is already generic and would just need a few `assert len(mask.shape) == 2` to be removed to create a BaseMask. 
The methods that need a specific implementation are `save, updateRectangle, updatePolygon, updatePoints, updateStencil, updateDisk, updateLine`.

The only challenge is that a 2D mask only needs to know about the data shape, whereas a ScatterMask will need to know about the actual data coordinates. 

The same applies to `MaskToolsWidget`.

**Comment by t20100** [comment]
Maybe have a look at PR #239 and xsocs: https://gitlab.esrf.fr/kmap/xsocs.

**Comment by vasole** [comment]
Can we not have a mask that adapts to the shape of the underlying data? The mask can be reshaped at will.

**Comment by t20100** [comment]
For images, the mask is reshaped if the image changed.

**Comment by PiRK** [comment]
The issue I see is that for an image the `updateRectangle/Circle`... methods can just return a mask array of the proper shape without much knowledge of the data, because the data "position" is given by its indices in the array. 

For a scatter, we need to look at the actual data (x, y) for each point to figure out if a point is in the rectangle/circle... before we can update the mask.

**Comment by vasole** [comment]
Why can you not use the data "position" as given by its index? 

Mask size equal to number of points

1D data ->  data[i] is associated to mask[i]
2D data -> data[i, j] is associated to mask[i *j + j]

**Comment by vasole** [comment]
Is this to be considered closed by #716?

**Comment by PiRK** [comment]
Yes, I will close it.
