### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#695]
I'm opening this issue to discuss the calibration objects.

So far, this is the code I have: 

https://github.com/PiRK/silx/blob/d271dc690ce96e789690b2674958be06f845dd46/silx/math/calibration.py

The `FunctionCalibration` is not used for the moment, and could be removed until a specific need arises.
A calibration object is mainly defined by a function already, its `__call__` method.

Usage example: https://github.com/silx-kit/silx/pull/638/files#diff-762cbffc2cee69b18c3551e1ee19bb85R344

**Comment by PiRK** [comment]
The idea behind the `is_affine` property and for the `get_slope` method is to determine if a random calibration object can be used as an axis modifier for our current `addImage` API: `origin, scale = calibration(0), calibration.get_slope()`

**Comment by PiRK** [comment]
The current status is that the `calibration`module is in the master (merged in #638): https://github.com/silx-kit/silx/blob/master/silx/math/calibration.py

There is currently no public sphinx documentation generated, but the class AbstractCalibration is mentioned in the documentation of `StackView.setStack()`: https://github.com/silx-kit/silx/blob/master/silx/gui/plot/StackView.py#L416

**Comment by vasole** [comment]
We leave the calibration object undocumented because the calibration can be passed as a tuple.
