### ISSUE TITLE
[plot] Profile toolbar refactoring

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#709]
ProfileToolBar._createProfile includes code that is only needed for Profile3DToolBar.
Would be good to refactor so that Profile3DToolBar override _createProfile to add its stuff.

**Comment by payno** [comment]
I don't know how far we should go on this factorization.
First we should create two ProfileToolBar because we have the 2D and the 3D case.

But from what I recall we said we should redo some stuff on the ProfileWindow to group those.

**Comment by woutdenolf** [comment]
Can be closed?

**Comment by vallsv** [comment]
Yes, it was fixed.
