### ISSUE TITLE
[plot] Add ColorBar to Plot2D

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#730]
Now that we have a colorbar that synchronizes itself with the plot, I think we can: 
- Have it embedded in Plot2D, hidden by default to keep backward compatibility (e.g.,  a `Plot2D.setColorBarVisible` method)
- Have it enabled when using `sx.imshow`

**Comment by vasole** [comment]
In matplotlib it is not enabled by default. However, I'm not against showing it because I consider the defaults of the dedicated implementations of PlotWindow (like Plot2D)  should show all the features.

**Comment by t20100** [comment]
If we want to be backward compatible, Plot2D should not display the colorbar by default, but just offer a method to show it... Unless we want to break this.

**Comment by vasole** [comment]
Perhaps Plot2D should offer an action to show/hide the colorbar with the default of not displaying it for backwards compatibility. That could be the same for imshow.

**Comment by t20100** [comment]
If someone embeds a Plot2D in his application, I think he does not want to have actions or colorabar popping-up when we make a new release, that's why I was thinking of a method to enable the colorbar.
But this is probably too conservative; to me the best way to use the plot in an application is to use a PlotWidget and compose the toolbar with only what is needed, this is resilient to updates of higher level widgets like Plot2D...

For imshow, which is meant for usage from the console, I would always display the colorbar.

**Comment by vasole** [comment]
Just to clarify: the action I mentioned was not excluding the method.

**Comment by vasole** [comment]
You should decide something.

We both agree that the best use for an application is to customize PlotWidget.

To me Plot2D should have all the 2D related bells and whistles at hand without requiring any programming. By that I mean that independently of the colorbar being or on off by default an action should be able to trigger it besides a method.

I can understand that for an application it can be surprising to see that a colorbar is appearing and that fully justifies the different default behavior you choose for imshow and for Plot2D. 

The only point where we seem to disagree is about the action not appearing as an icon in the toolbar. If an application wants to be sure about the toolbar it uses, it should build its own.

Summarizing:

- Different behavior between Plot2D and imshow respect colorbar. Agreed.
- A method to show/hide the colorbar in both of them. Agreed.
- An action to show/hide the colorbar in both of them. Decide. I would go for it.

**Comment by vasole** [comment]
In order to help you to decide.

Please note that I would make no exceptions. If we choose to have an action in Plot2D to trigger the colorbar, the same should be applied to the median filter.

**Comment by t20100** [comment]
What about having the colorbar in a DockWidget in the Plot2D : this allows to show/hide it without requiring an extra action in the toolbar.

If we consider Plot2D as a batteries-included data image widget, then thinking of it, I would break current behavior and have the colorbar visible by default provided there is a method to hide it.
