### ISSUE TITLE
[setup] build from source as user fails on Debian 6 

### ISSUE THREAD

**Issue by maurov** [silx-kit/silx#731]
Hello,

I would like to build `silx` from source on a beamline machine which is still running under Debian 6 and python 2.6. OK, I know that only python 2.7 is supported, but it is not so easy to upgrade it... and, by the way, I have built PyMca from source without problems.

If anybody could help, the trace is below, otherwise just close the issue.

Thanks,
Mauro

```
toscane:~/GIT/silx % SPECFILE_USE_GNU_SOURCE=1 python setup.py install --user
INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
running install
install_dir /users/opd16/.local/lib/python2.6/site-packages/
running bdist_egg
running egg_info
writing requirements to silx.egg-info/requires.txt
writing silx.egg-info/PKG-INFO
writing top-level names to silx.egg-info/top_level.txt
writing dependency_links to silx.egg-info/dependency_links.txt
reading manifest file 'silx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxi' under directory 'silx'
writing manifest file 'silx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'silx.math.medianfilter' extension
C compiler: gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC

compile options: '-Isilx/math/medianfilter/medianfilter.pyx -Isilx/math/medianfilter/include -I/usr/lib/pymodules/python2.6/numpy/core/include -I/usr/include/python2.6 -c'
gcc: silx/math/medianfilter/medianfilter.cpp
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
cc1plus: error: silx/math/medianfilter/medianfilter.pyx: not a directory
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
cc1plus: error: silx/math/medianfilter/medianfilter.pyx: not a directory
error: Command "gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isilx/math/medianfilter/medianfilter.pyx -Isilx/math/medianfilter/include -I/usr/lib/pymodules/python2.6/numpy/core/include -I/usr/include/python2.6 -c silx/math/medianfilter/medianfilter.cpp -o build/temp.linux-x86_64-2.6/silx/math/medianfilter/medianfilter.o" failed with exit status 1
```

**Comment by vallsv** [comment]
Hi. As you said, the project was not designed for python 2.6 / debian 6. Then you will have a lot of unexpected problems. Maybe you can try to upgrade setuptools and cython.

Good luck.

**Comment by t20100** [comment]
Hi,

You will probably also have trouble with missing python stuff (e.g., OrderedDict), and old version of matplotlib, numpy, etc... missing features or having changed the API...
Can you install mini/anaconda so you get python2.7 or 3 and recent packages?

**Comment by maurov** [comment]
@t20100 good idea of using miniconda. I installed then a miniconda environment with python2.7.

I still get an error building `medianfilter` (trace below). Any further idea?

```
building 'silx.math.medianfilter' extension
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-2.7/silx/math/medianfilter
compile options: '-Isilx/math/medianfilter/medianfilter.pyx -Isilx/math/medianfilter/include -I/users/opd16/miniconda2/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/users/opd16/miniconda2/envs/py27/include/python2.7 -c'
gcc: silx/math/medianfilter/medianfilter.cpp
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
cc1plus: error: silx/math/medianfilter/medianfilter.pyx: not a directory
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
cc1plus: error: silx/math/medianfilter/medianfilter.pyx: not a directory
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isilx/math/medianfilter/medianfilter.pyx -Isilx/math/medianfilter/include -I/users/opd16/miniconda2/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/users/opd16/miniconda2/envs/py27/include/python2.7 -c silx/math/medianfilter/medianfilter.cpp -o build/temp.linux-x86_64-2.7/silx/math/medianfilter/medianfilter.o" failed with exit status 1
```

**Comment by kif** [comment]
> cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
> cc1plus: error: silx/math/medianfilter/medianfilter.pyx: not a directory
> error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isilx/math/medianfilter/medianfilter.pyx -Isilx/math/medianfilter/include -I/users/opd16/miniconda2/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/users/opd16/miniconda2/envs/py27/include/python2.7 -c silx/math/medianfilter/medianfilter.cpp -o build/temp.linux-x86_64-2.7/silx/math/medianfilter/medianfilter.o" failed with exit status 1
> ```

Could it be that the C++ Henri wrote is too recent for the compiler available on debian6 ?

**Comment by vasole** [comment]
Well, I do not see why the instruction:

-Isilx/math/medianfilter/medianfilter.pyx

is found inside a command addressed to gcc. To me that points more
towards a Cython version problem.

**Comment by payno** [comment]
Wstrict-prototypes issue is a warning. Probably come from setup.py adding those compiler options for cython ( at least it is my guess ). It is not 'hard coded'.
The error is the second line -Isilx/math/medianfilter/medianfilter.pyx it try to add it in the like it as a directory.
This is an issue with the setup.py. I made a Pull request to deal with it.
Recent compiler manage it with a warning, previously it was an error.
Anyway it should work with this modification

**Comment by t20100** [comment]
The fix for the ``-Isilx/math/medianfilter/medianfilter.pyx`` issue is merged (PR #733) in the master.

**Comment by maurov** [comment]
The fix has worked wonderfully, thanks a lot! I close this issue.

PS: the test suite seems to work, only a couple of fails (trace below):

```
======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Plot with an image: test MaskToolsWidget interactions [] (origin=(0, 0), scale=(1, 1))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/opd16/miniconda2/envs/py27/lib/python2.7/site-packages/silx-0.5.0a0-py2.7-linux-x86_64.egg/silx/gui/plot/test/testMaskToolsWidget.py", line 196, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: test (silx.gui.plot.test.testPlotInteraction.TestSelectPolygon)
Test draw polygons + events
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/opd16/miniconda2/envs/py27/lib/python2.7/site-packages/silx-0.5.0a0-py2.7-linux-x86_64.egg/silx/gui/plot/test/testPlotInteraction.py", line 140, in test
    self.assertEqual(len(drawEvents[-1]['points']), 3)
AssertionError: 4 != 3

----------------------------------------------------------------------
Ran 905 tests in 401.712s

FAILED (failures=2, skipped=52)
Test suite failed
1
```

**Comment by t20100** [comment]
@maurov thanks for the feedback. The failing tests are tests simulating mouse interaction, they are quite fragile and can fail if you move the mouse during the tests.
