### ISSUE TITLE
silx script to execute main() function in module

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#74]
As discussed in our meeting, I'm working on a silx command line interface to be able to execute a main function in any module. Any criticism is welcome !

I tried two different ways for finding all available modules, and the most likely option is to browse through the silx package with `os.walk`. I have a heavily commented prototype to explain how it works: https://github.com/PiRK/silx/blob/silx_cli/scripts/runmodule_oswalk.py

All `.py` and `.so` files in a subfolder with a `__init__.py` file are considered to be modules. 

A modules can be called by its short name (e.g. `PlotWindow`) or it's long name (e.g. `silx.gui.plot.PlotWindow`). The long name is mandatory in case of ambiguity.

The `-h` option used together with a module name causes the docstring of the `main()` function to be printed. 

A `-l` option can be used to print a complete alphabetically sorted list of long module names. This list is already very long, so this option might soon become hard to use.

A `-s` option can be used to search a module by providing part of its name. All modules whose long name contain the provided search string are listed. Maybe I should change the search to do it on short names?  This would help restrict the number of matches, but the downside would be that we could not search all sub-modules of a given module (e.g `python runmodule_oswalk.py -s math` to find all `silx.math.*` modules)

So far, the main function should have following signature:

```
int main(*args)
```

The return value is used as the exit code (`sys.exit(main(*args))`).

`args` is the list of all arguments specified on the command line after the module name. For the moment I pass them as raw strings to the `main()` function. Do you think it would be a good idea to try to guess the type of the arguments, or should we just let the `main()` function handle all typecasting?

**Comment by vasole** [comment]
My comments:

- I would aim to the following to not imposing **anything** on the main function. If we decide to impose something to it, then I would be more in favor of defining a silx_main.

- I would only look for .py files and not for .pyd or .so or .dyld files (there is life beyond linux).

**Comment by PiRK** [comment]
Can I close this issue?
I believe the general consensus is now that applications should go into to the `silx.app` module and demos to the *examples* directory.
