### ISSUE TITLE
[icons] Issue with image embedded in svg icons

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#740]
On macOS with python2.7, PyQt4 (from silx wheelhouse) there are errors when loading svg icons that embed a base64 encoded jpeg image:

```
from silx import sx
from silx.gui import icons
icons.getQIcon('image')
```
Results in error message:
```
couldn't create image from  "data:image/jpeg;base64,/9j/4AAQ[...]
```

**Comment by t20100** [comment]
I have not encountered this anywhere else, so it might come from the PyQt wheel of silx wheelhouse.

**Comment by vallsv** [comment]
To me it is an issue only if we have this kind of images on our repo. And then it have to be vectorized. 

Else we can close this issue. Using raster image in svg do not make any sens for us.

**Comment by t20100** [comment]
We have icons with embedded images... Those displaying images...

**Comment by vasole** [comment]
Is that wheel compiled with QtSvg support?

**Comment by t20100** [comment]
Icons embedding images in base64 (some in png others in jpeg...):
close.svg
document-open.svg
draw-pencil.svg
edit-copy.svg
folder.svg
image-select-add.svg
image-select-box.svg
image-select-brush.svg
image-select-erase-rubber.svg
image-select-erase.svg
image.svg
math-peak-reset.svg
math-peak-search.svg
plot-roi-reset.svg
plot-window-image.svg
selected.svg
view-fullscreen.svg
view-nofullscreen.svg

**Comment by vallsv** [comment]
Outcha... I will take a look

**Comment by vasole** [comment]
Depending on how Qt was compiled, it will rely on libjpeg being provided by the system, by Qt itself or not supported at all. The default is to use the support provided by the system. In my system I make sure I compile with the libjpeg provided with Qt in order to make sure the fat binaries do not miss anything.

I wonder if there is a way to figure out the Qt compilation options from the PyQt4 wheel.

**Comment by vallsv** [comment]
Maybe it reuses the default qt plugins no? Then you can check if you have the expected files. Else you can check which file formats is supported at runtime (http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats). But maybe plugins are not used there.

As an expample here is what i have
```
imageformats
    libqgif.so  libqico.so  libqjpeg.so  libqmng.so  libqsvg.so  libqtga.so  libqtiff.so
iconengines
    libqsvgicon.so
```

**Comment by vasole** [comment]
Yes, but the support for those formats is decided when building Qt. We have to figure out what is available in the test machine where the problems are.

If you take a look at http://doc.qt.io/qt-4.8/configure-options.html you will see


-no-libjpeg	Do not compile JPEG support.	This option denotes a default value and needs to be evaluated. If the evaluation succeeds, the feature is included.
-qt-libjpeg	Use the libjpeg bundled with Qt.	
-system-libjpeg	Use libjpeg from the operating system.	See http://www.ijg.org. This option denotes a default value and needs to be evaluated. If the evaluation succeeds, the feature is included.

**Comment by vallsv** [comment]
My PR clean up unneeded raster images from icons. Only few images uses raster image, plus the project do not use it.
```
silx/resources/gui/icons/image-select-erase.svg
silx/resources/gui/icons/image-select-brush.svg
silx/resources/gui/icons/image-select-erase-rubber.svg
silx/resources/gui/icons/plot-window-image.svg
silx/resources/gui/icons/image-select-add.svg
silx/resources/gui/icons/image-select-box.svg
silx/resources/gui/icons/image.svg
```
But if there is a problem a problem with our Qt wheel it would be nice to fix it, if possible. But it is no more problem with the silx release. Then I unassign myself from this issue.

**Comment by t20100** [comment]
I'll look at the MacOS wheel.

**Comment by t20100** [comment]
Fixing the macOS wheel requires to rebuild Qt and PyQt from scratch and packaging the wheel... I'm not very keen on doing it unless it is needed...
By the way, in the first place, I made this wheel for the CI to work, and we also provide a PyQt5 wheel for python2.7 on macOS which seems to work OK.

Still to solve: try to remove remaining images

**Comment by t20100** [comment]
Closing, python2.7 and PyQt4 being dropped, this issue no longer occurs.
