### ISSUE TITLE
Sift documentation warning

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#752]
Here is few warning when building the documentation of the debian 8 package.
```
/mntdirect/_bliss/users/valls/workspace/test_build_silx/build/debian8/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_match2.jpg
/mntdirect/_bliss/users/valls/workspace/test_build_silx/build/debian8/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_frame_ROI.jpg
```

**Comment by kif** [comment]
On Fri, 21 Apr 2017 02:45:27 -0700
Valentin Valls <notifications@github.com> wrote:

> Here is few warning when building the documentation of the debian 8 package.
> ```
> /mntdirect/_bliss/users/valls/workspace/test_build_silx/build/debian8/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_match2.jpg
> /mntdirect/_bliss/users/valls/workspace/test_build_silx/build/debian8/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_frame_ROI.jpg
> ```

we should re-do the tutorials with jupyter now ... 
I will do it during the code camp using ExternalResources wich was just merged.

-- 
Jérôme Kieffer
tel +33 476 882 445
