### ISSUE TITLE
[Plot] Histograms

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#757]
Hi all, I have a couple issues with the display of histograms :

Context : displaying histograms :
``` python
Plot.addCurve(x, y, histogram='left')
# with len(x) = len(y) + 1
```

* the first one was, AFAIK, already there in 0.4 : the x/y log actions throw an exception (because x and y lengths aren't the same probably).
* the second one is a regression and probably appeared with the introduction of objects : addCurve throws an exception if x and y don't have the same length.

**Comment by payno** [comment]
I made a few modification, now this should be ok. But we should wait for @t20100 to review it before merging.
There is quit a lot of new classes and I don't know the structure of the code. My patch is maybe not ''adapted" to the OO architecture.'
