### ISSUE TITLE
Allow context menus for charts

### ISSUE THREAD

**Issue by rozyczko** [silx-kit/silx#760]
Enhancement request.

It would be beneficial to have a possibility of adding a custom context (right mouse click) menu to the charts.
There is a lot of operations which can be added to a plot, which shouldn't necessarily go in the toolbar, so context menus are ideal.

**Comment by vallsv** [comment]
That's something planed at some time. A refactoring was done for the coming 0.5 which allow us to implement this kind of stuffs. But yet it is not planed.

**Comment by vasole** [comment]
Yes, it is something planned. At this point the right click is set to a zoom back but it should be possible to overwrite that. For instance, assuming that should be the behavior if no context menu is applied or if the context menu only action is just the zoom back.

**Comment by t20100** [comment]
PR #976 removes right-click zoom interaction from the plot.
This allows to add context menus to the plot through QWidget API as illustrated in the sample code provided in PR #976 (https://github.com/t20100/silx/blob/bf45c30e497559dae77c923d46b27e33a2354223/examples/plotContextMenu.py).

@rozyczko, does that fit your needs?

**Comment by rozyczko** [comment]
@t20100 
Tested the example script on plot-zoom branch.
Looks good and is exactly what we need.
Once merged, this issue can be closed.
Thanks

**Comment by vasole** [comment]
Closed by #976
