### ISSUE TITLE
[Plot] DockWidgets should be just containers

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#772]
This is just a heads up.

The PR #771 illustrates a situation that can be common to other docked widgets.

It seems reasonable to have all the functionality available in the contained widget independently of being inside a dock widget or not. In other words, the dock container should not add other functionality than the docking capabilities.

This seems to have been discussed but I did not find an associated issue.

**Comment by t20100** [comment]
+1
Yes we started discussing it, to me the DockWidget should only manage layout stuff, not functionalities, and ideally be created by who is using the widget (e.g., PlotWindow in our case). This is clearly not the case as it is now.

**Comment by vasole** [comment]
Add to guidelines.
