### ISSUE TITLE
[MedianFilter] C++ implementation slower than C implementation in PyMca? 

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#773]
- Could it be that under windows only one thread is used? 
- The implementation in PyMca is twice as fast as the silx C++ implementation

![medianfilterpymca](https://cloud.githubusercontent.com/assets/5636251/25555542/8236ff5c-2ce9-11e7-91fb-2a4f64693ffb.png)

**Comment by vasole** [comment]
The PyMca implementation is single threaded.

**Comment by payno** [comment]
Yes might be an issue with threads.
What are the dimensions of the image ?

**Comment by vasole** [comment]
It is the scipy ascent image.

**Comment by vasole** [comment]
The image shape is 512x512

**Comment by dnaudet** [comment]
I compared it with the xsocs medfilts : I get the same timings as pymca, with or without threads : around 1.05s (k = [27, 27]). With silx i get something like 2s.
Differences : xsocs uses fused types, and doesnt check for conditionals.

**Comment by dnaudet** [comment]
It seems to me that there's a vector created for each pixel. If so have you tried creating one array per thread once and for all (and reuse that array)?
