### ISSUE TITLE
[plot] StackView Image Title

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#776]
Not the title displayed is "Image z="+value of axis in the slider
I would like to customize this title.

**Comment by vasole** [comment]
From the discussion we had, it seems a setTitleCallback method would do the job. If it is not provided, current behavior would be maintained.

**Comment by PiRK** [comment]
I submitted a pull request. I assumed that the callback takes as argument the frame index (0..n-1). Is that correct, or do you prefer the calibrated z value?
