### ISSUE TITLE
behavior median filter ( cpp implementation )

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#780]
Should have the same behavior as scipy.ndimage.median_filter( mode='nearest')

**Comment by vasole** [comment]
I think you can implement some (all?) of the options in scipy while keeping the shrinking window as an additional option ("shrinking") .

**Comment by payno** [comment]
This changed the implementation, expecially we are now using std::queue that we are updating at each iteration.
And we are not controling the number of thread. OpenMP is now dealing with it.

Here is a benchmark on my computer ( the cheating came from the multi threading but that is the point of this median filter). 
- Image dimensions are 1000x1000. 
- Y axis : the execution in s
- X axis : kernel dim (square kernel)

This benchmark (silx vs pymca vs scipy (nearest)) is available in silx/math/medianfilter/test

![perfmedianfilter](https://cloud.githubusercontent.com/assets/12907796/25669694/8d7bf4b4-302a-11e7-8496-281fd79e62f3.png)


output:

INFO:__main__:exec time silx (kernel size = 3) is 0.239403009415
INFO:__main__:exec time scipy (kernel size = 3) is 0.370594024658
INFO:__main__:exec time pymca (kernel size = 3) is 0.29501914978
INFO:__main__:exec time silx (kernel size = 5) is 0.397907972336
INFO:__main__:exec time scipy (kernel size = 5) is 1.04420685768
INFO:__main__:exec time pymca (kernel size = 5) is 0.902577877045
INFO:__main__:exec time silx (kernel size = 7) is 0.601320028305
INFO:__main__:exec time scipy (kernel size = 7) is 1.83525800705
INFO:__main__:exec time pymca (kernel size = 7) is 1.68223690987
INFO:__main__:exec time silx (kernel size = 11) is 1.25890898705
INFO:__main__:exec time scipy (kernel size = 11) is 4.02138400078
INFO:__main__:exec time pymca (kernel size = 11) is 3.89750289917
INFO:__main__:exec time silx (kernel size = 15) is 2.55191111565
INFO:__main__:exec time scipy (kernel size = 15) is 7.21389389038
INFO:__main__:exec time pymca (kernel size = 15) is 6.83304595947
INFO:__main__:exec time silx (kernel size = 25) is 5.35950708389
INFO:__main__:exec time scipy (kernel size = 25) is 18.5504860878
INFO:__main__:exec time pymca (kernel size = 25) is 18.0912461281

**Comment by dnaudet** [comment]
Couple comments, if performance is an issue :
- AFAIK deque elements are not contiguous in memory (unlike vector)
- what's the performance cost of push_back/pop_front vs allocating an array keeping an index of the line to remove?

**Comment by payno** [comment]
Sorry I miss your comment. In fact it as been move back to implementation with vectors.
Was less costly compared to all those push/ pop
