### ISSUE TITLE
common entry point for medianfilter cpp - opencl

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#787]
From PR  #668 discussion median filter implementation for opencl and cpp should have a common entry point.
(under silx.image)

**Comment by payno** [comment]
The user should specify an engine on it.
From my point of view user should be able to call the common function by only setting an array.
And if he wants he can tune the function.
 So we would have a signature like this:
    medfilt(data, kernel_size=3, conditional=False, engine=?):

Question is :
   1. Do you agree for this signature ? / having a default value for engine ?
   2. what should be default value of engine ? cpp or opencl ? One is faster, the other should run on more platform.

**Comment by vasole** [comment]
It was written in the minutes ;)

**Comment by kif** [comment]
"cpp" looks like a good default
