### ISSUE TITLE
Missing  manylinux1 wheels

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#805]
It was requested on a beamline.

**Comment by t20100** [comment]
That would be good to make them for the 0.5 release...

**Comment by vasole** [comment]
Optimized wheels and manylinux ....

For beamlines we already provide the debian packages.

The only case might be debian6 and that is not officially supported. Installing anaconda seems a better use case. 

Just for info, manylinux wheels for PyQt5 are only available for python 3.5 What is the reasoning behind us providing manylinux wheels when in any case it is very likely they are going to need to compile something else much harder to compile than silx?

**Comment by kif** [comment]
Hi Armando,

The lack of manylinux wheels is an issue for people just willing to make "pip install pyFAI" as pyFAI (is about to) depends on silx.

PyQtX.Y is not a dependency for silx to my knowledge.

The use-case for this is a virtual-env for testing a feature. The user preferred python 2.7 as his code was still for python2.

Cheers,

**Comment by t20100** [comment]
We are quite happy that our dependencies provide wheels for CI and fast installation in virtual environments, so I think it is quite nice to also provide wheels for people depending on silx.

And yes, wheels are not optimized and one should compile the package or use the Debian package to gain the most out of the C/C++ code, but I still think it is interesting to have wheels.

**Comment by vallsv** [comment]
BTW, you also can use that to compile the lib from the source code
```
pip install --no-binary :all: silx
```

**Comment by vasole** [comment]
@vallsv  That's the command I wanted.
@kif If the dependency is via pyFAI, if pyFAI uses the silx widgets in that case one of the Qt bindings is needed. What else is used from silx in pyFAI?

**Comment by kif** [comment]
On Thu, 11 May 2017 04:00:43 -0700
V. Armando Solé <notifications@github.com> wrote:

> @kif If the dependency is via pyFAI, if pyFAI uses the silx widgets in that case one of the Qt bindings is needed. What else is used from silx in pyFAI?

median filter, external resources, ... and a few others.

If you consider silx should only be about Qt you should have mentioned it earlier. 

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vasole** [comment]
On 11/05/2017 13:56, Jerome Kieffer wrote:
>
> median filter, external resources, ... and a few others.
>
> If you consider silx should only be about Qt you should have mentioned
> it earlier.

Certainly not, but what you mention is really forcing things.

You know that for tiny bits I do not put dependencies :-)

**Comment by kif** [comment]
On Thu, 11 May 2017 05:03:18 -0700
V. Armando Solé <notifications@github.com> wrote:

> You know that for tiny bits I do not put dependencies :-)

Are you suggesting pyFAI should not depend on silx ?

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vasole** [comment]
As a developer I am saying that if it would be just for the items you mention in your post, I would not put the dependency (among other reasons because you already had most of those things).

**Comment by kif** [comment]
On Thu, 11 May 2017 06:04:47 -0700
V. Armando Solé <notifications@github.com> wrote:

> As a developer I am saying that if it would be just for the items you mention in your post, I would not put the dependency (among other reasons because you already had most of those things).

I have already everything ... but I believed the idea was to remove duplicates

**Comment by vasole** [comment]
Closed  with 0.5.0 release.
