### ISSUE TITLE
[gui] Check h5pyd with tree and dataviewer

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#816]
Checking h5pyd can help to spot "non standard" API used in our code.

The code is not done to be asynchronous, but it can be useful to check anyway.

**Comment by vasole** [comment]
More than just to check. Apparently there is interest to support accessing a remote file.

**Comment by vallsv** [comment]
It's done. BTW we dont have integration tests for regression while it request to install h5serv.
