### ISSUE TITLE
[test] Create a target 'silx test' to launch unittests on the system

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#822]
It can be interesting to lauch unittests on a system without sourcecode

`./run_tests.py` can be optionally replaced by `./bootstrap.py silx test`

**Comment by t20100** [comment]
The separate `run_tests.py` allows to easily copy-paste it to other projects. That would be no more possible if embedded in the launcher.

To run the tests without the source, you can already run:
```
import silx.test
silx.test.run_tests()
```
... though this does not provide any options.

**Comment by vallsv** [comment]
We decide at the silx meeting to create a very simple entry-point for tests.

**Comment by t20100** [comment]
Closed by #925
