### ISSUE TITLE
[test] Filter stdout of the unittests

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#823]
We have more and more output.
It would be nice to filter it a little bit.

We can merge the code done in pyFAI. The behaviour a little bit to look like that:

- stdout are displayed together with failed tests
- we can still display it when we use verbose mode (that's useful to check warnings, and in dev mode)
- but the default output should only display dots and flags: `.....EF...ss.`...

**Comment by vasole** [comment]
Done.
