### ISSUE TITLE
[logging] Clean up library from logging.basicConfig

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#825]
`logging.basicConfig` should never be used by a library. The applications have to take care of the logging handlers.

You can read for example https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library

Maybe there is special cases, like notebooks or ipython consoles. But i hope it already provide configurer logging system.

**Comment by t20100** [comment]
In any case, I think scripts and console users should be able to use `silx` without configuring the logging module.

**Comment by vallsv** [comment]
You have to define what do you mean by `be able to use`.
Only the very first `logging.basicConfig` is used, others are ignored. Anyway it is not the responsibility of a library to configure an handler.

I also found few `logger.setLevel` in modules (2 or 3). I dont think it is a good idea. It should be reviewed and removed if it is not really needed.

Usually an application custom loggers one by one from config files, according to needs (you want to debug this part without been flooded by this other part). If modules overwrite the main configuration it can became really boring.

**Comment by t20100** [comment]
At first, I was expecting that if no one is configuring `logging` for silx, we should send errors and warnings to stdout (which is what `logging.basicConfig()` is doing).

But now, thinking of it, I would do as the Python documentation is recommending, i.e., not displaying logs by default as logs should be "optional" and serious error should raise an exception...

Maybe, the `sx` module which detects if it is running in the console can call `logging.basicConfig()` in that case.

**Comment by t20100** [comment]
From a quick look at the code, there are a few loggers created by specifying a name rather than `logging.getLogger(__name__)`.. and in those a few have a name that does not start with `"silx"`. We could also clean that.
 In particular the deprecation logger is named: `"DEPREACTION"`.
