### ISSUE TITLE
[mask] setSelectionMask can't process return value of getSelectionMask()

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#834]
When no mask is set, e.g. when the mask tools widget has just been initialized, the following code prints an error message:

`self._getMaskToolsDockWidget().setSelectionMask(self._getMaskToolsDockWidget().getSelectionMask())`

The error log is:
`ERROR:silx.gui.plot.MaskToolsWidget:Not an image, shape: 1`

We could avoid this by making `setSelectionMask` accept an empty array (and possibly None?) as a synonym for `resetSelectionMask()`

**Comment by PiRK** [comment]
Cf https://github.com/silx-kit/silx/pull/836#issuecomment-303086289 for why this issue is still open. This will be easier to fix after a refactoring of the mask.

**Comment by t20100** [comment]
Re-opened as not closed by PR #836
