### ISSUE TITLE
[Plot] Anchors on profiles

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#84]
Enhancements for PlotWindow profile toolbar:
- [x] Disable profile actions when no image is displayed
- [x] Update profile when image is updated
- [ ] Add draggable anchors to free profile to allow changing an already defined profile.

**Comment by vasole** [comment]
First two points seem feasible for 0.2.0 release...

**Comment by t20100** [comment]
First 2 points implemented in #116

**Comment by vallsv** [comment]
Closed by  #3011
