### ISSUE TITLE
[mask] cancel shape creation when using right mouse click

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#842]
Proposed by Jerome. I think it is convenient.

**Comment by t20100** [comment]
To make it clear, the idea is to allow the user to cancel a shape (rectangle, polygon) by pressing the right button while releasing the left button. This interaction is available in gimp for the rectangle selection tool.

The current implementation (at least for polygon) is close to inkscape polygon drawing: A left click on the first point ends the polygon creation, a left click elsewhere adds a point to the polygon while a right click adds a point and ends the polygon creation (while in inkscape it ends the polygon but does not add a point).

It seems both can be combined.
The only short coming for those 2 interactions is that they use the right mouse button that we might want to keep for a context menu...

**Comment by t20100** [comment]
To me this is no more relevant as we decided to keep the right mouse button for context menus, so I'm closing.
Reopen if you think otherwise.
