### ISSUE TITLE
[plot gl] Add support of math formula in axes labels and title

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#845]
matplotlib supports a subset of TeX to support math formula.

It seems possible to use matplotlib text render (class MathTextParser in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mathtext.py#L3210 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/texmanager.py for TeX-based rendering) to do the text rasterisation in a numpy array (the same way Qt is used to do the text rasterisation). This array can then be provided as a texture to OpenGL to display the text. This would enable the support of matplotlib text formatting.

**Comment by vallsv** [comment]
I am interested by the way you implement that. It can be useful for widgets in PyFAI too.

Then if the boiler plat to raster TeX as an image is big, or if we want an abstraction from matplotlib one of this day, it can be useful to have a silx API to play with that.

**Comment by t20100** [comment]
My idea was to have a function in silx wrapping matplotlib text raster the same way I wrapped Qt for text rasterization: https://github.com/silx-kit/silx/blob/master/silx/gui/_glutils/font.py#L70

**Comment by kklmn** [comment]
Hi!
Do you still plan to do it?

**Comment by t20100** [comment]
Hi,
I wanted to evaluate the effort to implement it before answering you... and I ended up implementing it. ;)

It is available in PR #3600 if you want to test it.

**Comment by kklmn** [comment]
Hi,
Tested, works as expected. Thanks!
