### ISSUE TITLE
[mask] The data field gives the value of the mask

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#848]
Not the data not the value of the data ... as expected

**Comment by vallsv** [comment]
Yes, we already talk about that. But it is definitively a problem on our GUI. Then i think it is important to fix.

Plus:
- Show an image
- The data field will be the value of the pixel of the image
- Open the mask
- The data field is now the value of the pixel of the mask
- Close the mask
- The data field is still the value of the pixel of the mask

**Comment by vallsv** [comment]
We decide with @t20100  to create a specific mask item and to filter it. As result the data of the next visible image will be displayed.
