### ISSUE TITLE
[fitwidget] It is not possible to fit an histogram

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#854]
It is not possible to select an histogram, and histogram are not part of `activeCurve`. Then it is not possible to fit an histogram from the plot using the current tool.

**Comment by PiRK** [comment]
The fit toolbar button could open a drop down menu or a dialog widget allowing to select any curve or histogram by its legend and type (eg '"Toto curve" (curve)') . That would be the least ambiguous way to proceed.

**Comment by vasole** [comment]
The proposed solution should only take effect in case of having histograms in the plot.

**Comment by vasole** [comment]
BTW, if the plot just contains one histogram and no curves, the dialog should not be shown either since there is no ambiguity to be resolved.
