### ISSUE TITLE
[spech5] Segmentation Fault in SpecH5

### ISSUE THREAD

**Issue by carichte** [silx-kit/silx#858]
silx.io.spech5.SpecH5 is supposed do be called with a file-path as argument.

As soon as any other kind of object is passed to SpecH5, this will result in a Segmentation Fault (tested on different machines)

This usage is not unusual:
```
with open('/data/visitor/ma3331/id01/knno-47-008-SSO.spec') as fh:
    s5 = silx.io.spech5.SpecH5(fh)
```

I mentioned it before in the mailing list: http://www.edna-site.org/lurker/message/20170424.143447.51ee80ca.en.html

Together with relative paths from `SpecH5Group.visit` (see https://github.com/silx-kit/silx/issues/614#issuecomment-305529363) fixing this would allow to use the `write_spec_to_h5` function to insert spec scans in existing h5 files.

**Comment by PiRK** [comment]
I made a commit that implements the relative path behavior for `visit` and `visititems`. It appears that this change did not break the `spectoh5` module, which is a good sign. 
I'm now a bit worried about this change in behavior affecting other users who got used to dealing with full pathes.

**Comment by vasole** [comment]
Can this be closed?

**Comment by carichte** [comment]
Yes it seems to work. Thanks!

**Comment by carichte** [comment]
Sorry I only checked before the .visit methods.

processing an opened spec file does not seem to work yet.

For python3, it fails because of `isinstance(filename, file)` which only works for python2.

Apart from that, it fails because in line:

https://github.com/silx-kit/silx/blob/master/silx/io/spech5.py#L1634

a `self.` is missing, leading to a `TypeError: coercing to Unicode: need string or buffer, file found`

**Comment by PiRK** [comment]
I just proposed a quick patch to fix the 2 issues you pointed at. 

It seems that it would be useful to add a unittest before we can safely close this issue.  I can do that early  next week.

**Comment by vallsv** [comment]
Thanks a lot Pierre. But take care of your holiday, we can manage the hot fix.

**Comment by vallsv** [comment]
It is merged.
I created a test coverage for SpecH5 using file descriptor. It can be improved later.
