### ISSUE TITLE
[view] Few comments about "about" in "silx view" 

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#860]
It would be great to have:
* [x]  the silx logo on the widget
* [x] the license
* [ ] hdf5plugins should not appear as a dependency as it is (and will remain) a hack

**Comment by vasole** [comment]
Is hdf5plugin a dependency? 

The use of hdf5plugin should be proposed at the moment data using those compressors are accessed unsuccessfully.

- Is it a hack? Probably (although then any distribution of a shared library either ending as dll, pyd or so would fit that condition).

- Is it useful? Indeed, as it works independently of using  HDF5 1.8 or HDF5 1.10, something that cannot be said with any other existing solution.

**Comment by vallsv** [comment]
Yes, that's why after thinking about that with Jerome, it's maybe more interesting to display supported HDF5 filters instead of displaying if `hdf5plugin` python module is available or not. But right now i remember that this HDF5 API (knowing which filters are available on the system) is buggy.

**Comment by vallsv** [comment]
I fix the 2 first points. I create the issue  #1064 for the last one, cause I think it is not yet possible to fix that.
