### ISSUE TITLE
[plot] Create an icon for pan mode

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#868]
This kind of tool is very useful for mask for example.

It is the same feature as the keyboard arrows. But providing this feature only with the keyboard is not enough, people usually search a tool to do that.

**Comment by vasole** [comment]
Do you mean for panning? (Panning is currently implemented but limited to the keyboard arrow keys)

**Comment by t20100** [comment]
The mouse pan interaction is already implemented in the Plot: `Plot.setInteractiveMode("pan")` but there is no action associated to it.

**Comment by vasole** [comment]
I agree they search for a tool to do that and we can put it. Although I think  using the arrows is better because one does not change mouse interaction mode.

**Comment by t20100** [comment]
And you can use keyboard arrows while drawing the mask... But we can still provide an action to enable panning mode.
