### ISSUE TITLE
run_tests: Change default to run tests from source rather than installed

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#887]
By default, `run_tests.py` runs the test on the installed version of silx rather than from the source (Running tests from the source can be forced with `-i`).
I would personally prefer it the other way around, so that it runs the tests from the source by default and optionally from the installed version.
In this case, the CI configs would need to be updated accordingly.

Any opinions?

**Comment by vallsv** [comment]
+1

We can use a new argument to avoid few conflict. `--installed` to test the installed version.

**Comment by vasole** [comment]
And if one has in addition the ``silx test`` launcher option that obviously tests the installed version ...
