### ISSUE TITLE
ColorBarWidget issues

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#889]
PR #878 hightlighted a few issues in the `ColorBarWidget`

Issues:
- `ColorBarWidget` is not synchronized when `PlotWidget`'s default colormap is updated.
- Changing the colormap from `ColormapDialog` does not update the colorbar.
- From the console, doing an `addImage` with a different colormap does not update the colorbar immediately. It is only updated when `PlotWindow` gets the focus when clicking on it.
- ColorBar.py l809 `assert(type(self._vmin) == type(self._vmax))`: why is it needed? One can enter vmin=1, vmax=1.5 and it should work.
- If setting a colorbar with vmin == vmax, the colorbar gradient is not updated and displays the previous colormap.
- Using ImageData.setColormap on the active image does not update the colorbar.

Those issues were found using PR #878 branch.

Improvements:
- large values of vmin or vmax enlarges the width of the colorbar. The QLabels could span over/under the ticks to minimize the width of the colorbar + we could display those values with a limited number of significant digits (and have the full value displayed in a tooltip). Anyway, I would not enlarge the colorbar gradient above a certain width.
- It is probably worth listening for active image changes only when the ColorBarWidget is visible.

Refactoring:
- Refactor set|getColormap to only store it once in _ColorScale (and do the checks once) and have proxy to access it in other classes.
- Use a common implementation of checks and erroneous cases (e.g., negative bound with log scale) for the plot and the colorbar.
- In _ColorScale, it looks possible to create the QLinearGradient during setColormap rather than for each paintEvent.

Fixing some of those issues would probably be easier with item's signals (#689) and colormap object ( #146).

**Comment by payno** [comment]
- ColorBar.py  l809 assert(type(self._vmin) == type(self._vmax)): why is it needed? One can enter vmin=1, vmax=1.5 and it should work.

   => yes it was probably code remaining from a previous computation of ticks steps.

+ large values of vmin or vmax enlarges the width of the colorbar. The QLabels could span over/under the ticks to minimize the width of the colorbar + we could display those values with a limited number of significant digits (and have the full value displayed in a tooltip). Anyway, I would not enlarge the colorbar gradient above a certain width.

  => we can have the same behavior as the values displayed on ticks (basically have a maximal width, if this width is higher then we switch to scientific display). Even if I am not such a big fan of this 'trick'.

**Comment by t20100** [comment]
Those 2 issues are related and requires  item's signals (#689):
- Using ImageData.setColormap on the active image does not update the colorbar.
- Changing the colormap from ColormapDialog does not update the colorbar.
