### ISSUE TITLE
Build not working under windows

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#9]
Problem
-----------

- Specfile build crashes under windows

Solution
-----------

- When dealing with multiplatform developments, one has to take care and systematically use os.path.join to build paths.

**Comment by vasole** [comment]
@PiRK Review required.

**Comment by vasole** [comment]
Not sure if it is an issue or not.

- If Cython is installed on the machine, the generated code works.

- If Cython is not installed on the machine, the supplied code does not work.

**Comment by PiRK** [comment]
I'll have a look at the cython issue.  I probably need to adjust the list of source files in io/setup.py if ``os.environ["WITH_CYTHON"] == "False"`` is set in the general setup.py, to remove the pyx file and include the .c file.

**Comment by PiRK** [comment]
File extensions  don't seem to be the problem, as ``fake_cythonize`` (https://github.com/silx-kit/silx/blob/master/setup.py#L296)  already takes care of replacing ``.pyx`` with ``.c`` in the absence of cython.

**Comment by kif** [comment]
On Sun, 06 Mar 2016 23:43:17 -0800
Pierre Knobel <notifications@github.com> wrote:

> File extensions  don't seem to be the problem, as ``fake_cythonize`` (https://github.com/silx-kit/silx/blob/master/setup.py#L296)  already takes care of replacing ``.pyx`` with ``.c`` in the absence of cython.

Look at the version of cython used and enforce the minimum version.

Armando, which version have you been using ?

**Comment by vasole** [comment]
- If I am not mistaken, I have been using cython > 0.17 in order to use memory views.

- FreeART wraps more advanced C++ features and I think it needs 0.22 minimum.

- I do not anticipate problems with the Cython version requirements if we make sure we distribute generated code.

**Comment by kif** [comment]
is this issue fixed ?

**Comment by PiRK** [comment]
We fixed the problem preventing building when cython isn't installed (#13). The previous  issue related to not using ``os.path`` has also been also fixed (#10).
