### ISSUE TITLE
[io] write_spec_to_h5 can't handle empty scans

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#92]
This fails :
```
#S 1  timescan 1 0
#D Tue May 03 17:13:44 2016
#T 1  (Seconds)
#G0 0
#G1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
#G3 0 0 0 0 0 0 0 0 0
#G4 0
#Q 
#P0  0 0 0.2 47.4 3.0905 1100 -0.553
#P1 11.831251 0 333.66188 -78.575001 -1896.0207 280.76377 3.37 60
#P2 122.78406 200 0 260 0 0 18.99 2.5e-05
#P3 9.9149625 6.25e-07 6.25e-07 2.845 61.692125 61.074125 
#UMI0     Current AutoM      Shutter     PPU13A_GAP W150B_GAP W150B_TAPER U17-6c_GAP
#UMI1       -0.01   OFF   FE closed        200.0000  260.0000      0.0000    19.0000
#UMI2 Refill in 0 sec, Fill Mode: 16 bunch / Message: May  3 09:34 MDT; Next injection at 09:40
#N 14
#L Time  Epoch  IC  avg  std  integ  VM_1  VM_2  T_simap  Storage Ring A  Single Bunch A  pico  Monitor  Seconds
#C Tue May 03 17:14:03 2016.  Scan aborted after 0 points.
```

**Comment by PiRK** [comment]
I found several problems in the SpecFile C library:

- `SfAllLabels` returns a non zero error status when parsing a `#L` line in an empty  scan. My workaround is to catch the generated `IndexError` and manually parsing the `#L` line (splitting on double-spaces)
- `SfData` causes a `Segmentation Fault` when trying to retrieve data from an empty scan. My workaround is to look for a `#C` line containing the string `aborted after 0 points` in the scan header. I'm not sure if this is a reliable safeguard, maybe it depends on the SPEC version used to write the file. An alternative method is to try to read a single data column with `SfDataColumnByName` before calling `SfData`, but I suspect this would affect performance more than testing the scan header for a `#C` line.

**Comment by PiRK** [comment]
`SfData`  doesn't directly cause the segmentation fault, but it doesn't seem to allocate memory for `data_info` in case there are no data points. Accessing `data_info[0]` caused the segfault. I fixed the bug in a cleaner way by checking `<long>data_info != 0` before accessing the array.
