### ISSUE TITLE
[GUI] tests and hdf5viewer example fail with PyQt5.9 wheel on Windows

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#936]

**Comment by t20100** [comment]
This looks to come from testing ThreadedPoolButton and Hdf5TreeModel which have some asynchronous tasks and from testing icons (no real idea why)...
Still need investigation

**Comment by PiRK** [comment]
As the segfault only happens after all tests have passed or after closing the applications using the asynchronous components, we can temporarily just pinpoint the PyQt version, to enable CI tests to pass.

**Comment by t20100** [comment]
We should not forget to undo version pin-pointing introduced in #935 as a temporary workaround for CI.

**Comment by t20100** [comment]
Might be related to https://www.riverbankcomputing.com/pipermail/pyqt/2017-July/039399.html

**Comment by vasole** [comment]
It is very likely (see entry on July 10th):

https://www.riverbankcomputing.com/static/Downloads/PyQt5/ChangeLog-5.9.1.dev1707101756

**Comment by vallsv** [comment]
It is not necessary to run the tests.  We crash even using the sx module:

![image](https://user-images.githubusercontent.com/7579321/30965980-8222f7ba-a457-11e7-9555-1aa5351c515e.png)

**Comment by t20100** [comment]
This issue remains for tests of ThreadedPushButton and hdf5TreeModel with latest version of PyQt5 (5.9.1).
It needs more investiguation.

**Comment by t20100** [comment]
See #1323 for further discussion of this issue with PyQt5.9.2.

**Comment by vallsv** [comment]
I send a message to the PyQt5 mailing list about the `QThreadPool`. I hope to have an answer.

**Comment by vallsv** [comment]
Using an own thread pool instead of the global one looks to fix the problem, at least with the toy example. I will investigate that solution on the full tests.

**Comment by vallsv** [comment]
Using both
```
test_suite.addTest(test_threadpoolpushbutton.suite())
test_suite.addTest(test_icons.suite())
```
looks to segfault again

**Comment by vallsv** [comment]
More precisely, this 3 tests together
```
    test_suite.addTest(test_threadpoolpushbutton.TestThreadPoolPushButton("testSaturateThreadPool"))
    test_suite.addTest(test_icons.TestIcons("testPngIcon"))
    test_suite.addTest(test_icons.TestIcons("testCacheReleased"))
```

**Comment by vallsv** [comment]
As result:
```
# bad
icon = Qt.QIcon(filename="foo.png")  # this segfault

# good
pixmap = Qt.QPixmap(filename="foo.png")
icon = Qt.QIcon(pixmap)
```
And
```
# bad
tp = qt.QThreadPool()  # this can segfault if you use all the available threads

# good
tp = qt.QThreadPool()
tp.setMaxThreadCount(tp.maxThreadCount())
```
