### ISSUE TITLE
[opencl] Clean sift.test.test_transform

### ISSUE THREAD

**Issue by pierrepaleo** [silx-kit/silx#944]
The `test_transform` module should be cleaned, and involve images of moderate size (not 3k x 3k).

**Comment by vasole** [comment]
Duplicate of #943 ?

**Comment by vasole** [comment]
OK, I see, your issue goes beyond just the fix and advocates code cleaning.

I have just proposed PR #945 that just fixes the image size but it does not clean anything.

**Comment by pierrepaleo** [comment]
Addressed by  #946.
