### ISSUE TITLE
[Plot] Image mask tools

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#98]
Functions (list taken from PyMca MaskImageWidget):
- Operation on the whole mask:
    - Clear
    - Inversion
- Drawing tools:
    - Brush (with settable width in image pixels)
    - Rectangle
    - Polygon
    - Above threshold
    - Below threshold
    - Within range
- Each draw tool can either paint or erase
- Multiple level of exclusive masks

Proposal: Regarding the number of tools and the fact that more tools will probably be needed, I'm thinking of making a DockWidget as for ROIs, e.g.:

![maskdockwidget](https://cloud.githubusercontent.com/assets/9449698/15957743/5eefdb50-2ef1-11e6-8e63-30b53de9cffe.png)

Ideas for future:
- History/undo/redo
- Drawing tools: circle, ring
- Edition of shapes as vector graphics
- shrink/expand mask
- show/hide different level of mask
- Load (replace of add) and Save masks

**Comment by vasole** [comment]
The advantage of your approach is that is very much in line with the Orange philosophy and extendible.

One can image a widget dedicated to perform a mask consisting on just an image view and a left widget with the above options in a vertical layout.

In any case you will need some icons to toggle the different modes (mask, interaction, drawing, ...), but the overall number of buttons will be reduced.

If nobody else has any objections, you can go ahead with that idea. In the worst of the cases we may end up having two ways of doing the things, what in itself is not so bad.
