### ISSUE TITLE
Is openCL optional

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/silx#983]
Can openCL please be optional, it really messes up the build process.

**Comment by vallsv** [comment]
I think it is. We only have few strong dependencies. Numpy and setuptools. The module `silx.opencl` will just not work in this case (and some algorithms).

**Comment by vasole** [comment]
I confirm. I have been using it without PyOpenCL installed for quite long.
If one cannot build and use silx without opencl it is to be considered a bug.

**Comment by CJ-Wright** [comment]
Awesome. I'm building it right now https://circleci.com/gh/conda-forge/silx-feedstock/3?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vallsv** [comment]
BTW, there is a strange `placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold` path in the circleci build. DO you have an idea where it cone from?

**Comment by CJ-Wright** [comment]
I personally don't know I think this is the [relevant discussion](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/fgDBJ2YwETI). I do know the placeholder is correct/is doing the right thing here.

**Comment by CJ-Wright** [comment]
I'm going to close this since silx seems to have built without openCL, although I'm more than happy to keep discussing the conda stuff.

**Comment by vallsv** [comment]
Yes, sure, it change nothing to the result.
